Update broken link after moving to `main` branch naming
renovatebot/renovate pull request #10344
Opened 2021-06-07 20:58 UTC by jamietanna

2021-06-07 20:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=10344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=10344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=10344) it.</sub>

2021-06-07 21:18 UTC, viceice approved these changes

2021-06-07 21:20 UTC, viceice requested changes

2021-06-07 21:20 UTC, viceice commented on docs/usage/gitlab-bot-security.md
> +Please see the [renovate-bot/renovate-runner README on GitLab](https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/README.md) for instructions on how to set this up as easily as possible.
```suggestion
Please see the [renovate-bot/renovate-runner README on GitLab](https://gitlab.com/renovate-bot/renovate-runner/-/blob/HEAD/README.md) for instructions on how to set this up as easily as possible.
```

2021-06-07 21:25 UTC, jamietanna commented on docs/usage/gitlab-bot-security.md
> +Please see the [renovate-bot/renovate-runner README on GitLab](https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/README.md) for instructions on how to set this up as easily as possible.
TIL you can do that!

2021-06-07 21:54 UTC, viceice reviewed
Next time no force push, we squash merge anyways.

You can also just accept /commit suggested changes via ui.

2021-06-07 21:56 UTC, viceice approved these changes

2021-06-07 22:04 UTC, merged

2021-06-08 09:03 UTC, renovate-release commented
:tada: This PR is included in version 25.38.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/25.38.1)
- `25.38.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: