feat: remove defaulting to semver versioning
renovatebot/renovate pull request #10431
Opened 2021-06-14 22:52 UTC by secustor

## Changes:

This PR removes the defaulting to semver if no other versioning is defined. 

## Context:

Closes #10320

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-06-15 04:11 UTC, viceice approved these changes
If i remember correctly renovate will fallback to semver in code anyway when versioning is undefined. Maybe we need to check that no warning is logged.

2021-06-15 04:20 UTC, viceice commented
https://github.com/renovatebot/renovate/blob/74d7691befa635c1220d8569936273bfb950e748/lib/versioning/index.ts#L18-L21

@rarkins Are we ok with this debug message then? I think that can happen with this PR.

2021-06-15 04:29 UTC, rarkins commented
Maybe lower it to trace and say "Defaulting to semver versioning"?

2021-06-15 04:30 UTC, viceice requested changes
@secustor Please change the logging as mentioned.

2021-06-15 20:15 UTC, rarkins submitted a review, later dismissed

2021-06-16 04:18 UTC, viceice reviewed
I think this makes the message more clear.

2021-06-16 04:18 UTC, viceice commented on lib/versioning/index.ts
> +    logger.trace('Missing versioning');
```suggestion
    logger.trace('Missing versioning, using semver as fallback.');
```

2021-06-17 08:42 UTC, viceice approved these changes

2021-06-17 08:51 UTC, merged

2021-06-17 09:05 UTC, renovate-release commented
:tada: This PR is included in version 25.45.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/25.45.0)
- `25.45.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: