Improve the default User-agent string.
renovatebot/renovate pull request #10606
Opened 2021-06-25 11:51 UTC by nielsbasjes

## Changes:

Change the default user-agent request header to something that conforms to what this header normally looks like.

## Context:

I'm the author of https://yauaa.basjes.nl/ which is intended to analyze the user-agent string.

The current value of the user-agent request header of Renovate is just the github url of the project which does not conform to common conventions and standards.

This change makes this header conform much better to the conventions and what is described in the RFC  https://datatracker.ietf.org/doc/html/rfc7231#section-5.5.3 

This change proposes to change the default string to: `RenovateBot/25.50.0 (https://github.com/renovatebot/renovate)`

It is still possible to override the value if so desired.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

One of the messages in my test run showed:
```json
"user-agent": "RenovateBot/0.0.0-semantic-release (https://github.com/renovatebot/renovate)",
```

2021-06-25 12:16 UTC, viceice requested changes
Needs snapshot updates, run `yarn jest -u`

2021-06-25 12:16 UTC, viceice commented on lib/util/http/index.ts
>    // eslint-disable-next-line no-param-reassign
```suggestion
```

2021-06-25 12:16 UTC, viceice commented on lib/util/http/index.ts
>    options.headers = {
```suggestion
  // eslint-disable-next-line no-param-reassign
  options.headers = {
```

2021-06-25 17:41 UTC, rarkins approved these changes

2021-06-26 06:54 UTC, viceice approved these changes

2021-06-26 07:02 UTC, merged

2021-06-26 11:30 UTC, renovate-release commented
:tada: This PR is included in version 25.51.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/25.51.3)
- `25.51.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: