feat: Support rebase only when newer version has been found
renovatebot/renovate pull request #10623
Opened 2021-06-26 20:15 UTC by bobvandevijver

## Changes:

This change should implement my feature request in https://github.com/renovatebot/renovate/discussions/10564. 

## Context:

Sometimes, you only want renovate to rebase/retry a PR whenever the external dependency has been changed in order to save valuable computing/pipeline resources. When using the new `rebaseWhen=newer-version` renovate will only update existing branches when it has found a newer version of the dependency.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-06-26 21:09 UTC, HonkingGoose requested changes
I think this is easier to read and understand. 😉

2021-06-26 21:09 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +It is also recommended avoiding `rebaseWhen=never` as it can result in conflicted branches with outdated PR descriptions and/or status checks.
```suggestion
We recommend you avoid setting `rebaseWhen` to `never` as you can end up with conflicted branches with outdated PR descriptions and/or status checks.
```

2021-06-26 21:09 UTC, HonkingGoose commented on docs/usage/updating-rebasing.md
> +When using the default configuration (`"rebaseWhen": "auto"`), this will happen automatically.
```suggestion
When you use the default configuration (`"rebaseWhen": "auto"`), this happens automatically.
```

2021-06-26 21:09 UTC, HonkingGoose commented on docs/usage/updating-rebasing.md
> +However, if you only want Renovate to rebase when a newer version of the dependency "foo" is available, you can configure `"rebaseWhen": "newer-version"`.
```suggestion
However, if you want Renovate to rebase only when a newer version of the dependency "foo" is available, you can configure `"rebaseWhen": "newer-version"`.
```

2021-06-26 21:09 UTC, HonkingGoose commented on docs/usage/updating-rebasing.md
> +This behaviour is fully disabled by configuring `"rebaseWhen": "never"` (not recommended).
```suggestion
If you don't want Renovate to rebase branches, you can configure `"rebaseWhen": "never"` (not recommended).
```

2021-06-28 07:32 UTC, viceice reviewed
I think this needs a real repo run even it's not easy to do.

2021-07-06 18:47 UTC, bobvandevijver commented
> I think this needs a real repo run even it's not easy to do.

I agree, I'm just having a hard time finding the required to create it. I'm working on it!

2021-07-18 08:44 UTC, rarkins commented
@viceice can you think of any simpler ways we could achieve this? I'd love to avoid complicating this interface if possible

2021-07-26 20:32 UTC, bobvandevijver commented
@rarkins / @viceice I just tested this on a real repository, and it doesn't seem to work as I had hoped. Probably caused because I simply do not have enough insight in the functioning inside the update logic. Maybe one of you could take a look?

2021-11-01 07:44 UTC, closed without merging