fix: changed logger level to info for --print-config to print all logs
renovatebot/renovate pull request #11299
Opened 2021-08-17 10:23 UTC by bprachi29

## Changes:

## Context:

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-08-17 10:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=11299) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=11299) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=11299) it.</sub>

2021-08-18 08:17 UTC, rarkins requested changes
@bprachi29 please follow our conventions for PR title and body

2021-08-20 17:57 UTC, JamieMagee commented
@bprachi29 Congratulations and thank you for your first pull request 🎉

I've updated your description to include some more information about the change. We ask people to add this to make it easier to track _why_ changes were made. If you open another PR, could you please include this information?

Thanks again!

2021-08-20 17:57 UTC, JamieMagee approved these changes

2021-08-23 06:59 UTC, bprachi29 commented
@JamieMagee thanks for updating it.

2021-08-23 14:27 UTC, merged

2021-08-23 14:39 UTC, renovate-release commented
:tada: This PR is included in version 26.4.4 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/26.4.4)
- `26.4.4`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: