fix(datasource/maven): look for maven snapshot pom
renovatebot/renovate pull request #11327
Opened 2021-08-18 18:36 UTC by bpfoster

Maven snapshot poms are stored in the repository with timestamp & build number replacing the -SNAPSHOT in the name.

The check for missing artifacts did not resolve these files and so SNAPSHOTS always appeared missing and were filtered out.

Not sure if the async handling in `filterMissingArtifacts()` is the best, please let me know if changes needed.

## Changes:

Maven snapshot dependencies should now be included without wholesale disabling the pom check via `RENOVATE_EXPERIMENTAL_NO_MAVEN_POM_CHECK`.

## Context:

This should fix issue #3728

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2021-08-28 21:19 UTC, viceice submitted a review, later dismissed
@zharinov Can you please review this?

2021-09-06 13:37 UTC, zharinov requested changes

2021-09-10 14:59 UTC, bpfoster commented on lib/datasource/maven/index.ts
> +    const queue = (await Promise.all(versionUrls))
Had a feeling this wasn't the best way to do this.  Apologies, my javascript knowledge is low.  Rewrote to use `pMap()` with no more `Promise.all()` - does that look better now?

2021-09-10 15:00 UTC, bpfoster commented on lib/datasource/maven/index.spec.ts
> +      .reply(404, '');
Rolled the snapshots into `mockGenericPackage`, is this what you were thinking?

2021-09-28 18:12 UTC, rarkins requested changes
Can you add some commenting to the primary logic to explain what's going on? This check logic has now got pretty large and would be increasingly challenging for anybody to debug or extend further

2021-09-29 12:06 UTC, bpfoster commented
Peppered some comments in to the affected logic.

2021-09-30 09:16 UTC, rarkins commented
Thanks @bpfoster. @zharinov can you review?

2021-10-10 06:52 UTC, zharinov approved these changes
Looks good to me.
@bpfoster, thanks for the PR of such a good quality!

2021-10-10 07:34 UTC, rarkins approved these changes

2021-10-10 07:41 UTC, merged