docs: update dependencyDashboard config option
renovatebot/renovate pull request #11352
Opened 2021-08-20 12:35 UTC by HonkingGoose

## Changes:

- Explain that from version `v26.0.0` the dashboard is turned on by default
- Explain how to turn the dashboard off

## Context:

I saw some confusion on how to turn off the dashboard in discussion #11330, so I'm trying to improve the docs here.

I noticed that https://docs.renovatebot.com/configuration-options/#dependencydashboard shows the following table for the `dependencyDashboard` property:

<html><body>

Name | Value
-- | --
type | boolean
default | false

</body>
</html>

I think this is the source of the table above?

https://github.com/renovatebot/renovate/blob/b9d015f025b0505af343d8482d355739b15a796e/lib/config/options/index.ts#L388-L395

Maybe we want/need to change this to `default: true`?

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-08-20 12:37 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +```
This is copy/pasted from the `key-concepts/dashboard.md` file.

2021-08-20 13:12 UTC, rarkins requested changes

2021-08-20 13:12 UTC, rarkins commented on docs/usage/configuration-options.md
> +Starting from version `v26.0.0` the "Dependency Dashboard" is enabled by default via our `config:base` preset.
```suggestion
Starting from version `v26.0.0` the "Dependency Dashboard" is enabled by default as part of the commonly-used `config:base` preset.
```

2021-08-20 14:53 UTC, rarkins approved these changes

2021-08-20 14:53 UTC, merged

2021-08-21 16:07 UTC, renovate-release commented
:tada: This PR is included in version 26.4.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/26.4.1)
- `26.4.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: