gradle @<ext> file extentions
renovatebot/renovate pull request #11541
Opened 2021-09-02 12:37 UTC by t-kulmburg

## Changes:

Before this change, gradle extentions, where the file type is defined behind the version, were not recognized. This PR adds this functionality, but the file extention is not really used to search the dependency.
Dependencies with such a qualifier look like this: `foo.bar:baz:1.2.3@ext`

## Context:

[Issue 11324](https://github.com/renovatebot/renovate/issues/11324)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2021-09-02 12:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=11541) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=11541) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Tobias Kulmburg<br/>:x: t-kulmburg<br/><hr/>**Tobias Kulmburg** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=11541) it.</sub>

2021-09-02 12:45 UTC, viceice requested changes
Please sign CLA, see CLA comment

2021-09-02 15:10 UTC, t-kulmburg commented
I just signed the CLA

2021-09-02 17:00 UTC, viceice commented on lib/manager/gradle/shallow/extract.spec.ts
> +  it('works with file-ext', async () => {
```suggestion

  it('works with file-ext', async () => {
```

Readabillity

2021-09-02 17:00 UTC, viceice commented on lib/manager/gradle/shallow/extract.spec.ts
> +  it('works with file-ext-var', async () => {
```suggestion

  it('works with file-ext-var', async () => {
```

2021-09-02 17:00 UTC, viceice commented on lib/manager/gradle/shallow/extract.spec.ts
>    it('inherits gradle variables', async () => {
```suggestion

  it('inherits gradle variables', async () => {
```

2021-09-06 13:29 UTC, zharinov approved these changes
Looks good to me

2021-09-06 17:42 UTC, viceice approved these changes

2021-09-06 17:49 UTC, merged

2021-09-06 17:59 UTC, renovate-release commented
:tada: This PR is included in version 26.21.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/26.21.0)
- `26.21.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: