fix(util): getHttpUrl is overwriting the username set by platform (fix #11710)
renovatebot/renovate pull request #11764
Opened 2021-09-15 14:05 UTC by uncycler

## Changes:

- Copy user attribute to token when the token is already part of it.
- Fix vscode jest arguments for remote container.

## Context:

The PR #11722 I proposed for fixing #11710 is not working. I'm not sure if it's the good way to do it, but this PR should definitely fix #11710. I've tried with bitbucket, github and gitlab.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2021-09-15 14:11 UTC, viceice requested changes
i think #11760 is a better solution

2021-09-15 14:18 UTC, uncycler commented
Awesome, I missed it. Thanks!

2021-09-16 06:31 UTC, viceice commented
Can you reopen this PR and only make the vscode jest setting please?

2021-09-16 06:33 UTC, viceice commented on lib/util/git/url.spec.ts
> +
```suggestion
```

2021-09-16 06:33 UTC, viceice commented on lib/util/git/url.ts
> +  }
```suggestion
  parsedUrl.token = token;
```

2021-09-16 06:35 UTC, viceice approved these changes

2021-09-16 06:42 UTC, merged

2021-09-16 10:08 UTC, renovate-release commented
:tada: This PR is included in version 27.9.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/27.9.1)
- `27.9.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: