docs: improve ignorePaths config option documentation
renovatebot/renovate pull request #11838
Opened 2021-09-21 16:07 UTC by HonkingGoose

## Changes:

- Make text more descriptive
- Add example of how to use `ignorePaths`
- Explain what `config:base` ignores for you when you extend from it

## Context:

I noticed somebody got very confused with the behavior of the `:ignoreModulesAndTests` preset:

- https://github.com/renovatebot/renovate/issues/11823

I checked our current docs for the `ignorePaths` config option, and it can use a bit of work to make things clearer.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-09-22 05:51 UTC, rarkins requested changes

2021-09-22 05:51 UTC, rarkins commented on docs/usage/configuration-options.md
> +With this setting you can selectively ignore package files that would normally be "autodiscovered" and updated by Renovate.
```suggestion
Renovate will extract dependencies from every file it finds in a repository, unless that file is explicitly ignored.
With this setting you can selectively ignore package files that would normally be "autodiscovered" and updated by Renovate.
```

2021-09-22 05:51 UTC, rarkins commented on docs/usage/configuration-options.md
> +For instance if your repository has an `"**/examples/**"` directory with many `package.json` files that you want to ignore.
```suggestion
For instance if you have a project with an `"**/examples/**"` directory you wish to ignore:
```

2021-09-22 05:51 UTC, rarkins commented on docs/usage/configuration-options.md
> +
```suggestion
```

2021-09-22 05:51 UTC, rarkins commented on docs/usage/configuration-options.md
> +  ]
```suggestion
  "ignorePaths": ["**/examples/**"]
```

2021-09-22 05:51 UTC, rarkins commented on docs/usage/configuration-options.md
```suggestion

Useful to know: Renovate's default ignore is `node_modules` and `bower_components` only, however if you are extending the popular `config:base` preset then it adds ignore patterns for `vendor`, `examples`, `test(s)` and `fixtures` directories too.

```

2021-09-22 08:11 UTC, HonkingGoose commented
Thank you very much @rarkins! That is way better than my text! I've applied all your suggestions.

I wanted to add the explanation of what `config:base` ignores for you, but couldn't find the right words to say so. So thanks again for adding that explanation!

I think this is ready for a new round of review. 😉

2021-09-22 10:55 UTC, rarkins approved these changes

2021-09-22 10:56 UTC, rarkins requested changes

2021-09-22 10:56 UTC, rarkins commented on docs/usage/configuration-options.md
> +For instance if you have a project with an `"**/examples/**"` directory you wish to ignore:
```suggestion
For instance if you have a project with an `"examples/"` directory you wish to ignore:
```

2021-09-22 11:28 UTC, rarkins approved these changes

2021-09-22 11:28 UTC, merged

2021-09-23 07:02 UTC, renovate-release commented
:tada: This PR is included in version 27.16.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/27.16.0)
- `27.16.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: