docs: explain that Renovate automerge takes time
renovatebot/renovate pull request #11855
Opened 2021-09-22 20:14 UTC by HonkingGoose

## Changes:

- Explain that Renovate automerges takes time
- Explain that users should not expect Renovate automerges to happen right away
- Explain that Renovate needs "a gap to merge into the commit highway"

## Context:

Based on discussion: https://github.com/renovatebot/renovate/discussions/11853

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-09-22 20:15 UTC, HonkingGoose commented on docs/usage/key-concepts/automerge.md
> +Wait for at least an hour before troubleshooting.
Feel free to suggest a suitable time-frame that people should wait before starting troubleshooting on... 😉

2021-09-22 20:19 UTC, viceice approved these changes, later dismissed

2021-09-23 07:03 UTC, rarkins requested changes

2021-09-23 07:03 UTC, rarkins commented on docs/usage/key-concepts/automerge.md
> +Wait for at least an hour before troubleshooting.
```suggestion
Wait for at least an hour or two before troubleshooting to ensure that Renovate has had the time to run once in a state where tests have passed and the branch is up-to-date with its base branch.
```

2021-09-23 07:15 UTC, rarkins approved these changes

2021-09-23 07:23 UTC, merged

2021-09-23 11:30 UTC, renovate-release commented
:tada: This PR is included in version 27.17.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/27.17.0)
- `27.17.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: