feat(versioning/semver): add semver-coerced versioning
renovatebot/renovate pull request #11995
Opened 2021-10-04 04:21 UTC by olegkrivtsov

## Changes:

This is my work in progress for issue #5623. I decided to push what I have for now to request some help/review. 

The task was to wrap inputs with `semver.coerce()` and consume them to the API exported by the module. I tried to do that, but ran into problems with unit tests. The problems seem to be related to the way `semver.coerce()` handles the version string. If it finds surrounding text (non-digits), it ignores that text. So, my `isValid()` function doesn't validate the version string correctly. It accepts ranges as well as malformed versions.

For example:

```
isValid('v2') => true // correct
isValid('v2foo') => true // incorrect - this is a malformed version
isValid('~v1.0.0`) => true // incorrect - this is a range
```

Not sure - either I don't understand the task correctly, or `semver.coerce()` is not good for this task. Could you please review my code and advice the best way to move forward?

## Context:

Work in progress #5623

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-10-05 03:55 UTC, rarkins commented
you should not be making any changes to lib/versioning/semver - you should add lib/versioning/semver-coerced

2021-10-05 04:10 UTC, olegkrivtsov commented
Thanks @rarkins. That was not clear from the previous discussion, sorry. I'll do as requested.

2021-10-08 04:06 UTC, rarkins commented
Please use the "request review" option in GitHub in future - no need for comments

2021-10-08 04:10 UTC, rarkins requested changes

2021-10-11 10:40 UTC, rarkins requested changes

2021-10-13 09:48 UTC, rarkins approved these changes

2021-10-20 11:49 UTC, merged

2021-10-20 12:01 UTC, renovate-release commented
:tada: This PR is included in version 28.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/28.3.0)
- `28.3.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: