feat(github): Use native auto-merge when possible
renovatebot/renovate pull request #12045
Opened 2021-10-06 15:45 UTC by zharinov

## Changes:

## Context:

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-10-13 12:05 UTC, rarkins requested changes

2021-10-15 11:43 UTC, rarkins requested changes

2021-10-15 13:10 UTC, rarkins requested changes

2021-10-15 14:00 UTC, rarkins requested changes

2021-10-19 13:58 UTC, rarkins submitted a review, later dismissed

2021-10-19 14:06 UTC, viceice submitted a review, later dismissed
will cause constant logging on some of my github repos 😉

2021-10-19 14:22 UTC, viceice approved these changes
🤷‍♂️ Not sure, i think it should be ok to have this as is.

2021-10-20 02:40 UTC, JamieMagee approved these changes
LGTM

2021-10-20 03:31 UTC, merged