feat: new helmsman manager
renovatebot/renovate pull request #12206
Opened 2021-10-18 19:57 UTC by secustor

## Changes:
Implements support for helmsman desired state configurations if they are written in a YAML file. 

## Context:
Closes #11848

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-10-19 06:45 UTC, viceice requested changes

2021-10-19 07:24 UTC, HonkingGoose requested changes
Let's get started by using one sentence per line.

2021-10-19 07:40 UTC, HonkingGoose requested changes

2021-10-20 04:52 UTC, rarkins requested changes

2021-10-20 08:03 UTC, HonkingGoose requested changes

2021-10-20 08:13 UTC, HonkingGoose submitted a review, later dismissed

2021-10-20 08:19 UTC, rarkins submitted a review, later dismissed

2021-10-21 07:40 UTC, viceice approved these changes

2021-10-21 07:41 UTC, merged