refactor: improve logging when maven resources are not available
renovatebot/renovate pull request #12360
Opened 2021-10-27 15:07 UTC by antonmos

## Changes:

When there is a problem fetching maven resources we see the following errors in the logs:

```
DEBUG: Can't check HTTP resource existence
{
  "failedUrl": "https://<redacted>/clj-http/clj-http/0.1.1/clj-http-0.1.1.pom"
}
DEBUG: Content is not found for Maven url: https://<redacted>/honeysql/honeysql/0.5.3-SNAPSHOT/maven-metadata.xml
```

The lack of status code makes it difficult to understand the root cause, especially when dealing with private maven repos.

## Context:

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-10-27 15:59 UTC, viceice requested changes

2021-10-27 18:21 UTC, viceice submitted a review, later dismissed
@rarkins maybe a good idea to add this to other logs too?

2021-10-28 09:15 UTC, rarkins submitted a review, later dismissed

2021-10-30 02:35 UTC, rarkins approved these changes

2021-10-30 02:43 UTC, merged

2021-10-31 05:31 UTC, renovate-release commented
:tada: This PR is included in version 28.17.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/28.17.1)
- `28.17.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: