feat(config): add supportedBy field to config definitions
renovatebot/renovate pull request #12395
Opened 2021-10-29 10:16 UTC by olegkrivtsov

## Changes:

Add “supportedBy” field to config definitions #2271

## Context:

Closes #2271

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-10-29 10:42 UTC, rarkins requested changes
Needs conflicts resolved

2021-11-01 02:20 UTC, olegkrivtsov commented
Hi @rarkins thanks for this info. I've synced my fork with the upstream repo and resolved the conflicts.

2021-11-01 07:21 UTC, rarkins requested changes
Skip languages (I have suggested removal).

Please also add a test so that `supportedManagers` contains only valid manager and same with `supportedPlatforms`.

2021-11-01 07:21 UTC, rarkins commented on lib/config/options/index.ts
> +    supportedPlatforms: ['github'],
```suggestion
    supportedManagers: ['npm'],
    supportedPlatforms: ['github'],
```

2021-11-01 07:21 UTC, rarkins commented on lib/config/options/index.ts
> +    supportedManagers: ['npm', 'yarn', 'pnpm', 'meteor'],
```suggestion
```

2021-11-01 07:21 UTC, rarkins commented on lib/config/options/index.ts
> +    supportedManagers: ['gomod'],
```suggestion
```

2021-11-01 07:21 UTC, rarkins commented on lib/config/options/index.ts
> +    supportedManagers: ['docker', 'docker-compose'],
```suggestion
```

2021-11-01 07:21 UTC, rarkins commented on lib/config/options/index.ts
> +    supportedManagers: ['pip'],
```suggestion
```

2021-11-01 07:21 UTC, rarkins commented on lib/config/options/index.ts
> +      'poetry',
```suggestion
      'bundler',
      'composer',
      'gomod',
      'npm',
      'pipenv',
      'poetry',
```

2021-11-01 07:21 UTC, rarkins commented on lib/config/options/index.ts
> +    supportedManagers: ['gradle', 'maven'],
```suggestion
```

2021-11-03 05:47 UTC, rarkins approved these changes

2021-11-03 05:48 UTC, merged

2021-11-03 06:00 UTC, renovate-release commented
:tada: This PR is included in version 28.23.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/28.23.0)
- `28.23.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: