docs: Update local-development.md
renovatebot/renovate pull request #12578
Opened 2021-11-09 15:03 UTC by infraredgirl

- Remove incorrect mention of number of steps
- Remove unnecessary `rm` command, since `>` redirect will already remove the file

As an aside, the `yarn start myaccount/therepo --log-level=debug` is giving me 

```error: unknown option '--log-level=debug'```

which seems to be coming form the underlying `node` command. Apparently, `node` does not have the `--log-level` command line option, and I could not find anything similar among existing command line arguments.

2021-11-09 15:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=12578) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=12578) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=12578) it.</sub>

2021-11-09 16:12 UTC, rarkins commented
The --log-level=debug param is incorrect too. We switched to env only (LOG_LEVEL=debug) so that CLI parsing can be debug logged too!

2021-11-09 16:37 UTC, infraredgirl commented
> The --log-level=debug param is incorrect too. We switched to env only (LOG_LEVEL=debug) so that CLI parsing can be debug logged too!

Thanks for the pointer - I'll make an update to address for this!

2021-11-09 17:25 UTC, rarkins requested changes

2021-11-09 17:25 UTC, rarkins commented on docs/development/local-development.md
> +The example command save Renovate's output to the `debug.log` file (and overwrite `debug.log` if it already exists).
```suggestion
The example command will redirect/save Renovate's output to the `debug.log` file (and overwrite `debug.log` if it already exists).
```

2021-11-10 04:50 UTC, JamieMagee commented on docs/development/local-development.md
> +You only need to do these steps this one time.
```suggestion
You only need to do these steps once.
```

2021-11-10 10:47 UTC, rarkins approved these changes

2021-11-10 10:57 UTC, merged

2021-11-10 11:34 UTC, renovate-release commented
:tada: This PR is included in version 29.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/29.4.0)
- `29.4.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: