Terraform bitbucket modules
renovatebot/renovate pull request #12770
Opened 2021-11-19 22:15 UTC by edmeister

## Changes:

Terraform modules using Bitbucket source URL's can benefit from the Bitbucket API functionality when they are parsed as `bitbucket-tags` instead of generic git tags. One of the benefits is that tags and releases are timestamped, which enables the option to use `stabilityDays` (https://docs.renovatebot.com/configuration-options/#stabilitydays) configuration.

## Context:

Closes #12769

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2021-11-24 17:27 UTC, secustor requested changes
some small nitpicks, but else lgtm

2021-11-25 13:12 UTC, edmeister commented on lib/manager/terraform/__fixtures__/1.tf
> +  token   = var.gitlab_token
The string-interpolated variant is no longer clean code since Terraform 0.12, but ok.

2021-11-25 14:18 UTC, secustor approved these changes

2021-11-25 21:06 UTC, merged

2021-11-25 21:23 UTC, renovate-release commented
:tada: This PR is included in version 29.25.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/29.25.0)
- `29.25.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: