feat(config): Make ignore comment configurable
renovatebot/renovate pull request #12917
Opened 2021-12-02 12:46 UTC by infraredgirl

## Changes:

When a PR is closed, Renovate posts a comment to let users know
that future updates will be ignored. This change makes contents of that
comment configurable via the config file.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-12-02 12:55 UTC, rarkins requested changes
I'm wondering if it would be better to use an object for this config, like we do with product links: https://github.com/renovatebot/renovate/blob/e8e99ef5b74a1117f9dc840dc01a4778a7c459ee/lib/config/options/index.ts#L126-L141

It could be called something like `userStrings` and then have fields like `ignoreDigest`, `ignoreMajor`, etc.

2021-12-02 19:49 UTC, infraredgirl commented
Thanks for the review!

> I'm wondering if it would be better to use an object for this config, like we do with product links

Makes total sense. Fixed in https://github.com/renovatebot/renovate/pull/12917/commits/a964e86bff3ecac6a785792bc99f95195eb2f83f.

2021-12-08 13:11 UTC, rarkins approved these changes

2021-12-08 13:11 UTC, merged

2021-12-08 13:38 UTC, renovate-release commented
:tada: This PR is included in version 29.36.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/29.36.0)
- `29.36.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: