fix: add option to disable caching regex
renovatebot/renovate pull request #13068
Opened 2021-12-12 13:20 UTC by RahulGautamSingh

## Changes:

Added an option to disable regex caching
Implemented disable caching on some regex which are constructed using dynamic strings.

## Context:

Fixes #12944 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-12-12 13:31 UTC, rarkins requested changes
Some changes need reverting because they are based of module-level consts or should be cached for other reasons

2021-12-12 13:31 UTC, rarkins commented on lib/config/presets/index.ts
> +      const re = regEx(`{{${arg}}}`, 'g', false); // TODO #12071
```suggestion
      const re = regEx(`{{${arg}}}`, 'g', false);
```

2021-12-12 13:31 UTC, rarkins commented on lib/config/secrets.ts
> +);
Revert all this. It should be cached

2021-12-12 13:31 UTC, rarkins commented on lib/datasource/go/releases-goproxy.ts
> +    : null;
Revert this change as this pattern is unlikely to vary much, or at all

2021-12-12 13:31 UTC, rarkins commented on lib/manager/npm/post-update/index.ts
> +  const re = regEx(`${token}`, 'g', false);
```suggestion
  const tokenRe = regEx(`${token}`, 'g', false);
```

2021-12-12 13:31 UTC, rarkins commented on lib/manager/npm/post-update/index.ts
> +          contents: res.lockFile.replace(re, ''),
```suggestion
          contents: res.lockFile.replace(tokenRe, ''),
```

2021-12-12 13:31 UTC, rarkins commented on lib/manager/pip_requirements/extract.ts
> +  const pkgValRegex = regEx(`^${dependencyPattern}$`, undefined, false);
Revert

2021-12-12 13:31 UTC, rarkins commented on lib/manager/pipenv/extract.ts
> +const specifierRegex = regEx(`^${specifierPattern}$`, undefined, false);
revert

2021-12-12 13:35 UTC, viceice commented on lib/util/regex.ts
> +  flags?: string,
```suggestion
  flags?: string | undefined,
```
Required for strict null checks

2021-12-12 13:35 UTC, viceice commented on lib/config/secrets.ts
> +);
I think this should be cached

2021-12-13 13:56 UTC, RahulGautamSingh commented
```js
export function regEx(pattern: string | RegExp, flags?: string): RegExp {
  const key = `${pattern.toString()}:${flags}`;
 ```
Should we use a default value for flags(maybe an empty string)?
Currently the value is `undefined` incase no value is provided, which doesn't seem to be a good practice.

2021-12-15 07:39 UTC, rarkins commented
> ```js
> export function regEx(
>   pattern: string | RegExp,
>   flags?: string | undefined,
>   useCache = true
> ): RegExp {
>   const key = `${pattern.toString()}:${flags}`; 
> ```
> 
> Should we use a default value for flags(maybe an empty string)? Currently the value is `undefined` incase no value is provided. It makes the stored key look like this `foo:undefined` which doesn't seem to be a good practice.

I think you can make the logic for constructing the key more advanced. e.g. omit the `:` if it's not defined.

2021-12-16 18:52 UTC, RahulGautamSingh commented
> > ```js
> > export function regEx(
> >   pattern: string | RegExp,
> >   flags?: string | undefined,
> >   useCache = true
> > ): RegExp {
> >   const key = `${pattern.toString()}:${flags}`; 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should we use a default value for flags(maybe an empty string)? Currently the value is `undefined` incase no value is provided. It makes the stored key look like this `foo:undefined` which doesn't seem to be a good practice.
> 
> I think you can make the logic for constructing the key more advanced. e.g. omit the `:` if it's not defined.

The current logic to create a key is readable and concise as it covers the 2 parts of a regex i)the pattern and ii)flags.
Changing the logic without a good reason might take the readability away I guess.
So, I have added a ternary operation to remove omit the `:` and `undefined` in absence of flag.

2021-12-17 07:43 UTC, rarkins approved these changes

2021-12-17 08:43 UTC, merged

2021-12-17 09:02 UTC, renovate-release commented
:tada: This PR is included in version 31.4.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.4.1)
- `31.4.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: