docs(bitbucket-cloud): Document required permission scopes
renovatebot/renovate pull request #13179
Opened 2021-12-17 23:06 UTC by maxbrunet

## Changes:

It is the scopes I have identified and been running with. I think this useful to know them when creating the App password and follow the principle of least privilege.

All scopes are documented here:
https://developer.atlassian.com/cloud/bitbucket/rest/intro/#scopes

The name between back-ticks is the actual name of the scope, and between parentheses is how they appear on the "Add App password" page. 

## Context:

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-12-18 05:32 UTC, rarkins approved these changes, later dismissed

2021-12-18 10:21 UTC, HonkingGoose requested changes

2021-12-18 10:21 UTC, HonkingGoose commented on docs/usage/getting-started/running.md
> +Required permission scopes:
```suggestion
Give the bot account the following permission scopes:
```

2021-12-18 22:48 UTC, maxbrunet commented on docs/usage/getting-started/running.md
> +Give the bot account the following permission scopes:
```suggestion
Give the bot App password the following permission scopes:
```

2021-12-19 04:07 UTC, rarkins approved these changes

2021-12-19 04:18 UTC, merged

2021-12-20 05:48 UTC, renovate-release commented
:tada: This PR is included in version 31.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.8.0)
- `31.8.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: