refactor: prepare esm helper
renovatebot/renovate pull request #13250
Opened 2021-12-22 15:14 UTC by viceice

## Changes:
- add `expose.cjs` file to (dynamic) import `package.json` and `re2`;
- I don't like to make the `regEx` async to use dynamic typescript import.
- We can't import json files in esm by default yet, needs node [`--experimental-json-modules`](https://nodejs.org/api/esm.html#no-json-module-loading)

## Context:
- #13181 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-12-22 15:16 UTC, viceice commented on lib/expose.cjs
> +  return require('re2');
We have over 800 references to `regEx`, so i don't like to make it async. so this is a esm workaround, as this file is always interpreted as cjs. 🙃

2021-12-22 15:16 UTC, viceice commented on lib/expose.cjs
> +const pkg = (() => require('../package.json'))();
require can't used in esm, so this workaround

2021-12-22 15:21 UTC, rarkins requested changes

2021-12-22 15:21 UTC, rarkins commented on lib/globals.d.ts
> +  const value: RenovatPackageJson;
```suggestion
  type RenovatePackageJson = import('./types').RenovatePackageJson;
  const value: RenovatePackageJson;
```

2021-12-22 15:21 UTC, rarkins commented on lib/types/base.ts
> +export type RenovatPackageJson = PackageJson & {
```suggestion
export type RenovatePackageJson = PackageJson & {
```

2021-12-22 15:58 UTC, rarkins approved these changes

2021-12-22 16:01 UTC, merged

2021-12-23 08:28 UTC, renovate-release commented
:tada: This PR is included in version 31.12.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.12.0)
- `31.12.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: