chore: log warning for managers which don't support replacements
renovatebot/renovate pull request #13276
Opened 2021-12-24 01:13 UTC by JamieMagee

## Changes:

Add a log message for the managers which don't support replacements yet.

## Context:

https://github.com/renovatebot/renovate/pull/13211#issuecomment-1000171457

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-12-24 05:52 UTC, rarkins submitted a review, later dismissed

2021-12-24 07:20 UTC, viceice submitted a review, later dismissed

2021-12-24 07:21 UTC, viceice commented
I think this should be a fix PR?

2021-12-24 10:32 UTC, astellingwerf requested changes
Two of the managers warnings are very confusing.

2021-12-24 10:32 UTC, astellingwerf commented on lib/manager/maven/update.ts
> +    logger.warn('gomod manager does not support replacement updates yet');
```suggestion
    logger.warn('maven manager does not support replacement updates yet');
```

2021-12-24 10:32 UTC, astellingwerf commented on lib/manager/gradle/shallow/update.ts
> +    logger.warn('maven manager does not support replacement updates yet');
```suggestion
    logger.warn('gradle manager does not support replacement updates yet');
```

2021-12-24 21:39 UTC, JamieMagee commented
> Two of the managers warnings are very confusing.

Thanks! Copy-paste error 🤦

2021-12-24 21:47 UTC, JamieMagee commented
> I think this should be a fix PR?

Changed from `chore` to `fix`

2021-12-27 07:30 UTC, rarkins approved these changes, later dismissed

2022-01-05 15:28 UTC, viceice reviewed
Looks like there's something wrong with the tests. Also some coverage seems missing.

2022-01-14 05:48 UTC, rarkins approved these changes

2022-01-14 06:02 UTC, viceice approved these changes

2022-01-14 06:13 UTC, merged