fix(pr): monorepo changelog with sourceDirectory
renovatebot/renovate pull request #13366
Opened 2022-01-04 13:25 UTC by zanitete

take sourceDirectory into account when removing duplicates

## Changes:

## Context:

## Documentation

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-01-04 14:14 UTC, rarkins requested changes
Please add a test to ensure we don't regress in future

2022-01-04 14:15 UTC, viceice reviewed
I think this needs a test case

2022-01-04 14:15 UTC, viceice commented on lib/workers/pr/index.ts
> +    }${upgrade.sourceDirectory ? `:${upgrade.sourceDirectory}` : ''}`;
`sourceDirectory` should only be used with `sourceUrl`

2022-01-05 10:39 UTC, viceice approved these changes, later dismissed

2022-01-16 10:33 UTC, rarkins commented
@zanitete please update the branch so that status checks can pass

2022-01-28 09:31 UTC, rarkins submitted a review, later dismissed

2022-01-28 10:57 UTC, viceice approved these changes, later dismissed

2022-01-28 11:39 UTC, rarkins commented
@zanitete needs updating from main branch

2022-01-28 13:08 UTC, zanitete commented
👍 done!

2022-01-28 13:17 UTC, viceice approved these changes

2022-01-28 13:18 UTC, viceice commented
> 👍 done!

https://github.com/renovatebot/renovate/blob/main/.github/contributing.md#re-requesting-a-review

2022-01-28 13:49 UTC, merged

2022-01-28 14:11 UTC, renovate-release commented
:tada: This PR is included in version 31.60.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.60.0)
- `31.60.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: