feat(config): Make project name configurable
renovatebot/renovate pull request #13369
Opened 2022-01-04 14:25 UTC by infraredgirl

## Changes: 
Make project name configurable

## Documentation (please check one with an [x])

- [X] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [X] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-01-04 14:30 UTC, viceice requested changes
Please create a feature request, so we know what should be solved with this change.

2022-01-05 15:03 UTC, infraredgirl commented
I created a feature request: https://github.com/renovatebot/renovate/issues/13388. Please let me know your thoughts on this feature request in general, and this implementation in particular!

2022-01-07 11:15 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +The name of this project. Defaults to "Renovate".
```suggestion
The name of this project.
Defaults to "Renovate".
```

Please use our "one sentence per line" pattern.

2022-01-28 09:25 UTC, rarkins requested changes

2022-04-28 07:50 UTC, closed without merging