fix: only update lock files if necessary
renovatebot/renovate pull request #13462
Opened 2022-01-10 12:15 UTC by secustor

only update lock files if necessary when using `update-lockfile`… and missing `updateLockDependency`

## Changes:
Detect if the artifacts are already up to date if running not in `lockfileMaintenance` mode and the manager does not export a `updateLockDependency` function

## Context:
Closes #13363

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

https://github.com/secustor/renovate-flapping-grouped-terraform-updates

2022-01-10 17:41 UTC, viceice reviewed
Otherwise LGTM

2022-01-10 17:41 UTC, viceice commented on lib/workers/branch/get-updated.spec.ts
> +      expect(res).toMatchSnapshot({
Use to equal matcher, as the object is pretty simple

2022-01-10 19:05 UTC, viceice approved these changes

2022-01-10 19:07 UTC, viceice requested changes

2022-01-10 19:07 UTC, viceice commented on lib/workers/branch/get-updated.ts
> +            )) !== file.contents
Wait, the contents can be a buffer (Gradle wrapper) or directory (git submodule).

So that needs to be handled too.

2022-01-10 19:20 UTC, rarkins commented
I have personal painful experience that modifying this type of logic can backfire, so I'd like to review it very carefully before merging

2022-01-28 16:00 UTC, viceice commented on lib/workers/branch/get-updated.ts
> +            (await getFile(
I still think we get into trouble when the file is the gradle wrapper jar. Which is binary.

2022-01-29 06:37 UTC, rarkins commented
How many managers do we have left which support update-lock file but which don't have an updateLockedDependency function?

2022-01-31 17:51 UTC, secustor commented
> How many managers do we have left which support update-lock file but which don't have an updateLockedDependency function?

> - `update-lockfile` = Update the lock file when in-range updates are available, otherwise `replace` for updates out of range. Works for `bundler`, `composer`, `npm`, `yarn`, `terraform` and `poetry` so far

Terraform is the only one

2022-03-25 09:44 UTC, rarkins commented
Sorry, but I'd prefer to avoid this branch worker change only for terraform

2022-03-25 09:44 UTC, closed without merging