docs: baseBranches not working on forking renovate
renovatebot/renovate pull request #13543
Opened 2022-01-13 15:06 UTC by HonkingGoose

## Changes:

- Add note that explains that `baseBranches` is not supported on the Forking Renovate sister app

## Context:

As requested by @rarkins in https://github.com/renovatebot/renovate/issues/7850#issuecomment-1012175098

> @HonkingGoose could you also add this note regarding forking renovate? i.e. that baseBranches it not currently supported

I've also added this as a drawback in the draft PR that adds more information about forking renovate: see #13535.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-01-13 15:45 UTC, viceice submitted a review, later dismissed

2022-01-13 16:07 UTC, rarkins requested changes

2022-01-13 16:07 UTC, rarkins commented on docs/usage/configuration-options.md
> +Note: the `baseBranches` config option is not supported on the Forking Renovate app.
```suggestion
Note: the `baseBranches` config option is not supported when `forkMode` is enabled, including in the Forking Renovate app.
```

2022-01-14 09:02 UTC, merged

2022-01-14 09:17 UTC, renovate-release commented
:tada: This PR is included in version 31.25.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.25.0)
- `31.25.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: