Feat/conflict-detection-cache
renovatebot/renovate pull request #13764
Opened 2022-01-24 07:11 UTC by zharinov

## Changes:

- Add repository-level caching for conflict check results

## Context:

- Ref: #3866
- Ref: #12575

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2022-01-24 16:51 UTC, viceice reviewed
otherwise LGTM

2022-01-24 16:51 UTC, viceice commented on lib/util/git/index.ts
> +  setCachedConflictResult(baseBranch, baseBranchSha, branch, branchSha, result);
Should we unset when we make a new commit ?

2022-01-24 17:11 UTC, viceice submitted a review, later dismissed

2022-01-26 06:48 UTC, rarkins requested changes

2022-01-28 03:06 UTC, zharinov commented on lib/util/git/index.ts
> +  const branchSha = getBranchCommit(branch)?.slice(0, 7);
I think, it would be easier to just use long-form SHA, isn't it?

2022-01-28 07:22 UTC, rarkins approved these changes

2022-01-28 07:24 UTC, rarkins requested changes

2022-01-28 07:24 UTC, rarkins commented on lib/util/git/index.ts
> +    return cachedResult;
```suggestion
    logger.debug(`Using cached result ${cachedResult} for isBranchConflicted(${baseBranch}, ${branch})`);
    return cachedResult;
```

2022-01-28 08:11 UTC, viceice commented on lib/util/git/types.ts
> +interface TargetBranchConflicts {
```suggestion
export interface TargetBranchConflicts {
```
We should export public interfaces when they are already exported implicit

2022-01-28 08:11 UTC, viceice commented on lib/util/git/types.ts
> +interface SourceBranchConflict {
```suggestion
export interface SourceBranchConflict {
```

2022-01-28 08:11 UTC, viceice commented on lib/util/git/types.ts
> +type SourceBranchName = BranchName;
```suggestion
export type BranchName = string;
export type TargetBranchName = BranchName;
export type SourceBranchName = BranchName;
```

2022-01-28 08:44 UTC, rarkins approved these changes

2022-01-28 08:53 UTC, viceice approved these changes

2022-01-28 08:53 UTC, merged

2022-01-28 09:11 UTC, renovate-release commented
:tada: This PR is included in version 31.59.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.59.0)
- `31.59.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: