fix(docker): Skip lookup of dependencies with variable in image name
renovatebot/renovate pull request #13951
Opened 2022-02-01 20:49 UTC by rv2673

## Changes:

- Check for variable in cleaned depName. (Just like with variable check in docker image tag)

## Context:

Closes #13425

This check should be safe since according to [docker documentation](https://docs.docker.com/engine/reference/commandline/tag/#extended-description) it is not valid character in name components segments nor is it an allowed character is hostnames.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-02-01 20:55 UTC, rarkins requested changes

2022-02-01 20:55 UTC, rarkins commented on lib/manager/dockerfile/extract.ts
> +  if (depName && depName.indexOf(variableMarker) !== -1) {
```suggestion
  if (depName?.includes(variableMarker)) {
```

2022-02-01 21:07 UTC, viceice approved these changes

2022-02-02 08:09 UTC, rarkins approved these changes

2022-02-02 08:09 UTC, merged

2022-02-02 08:36 UTC, renovate-release commented
:tada: This PR is included in version 31.65.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.65.3)
- `31.65.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: