feat(manager/pip-compile): support basic arguments
renovatebot/renovate pull request #14098
Opened 2022-02-08 16:39 UTC by msw-kialo

## Changes:

Parse `requirements.txt` file to detect previously used arguments to
call `pip-compile`. Most notably are `--generated-hashes` to support the [Hash-Checking Mode](https://pip-tools.readthedocs.io/en/latest/#using-hashes), and `--allow-unsafe` to [prepare for the planned change](https://pip-tools.readthedocs.io/en/latest/#deprecations).
Furthermore, `--output-file` is supported (but with Renovate's value) as it is commonly used (like by Dependabot).

## Context:

Contribution to #2334

## Open Questions

I wrote this as a minimal viable version (at least for my use-case) to get the discussion starting. I was unsure regarding the following points and would be happy to get comments in the review if needed:

- Better approaches to parse the file (e.g. parsing line based instead of this single regex)?
- How much logging is wanted for this feature (I think it would be good to have a way to figure how why arguments were rejected)?
- Does this need more/higher unit tests?
- Should I allow as many options as possible (like going through the list of currently supported arguments). I haven't used most of them and can't test whether it actually works.
- Some arguments could also be detected/guest by inspecting the `requirements.txt` content itself (like `--hash=` arguments should imply `--generate-hashes` this should also work if `--no-header` or a custom wrapper command is used).
- How much documentation is wanted here?

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2022-02-08 17:09 UTC, viceice commented on lib/manager/pip-compile/artifacts.spec.ts
> +import { git, loadFixture, mocked } from '../../../test/util';
Please use `Fixtures.get`  from `test/fixtures`

2022-02-09 08:23 UTC, HonkingGoose requested changes

2022-02-10 08:21 UTC, viceice commented on lib/manager/pip-compile/artifacts.ts
> +        args.push(`--output-file=${upath.parse(outputFileName).base}`);
I think we should warn if there is a mismatch. We should at least issue an info log message.

2022-02-10 08:21 UTC, viceice commented on lib/manager/pip-compile/artifacts.ts
> +          { argument: argument },
```suggestion
          { argument },
```
Simplify. 😉

2022-02-10 15:40 UTC, viceice commented on lib/manager/pip-compile/artifacts.ts
> +        args.push(`--output-file=${upath.parse(outputFileName).base}`);
```suggestion
        const file = upath.parse(outputFileName).base;
        if (argument !== `--output-file=${file}`) {
          // we don't trust the user-supplied output-file argument; use our value here
          logger.warn(
            { argument },
            'pip-compile was previously executed with an unexpected `--output-file` filename'
          );
        }
        args.push(`--output-file=${file}`);
```

2022-02-10 15:41 UTC, viceice reviewed
I still can't apply my suggestions nor update the branch 🤷‍♂️

2022-02-10 15:42 UTC, viceice commented
Please enable maintainer access checkbox.

2022-02-10 16:57 UTC, viceice approved these changes

2022-02-10 17:30 UTC, merged

2022-02-10 17:52 UTC, renovate-release commented
:tada: This PR is included in version 31.76.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.76.0)
- `31.76.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: