Pin dependencies
renovatebot/renovate pull request #14144
Opened 2022-02-10 17:05 UTC by PhilipAbed

## Changes:

changed the preset for :pinDependencies, as it doesn't support all managers, and is used usually for package.json `dependencies` section/field

## Context:

:pinDependencies doesnt work for all managers
discussion [14126](https://github.com/renovatebot/renovate/discussions/14126)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-02-10 17:17 UTC, viceice approved these changes, later dismissed

2022-02-10 17:39 UTC, HonkingGoose requested changes

2022-02-10 17:39 UTC, HonkingGoose commented on lib/config/presets/internal/default.ts
> +      'Pin dependency versions where depType=dependencies. Usually applies only to non-dev dependencies in <code>package.json</code>',
```suggestion
      'Pin dependency versions where <code>depType=dependencies</code>. Usually applies only to non-dev dependencies in <code>package.json</code>',
```

We can add the `<code>` formatting to `depType=dependencies` as well.

2022-02-13 08:38 UTC, rarkins approved these changes

2022-02-13 08:59 UTC, merged

2022-02-13 09:20 UTC, renovate-release commented
:tada: This PR is included in version 31.81.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.81.2)
- `31.81.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: