Refactor pep440 range.ts
renovatebot/renovate pull request #14210
Opened 2022-02-14 09:48 UTC by Gabriel-Ladzaretti

## Changes:
refactored lib/versioning/pep440/range.ts.

## Context:
related to issue #6241

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:
- [x] Ran existing unit tests.
- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-02-14 13:05 UTC, viceice requested changes
I'd this really a refactor PR or does it change runtime behavior?

2022-02-14 13:05 UTC, viceice commented on lib/versioning/pep440/range.ts
> +  // istanbul ignore next
When does this happen
?

2022-02-14 13:05 UTC, viceice commented on lib/versioning/pep440/range.ts
> +  });
```suggestion
  }).filter(is.nonEmptyString);
```

2022-02-14 16:30 UTC, Gabriel-Ladzaretti commented
this is purely a refactor PR, it shouldn't change any run time behavior.
Did this as a preparation to the needed changes required in #6241 that i want to implement.

2022-02-14 17:25 UTC, viceice commented
> @viceice 
> This is purely a refactor PR, it shouldn't change any runtime behavior.
> Did this as a preparation to the required changes that I want to implement in issue #6241.

Ok, why the test then changed? Simply added test cases? Can't compare without spaces from mobile app.

2022-02-14 17:51 UTC, viceice approved these changes

2022-02-15 07:32 UTC, rarkins approved these changes

2022-02-15 08:41 UTC, merged

2022-02-15 20:05 UTC, renovate-release commented
:tada: This PR is included in version 31.82.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.82.2)
- `31.82.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: