add authentification for submodule update
renovatebot/renovate pull request #14249
Opened 2022-02-16 10:51 UTC by Shegox

## Changes:

Add authentication to `simple-git` using the new GIT Environment variables option.

## Context:

This is only a PoC to share a potential solution; don't merge/review yet.

Fixes #10149

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-02-16 13:27 UTC, viceice requested changes

2022-02-16 13:27 UTC, viceice commented on lib/manager/git-submodules/update.ts
> +import simpleGit from 'simple-git';
Why rename?

2022-02-16 13:27 UTC, viceice commented on lib/manager/git-submodules/update.ts
> +  const hostRules = getAll() || [];
We shouldn't use all hostrules. Instead we should read all submodule urls and check for matching hostrules only.

2022-06-29 14:19 UTC, PhilipAbed commented
Hi @Shegox this is very old, is this still relevant?

2022-10-19 04:53 UTC, rarkins commented
Closing due to staleness

2022-10-19 04:53 UTC, closed without merging