docs(use cases): simplify
renovatebot/renovate pull request #14391
Opened 2022-02-24 11:11 UTC by HonkingGoose

## Changes

- Shorten sentences
- Remove fluff
- Replace difficult words with common words where possible
- Use more lists
- Use more headings
- Use words like "you", "our" and "we"
- Write the docs from the reader's point of view

## Context

I think this is a lot easier to understand than what we had before.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-02-24 15:28 UTC, rarkins requested changes

2022-02-24 15:28 UTC, rarkins submitted a review, later dismissed

2022-02-24 15:44 UTC, HonkingGoose reviewed
Probably should fix this typo.

2022-02-24 15:44 UTC, HonkingGoose commented on docs/usage/getting-started/use-cases.md
> +You can set the time ranges during Renovate create updates in the `schedule` field.
```suggestion
You can set the time ranges during which Renovate creates updates in the `schedule` field.
```

2022-02-24 16:44 UTC, merged

2022-02-25 13:36 UTC, renovate-release commented
:tada: This PR is included in version 31.92.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/31.92.0)
- `31.92.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: