fix(github): Ignore vulnerability alerts in FIXED or DISMISSED states
renovatebot/renovate pull request #14431
Opened 2022-02-26 23:07 UTC by nyg

## Changes

When querying Github's GraphQL API to retrieve vulnerability alerts, only retrieve those that are in OPEN state.

## Context

Closes #14316

The GraphQL request to retrieve vulnerabilities currently ignores their state (OPEN, FIXED or DISMISSED).

Fixed or dismissed vulnerabilities should not be considered as renovate will try to create PRs for these vulnerabilities, when actually the dependencies are already fixed (or the owner has decided they should not be fixed). This will also propose the PRs in the Dashboard issue under "Other branches" or "Ignored or blocked".

It seems this state was added recently, which may explain why this issue was not noticed before.

https://docs.github.com/en/graphql/reference/enums#repositoryvulnerabilityalertstate
https://docs.github.com/en/graphql/overview/changelog (Enum added on Feb 16th, 2022)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

*Note*: I have not written any test for this as this is a feature of Github's GraphQL API. Let me know if I should still be writing a test for it.

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [X] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-02-27 00:49 UTC, viceice requested changes
This will potentially break GHE and needs tests.

2022-02-28 16:38 UTC, rarkins commented
If it's too complicated to add GHE version detection to this, it would be better to undo this change and add the appropriate filtering on our client side instead, so it works with all.

2022-02-28 16:41 UTC, viceice commented
We already know if we on GHE, so check should be easy. We can enable filter on GHE when we know on which GHE version it's available later.

2022-02-28 17:07 UTC, rarkins commented
But the problem this is addressing will still exist on GHE in the meantime?

2022-02-28 17:18 UTC, nyg commented
> If it's too complicated to add GHE version detection to this, it would be better to undo this change and add the appropriate filtering on our client side instead, so it works with all.

Indeed, I think it would be a bit complicated to check for the GHE versions that support of not the new `state` field.

But then, how would you filter on the client side? Because if we add the `state` field to the query, then it's also going to fail with the GHE versions that don't support it.

One option I thought about, but don't know if it's doable, is schema introspection, i.e. to check if the `state` field is present or not, and depending on the result include or not the state field in the query.

> But the problem this is addressing will still exist on GHE in the meantime?

From what I understand, yes.

2022-03-25 10:12 UTC, rarkins commented
Replaced by #14795 (perform ignore on the client side so that it works for GHE too)

2022-03-25 16:33 UTC, rarkins commented
Reopening this, as I changed my mind :)

2022-03-27 10:43 UTC, nyg commented on lib/modules/platform/github/index.ts
> +    '~3.0.25 || ~3.1.17 || ~3.2.9 || ~3.3.4'
Yes, I just pushed the change!

2022-03-27 11:12 UTC, rarkins approved these changes, later dismissed

2022-03-27 12:02 UTC, viceice reviewed
Otherwise LGTM

2022-03-27 12:02 UTC, viceice commented on lib/modules/platform/github/index.spec.ts
> +      expect(httpMock.getTrace()).toMatchSnapshot();
Please remove this. Is obsolete

2022-03-27 14:08 UTC, rarkins submitted a review, later dismissed

2022-03-27 14:33 UTC, viceice reviewed
Needs snapshot update

2022-03-28 12:16 UTC, merged

2022-03-28 12:37 UTC, renovate-release commented
:tada: This PR is included in version 32.9.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.9.0)
- `32.9.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-06-07 07:31 UTC, renovate-release commented
:tada: This issue has been resolved in version 32.76.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.76.3)
- `32.76.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: