feat(argocd): support applicationsets
renovatebot/renovate pull request #14496
Opened 2022-03-03 14:47 UTC by alxbse

## Changes

This adds support for ApplicationSets to the argocd manager. ApplicationSets will be natively supported in ArgoCD from version 2.3.0 onwards. More info on ApplicationSets can be found in the official repository: https://github.com/argoproj/applicationset.

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [X] Both unit tests + ran on a real repository

2022-03-03 15:01 UTC, viceice requested changes

2022-03-03 15:12 UTC, alxbse commented on lib/manager/argocd/__snapshots__/extract.spec.ts.snap
> +      "gs://helm-charts-internal",
I copied the existing tests for the ArgoCD Application type which has this example. I'll update is to https instead.

2022-03-03 15:12 UTC, alxbse commented on lib/manager/argocd/extract.spec.ts
> +      expect(result.deps).toMatchSnapshot();
Same thing, I copied the existing tests. Could you please be more specific here?

2022-03-03 16:01 UTC, alxbse commented on lib/manager/argocd/extract.spec.ts
> +      expect(result.deps).toMatchSnapshot();
Looking at the other tests I think I understand what you mean and I have update accordingly.

2022-03-14 10:16 UTC, viceice approved these changes

2022-03-14 10:31 UTC, merged

2022-03-14 10:55 UTC, renovate-release commented
:tada: This PR is included in version 32.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.4.0)
- `32.4.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: