fix(lib/modules/manager/gitlabci): fixed image regex
renovatebot/renovate pull request #14704
Opened 2022-03-17 09:15 UTC by hasanwhitesource

## Changes

Fixed regex to skip a string if it ends with `:`

## Context

Closes #14340

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-03-17 10:00 UTC, viceice requested changes
Please add a test.

2022-03-17 11:17 UTC, viceice commented on lib/modules/manager/gitlabci/__fixtures__/gitlab-ci.8.yaml
> +job1:
Can't we simply add a new value to existing test instead of crfeating this huge new test?

2022-03-17 11:45 UTC, hasanwhitesource commented
I have removed a few cases and moved the most important check to the `extracts multiple named services` test which I think is the most relevant to this case.

2022-03-17 17:10 UTC, viceice approved these changes

2022-03-20 07:51 UTC, hasanwhitesource commented
@rarkins any updates here?

2022-03-20 08:17 UTC, merged

2022-03-20 08:43 UTC, renovate-release commented
:tada: This PR is included in version 32.6.6 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.6.6)
- `32.6.6`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: