docs: Add Nodenv and .node-version to Node page
renovatebot/renovate pull request #14719
Opened 2022-03-17 19:58 UTC by shaneog

## Changes

Docs: Add Nodenv and .node-version to Node page

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-03-18 09:08 UTC, HonkingGoose requested changes

2022-03-18 09:08 UTC, HonkingGoose commented on docs/usage/node.md
> +- The [`.node-version`](https://github.com/nodenv/nodenv#choosing-the-node-version) file for the [Nodenv](https://github.com/nodenv/nodenv) environment manager
```suggestion
- The [`.node-version`](https://github.com/nodenv/nodenv#choosing-the-node-version) file for the [nodenv](https://github.com/nodenv/nodenv) environment manager
```

The project itself doesn't capitalize their name, so we should follow their example.

2022-03-18 09:48 UTC, HonkingGoose approved these changes
I'm happy with the docs now.

Maintainers need to check if the description is accurate to the code though. 😉

2022-03-18 10:54 UTC, rarkins approved these changes

2022-03-18 10:54 UTC, merged

2022-03-20 08:43 UTC, renovate-release commented
:tada: This PR is included in version 32.6.6 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.6.6)
- `32.6.6`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: