feat: match source urls
renovatebot/renovate pull request #14813
Opened 2022-03-27 09:50 UTC by RahulGautamSingh

## Changes

- Add matchSourceUrls in package rules with tests.
- Add related details in config options & config docs.

## Context

- Ref : #14561 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-03-27 14:11 UTC, rarkins requested changes

2022-03-27 14:11 UTC, rarkins commented on docs/usage/configuration-options.md
> +      "matchSourceUrls": ["https://github.com/facebook/react-native"]
```suggestion
      "matchSourceUrls": ["https://github.com/facebook/react"],
      "groupName": "React"
```

2022-03-27 14:11 UTC, rarkins commented on lib/config/options/index.ts
> +      'A list of source URLs to match against, useful in preventing accidental grouping of packages with similar url prefixes.',
```suggestion
      'A list of source URLs to exact match against.',
```

2022-03-27 14:11 UTC, rarkins commented on lib/util/package-rules.spec.ts
> +            'https://github.com/vuejs/',
This is not a good example as it's not a repo. Use react/react-native instead

2022-03-28 02:29 UTC, rarkins approved these changes

2022-03-28 06:52 UTC, viceice approved these changes

2022-03-28 07:58 UTC, merged

2022-03-28 08:19 UTC, renovate-release commented
:tada: This PR is included in version 32.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.8.0)
- `32.8.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: