fix: set `mergable`=`false` for `ignorePaths` config option
renovatebot/renovate pull request #14946
Opened 2022-04-04 16:49 UTC by HonkingGoose

## Changes

- Add `mergeable` = `false` property for `ignorePaths` config option

## Context

Trying to fix a problem found in discussion: https://github.com/renovatebot/renovate/discussions/14941

Our [docs for the `ignorePaths` config option](https://docs.renovatebot.com/configuration-options/#ignorepaths) do not mention the `mergeable` key.

Please review if I'm making the change in the correct place/file. 😉 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-04-04 17:16 UTC, rarkins commented
Any others which are missing this value?

2022-04-04 17:26 UTC, HonkingGoose commented
I think the [`abortIgnoreStatusCodes` table](https://docs.renovatebot.com/configuration-options/#abortignorestatuscodes) is missing the `mergeable` value as well. There's an admonition that says:

> This field is _not_ mergeable, so the last-applied host rule takes precedence.

2022-04-05 06:25 UTC, viceice requested changes

2022-04-05 17:23 UTC, HonkingGoose commented on lib/config/options/index.ts
> +    mergeable: false,
I don't know how it works right now, but the docs generator should include all relevant fields in the tables. 😄

2022-04-10 07:06 UTC, rarkins commented on lib/config/options/index.ts
> +    mergeable: false,
Let's do it separately

2022-04-10 07:07 UTC, merged

2022-04-10 07:36 UTC, renovate-release commented
:tada: This PR is included in version 32.17.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.17.1)
- `32.17.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-10 08:35 UTC, viceice commented
i remember you, that this doesn't change anything as false is the default value.

2022-04-10 08:52 UTC, HonkingGoose commented
@rarkins and @viceice it sounds like this pull request is the wrong way to fix the problem.

I think @viceice wants to update the docs generating script, so it copies the setting for `mergeable` into the Markdown tables?

2022-04-10 08:54 UTC, viceice commented
> @rarkins and @viceice it sounds like this pull request is the wrong way to fix the problem.
> 
> I think @viceice wants to update the docs generating script, so it copies the setting for `mergeable` into the Markdown tables?

yes, but this PR also don't harm. so please create a new issue to publish mergable settings to the docs. we probably also need a introduction what its meant for.