Rely on versioning for python packages based on package types e.g. git & pypi
renovatebot/renovate pull request #15447
Opened 2022-05-04 11:08 UTC by mikhailadvani

## Changes

Rely on versioning for python packages based on package types e.g. git & pyp

## Context

Closes #15427 #15428 
Alternative to #15428 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-05-04 11:38 UTC, viceice approved these changes

2022-05-04 11:39 UTC, viceice requested changes
please force push with a semantic commit title and update PR title

2022-05-05 03:21 UTC, rarkins requested changes

2022-05-05 03:21 UTC, rarkins commented on lib/config/options/index.ts
> -    default: {
Please set an empty default, i.e. `default: {}`

2022-05-05 09:23 UTC, rarkins approved these changes

2022-05-05 10:28 UTC, mikhailadvani commented
@viceice can you please approve as well

2022-05-05 10:56 UTC, merged

2022-05-05 11:18 UTC, renovate-release commented
:tada: This PR is included in version 32.42.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.42.1)
- `32.42.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-05 14:29 UTC, viceice approved these changes