fix(manager/sbt): handle new line after equalities in the file
renovatebot/renovate pull request #15613
Opened 2022-05-17 10:45 UTC by hasanwhitesource

## Changes

Before parsing we are now replacing '=\n' with '=' at the end of each line to make the parsing work in case of having a definition for a variable and then setting its value in a new line.

## Context

Closes #14846 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-05-18 07:37 UTC, Gabriel-Ladzaretti commented on lib/modules/manager/sbt/extract.ts
> +  const lines = goodContentForParsing.split(regEx(/\n/)).map(stripComment);
```suggestion
  const goodContentForParsing = content.replace(equalsToNewLineRe, '=');
  const lines = goodContentForParsing.split(newlineRegex).map(stripComment);
```

please use `newlineRegex` from `util/regex` module

2022-05-18 15:11 UTC, viceice reviewed
see suggestions, otherwise LGTM

2022-05-19 06:43 UTC, hasanwhitesource commented
@rarkins I think we are done here

2022-05-19 07:20 UTC, zharinov requested changes

2022-05-19 07:20 UTC, zharinov commented on lib/modules/manager/sbt/extract.ts
> +  const equalsToNewLineRe = regEx(/=\s*\n/, 'gm');
```suggestion
  const equalsToNewLineRe = regEx(`=\\s*${newlineRegex.source}`, 'gm');
```

2022-05-19 07:22 UTC, zharinov approved these changes
LGTM

2022-05-19 08:04 UTC, Gabriel-Ladzaretti approved these changes
LGTM

2022-05-20 07:31 UTC, rarkins approved these changes

2022-05-20 07:50 UTC, merged

2022-05-20 08:09 UTC, renovate-release commented
:tada: This PR is included in version 32.64.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.64.1)
- `32.64.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: