docs: move about us file and credit contributors
renovatebot/renovate pull request #15661
Opened 2022-05-20 10:19 UTC by HonkingGoose

## Changes

- Move `about-us.md` file from our docs repo to the main Renovate repo
- Credit:
  - Maintainers 
  - Frequent contributors for smaller parts
  - Helpful contributions, even one-offs
- Bump amount of contributors to Renovate to `600`

## Context

This PR replaces https://github.com/renovatebot/renovatebot.github.io/pull/173.

Closes #11187.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-05-20 11:10 UTC, astellingwerf requested changes
`- [@astellingwerf](https://github.com/astellingwerf) reviews PRs` 😃

2022-05-20 11:10 UTC, astellingwerf commented on docs/usage/about-us.md
> +- [@danports](https://github.com/danports) Worked on the Flux manager, and other managers. Feel free to ping `@danports` for any Flux-related issue or PR.
All other sentences have a lower case letter after the username, and don't end with a full stop, so:
```suggestion
- [@danports](https://github.com/danports) worked on the Flux manager, and other managers. Feel free to ping `@danports` for any Flux-related issue or PR
```

2022-05-23 07:28 UTC, HonkingGoose reviewed
Let's improve the link names.

2022-05-23 07:28 UTC, HonkingGoose commented on docs/usage/about-us.md
> +The source code for Renovate is available on GitHub ([renovatebot/renovate](https://github.com/renovatebot/renovate)).
```suggestion
The source code for Renovate is available on [GitHub at `renovatebot/renovate`](https://github.com/renovatebot/renovate).
```

2022-05-23 07:28 UTC, HonkingGoose commented on docs/usage/about-us.md
> +The Renovate docs are built from Markdown files in [Renovate's Open Source repos](https://github.com/renovatebot/).
```suggestion
The Renovate docs are built from Markdown files in our [`renovatebot/renovate` repository](https://github.com/renovatebot/).
```

2022-05-23 07:28 UTC, HonkingGoose commented on docs/usage/about-us.md
> +Most of the source files can be found in the [main Renovate repository](https://github.com/renovatebot/renovate/tree/main/docs/usage).
```suggestion
Most of the source files can be found in the [`docs/usage/` directory](https://github.com/renovatebot/renovate/tree/main/docs/usage).
```

2022-05-25 07:30 UTC, HonkingGoose commented on docs/usage/about-us.md
> +- [@danports](https://github.com/danports) worked on the Flux manager, and other managers. Feel free to ping `@danports` for any Flux-related issue or PR
```suggestion
- [@danports](https://github.com/danports) worked on the Flux manager, and other managers. Feel free to ping `@danports` for any Flux-related issue or PR
- [@shegox](https://github.com/shegox) worked on the Go manager, and improved our docs
```

2022-05-25 13:03 UTC, astellingwerf commented
See #15729

2022-05-25 15:31 UTC, JamieMagee approved these changes, later dismissed
Thank you ❤️ 

Might require changes due to #15729, but approved to prevent blocking

2022-05-26 04:57 UTC, rarkins approved these changes

2022-05-26 05:07 UTC, merged

2022-05-26 06:20 UTC, renovate-release commented
:tada: This PR is included in version 32.66.5 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.66.5)
- `32.66.5`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: