docs: create key concepts page for pull requests
renovatebot/renovate pull request #15822
Opened 2022-06-01 08:55 UTC by HonkingGoose

## Changes

- Create a Pull Requests key concepts page that explains:
  - why we have immortal PRs in the first place
  - that we use branch name and PR title as cache keys
  - how to get rid of immortal PRs
  - how Renovate finds existing PRs 
  - how Renovate behaves in case of immortal or non-immortal PRs
  - how Renovate can ignore PRs

## Context

Closes #15797.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-06-01 08:57 UTC, HonkingGoose commented on docs/usage/key-concepts/immortal-pull-requests.md
> +...TODO...
@rarkins can you explain how to fix immortal PRs?

I guess the real fix is to get the unique version into the branch name and PR title, so the "cache key" is unique?

2022-06-02 12:44 UTC, rarkins commented
I think we could make this page more generic to talk about Pull Request closing, reuse and immortality

2022-06-02 16:36 UTC, HonkingGoose commented
> I think we could make this page more generic to talk about Pull Request closing, reuse and immortality

Sounds good to me.

@rarkins Can you first push a explanation on how to fix 👻 immortal PRs into my branch? After that's done, I'll make the page more generic by covering:

- [ ] PR closing
- [ ] PR re-use
- [ ] PR immortality

2022-07-06 12:23 UTC, rarkins commented
I think we should have this page a bit more generic and not specific to immortal. e.g. explaining the theory of how Renovate locates existing PRs and how it behaves in case of immortal or non-immortal, ignoring PRs, etc.

2022-07-07 09:29 UTC, HonkingGoose commented
@rarkins I've renamed the file, and created some new sections for the concepts you want to cover.

The next step is that one of the Renovate maintainers fills out my placeholder sections with the correct content. I don't know enough about Renovate's PR handling to do this right.

I'll stop pushing things, so that you maintainers can write new content and push it into my branch. 😉

2022-07-16 06:43 UTC, fregante commented
Will PRs mentioning "Immortal PR" link to this page? The main piece of information I want to know is "How I can disable immortal PRs" which would currently be followed by "You can't"

2022-07-16 07:21 UTC, HonkingGoose commented
> Will PRs mentioning "Immortal PR" link to this page? The main piece of information I want to know is "How I can disable immortal PRs" which would currently be followed by "You can't"

I like this idea, see issue:

- #16611

2022-10-05 12:01 UTC, rarkins requested changes

2022-10-06 14:06 UTC, rarkins approved these changes

2022-10-06 14:07 UTC, merged