Draft: fix: resolve members in groups from CODEOWNERS
renovatebot/renovate pull request #15835
Opened 2022-06-01 18:37 UTC by suprememoocow

## Changes

Resolves groups in CODEOWNERS 

## Context

Closes https://github.com/renovatebot/renovate/issues/14777

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-06-01 18:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=15835) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=15835) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=15835) it.</sub>

2022-06-01 19:17 UTC, viceice requested changes
issue is still on requirements and we don't agreed to any solution. this needs a lot more discussion

2022-06-02 05:53 UTC, suprememoocow commented
> issue is still on requirements and we don't agreed to any solution. this needs a lot more discussion

Fair enough. I stumbled across this issue as it's affecting projects I work on and figured I'd try and propose a fix. I'll close for now.

2022-06-02 05:53 UTC, closed without merging

2022-06-23 00:20 UTC, Wirone commented
@viceice how `issue is still on requirements` when it has `help wanted` label added by @rarkins _after_ our discussion? Wouldn't it be better to just look at this implementation and decide if it actually solves that problem? IMHO I've provided enough information about why it does not work currently and how it should work - as far as I see this PR provides proper changes, but probably some tweaks (and tests) are required.

Anyway, thanks @suprememoocow for working on it! 🍻