feat: add bazel "maybe" macro support
renovatebot/renovate pull request #16003
Opened 2022-06-10 19:15 UTC by jbedard

## Changes

Adding support for the [maybe](https://docs.bazel.build/versions/0.29.1/repo/utils.html#maybe) function.

## Context

This is a util function recommended instead of always wrapping imports in `if`.

IMO there's probably a better way of doing this by making the lexer more specific/realistic instead of just matching any type of import as a giant string. That's probably a bigger change for another time though...

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-06-10 19:24 UTC, jbedard commented
Is there an easy way of testing this in another repo? I'd like to test it in a real environment and not just the unit tests...

FYI @alexeagle

2022-06-10 19:40 UTC, alexeagle commented
Some add'l background for maintainers here: the "maybe" function is defined here:
https://github.com/bazelbuild/bazel/blob/6530488ba1914645b1e24f9c6f132ecf5f8a2ccb/tools/build_defs/repo/utils.bzl#L218-L233

It can be pretty trivially inlined, so the workaround for all Bazel users until we have this feature is to de-sugar it like:
https://github.com/aspect-build/rules_py/pull/60

2022-06-11 05:20 UTC, rarkins approved these changes, later dismissed

2022-06-11 06:20 UTC, zharinov requested changes

2022-06-11 06:20 UTC, zharinov commented on lib/modules/manager/bazel/extract.ts
> +          ')\\s*\\('
Parens should be handled somewhere else

```suggestion
        [
          'container_pull',
          'http_archive',
          'http_file',
          'go_repository',
          'git_repository',
          'maybe',
        ].join('|')
```

2022-06-11 06:24 UTC, zharinov submitted a review, later dismissed

2022-06-11 07:47 UTC, viceice commented
needs null check fix

2022-06-22 06:02 UTC, rarkins approved these changes

2022-06-22 06:16 UTC, merged

2022-06-22 06:41 UTC, renovate-release commented
:tada: This PR is included in version 32.93.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.93.0)
- `32.93.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: