refactor: move update internal deps to lookup
renovatebot/renovate pull request #16059
Opened 2022-06-14 00:59 UTC by RahulGautamSingh

## Changes
- move `updateInternalDeps` to lookup

## Context
- @viceice 's [comment](https://github.com/renovatebot/renovate/pull/16020#discussion_r895752514)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-06-14 04:29 UTC, rarkins requested changes

2022-06-14 04:29 UTC, rarkins commented on lib/workers/repository/process/fetch.ts
> +  if (!packageFileConfig.updateInternalDeps && dep.isInternal) {
Reverse the ordering here

2022-06-14 04:29 UTC, rarkins commented on lib/workers/repository/process/fetch.spec.ts
> +      expect(packageFiles).toMatchSnapshot();
Avoid using only snapshots. Write an explicit test instead

2022-06-14 18:43 UTC, viceice approved these changes

2022-06-15 04:11 UTC, rarkins approved these changes

2022-06-15 04:21 UTC, merged