refactor(modules/datasource): fix null-check issues
renovatebot/renovate pull request #16153
Opened 2022-06-20 10:51 UTC by RahulGautamSingh

## Changes
- Strict null check implementation

## Context
- #7154
- requires #16150

2022-06-20 11:17 UTC, viceice requested changes

2022-06-20 11:17 UTC, viceice commented on lib/modules/datasource/cdnjs/index.spec.ts
> +        .reply(200, null as never);
null isn't allowed / valid
```suggestion
        .reply(200);
```

Use this to force got to throw an error
```suggestion
        .reply(200, '{');
```

2022-06-20 11:17 UTC, viceice commented on lib/modules/datasource/clojure/index.spec.ts
> +      .reply(404, null as never);
see other comment

2022-06-20 12:35 UTC, viceice reviewed
some suggestions

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/dart/index.spec.ts
> +        .reply(200, null as never);
```suggestion
      httpMock.scope(baseUrl).get('/non_sense').reply(200, '}');
```

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/datasource.spec.ts
> +    return Promise.resolve(undefined as never);
use `null`, is it's the allowed value
https://github.com/renovatebot/renovate/blob/9e28ef32752536501af3fbff8a63ccbe5343591c/lib/modules/datasource/types.ts#L78

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/datasource.spec.ts
> +    ).rejects.toThrow(EXTERNAL_HOST_ERROR);
```suggestion
    await expect(
      testDatasource.getReleases(partial<GetReleasesConfig>({}))
    ).rejects.toThrow(EXTERNAL_HOST_ERROR);
```

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/galaxy-collection/index.spec.ts
> +          depName: null as never,
```suggestion
          depName: '',
```

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/git-refs/index.spec.ts
> +          return Promise.resolve(null) as unknown as Response<string>;
```suggestion
          return Promise.resolve('') as Response<string>;
```

https://github.com/renovatebot/renovate/blob/de70ecad0409d99e3ae548deac7c6ef3e662b02d/lib/modules/datasource/git-refs/base.ts#L33-L38

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/git-tags/index.spec.ts
> +          return Promise.resolve(null) as unknown as Response<string>;
```suggestion
          return Promise.resolve('') as Response<string>;
```

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/github-releases/common.spec.ts
> +      const sourceUrl = getSourceUrlBase(null as never);
```suggestion
      const sourceUrl = getSourceUrlBase(undefined);
```

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/github-tags/index.spec.ts
> +      const res = await github.getDigest({ packageName }, null as never);
```suggestion
      const res = await github.getDigest({ packageName }, undefined);
```

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/github-tags/index.spec.ts
> +      const res = await github.getDigest({ packageName }, null as never);
```suggestion
      const res = await github.getDigest({ packageName }, undefined);
```

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/github-tags/index.spec.ts
> +        null as never
```suggestion
        undefined
```

2022-06-20 12:35 UTC, viceice commented on lib/modules/datasource/go/releases-goproxy.spec.ts
> +      expect(datasource.parseGoproxy(null as never)).toBeEmpty();
```suggestion
      expect(datasource.parseGoproxy(undefined)).toBeEmpty();
```

2022-06-20 12:43 UTC, viceice commented on lib/modules/datasource/conan/index.spec.ts
> +        .reply(200, null as never);
```suggestion
        .reply(200);
```
Will this work?

2022-06-20 12:45 UTC, RahulGautamSingh commented on lib/modules/datasource/conan/index.spec.ts
> +        .reply(200, null as never);
it should.

2022-06-20 14:24 UTC, viceice approved these changes

2022-06-20 14:24 UTC, merged

2022-06-21 06:06 UTC, renovate-release commented
:tada: This PR is included in version 32.91.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.91.2)
- `32.91.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: