fix: update default dependencyDashboardHeader
renovatebot/renovate pull request #16206
Opened 2022-06-23 12:41 UTC by HonkingGoose

## Changes

- Update the default `dependencyDashboardHeader`
  - Use plain language
  - Use a better name for the link
  - Ends the last sentence with a full stop

## Context

Closes #15322.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-06-24 05:51 UTC, rarkins requested changes

2022-06-24 05:51 UTC, rarkins commented on lib/config/options/index.ts
> +      'This issue lists all Renovate updates and their statuses. It also shows the dependencies that Renovate detected in your repository. Read the [Dependency Dashboard](https://docs.renovatebot.com
```suggestion
      'This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.',
```

2022-06-24 08:55 UTC, HonkingGoose commented on lib/config/options/index.ts
> +      'This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.',
I don't know how to fix this warning. I'll let the maintainers decide what we should do here. 😉

2022-06-24 10:42 UTC, rarkins approved these changes

2022-06-25 12:51 UTC, HonkingGoose commented
We still need to fix the warning before this can be merged?

2022-06-27 19:25 UTC, viceice approved these changes

2022-06-28 02:36 UTC, merged

2022-06-28 03:00 UTC, renovate-release commented
:tada: This PR is included in version 32.99.7 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.99.7)
- `32.99.7`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: