fix(http): support asset download via octet-stream header in github http
renovatebot/renovate pull request #16255
Opened 2022-06-27 05:35 UTC by lyonlai

## Changes

As part of the Hermit manager feature from #16250, this PR contains the changes that make github http able to download private repo's release asset by specifying `application/octet-stream` in the `accept` header.

## Context

Issue: #16119
PR: #16250

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [X] Both unit tests + ran on a real repository

2022-06-27 06:59 UTC, zharinov requested changes
Thank you @lyonlai for small-scoped PRs

2022-06-27 06:59 UTC, zharinov commented on lib/util/http/github.spec.ts
> +      );
```suggestion
      const content = 'foobar';
      hostRules.add({ hostType: 'github', token: 'x-access-token:123test' });
      httpMock
        .scope(githubApiHost)
        .get('/repos/some-owner/some-repo/releases/tags/some-tag')
        .reply(200, Buffer.from(content, 'utf-8'), {
          'content-type': 'application/octet-stream',
          'content-length': `${content.length}`,
          'content-disposition': 'attachment; filename=reply_file_2.tar.gz',
        });

      const res = await githubApi.get(
        '/repos/some-owner/some-repo/releases/tags/some-tag',
        {
          headers: { accept: 'application/octet-stream' },
        }
      );

      expect(res.body).toBe('foobar');
```

2022-06-27 07:15 UTC, zharinov approved these changes, later dismissed

2022-06-27 08:49 UTC, viceice requested changes

2022-06-27 08:49 UTC, viceice commented on lib/util/http/github.spec.ts
> +      );
This looks wrong, as `Http.get` returns string type. I don't like this, as we again have wrong runtime types.

Can't you use `Http.stream()` for binary downloads instead? So you can directly pipe it to a files, like we do for terraform binaries hash computation ?

https://github.com/renovatebot/renovate/blob/f5f06c73be8c5b29f3458c40bc0d18259685296e/lib/modules/manager/terraform/lockfile/hash.ts#L75-L79

or bazel hash

https://github.com/renovatebot/renovate/blob/10302eba68fba11b8e6aa667529d64d708a54d97/lib/modules/manager/bazel/update.ts#L59-L61

2022-06-29 05:09 UTC, viceice commented on lib/util/http/index.ts
> +    let combinedOptions: any = {
```suggestion
    // TODO: fix types (#7154)
    let combinedOptions: any = {
```

2022-06-29 05:09 UTC, viceice approved these changes

2022-06-30 07:54 UTC, merged

2022-06-30 08:18 UTC, renovate-release commented
:tada: This PR is included in version 32.100.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.100.3)
- `32.100.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: