chore(docs): Suggest to let Renovate bypass mandatory Pull Request
renovatebot/renovate pull request #16370
Opened 2022-07-01 16:24 UTC by Shegox

## Changes

This PR recommends that users should add Renovate to the list of users, which are allowed to bypass mandatory Pull Request instead of installing the auto-approve App. 
This has the advantage that no additional App is required. In the long term, renovate-approve could be deprecated in favor of this approach overall.

## Context

GitHub added this new feature in November 2021 and I couldn't find it yet in the Renovate docs.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

Merging without approval: https://github.com/tobias-something-something/automerge-test/pull/3
<img width="712" alt="image" src="https://user-images.githubusercontent.com/16856448/176933299-800a0526-9a32-4922-b2eb-8e0f3eb28840.png">
although required PRs are configured
<img width="604" alt="image" src="https://user-images.githubusercontent.com/16856448/176933401-cedbe694-45c6-445b-aeee-dd08413df177.png">

2022-07-01 16:39 UTC, HonkingGoose commented
> GitHub added this new feature in November 2021 and I couldn't find it yet in the Renovate docs.

You're totally right! 😉 I created an issue to figure out how to describe the branch protection exception for Renovate in our docs:

- https://github.com/renovatebot/renovate/issues/15659

The problem is that we should probably change more than just add a single line somewhere in the docs. And also, if we tell our users to add Renovate bot as an exception, it should work for `automerge=pr` and `automerge=branch`.

2022-07-01 16:46 UTC, Shegox commented
> > GitHub added this new feature in November 2021 and I couldn't find it yet in the Renovate docs.
> 
> You're totally right! 😉 I created an issue to figure out how to describe the branch protection exception for Renovate in our docs:
> 
> * [Renovate bot can be excepted from branch protection rules on GitHub #15659](https://github.com/renovatebot/renovate/issues/15659)
> 
> The problem is that we should probably change more than just add a single line somewhere in the docs. And also, if we tell our users to add Renovate bot as an exception, it should work for `automerge=pr` and `automerge=branch`.

I searched if there was an issue already open for this, but missed that one. 😅 

In my test, a PR merge worked.

2022-07-01 19:00 UTC, rarkins commented on docs/usage/key-concepts/automerge.md
Good to mention both, seeing as the GitHub feature is new and we're not 100% sure it's superior in every way

2022-07-01 19:17 UTC, Shegox commented
And testing using `autoMergeType: branch` via https://github.com/tobias-something-something/automerge-test/commit/b5df255050fc972f95cf42714e1c7c5584d6e42c, works as well as expected.

So overall it seems to work for all my tested cases: branch and PR and even works, if "Require review from Code Owners" is enabled: 
<img width="745" alt="image" src="https://user-images.githubusercontent.com/16856448/176956593-4e662c57-ad85-47ee-a4b5-bc2c7628246f.png">

2022-07-02 06:33 UTC, rarkins submitted a review, later dismissed

2022-07-02 06:59 UTC, HonkingGoose requested changes
Small style change.

2022-07-02 06:59 UTC, HonkingGoose commented on docs/usage/key-concepts/automerge.md
> +If you're on `github.com` or GitHub Enterprise Server (>=3.4) you can let Renovate bypass the mandatory Pull Request reviews using the "[Allow specified actors to bypass required pull requests](https
```suggestion
If you're on `github.com` or GitHub Enterprise Server (`>=3.4`) you can let Renovate bypass the mandatory Pull Request reviews using the "[Allow specified actors to bypass required pull requests](https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/)" option in your branch protection rules.
```

2022-07-02 07:33 UTC, HonkingGoose approved these changes

2022-07-02 09:12 UTC, merged

2022-07-02 09:36 UTC, renovate-release commented
:tada: This PR is included in version 32.103.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.103.0)
- `32.103.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: