Update the configuration-options documentation with a CodePen for validating whether a later.js schedule is valid or not.
renovatebot/renovate pull request #16431
Opened 2022-07-06 03:06 UTC by paulzakin

## Changes

- Update the configuration-options documentation with a CodePen for validating whether a later.js schedule is valid or not.

## Context

I think for individuals who aren't familiar with later.js (like me!), it can be difficult to tell whether a `schedule` is valid. Plus, I found their documentation was missing some sort of "demo" feature. Hence, I wiped up a quick CodePen to validate whether the proposed schedule is valid. It also lists the next two occurences in that schedule. I found this very helpful in reaching an intuitive understanding of how the schedules worked, and it may be helpful to other users as well.

> Happy to transfer/surrender ownership of the CodePen to renovate as needed. 

## Documentation (please check one with an [x])

- [X] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [X] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-07-06 04:26 UTC, rarkins commented
One challenge here - Renovate accepts only a *subset* of Later.js schedules. For example the default "every 5 minutes" is not a valid Renovate schedule. Can this codepen be made to mimic what Renovate considers valid?

2022-07-06 04:43 UTC, paulzakin commented
@rarkins No promises but happy to take a look at modifying it! 

Any pointers on where in the codebase should I look for that Renovate-flavored Later.js? Happy to look myself, but appreciate any points in the right direction!

2022-07-06 05:50 UTC, rarkins commented
The logic is all in https://github.com/renovatebot/renovate/blob/main/lib/workers/repository/update/branch/schedule.ts

2022-07-06 06:59 UTC, HonkingGoose requested changes

2022-07-06 07:30 UTC, paulzakin commented
> The logic is all in https://github.com/renovatebot/renovate/blob/main/lib/workers/repository/update/branch/schedule.ts

Awesome will take a look

2022-07-06 07:31 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +
```suggestion
```

Drop this double newline. 😄

2022-07-07 16:57 UTC, paulzakin commented
Alright, updated with the rules - take a look:

https://codepen.io/rationaltiger24/pen/ZExQEgK

2022-07-08 05:47 UTC, rarkins commented
> By I assume Rennovate would not run every minute under this configuration? Or am I missing something?

That's right. Schedules do not *trigger* Renovate to run. Instead, if Renovate is running AND the schedule matches at that time, then it will create branches/PRs.

2022-07-08 12:21 UTC, paulzakin commented
> > By I assume Rennovate would not run every minute under this configuration? Or am I missing something?
> 
> That's right. Schedules do not _trigger_ Renovate to run. Instead, if Renovate is running AND the schedule matches at that time, then it will create branches/PRs.

That makes sense, but what triggers Renovate to run, assuming it is a GitHub app that is installed

2022-07-08 12:22 UTC, viceice commented
> > > By I assume Rennovate would not run every minute under this configuration? Or am I missing something?
> > 
> > 
> > That's right. Schedules do not _trigger_ Renovate to run. Instead, if Renovate is running AND the schedule matches at that time, then it will create branches/PRs.
> 
> That makes sense, but what triggers Renovate to run, assuming it is a GitHub app that is installed

It tries to run hourly ba default and reduces cycles if no activity on repo. You can always trigger a run from dependency dashboard.

2022-07-08 12:25 UTC, paulzakin commented
> > > > By I assume Rennovate would not run every minute under this configuration? Or am I missing something?
> > > 
> > > 
> > > That's right. Schedules do not _trigger_ Renovate to run. Instead, if Renovate is running AND the schedule matches at that time, then it will create branches/PRs.
> > 
> > 
> > That makes sense, but what triggers Renovate to run, assuming it is a GitHub app that is installed
> 
> It tries to run hourly by default and reduces cycles if no activity on repo. You can always trigger a run from dependency dashboard.

Perfect that makes sense to me!

2022-07-09 06:52 UTC, rarkins approved these changes

2022-07-09 07:03 UTC, merged

2022-07-09 07:27 UTC, renovate-release commented
:tada: This PR is included in version 32.108.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.108.0)
- `32.108.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: