feat(gradle): add support for further apply-from patterns
renovatebot/renovate pull request #16507
Opened 2022-07-10 14:31 UTC by Churro

## Changes

- Adds support for more patterns that are commonly used with `apply from`:
  ```
  apply from: new File(somedir, "${otherdir}/foo.gradle")
  apply(from = File(base, "bar.gradle"))
  apply from: project.file("${somedir}/foo.gradle")
  apply from: rootProject.file("${somedir}/foo.gradle")
  ```
- For `File`, support is added for all possible constructors except URIs (see [here](https://developer.android.com/reference/kotlin/java/io/File#summary) and [here](https://docs.oracle.com/javase/8/docs/api/java/io/File.html))

## Context

- PR https://github.com/renovatebot/renovate/pull/16030

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-07-10 15:27 UTC, zharinov requested changes

2022-07-10 15:27 UTC, zharinov commented on lib/modules/manager/gradle/parser.ts
> +    scriptFile = upath.join(parentPath, scriptFile);
Just in case:

```suggestion
    if (parentPath && scriptFile) {
      scriptFile = upath.join(parentPath, scriptFile);
    }
```

2022-07-10 15:38 UTC, Churro commented on lib/modules/manager/gradle/parser.ts
> +    scriptFile = upath.join(parentPath, scriptFile);
Good catch, thanks! 👍

2022-07-10 15:50 UTC, zharinov approved these changes

2022-07-19 19:31 UTC, Churro commented
@rarkins or @viceice, could one you please review? 😊

2022-07-19 19:35 UTC, viceice approved these changes

2022-07-20 05:32 UTC, rarkins approved these changes

2022-07-20 05:45 UTC, merged

2022-07-20 06:08 UTC, renovate-release commented
:tada: This PR is included in version 32.120.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.120.0)
- `32.120.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: