fix(datasource/go): consider all available datasources for go-import
renovatebot/renovate pull request #16544
Opened 2022-07-12 12:03 UTC by tessig

## Changes

For go modules behind a proxy, the source is given via meta tag `go-import`. For the moment, only Github is supported as datasource.
This uses the datasource selection already in place for the old `go-source` tag and falls back to the hardcoded github, if no datasource was found.

## Context

Closes #16543

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2022-07-13 04:34 UTC, rarkins commented
Hi, thanks for the PR. What's the next step here? I'm a little confused as I was expecting to see `go-import` and/or `go-source` strings within the changes

2022-07-13 07:37 UTC, tessig commented
Hi, the checks for `go-source` and `go-import` are already there (lines 75 and 162). I just moved the datasource detection from `goSourceHeader` func to a separate function and reused it in `goImportHeader`.

Next steps are:
* add a test case to `base.spec.ts`
* set up a public example

2022-07-19 05:21 UTC, rarkins commented
Is the test repository meant to show an *error*? I.e. the non working case and not the working case?

2022-07-19 07:47 UTC, tessig commented
Yes, the test repo shows the current state. Was unsure if you wanted to see both results.
But I just ran this branch against the test repository.

2022-07-19 09:12 UTC, rarkins commented
Are there any public go modules/packages this can be tested against?

2022-07-19 09:30 UTC, rarkins commented
Yes but if you wrote both the code and the test then it's possible both are wrong. It would be entirely possible that your new code works with no module in the world except the one you wrote specifically to test against. Is there really no publicly available module (a "real" package) which benefits from this fix?

2022-07-24 07:03 UTC, rarkins requested changes

2022-07-24 07:03 UTC, rarkins commented on lib/modules/datasource/go/base.ts
> +    if (datasource === null) {
```suggestion
    if (datasource !== null) {
      return datasource;
    }
```

Return early to reduce white space

2022-07-27 06:23 UTC, rarkins approved these changes

2022-07-27 06:40 UTC, zharinov approved these changes

2022-07-27 07:13 UTC, viceice approved these changes

2022-07-27 07:13 UTC, merged

2022-07-27 07:35 UTC, renovate-release commented
:tada: This PR is included in version 32.131.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.131.2)
- `32.131.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: