Add more Nestjs Repositories
renovatebot/renovate pull request #16668
Opened 2022-07-20 15:51 UTC by Xyaren

## Changes

Added several NestJs Repositories similar to #16520.

## Context

Nestjs dependencies are updateable on their own most times.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-07-21 05:19 UTC, rarkins approved these changes, later dismissed

2022-07-21 09:49 UTC, SchroederSteffen commented
I was also thinking about adding more repositories. I hesitated to do so, because they use different major versions and I wasn't sure if this causes issues. E.g. `@nestjs/swagger` is on `6.x` while the core packages are on `9.x`.

Instead of listing them all, we could also just use the prefix `https://github.com/nestjs`, no?

2022-07-22 07:33 UTC, Xyaren commented
Although they are using different major versions they are quite strong coupled. Currently I have two separate Merge Requests from Renovate which are both failing, one for nest-monorepo, one for swagger.

2022-07-22 07:38 UTC, viceice requested changes
I think they should only be grouped for major updates then. something like we to with ts-jest.
https://github.com/renovatebot/renovate/blob/4953abf7caccaf0b07ea708550e33e6b6526e47b/lib/config/presets/internal/group.ts#L642-L651

2022-07-22 12:55 UTC, Xyaren commented
Should I do this for all the nestjs modules ?

2022-07-22 13:42 UTC, viceice commented
yes, the first one

2022-07-22 13:50 UTC, Xyaren commented
Should I remove the nestsjs monorepo defenition then ? 
The group would cover all the modules already right ?

2022-07-22 14:14 UTC, viceice commented
If the core newjs repo published multiple packages, it should stay as a single monorepo

2022-07-24 07:33 UTC, viceice commented on lib/config/presets/internal/group.ts
> +  nestjsMajor: {
i think you also need to update the `groupRecommend` preset above

2022-08-29 20:28 UTC, viceice commented on lib/config/presets/internal/group.ts
> +  nestjsMajor: {
☝️

2022-10-19 05:14 UTC, rarkins requested changes

2022-10-19 05:14 UTC, rarkins commented on lib/config/presets/internal/monorepo.ts
> -    'https://github.com/nestjs/terminus',
Why not group these anymore?

2022-10-19 05:14 UTC, rarkins commented on lib/config/presets/internal/group.ts
> +        matchUpdateTypes: ['major'],
Why only group if the updates are major?

2022-10-19 07:10 UTC, closed without merging