fix(manager/nuget): optimize xml error handling
renovatebot/renovate pull request #16681
Opened 2022-07-21 10:56 UTC by viceice

## Changes
- catch xml errors 

## Context
- fixes #16656

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-07-21 14:56 UTC, zharinov requested changes

2022-07-21 14:56 UTC, zharinov commented on lib/modules/manager/nuget/package-tree.spec.ts
> +    });
Let's remove unrelated circular dependency handling

```suggestion
    it('throws error on invalid xml file', async () => {
      git.getFileList.mockResolvedValue(['foo/bar.csproj']);
      Fixtures.mock({ '/tmp/repo/foo/bar.csproj': '<invalid' });

      await expect(getDependentPackageFiles('foo/bar.csproj')).rejects.toThrow(
        'Invalid xml file: foo/bar.csproj'
      );
    });
```

2022-07-22 06:56 UTC, zharinov approved these changes

2022-07-22 07:03 UTC, rarkins approved these changes

2022-07-22 07:15 UTC, merged

2022-07-22 07:38 UTC, renovate-release commented
:tada: This PR is included in version 32.122.4 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.122.4)
- `32.122.4`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: