docs(regex): clarify regex manager limitations
renovatebot/renovate pull request #16709
Opened 2022-07-22 15:18 UTC by foolioo

## Changes

No behavioral changes, only adding more information to the docs.

## Context

Regex manager has few limitations that do no appear in the documentation and were revealed during issues and discussions. To save others some time in the future, the information was added to the docs.

Relates to #16696, #10284

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-07-22 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=16709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=16709) before we can accept your contribution.<br/><hr/>**x** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=16709) it.</sub>

2022-07-23 09:51 UTC, HonkingGoose requested changes
>  you should be aware when using the `^` and/or `$` regex assertions.

It feels like something important is left out here. Is it clear to regex users what they should _do_ based on this "be aware" text?

2022-07-23 09:51 UTC, HonkingGoose commented on lib/modules/manager/regex/readme.md
> +The Regex manager is using [RE2 which does not support backreferences and lookahead assertions](https://github.com/uhop/node-re2#limitations-things-re2-does-not-support). The Regex manager matches ar
```suggestion
The `regex` manager uses RE2 which does not support [backreferences and lookahead assertions](https://github.com/uhop/node-re2#limitations-things-re2-does-not-support).
The `regex` manager matches are done per-file and not per-line, you should be aware when using the `^` and/or `$` regex assertions.
```

Changes:

- Use `monospace` style for the `regex` manager
- Replace `is using` -> `uses`
- Use one sentence per line
- Shorten the link text

2022-07-24 05:51 UTC, rarkins approved these changes

2022-07-24 06:25 UTC, merged

2022-07-24 06:53 UTC, renovate-release commented
:tada: This PR is included in version 32.126.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.126.0)
- `32.126.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: