Docs: Gitea account must have full name set for Git identity
renovatebot/renovate pull request #16792
Opened 2022-07-26 19:28 UTC by rom4nik

## Changes

https://github.com/renovatebot/renovate/discussions/16323#discussioncomment-3046928 - adding that to docs.

## Context

As a new user of Renovate I had to spend a bit too much time to realize my bot account just needed full name set, since it's pulled from Gitea API.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-07-26 19:42 UTC, viceice requested changes

2022-07-26 19:42 UTC, viceice commented on lib/modules/platform/gitea/index.md
> +First, [create a Personal Access Token](https://docs.gitea.io/en-us/api-usage/#authentication) for the bot account. Let Renovate use your PAT by doing _one_ of the following:
```suggestion
First, [create a Personal Access Token](https://docs.gitea.io/en-us/api-usage/#authentication) for the bot account.
Let Renovate use your PAT by doing _one_ of the following:
```
revert, we prefer one sentence per line

2022-07-26 19:42 UTC, viceice commented on lib/modules/platform/gitea/index.md
> +Remember to set `platform=gitea` somewhere in your Renovate config file. The account must have full name (and email address) set to allow Renovate to estabilish Git identity.
```suggestion
Remember to set `platform=gitea` somewhere in your Renovate config file.
The account must have full name (and email address) set to allow Renovate to estabilish Git identity.
```
or set `gitAuthor` config option.

2022-07-27 15:59 UTC, viceice approved these changes

2022-07-27 17:04 UTC, HonkingGoose approved these changes

2022-07-27 17:33 UTC, merged

2022-07-28 10:52 UTC, renovate-release commented
:tada: This PR is included in version 32.131.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.131.3)
- `32.131.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: