feat(platform/gitea): support draft PR
renovatebot/renovate pull request #16888
Opened 2022-08-01 09:01 UTC by viceice

## Changes

## Context
- closes #12717

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-08-01 09:08 UTC, HonkingGoose requested changes

2022-08-01 09:08 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +    GitLab and Gitea implements draft status by checking whether the PR's title starts with certain strings.
```suggestion
    GitLab and Gitea implement draft status by checking if the PR's title starts with certain strings.
```

- `Implement` is singular here
- Replace `whether` with `if`

2022-08-02 08:21 UTC, rarkins approved these changes

2022-08-02 09:47 UTC, merged

2022-08-02 10:11 UTC, renovate-release commented
:tada: This PR is included in version 32.139.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.139.0)
- `32.139.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: