docs(platformAutomerge): recommend setting required status checks
renovatebot/renovate pull request #16965
Opened 2022-08-04 10:30 UTC by HonkingGoose

## Changes

- Add admonition to tell our users they _must_ set required status checks, or Renovate will automerge PRs even if all tests fail

## Context

Closes #16964

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-08-04 10:36 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +    If you're using another platform, search their documentation for a similar feature.
I don't know how to format this text so:

- Prettier ignores the formatting
- Material for MkDocs renders the admonition correctly on the published page

Here's what the end-result should look like:

> Before you enable `platformAutomerge` you must tell your Git hosting platform what test(s) must pass before the PR is allowed to be auto-merged.
> If you don't do this, Renovate auto-merges PRs even if all test fail!
> 
> On GitHub this is called "Require status checks before merging", which you can find in the "Branch protection rules" section of the settings for your repository.
> - [GitHub docs, about protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)
> - [GitHub docs, require status checks before merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging)
>
> If you're using another platform, search their documentation for a similar feature.

If you have any tips/tricks/suggestions, please let me know. 😉

2022-08-04 11:29 UTC, viceice commented on docs/usage/configuration-options.md
> +    If you don't do this, Renovate auto-merges PRs even if all test fail!
```suggestion
    If you don't do this, The platform auto-merges PRs even if all test fail!
```
the platform will do the auto-merge

2022-08-04 11:46 UTC, rarkins requested changes

2022-08-04 11:46 UTC, rarkins commented on docs/usage/configuration-options.md
> +    If you don't do this, Renovate auto-merges PRs even if all test fail!
```suggestion
    If you don't do this, the platform might merge Renovate PRs even if the repository's tests haven't started, are in still in progress, or possibly even when they have failed. 
```

2022-08-05 04:49 UTC, rarkins requested changes

2022-08-05 04:49 UTC, rarkins commented on docs/usage/configuration-options.md
> +    Before you enable `platformAutomerge` you must tell your Git hosting platform what test(s) must pass before the PR is allowed to be auto-merged.
```suggestion
    Before you enable `platformAutomerge` you should enable your Git hosting platform's capabilities to enforce test passing before PR merge.
```

2022-08-05 18:53 UTC, rarkins submitted a review, later dismissed

2022-08-06 11:30 UTC, merged

2022-08-06 13:19 UTC, renovate-release commented
:tada: This PR is included in version 32.150.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.150.3)
- `32.150.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: