feat(manager:conda): add manager for conda
renovatebot/renovate pull request #17156
Opened 2022-08-12 15:18 UTC by morremeyer

## Changes

This is a first implementation of a manager for conda as discussed in #2213.

It has very limited support for version specifications, namely: only exact matching of release versions that have three components and can therefore be assumed to be semver compliant.

## Context

Conda [versioning](https://github.com/conda/conda/blob/0ce67ff01354667d6cf8c956839a401f42e41bde/conda/models/version.py#L49) and [dependency definitions](https://github.com/conda/conda/blob/0ce67ff01354667d6cf8c956839a401f42e41bde/conda/models/match_spec.py#L69) are very different from what renovate already supports. 

@ekeih and I discussed how to best get something of value to all renovate users where we can guarantee that updates are correct, but without making this a huge initial implementation with full conda versioning support and all shenanigans.

We therefore implemented this limited support to get started and get familiar with the codebase (again).

If you're visiting this PR in the future: We're actively talking to the maintainers about how we can improve the support over time. There's already several ideas for improvements already.

## Documentation

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2022-08-12 15:36 UTC, viceice reviewed
it seems channels should be part of the registry url, one for each channel. that would make more sense in my eyes

2022-08-12 15:36 UTC, viceice commented on lib/modules/manager/conda/extract.spec.ts
> +      expect(res).toMatchSnapshot();
please read our best practices guide and don't use toEqual or toMatchObject. reduce deps in fixture to minimum 

guide is in docs/development folder

2022-08-12 15:36 UTC, viceice commented on lib/modules/manager/conda/extract.ts
> +    parsedContent = load(content, { json: true }) as any;
cast to correct type

2022-08-12 15:36 UTC, viceice commented on lib/modules/manager/conda/extract.ts
> +  let parsedContent: CondaEnvironment;
```suggestion
  let parsedContent: CondaEnvironment | null;
```
yaml load can return null for empty docs

2022-08-12 15:36 UTC, viceice commented on lib/modules/manager/conda/extract.ts
> +      };
return null instead

2022-08-12 15:36 UTC, viceice commented on lib/modules/manager/conda/extract.ts
> +  parsedContent.dependencies?.forEach((parsedDep) => {
use `for...of` loop, checkout best practices

2022-08-12 15:36 UTC, viceice commented on lib/modules/manager/conda/extract.ts
> +      cloneDep.packageName = cloneDep.depName;
if it's same as depName, remove

2022-08-12 15:36 UTC, viceice commented on lib/modules/manager/conda/extract.ts
> +    dep.versioning = 'semver';
i think you should use pep440 versioning instead, as it will support most of your limitations

2022-12-19 09:05 UTC, HonkingGoose requested changes

2022-12-19 09:05 UTC, HonkingGoose commented on lib/modules/manager/conda/readme.md
> +Renovate has no concept of conda channels and their different priorities. The manager will open separate PRs for updates from different channels. This allows you to make a decision about which update
```suggestion
Renovate has no concept of conda channels and their different priorities.
The manager will open separate PRs for updates from different channels.
This allows you to make a decision about which updates to merge.
```

We use the "one sentence per line" pattern in our docs.

2022-12-19 09:05 UTC, HonkingGoose commented on lib/modules/manager/conda/readme.md
> +When enabling the manager, you will get _Package Lookup Warnings_ for all packages that are not present in all channels. This is, again, due to renovate not having a concept of conda channels and tre
```suggestion
When enabling the manager, you will get _Package Lookup Warnings_ for all packages that are not present in all channels.
This is, again, due to Renovate not having a concept of conda channels and treating each package for each channel as a separate dependency.
You can safely ignore those warnings for a package if they do not occur for all channels you are using (including the default channels).
```

2022-12-19 09:05 UTC, HonkingGoose commented on lib/modules/manager/conda/readme.md
> +The `conda` manager only supports a subset of the conda environment.yml specification. The following limitations exist:
```suggestion
The `conda` manager only supports a subset of the conda `environment.yml` specification.
The following limitations exist:
```

2022-12-19 09:05 UTC, HonkingGoose commented on lib/modules/manager/conda/readme.md
> +- There is no support for the nonstandard keys introduced by [conda-lock](https://github.com/conda-incubator/conda-lock).
```suggestion
- Only [release versions](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#supported-version-strings) that are strictly semantically versioned are supported. For example: `2.1.5` is supported but `3.1.7.6` is not
- The default `msys2` channel for Windows is not added when using default channels as Renovate doesn't know which operating system you will use the `environment.yml` file with. If you use Windows, you will have to explicitly include the `msys2` channel to get all updates
- key-value arguments in dependency specifications are not supported
- The key `pip` in the `dependencies` list is ignored if it is a list
- Renovate doesn't support the non-standard keys introduced by [conda-lock](https://github.com/conda-incubator/conda-lock)
```

Changes:

- Drop `.` at the end of list items to match the style in the rest of the docs
- Rewrite some sentences
- Small grammar/typo fixes

2023-06-18 09:41 UTC, rarkins commented
@morremeyer let's close this after 6 months inactivity. Of course, hopeful you can reopen or replace it soon :)

2023-06-18 09:41 UTC, closed without merging

2023-06-19 08:29 UTC, morremeyer commented
@rarkins Good call, yes. I hope we can get to work on this again soon.

We definitely already have a much better idea of how to go about implementing it better than this first attempt.