feat: add group preset all pateches together
renovatebot/renovate pull request #17155
Opened 2022-08-12 15:02 UTC by StanGirard

## Changes

Added the new group preset: `allPatches` in order to group patches together.

## Context

We were creating a default configuration for all of our projects at my company. We wanted to simplify as much as possible the default configuration. We wanted to group patches together in order to reduces CI time, however the preset did not exist. 
Therefor the creation of this new preset

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [X] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-08-12 15:14 UTC, viceice reviewed
not sure if this is a benefit for many users.

it also only works when you separate minor and patch updates

2022-08-12 15:33 UTC, StanGirard commented
Separating minor and patches allows us as SRE to automate security patches of different applications. Might not be useful for developers, but as an SRE, it is a feature that I've used on all my projects.

2022-08-12 15:37 UTC, viceice commented
most users don't use that to reduce noise

2022-08-12 15:46 UTC, StanGirard commented
I understand the noise issue. Therefore the grouping. We use this present in order to not receive any notification for patches:

```json
"extends": [
    "config:base",
    ":automergePatch"
  ],
  "platformAutomerge": true,
  "automergeType": "branch",
  "packageRules": [
    {
      "matchPackagePatterns": [
        "*"
      ],
      "matchUpdateTypes": [
        "patch"
      ],
      "groupName": "all patch dependencies",
      "groupSlug": "all-patch"
    }
  ]
  ```

2022-08-12 15:53 UTC, viceice commented
this won't work when there is a minor and a patch update. then you only get the minor PR.

2022-12-17 06:43 UTC, rarkins requested changes

2022-12-17 06:43 UTC, rarkins commented on lib/config/presets/internal/group.ts
> +        matchPackagePatterns: ['*'],
```suggestion
```
Not needed

2022-12-17 06:43 UTC, rarkins commented on lib/config/presets/internal/group.ts
> +    description: 'Group all `patch` updates together.',
```suggestion
    description: 'Group all `patch` updates together. Combine with separateMinorPatch=true',
```

2023-03-04 10:57 UTC, closed without merging