docs(labels): note that labels are only added at PR creation time
renovatebot/renovate pull request #17234
Opened 2022-08-17 11:45 UTC by rarkins

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-08-17 11:46 UTC, rarkins commented on docs/usage/configuration-options.md
> +If you wish too add labels, see the `addLabels` config option, which is instead mergeable.
```suggestion
If you wish to instead add/combine labels, see the `addLabels` config option, which is mergeable.
```

2022-08-17 13:00 UTC, HonkingGoose requested changes

2022-08-17 20:55 UTC, HonkingGoose approved these changes

2022-08-17 21:22 UTC, viceice approved these changes

2022-08-17 21:34 UTC, merged

2022-08-18 05:31 UTC, renovate-release commented
:tada: This PR is included in version 32.163.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.163.1)
- `32.163.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: