fix/crate lookup package name lowercase
renovatebot/renovate pull request #17278
Opened 2022-08-19 10:12 UTC by blackcodefan

## Changes

Changed to use the lowercased package name in the `/lib/modules/datasource/crate -> getIndexSuffix()`.

## Context
#17098

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [X] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-08-19 10:55 UTC, rarkins requested changes
Please add at least one test

2022-08-19 13:53 UTC, blackcodefan commented
> Please add at least one test

Added getIndexSuffix function test cases.

2022-08-29 20:22 UTC, viceice commented on lib/modules/datasource/crate/index.spec.ts
> +// import { logger } from '../../../logger';
```suggestion
```

2022-08-30 11:46 UTC, rarkins commented
The whole URL should be lower-cased, not just the index parts. Best to start over

2022-08-30 11:46 UTC, closed without merging