Update flux manager readme
renovatebot/renovate pull request #17507
Opened 2022-08-30 09:17 UTC by gberche-orange

## Changes

## Documentation 

Highlight current manager support with headers

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] render markdown to preview to https://docs.renovatebot.com/modules/manager/flux/

2022-08-30 10:00 UTC, rarkins approved these changes, later dismissed

2022-08-30 11:59 UTC, HonkingGoose requested changes

2022-08-30 11:59 UTC, HonkingGoose commented on lib/modules/manager/flux/readme.md
> +### Versionning
```suggestion
### Versioning
```

2022-08-30 11:59 UTC, HonkingGoose commented on lib/modules/manager/flux/readme.md
> +2. Flux [system](https://fluxcd.io/docs/installation) manifests
```suggestion
This manager parses [Flux](https://fluxcd.io/) YAML manifests and supports:

1. [`HelmRelease`](https://fluxcd.io/docs/components/helm/helmreleases/) resources
1. Flux [system](https://fluxcd.io/docs/installation) manifests

```

This should fix the linting problem.
We can just rely on the site generator to number ordered lists for us. 😉

2022-08-30 11:59 UTC, HonkingGoose commented on lib/modules/manager/flux/readme.md
> +Support updating flux system manifests generated during [flux installation](https://fluxcd.io/docs/installation/#customize-flux-manifests).
```suggestion
Support updating Flux system manifests generated during [Flux installation](https://fluxcd.io/docs/installation/#customize-flux-manifests).
```

2022-08-30 11:59 UTC, HonkingGoose commented on lib/modules/manager/flux/readme.md
> +### Flux system support
```suggestion
### Flux system manifests support
```

2022-08-30 11:59 UTC, HonkingGoose commented on lib/modules/manager/flux/readme.md
>  2. You run a Docker image based on [containerbase](https://github.com/containerbase), such as the official Renovate images, and have `binarySource=install` configured
```suggestion
1. The `flux` tool is pre-installed, or
1. You run a Docker image based on [containerbase](https://github.com/containerbase), such as the official Renovate images, and have `binarySource=install` configured
```

2022-08-30 12:10 UTC, HonkingGoose commented on lib/modules/manager/flux/readme.md
> +
```suggestion
```

2022-08-30 12:10 UTC, gberche-orange commented
thanks @HonkingGoose !

2022-08-30 12:13 UTC, HonkingGoose commented
Cheers @gberche-orange! 😄

2022-08-31 06:20 UTC, rarkins approved these changes

2022-08-31 06:31 UTC, merged

2022-08-31 07:17 UTC, renovate-release commented
:tada: This PR is included in version 32.185.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.185.2)
- `32.185.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: