fix: make baseBranch type non-optional in BranchConfig
renovatebot/renovate pull request #17920
Opened 2022-09-22 15:10 UTC by RahulGautamSingh

## Changes
fix: make baseBranch type non-optional in BranchConfig

## Context
- Ref: #7154

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-09-24 12:08 UTC, viceice commented on lib/workers/repository/update/branch/reuse.spec.ts
> +      config = partial<BranchConfig>({
you should add `baseBranch` to config if it's required by test.

2022-09-24 13:58 UTC, RahulGautamSingh commented
Blocked by #17848
After mentioned PR is merged we will use new `BranchCache` with `baseBranch` field. I think better to merge this PR after that one after I update accordingly. 
Okay to not review for now.

2022-09-24 15:59 UTC, rarkins submitted a review, later dismissed

2022-09-24 16:41 UTC, viceice requested changes
blocked

2022-10-10 04:51 UTC, rarkins approved these changes

2022-10-10 06:38 UTC, viceice approved these changes

2022-10-10 06:38 UTC, merged

2022-10-10 07:03 UTC, renovate-release commented
:tada: This PR is included in version 32.228.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.228.1)
- `32.228.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: