feat(azure): be able to define a required reviewer for PRs
renovatebot/renovate pull request #18111
Opened 2022-10-04 15:37 UTC by sch1ldkr0ete

## Changes

When a reviewer for an Azure DevOps PR is prefixed with `required:` the reviewer will be marked as a required reviewer in the Azure DevOps PR.

## Context

Please have a look at the discussion [#17659](https://github.com/renovatebot/renovate/discussions/17659).

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-10-06 15:34 UTC, JamieMagee commented on lib/modules/platform/azure/index.ts
> +  const reqReviewerIndicator = 'required:';
tiny nit

```suggestion
  const requiredReviewerPrefix = 'required:';
```

2022-10-06 15:38 UTC, JamieMagee requested changes
Overall looks good. Just some lint and test fixes before I can sign off and merge.

2022-10-07 11:04 UTC, sch1ldkr0ete commented on lib/modules/platform/azure/index.ts
> +  const reqReviewerIndicator = 'required:';
Thanks! I used your suggestion.

2022-10-07 11:06 UTC, sch1ldkr0ete commented
> Overall looks good. Just some lint and test fixes before I can sign off and merge.



> Overall looks good. Just some lint and test fixes before I can sign off and merge.

Done:)

2022-10-07 13:10 UTC, JamieMagee submitted a review, later dismissed

2022-10-07 15:02 UTC, sch1ldkr0ete commented
Just fixed a remaining linting issue in the docs. Hope that was okay.

Should I add some tests for keeping the code coverage percentage?

2022-10-07 16:04 UTC, viceice commented
> Just fixed a remaining linting issue in the docs. Hope that was okay.
> 
> Should I add some tests for keeping the code coverage percentage?

yes, needs to stay on 100%

2022-10-07 17:43 UTC, sch1ldkr0ete commented
I marked one of the azure test reviewers as required. The coverage should be back to 100%:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/22296278/194618005-79b87ba8-829b-445c-be25-ac9a9a79c330.png">

2022-10-07 17:55 UTC, JamieMagee approved these changes

2022-10-10 05:40 UTC, merged

2022-10-10 06:21 UTC, renovate-release commented
:tada: This PR is included in version 32.228.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.228.0)
- `32.228.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: