feat(presets): add 'SPFx' monorepo
renovatebot/renovate pull request #18127
Opened 2022-10-05 10:25 UTC by fzoske

## Changes

Add spfx monorepo

https://aka.ms/spfx

## Context

All packages need to be in the same version (https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.15.2)

<img width="881" alt="Screenshot 2022-10-05 at 12 24 23" src="https://user-images.githubusercontent.com/4045832/194039062-3bf75278-d3ac-4d32-836b-9e7c34f93d3a.png">

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-10-05 10:41 UTC, viceice requested changes
why not using grouping via sourceUrl, like the other monorepos above?

2022-10-05 10:47 UTC, fzoske commented
I could not find the source for the packages, aka.ms/spfx is a documentation page
On the other hand @microsoft/eslint-plugin-spfx for exmample does not have an associated url: https://www.npmjs.com/package/@microsoft/eslint-plugin-spfx

2022-10-06 17:53 UTC, JamieMagee commented
I can confirm that these packages are not released on GitHub

2022-10-06 18:01 UTC, JamieMagee requested changes
Requires lint fixes

2022-10-17 03:09 UTC, rarkins submitted a review, later dismissed

2022-10-17 03:51 UTC, JamieMagee submitted a review, later dismissed

2022-10-17 07:06 UTC, viceice commented on lib/config/presets/internal/monorepo.ts
> +  spfx: ['^@microsoft/sp-', '^@microsoft/eslint-.*-spfx'],
can it match any false positive package?
```suggestion
  spfx: ['^@microsoft\\/sp-', '^@microsoft\\/eslint-.+-spfx$'],
```

2022-10-17 08:53 UTC, rarkins approved these changes

2022-10-17 10:18 UTC, viceice approved these changes
hopefully we don't get false positives 🤷‍♂️

2022-10-17 10:18 UTC, merged

2022-10-17 10:46 UTC, renovate-release commented
:tada: This PR is included in version 32.239.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.239.0)
- `32.239.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: