feat(helmv3): add postUpdateOption to update subchart archives
renovatebot/renovate pull request #18162
Opened 2022-10-06 21:06 UTC by secustor

## Changes
Adding a `postUpdateOption` which adds changes done by `helm dependency update` to file changes uploaded by Renovate. 

## Context
Closes #18110

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

https://github.com/secustor/renovate-helm-tarball-reproducer

2022-10-07 04:45 UTC, viceice commented on lib/modules/manager/helmv3/artifacts.spec.ts
> +    ).toMatchSnapshot([
use toEqual

2022-10-07 04:45 UTC, viceice commented on lib/modules/manager/helmv3/artifacts.spec.ts
> +    expect(execSnapshots).toMatchSnapshot();
use toMatchObject

2022-10-07 04:45 UTC, viceice commented on lib/modules/manager/helmv3/readme.md
> +```json5
please use normal JSON style

2022-10-07 09:22 UTC, HonkingGoose requested changes
How about this?

2022-10-07 09:22 UTC, HonkingGoose commented on lib/modules/manager/helmv3/readme.md
> +```json5
```suggestion
```json
```

2022-10-07 09:22 UTC, HonkingGoose commented on lib/modules/manager/helmv3/readme.md
> +If updates to sub chart archives are desired, a `postUpdateOption` named `helmUpdateSubChartArchives` can be used.
```suggestion
To get updates for subchart archives put `helmUpdateSubChartArchives` in your `postUpdateOption` configuration.
```

2022-10-07 09:22 UTC, HonkingGoose commented on lib/modules/manager/helmv3/readme.md
> +After enabling this option archives located in the `/chart` folder are managed by Renovate.
```suggestion
Renovate now updates archives in the `/chart` folder.
```

2022-10-07 09:22 UTC, HonkingGoose commented on lib/modules/manager/helmv3/readme.md
> +### SubChart archives
```suggestion
### Subchart archives
```

The helm docs call it `subchart` or `subcharts` [^helm]. So let's use their terms in our docs. 😉 

[^helm]: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

2022-10-07 20:54 UTC, HonkingGoose requested changes

2022-10-07 20:54 UTC, HonkingGoose commented on lib/modules/manager/helmv3/readme.md
> +To get updates for subchart archives put `helmUpdateSubChartArchives` in your `postUpdateOption` configuration.
```suggestion
To get updates for subchart archives put `helmUpdateSubChartArchives` in your `postUpdateOptions` configuration.
```

Fixing a typo in the config option name.

2022-10-08 14:11 UTC, viceice commented on lib/modules/manager/helmv3/artifacts.spec.ts
> +    expect(execSnapshots).toBeArrayOfSize(2);
we don't need this, next march will do it

2022-10-08 14:11 UTC, viceice commented on lib/modules/manager/helmv3/artifacts.spec.ts
> +    expect(execSnapshots).toBeArrayOfSize(2);
same here

2022-10-08 14:11 UTC, viceice commented on lib/modules/manager/helmv3/artifacts.spec.ts
> +    expect(execSnapshots).toBeArrayOfSize(2);
same

2022-10-08 14:11 UTC, viceice commented on lib/modules/manager/helmv3/artifacts.spec.ts
> +    expect(execSnapshots).toBeArrayOfSize(2);
same

2022-10-08 14:11 UTC, viceice commented on lib/modules/manager/helmv3/artifacts.spec.ts
> +    expect(execSnapshots).toBeArrayOfSize(2);
same

2022-10-08 16:32 UTC, HonkingGoose submitted a review, later dismissed
Docs look good to me.

2022-10-11 15:50 UTC, viceice approved these changes

2022-10-11 16:00 UTC, merged

2022-10-11 16:43 UTC, renovate-release commented
:tada: This PR is included in version 32.234.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/32.234.0)
- `32.234.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: