Allow users to ignore the last X minor or major releases
renovatebot/renovate pull request #18218
Opened 2022-10-09 15:17 UTC by quentinus95

## Changes

This pull request provides two new configuration options, please read the context section to understand why this is useful:
- `ignoreLastXMajor`: ignore the last X major versions 
- `ignoreLastXMinor`: ignore the last X minor versions

## Context

The aim of this pull request is to help to ignore new versions of a dependency or package that might provide a decrease of stability. This is particularly useful when having dependencies that release a lot of new versions in a short amount of time (e.g., an NPM dependency that release a patch every week, and a minor every month). It is also useful for dependencies that have monthly releases (e.g., GitLab releases a new version every month. It can be useful to upgrade to the last patch of the previous release every month instead of the new minor right away). Furthermore, it can also be useful for critical dependencies (e.g., always ignoring the last two major releases of Kubernetes while benefiting from the last patches of the previous majors.

Today, the number of updates can be overwhelming. Having a way to ignore most of the patches and always update to the last patch of the previous minor can provide a good trade-off between last features and quick fixes that followed. Packages sometimes provide maintenance rules for multiple versions at the same time (e.g., Symfony might release a patch for critical security issues over multiple majors). With this new configuration solution you can still benefit from those fixes. You may also sometimes need to plan for extensive work when upgrading to a major version. For such situations, Renovate might not be very useful. You know that you need to update to a major, it will require several weeks for your team to upgrade. You don't want to be flooded by Renovate for each patch on this version.

Finally, you can combine both options. For instance, you may want to ignore the last major and the last minor of a specific package (e.g., Kubernetes).

## Documentation (please check one with an [x])

I need help on what and where I should update documentation. Moreover, I need help to understand how I can plug my feature to the actual configuration options.

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-10-09 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=18218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=18218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=18218) it.</sub>

2022-10-10 04:53 UTC, rarkins requested changes
Please create a github issue to discuss requirements/naming/etc first, you can copy/paste some of the context from this PR

2022-10-10 10:45 UTC, quentinus95 commented
@rarkins done, see https://github.com/renovatebot/renovate/issues/18236 :pray:

2022-10-11 15:59 UTC, viceice reviewed
still needs discussion, see issue

2022-12-17 16:27 UTC, rarkins requested changes

2022-12-17 16:27 UTC, rarkins commented on lib/workers/repository/process/lookup/filter.ts
> +    if (lastMajor !== null) {
```suggestion
    if (is.number(lastMajor)) {
```

2022-12-17 16:27 UTC, rarkins commented on lib/workers/repository/process/lookup/filter.ts
> +    if (lastMinor !== null) {
```suggestion
    if (is.number(lastMinor)) {
```

2023-05-11 19:11 UTC, closed without merging