fix(datasource/docker): handle prop querying of a non existent object in getLabel()
renovatebot/renovate pull request #18574
Opened 2022-10-26 09:24 UTC by Gabriel-Ladzaretti

## Changes
Now ~~using the [optional chaining (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator~~ verifying object existanse before querying its prop within `getLabel`'s inner response object.

Similary to what is described in [this](https://github.com/renovatebot/renovate/discussions/18544) discussion, running the newly added test on branch main fails as expected with:
![image](https://user-images.githubusercontent.com/97394622/197987950-6d31d962-9788-48d5-90f0-ba8818c20289.png)

## Context
https://github.com/renovatebot/renovate/discussions/18544#discussioncomment-3960825

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Unit tests

2022-10-26 09:43 UTC, viceice requested changes

2022-10-26 09:43 UTC, viceice commented on lib/modules/datasource/docker/index.ts
> +      labels = JSON.parse(configResponse.body).config?.Labels;
we should log a debug message when config is missing and log the object to see why it's missing

2022-10-26 10:35 UTC, viceice commented on lib/modules/datasource/docker/index.ts
> +          { configResponse },
```suggestion
          { config: body },
```

only log the body, not the full request

2022-10-29 15:58 UTC, rarkins approved these changes

2022-10-29 16:07 UTC, viceice approved these changes

2022-10-29 16:21 UTC, merged

2022-10-29 16:53 UTC, renovate-release commented
:tada: This PR is included in version 34.9.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.9.1)
- `34.9.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: