feat(platform/gitea): sort autodiscover repos by updated descending
renovatebot/renovate pull request #18636
Opened 2022-10-28 09:35 UTC by viceice

## Changes
Let gitea sort the auto discovered repos by updated date in descending order

## Context
This will allow recently updated repos faster. Not updated repos will probably skipped anyways.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-10-28 09:35 UTC, viceice commented
@rarkins thinking of making it configurable via experimental env option?

2022-11-01 09:34 UTC, HonkingGoose requested changes
Some layout changes.

2022-11-01 09:34 UTC, HonkingGoose commented on docs/usage/self-hosted-experimental.md
> +    Gitea only
```suggestion
    For the Gitea platform only.
```

2022-11-01 09:34 UTC, HonkingGoose commented on docs/usage/self-hosted-experimental.md
> +Allowed values: `alpha`, `created`, `updated`, `size`, `id`
```suggestion
Allowed values:

- `alpha`
- `created`
- `updated`
- `size`
- `id`
```

2022-11-01 09:34 UTC, HonkingGoose commented on docs/usage/self-hosted-experimental.md
> +Default value: `alpha`
```suggestion
Default value: `alpha`.
```

2022-11-01 09:50 UTC, rarkins submitted a review, later dismissed

2022-11-01 09:57 UTC, rarkins approved these changes

2022-11-01 10:12 UTC, merged

2022-11-01 10:42 UTC, renovate-release commented
:tada: This PR is included in version 34.12.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.12.0)
- `34.12.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: