refactor: reduce debug metadata
renovatebot/renovate pull request #18737
Opened 2022-11-03 14:52 UTC by RahulGautamSingh

Co-authored-by: Rhys Arkins <rhys@arkins.net>

## Context
- Closes: #18455 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-11-04 19:44 UTC, rarkins requested changes

2022-11-04 19:44 UTC, rarkins commented on lib/modules/manager/bazel/update.ts
> +        // unsure
```suggestion
```

2022-11-04 19:44 UTC, rarkins commented on lib/modules/platform/github/index.ts
> +    logger.debug(`Overriding default GitHub endpoint: ${endpoint}`);
```suggestion
    logger.debug(`Overriding default GitHub endpoint with ${endpoint}`);
```

2022-11-04 19:44 UTC, rarkins commented on lib/modules/platform/github/index.ts
> +      logger.debug(`Recreated autoclosed branch: ${branchName}`);
```suggestion
      logger.debug(`Recreated autoclosed branch ${branchName} with sha ${sha}`);
```

2022-11-04 19:44 UTC, rarkins commented on lib/modules/platform/github/index.ts
> +        logger.debug(`Reusing issue title: ${title}`);
```suggestion
        logger.debug(`Reusing issue title: "${reuseTitle}"`);
```

2022-11-04 19:44 UTC, rarkins commented on lib/util/exec/docker/index.ts
> +      logger.debug(`Removing container with ID:${containerId}`);
```suggestion
      logger.debug(`Removing container with ID: ${containerId}`);
```

2022-11-04 19:44 UTC, rarkins commented on lib/util/exec/index.ts
> +    logger.debug(`Using docker to execute image:${docker.image}`);
```suggestion
    logger.debug(`Using docker to execute image: ${docker.image}`);
```

2022-11-04 19:44 UTC, rarkins commented on lib/util/git/index.ts
> +      logger.debug(`Setting git author email:${gitAuthorEmail}`);
```suggestion
      logger.debug(`Setting git author email: ${gitAuthorEmail}`);
```

2022-11-04 19:44 UTC, rarkins commented on lib/util/git/index.ts
> +    logger.debug(`Git clone completed in ${durationMs}`);
```suggestion
    logger.debug({ durationMs }, 'git clone completed');
```

Revert this as I use it for metrics in the app

2022-11-04 19:44 UTC, rarkins commented on lib/util/http/throttle.ts
>        logger.debug({ intervalMs, host }, 'Using throttle');
```suggestion
      logger.debug(`Using throttle ${intervalMs} intervalMs for host ${host}`);
```

2022-11-04 19:44 UTC, rarkins commented on lib/workers/global/autodiscover.ts
> +          );
```suggestion
logger.debug({ repository }, 'Using configured repository settings');
```

Revert because `repository` is special metadata

2022-11-04 19:44 UTC, rarkins commented on lib/workers/repository/process/lookup/index.ts
> +        logger.debug(`Found deprecationMessage for dep:${depName}`);
```suggestion
        logger.debug(`Found deprecationMessage for dependency ${depName}`);
```

2022-11-04 19:44 UTC, rarkins commented on lib/workers/repository/update/branch/auto-replace.ts
> +  logger.debug('Branch dep is already updated');
```suggestion
  logger.debug(`Branch dep ${depName} in ${packageFile} is already updated`);
```

2022-11-05 06:10 UTC, RahulGautamSingh commented on lib/workers/repository/update/branch/auto-replace.ts
> +    logger.debug(`No newUpgrade in ${packageFile!}`);
thoughts??

2022-11-05 06:33 UTC, rarkins commented on lib/workers/global/autodiscover.ts
> +logger.debug({ repository }, 'Using configured repository settings');
```suggestion
          logger.debug({ repository }, 'Using configured repository settings');
```

2022-11-05 06:34 UTC, rarkins approved these changes, later dismissed

2022-11-07 11:11 UTC, rarkins approved these changes

2022-11-07 11:29 UTC, merged

2022-11-07 21:22 UTC, renovate-release commented
:tada: This PR is included in version 34.20.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.20.1)
- `34.20.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: