feat(release notes): be able to fetch release notes from Azure DevOps
renovatebot/renovate pull request #19136
Opened 2022-11-28 07:58 UTC by sch1ldkr0ete

## Changes

Add support for fetching release notes from Azure DevOps. (Just for markdown saved in the source repo, release lists are pretty special in Azure DevOps.)

## Context

Closes #18324

## Documentation (please check one with an [x])

- [ x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ x] Both unit tests + ran on a real repository

2022-12-17 09:17 UTC, rarkins requested changes

2022-12-19 08:50 UTC, HonkingGoose commented on lib/util/http/azure.spec.ts
> +  it('gets paginated json', async () => {
```suggestion
  it('gets paginated JSON', async () => {
```

Abbreviations should be capitalized.

2023-01-23 09:39 UTC, viceice requested changes

2023-01-23 09:39 UTC, viceice commented on docs/usage/configuration-options.md
> +- Azure DevOps (.com)
```suggestion
- Azure DevOps (.com)
- GitHub (.com and Enterprise Server)
- GitLab (.com and CE/EE)
```

sort

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/release-notes.spec.ts
> +        } as ChangeLogRelease
```suggestion
        } satisfies ChangeLogRelease
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/release-notes.spec.ts
> +        } as ChangeLogRelease
```suggestion
        } satisfies ChangeLogRelease
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/release-notes.spec.ts
> +      expect(res).toMatchSnapshot({
```suggestion
      expect(res).toMatchObject({
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/release-notes.spec.ts
> +        } as ChangeLogRelease
```suggestion
        } satisfies ChangeLogRelease
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/release-notes.spec.ts
> +        {} as ChangeLogRelease
```suggestion
        {} satisfies ChangeLogRelease
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/release-notes.spec.ts
> +} as ChangeLogProject;
```suggestion
} satisfies ChangeLogProject;
```

2023-01-23 09:39 UTC, viceice commented on lib/util/http/azure.ts
> +  async getJsonPaginated<T>(
Don't use new function for pagiantion. Checkout github and gitab http for pagination.

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/azure.spec.ts
> +};
```suggestion
} satisifes BranchUpgradeConfig;
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/azure.spec.ts
> +const upgrade: BranchUpgradeConfig = {
```suggestion
const upgrade = {
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/azure.spec.ts
> +jest.mock('../../../../../modules/datasource/npm');
```suggestion
jest.mock('../../../../../modules/datasource');
```

better mock datasource completely

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/azure.spec.ts
> +      ).toMatchSnapshot({
```suggestion
      ).toMatchObject({
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/azure.spec.ts
> +      ).toMatchSnapshot({
```suggestion
      ).toMatchObject({
```

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/azure/index.ts
> +export const id = 'azure-changelog';
why exporting?

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/azure/index.ts
> +  )}git/repositories/${urlEncodedRepo}/refs?filter=tags&$top=100&api-version=7.0`;
use `joinUrlParts` helper to concat url parts

2023-01-23 09:39 UTC, viceice commented on lib/workers/repository/update/pr/changelog/azure/index.ts
> +    return tags.map((tag) => tag.name).filter(Boolean);
```suggestion
    return tags.map((tag) => tag.name).filter(is.string);
```

2023-01-23 09:41 UTC, viceice commented
Please read our devel best practices
https://github.com/renovatebot/renovate/blob/ca66adabdb103f62722d1b87710f9e7e7158f34f/docs/development/best-practices.md#L1-L2

2023-03-14 11:59 UTC, sorensenmatias commented
Any news on getting this merged? It would be really useful for our organization.

2023-06-26 10:03 UTC, sorensenmatias commented
@sch1ldkr0ete @viceice Hi! Is there some way we can progress this and get it merged? It is a really important change for our organization since we deploy a lot of internal packages via Azure private feeds.

2023-06-26 10:26 UTC, viceice commented
🤷‍♂️ it's not marked to be reviewed again. we don't monitor for changes. so the author needs to use the GitHub request review feature.

@sorensenmatias feel free to open a new PR with the requested changes to continue.

2023-06-26 12:31 UTC, sch1ldkr0ete commented
Sorry!  This got out of my focus. I will process the requested changes this week.

2023-07-03 10:00 UTC, setchy commented
@sch1ldkr0ete - these may be of interest. I recently refactored the changelog module https://github.com/renovatebot/renovate/pull/23076 in preparation for adding new changelog sources, eg: Bitbucket Cloud https://github.com/renovatebot/renovate/pull/22094

2023-07-29 09:06 UTC, sch1ldkr0ete commented on lib/workers/repository/update/pr/changelog/release-notes.spec.ts
> +  baseUrl: 'https://dev.azure.com/some-org/some-project/',
Cannot see the problem here.

2023-09-23 08:04 UTC, rarkins commented
@sch1ldkr0ete I noticed that this PR seems to still have some review comments from @viceice 

Do you expect to have time to resume work on the PR?

2023-09-26 20:31 UTC, rarkins commented
Closing due to inactivity, PR would be welcome again

2023-09-26 20:31 UTC, closed without merging