Add preset for appVersion in helm charts
renovatebot/renovate pull request #19371
Opened 2022-12-13 08:00 UTC by jkroepke

## Changes

Adds a new regex preset for appVersion in Chart.yaml

## Context

See #13968 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-12-13 08:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=19371) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=19371) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=19371) it.</sub>

2022-12-13 09:41 UTC, HonkingGoose commented on lib/config/presets/internal/regex-managers.ts
> +
Please run `yarn prettier-fix`, because there's an extra newline. 😉

2022-12-13 23:26 UTC, jkroepke commented on lib/config/presets/internal/regex-managers.ts
> +
done

2022-12-14 08:33 UTC, HonkingGoose commented
Hi @jkroepke,

Thanks you for applying my suggestion. 😄 

Next time, please don't force push to your pull request branch. Here's why: [^quote]

> ## Do not force push to your pull request branch
> 
> Please do not force push to your PR's branch after you have created your PR, as doing so forces us to review the whole PR again. This makes it harder for us to review your work because we don't know what has changed. PRs will always be squashed by us when we merge your work. Commit as many times as you need in your pull request branch.
> 
> If you are updating your PR branch from within the GitHub PR interface, then only use the default "Update branch" button.
> 
> Force pushing a PR is OK when:
> 
> - you need to make large changes on a PR which require a full review anyway
> - you need to bring the branch up-to-date with the target branch and incorporating the changes is more work than to create a new PR

[^quote]: [Renovate's contributing guide](https://github.com/renovatebot/renovate/blob/main/.github/contributing.md#do-not-force-push-to-your-pull-request-branch)

2022-12-15 12:08 UTC, rarkins commented
Is it possible to supplement this with an example in https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/regex/readme.md which references this preset?

2022-12-19 22:40 UTC, jkroepke commented
> Is it possible to supplement this with an example in [`main`/lib/modules/manager/regex/readme.md](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/regex/readme.md?rgh-link-date=2022-12-15T12%3A08%3A05Z) which references this preset?

Not sure, if its worth. Added.

2022-12-21 07:58 UTC, HonkingGoose requested changes

2022-12-21 07:58 UTC, HonkingGoose commented on lib/config/presets/internal/regex-managers.ts
> +    description: 'Update `appVersion` value in helm chart Chart.yaml.',
```suggestion
    description: 'Update `appVersion` value in Helm chart Chart.yaml.',
```

Helm is a proper noun, so we should capitalize it.

2022-12-21 07:58 UTC, HonkingGoose commented on lib/modules/manager/regex/readme.md
> +Simplified version of such comments can be used to increase to readability.
```suggestion
You can use simple versions of such comments to increase readability.
```

2022-12-21 07:58 UTC, HonkingGoose commented on lib/modules/manager/regex/readme.md
> +can be hard-coded. For example:
```suggestion
For example the `appVersion` property in a `Chart.yaml` of a Helm chart is always referenced to an Docker image.
In such scenarios, some values can be hard-coded.
For example:
```

2022-12-21 07:58 UTC, HonkingGoose commented on lib/modules/manager/regex/readme.md
> +Using the regexManagers below, renovate will look for available docker tag of the image `amazon/amazon-eks-pod-identity-webhook`.
```suggestion
Using the `regexManagers` below, Renovate looks for available Docker tags of the image `amazon/amazon-eks-pod-identity-webhook`.
```

2023-01-04 08:18 UTC, jkroepke commented
Thanks for the reviews

2023-01-04 09:00 UTC, viceice commented on lib/config/presets/internal/regex-managers.ts
> +          '#\\s*renovate: image=(?<depName>.*?)\\s+appVersion:\\s*[\\"\\']?(?<currentValue>[\\w+\\.\\-]*)',
```suggestion
          '#\\s*renovate: image=(?<depName>.*?)\\s+appVersion:\\s*["\']?(?<currentValue>[\\w+\\.\\-]*)',
```
looks like wrong escapes

2023-01-16 09:22 UTC, viceice approved these changes

2023-01-16 09:47 UTC, secustor approved these changes

2023-01-16 10:14 UTC, merged

2023-01-16 10:48 UTC, renovate-release commented
:tada: This PR is included in version 34.103.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.103.0)
- `34.103.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: