Vendir manager
renovatebot/renovate pull request #19560
Opened 2022-12-23 21:50 UTC by dominik-bln

## Changes

Adds a very basic vendir manager, initially only with the ability to update dependencies of the `helmChart` type.

## Context

- #17711

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2022-12-29 14:59 UTC, HonkingGoose requested changes

2022-12-29 14:59 UTC, HonkingGoose commented on lib/modules/manager/vendir/__fixtures__/empty-directories.yml
> +apiVersion: vendir.k14s.io/v1alpha1
Please create a `readme.md` file in this location: `lib/modules/manager/vendir/readme.md` and explain the limitations of the new Vendir manager, like this:

> The Vendir manager can only updates dependencies of the `helmChart` type.

2023-01-04 13:50 UTC, HonkingGoose commented on lib/modules/manager/vendir/readme.md
> +of the `helmChart` type.
```suggestion
The [vendir](https://carvel.dev/vendir/) manager only updates dependencies of the `helmChart` type.
```

2023-03-04 11:33 UTC, rarkins requested changes

2023-03-04 11:33 UTC, rarkins commented on lib/modules/manager/vendir/extract.spec.ts
> +const emptyDirectories = Fixtures.get('empty-directories.yml');
Please convert to inline codeBlock format

2023-03-04 11:33 UTC, rarkins commented on lib/modules/manager/vendir/extract.spec.ts
> +      expect(result).toMatchSnapshot({
```suggestion
      expect(result).toMatchObject({
```

2023-06-18 09:52 UTC, rarkins commented
Closed due to inactivity

2023-06-18 09:52 UTC, closed without merging