chore: relative links for contribution guidelines
renovatebot/renovate pull request #19715
Opened 2023-01-07 11:13 UTC by lmilbaum

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-01-07 11:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=19715) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=19715) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=19715) it.</sub>

2023-01-07 12:33 UTC, rarkins commented
Thanks for the PR. How confident are you that these relative links work in every case?

2023-01-07 13:07 UTC, lmilbaum commented
> Thanks for the PR. How confident are you that these relative links work in every case?

I am confident with the md files. Not confident with the others. Didn't figure out yet how to validate them. Any idea?

2023-01-07 13:17 UTC, rarkins commented
We can maybe manually edit some existing ones and test if it still works correctly afterwards

2023-01-21 21:36 UTC, lmilbaum commented
Shell I close the PR?

2023-01-22 07:59 UTC, rarkins requested changes

2023-01-22 07:59 UTC, rarkins commented on .github/pull_request_template.md
> +<!-- Please read [contributing guidelines](.github/contributing.md) before you create your pull request.-->
```suggestion
<!-- Please read https://github.com/renovatebot/renovate/blob/main/.github/contributing.md before you create your pull request.-->
```

2023-01-22 07:59 UTC, rarkins commented on .github/label-actions.yml
> +    Please read our [contributing guidelines](.github/contributing.md#resolve-review-comments-instead-of-commenting) to reduce noise.
```suggestion
    Please read our [contributing guidelines](https://github.com/renovatebot/renovate/blob/main/.github/contributing.md#resolve-review-comments-instead-of-commenting) to reduce noise.
```

2023-01-22 09:12 UTC, rarkins submitted a review, later dismissed

2023-01-22 19:32 UTC, rarkins approved these changes

2023-01-22 19:53 UTC, merged

2023-01-23 07:24 UTC, renovate-release commented
:tada: This PR is included in version 34.109.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.109.0)
- `34.109.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: