fix(pub): update to only lock updated dependencies
renovatebot/renovate pull request #19825
Opened 2023-01-13 11:20 UTC by zeshuaro

## Changes

- Update to specify the updated dependencies for the `pub` manager when we attempt to lock their versions with `pub upgrade`
- I loosely referenced the code from the `poetry` manager

## Context

Closes #19653 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository
  - See [this](https://github.com/barriot/r1/pull/3/files) PR for the current behaviour, where transitive dependency in the lock file is updated as part of the main dependency update
  - See [this](https://github.com/barriot/r0/pull/8/files) PR for the new behaviour where the transitive dependency is not updated, only the main dependency is

2023-01-13 11:21 UTC, zeshuaro commented on lib/modules/manager/pub/artifacts.ts
> +  if (!is.nonEmptyArray(updatedDeps) && !isLockFileMaintenance) {
Doesn't seem like any other managers are checking `config.updateType === 'lockfileUpdate'`, and I referenced other managers with this change

2023-01-13 11:22 UTC, zeshuaro commented on lib/modules/manager/pub/artifacts.ts
> -      newLockFileContent === undefined
Doesn't seem like any other managers are checking `newLockFileContent === undefined` so I removed it

2023-01-18 16:46 UTC, JamieMagee commented on lib/modules/manager/pub/artifacts.ts
> +  if (!is.nonEmptyArray(updatedDeps) && !isLockFileMaintenance) {
Avoids a double negative:
```suggestion
  if (is.emptyArray(updatedDeps) && !isLockFileMaintenance) {
```

2023-01-18 16:55 UTC, JamieMagee commented
Does `pub upgrade` with a specific dependency also handle indirect dependencies? For example, if I depend on A, and A depends on B, does `pub upgrade A` also upgrade B when required?

2023-01-19 07:01 UTC, zeshuaro commented
> Does pub upgrade with a specific dependency also handle indirect dependencies? For example, if I depend on A, and A depends on B, does pub upgrade A also upgrade B when required?

Yes it does, see this PR for example: https://github.com/barriot/r2/pull/12

2023-01-19 07:13 UTC, viceice requested changes

2023-01-19 07:13 UTC, viceice commented on lib/modules/manager/pub/artifacts.ts
> +    logger.debug(`Updating ${lockFileName}`);
```suggestion
```
you'll see the exec in logso this isn't required

2023-01-19 07:13 UTC, viceice commented on lib/modules/manager/pub/artifacts.ts
> +      logger.debug(`${lockFileName} is unchanged`);
```suggestion
```
upper layer will log if there are updated log files

2023-01-19 07:13 UTC, viceice commented on lib/modules/manager/pub/artifacts.ts
> +    logger.debug(`Returning updated ${lockFileName}`);
```suggestion
```
see other comment

2023-01-19 15:46 UTC, JamieMagee approved these changes

2023-01-19 20:59 UTC, viceice approved these changes

2023-01-20 06:28 UTC, merged

2023-01-20 07:07 UTC, renovate-release commented
:tada: This PR is included in version 34.107.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.107.0)
- `34.107.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: