chore: create discussion forms
renovatebot/renovate pull request #19894
Opened 2023-01-18 10:34 UTC by HonkingGoose

## Changes

- Create discussion forms for:
  - Ideas & General Discussion
  - Mend Renovate App Support 
  - Questions & Answers

## Context

The Poll discussion type has no form, because that's not supported by GitHub. 😄 

Closes #19810.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-01-18 15:28 UTC, rarkins requested changes

2023-01-18 15:28 UTC, rarkins commented on .github/DISCUSSION_TEMPLATE/mend-renovate-app-support.yml
> +      required: true
I think let's remove this part, as the quantity of people ticking yes is likely to be very low

2023-01-18 15:28 UTC, rarkins commented on .github/DISCUSSION_TEMPLATE/questions-answers.yml
> +      required: true
Also remove

2023-01-19 05:42 UTC, rarkins approved these changes, later dismissed

2023-01-19 05:43 UTC, rarkins commented
One question: if we adopt these templates, but need to convert issues to discussions, do they bypass these templates?

2023-01-19 17:45 UTC, HonkingGoose commented
There are some problems with my YAML. I'll go fix those first.

2023-01-19 18:06 UTC, HonkingGoose reviewed
I think we're good to merge, just wanted to highlight a gotcha. 😉

2023-01-19 18:06 UTC, HonkingGoose commented on .github/DISCUSSION_TEMPLATE/ideas-general-discussion.yml
> +body:
The filename of the discussion forms must match the category names in the discussion tab on the repository.

This means that if you change the name of the discussion, you should also rename the corresponding template file.

2023-01-21 04:53 UTC, rarkins approved these changes

2023-01-21 04:53 UTC, merged

2023-01-21 09:37 UTC, renovate-release commented
:tada: This PR is included in version 34.108.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.108.3)
- `34.108.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: