docs: add snippet on how to auth maven with gitlab pipelines
renovatebot/renovate pull request #20089
Opened 2023-01-29 10:11 UTC by simPod

## Changes

Add snippet to docs on how to auth maven with gitlab pipelines.

## Context

There have been some struggle on how to make it work, see https://github.com/renovatebot/renovate/issues/20071

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-01-29 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=20089) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=20089) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=20089) it.</sub>

2023-01-29 10:22 UTC, viceice requested changes
this should be in private packages doc

2023-01-29 13:53 UTC, HonkingGoose requested changes

2023-01-29 13:53 UTC, HonkingGoose commented on docs/usage/getting-started/private-packages.md
> +Gilab package registry can be authorized using `Authorization: Bearer <token>`.
```suggestion
GitLab package registry can be authorized using `Authorization: Bearer <token>`.
```

I guess you mean GitLab here?

2023-01-29 13:53 UTC, HonkingGoose commented on docs/usage/getting-started/private-packages.md
> +In Gitlab Pipelines authorization can be achieved using following config:
```suggestion
In GitLab Pipelines authorization can be achieved using following config:
```

2023-01-30 06:16 UTC, merged

2023-01-30 06:54 UTC, renovate-release commented
:tada: This PR is included in version 34.116.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.116.2)
- `34.116.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: