Fetch metadata for rubygems
renovatebot/renovate pull request #20094
Opened 2023-01-29 14:55 UTC by Tranquility

## Changes

Use rubygems datasource that fetches metadata and add throttle to not exceed api rate limit. I don't know if this is the right approach so I created this as a draft mr and did not delete the versions-datasource yet.

## Context

closes #3670

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-01-29 15:16 UTC, viceice reviewed
this makes performance much more worse. I'm not sure we can accept this change. 🤔

2023-01-29 15:24 UTC, Tranquility commented
> this makes performance much more worse. I'm not sure we can accept this change. 🤔

Yes, that's why I wasn't sure about the approach. What would be the solution? Isn't this only a problem when it runs for the first time because it is cached afterwards? 
How could we only use the datasource with the metadata when we really need to?

2023-02-04 14:50 UTC, Tranquility commented
@rarkins do you have any suggestions how to improve this?

2023-02-10 10:39 UTC, rarkins requested changes
I think what we should be doing is _supplementing_ the versions datasource with metadata. The metadata for any package (e.g. source URL, home page) can be cached a long time, such as 24 hours or even a week. Here is some prior art from Rust crates.io: https://github.com/renovatebot/renovate/blob/a91ca62b466b57aa9a18f4e15bd04eb5552278b1/lib/modules/datasource/crate/index.ts#L116-L127

2023-02-10 10:39 UTC, rarkins commented on lib/config/presets/internal/workarounds.ts
> +  },
I think we should have this type of thing as default/embedded when we know a certain registry doesn't want to be overloaded

2023-06-18 09:49 UTC, rarkins commented
Will be replaced by some work by @zharinov

2023-06-18 09:49 UTC, closed without merging