refactor: ExtractResult (wip)
renovatebot/renovate pull request #20131
Opened 2023-01-31 14:33 UTC by RahulGautamSingh

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-01-31 16:39 UTC, rarkins requested changes

2023-01-31 16:39 UTC, rarkins commented on lib/workers/repository/extract/index.ts
> +
This probably should move to a types file

2023-01-31 18:34 UTC, rarkins approved these changes

2023-01-31 18:36 UTC, rarkins approved these changes

2023-01-31 18:38 UTC, viceice commented
disabled automerge as PR title says it's wip

2023-01-31 19:05 UTC, merged

2023-02-01 06:45 UTC, renovate-release commented
:tada: This PR is included in version 34.118.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.118.3)
- `34.118.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: