docs: adds configuration template to revert standard naming convention for Azure Pipelines
renovatebot/renovate pull request #20208
Opened 2023-02-03 19:43 UTC by jessehouwing

## Changes

This PR adds documentation on how to use the standard naming convention and only issue updates for major versions.

## Context
Azure pipelines' default naming convention is `Taskname@majorVersion`, RenovateBot's default convention is `@TaskName@Major.Minor.Patch`.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] No code was changed
- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-02-03 22:01 UTC, HonkingGoose requested changes

2023-02-03 22:01 UTC, HonkingGoose commented on lib/modules/manager/azure-pipelines/readme.md
> +It updates container and repository resources from the `resources` block as well as tasks from `steps` blocks.
```suggestion
Renovate now updates container and repository resources from the `resources` block, plus tasks from `steps` blocks.
```

2023-02-04 08:55 UTC, rarkins approved these changes

2023-02-04 08:56 UTC, merged

2023-02-04 09:33 UTC, renovate-release commented
:tada: This PR is included in version 34.122.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.122.1)
- `34.122.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: