When `--include-forks` is passed, assume `=true`
renovatebot/renovate pull request #20206
Opened 2023-02-03 19:25 UTC by jessehouwing

## Changes

Changes `--include-forks` from a parameter to a switch by assuming `=true` when no value is passed in.

## Context

Make the `--include-forks` act like other switches such as: `--autodiscover` and `--dry-run`.

## Documentation (please check one with an [x])

The documentation mentions `--include-forks=true` once, I could replace it, but the value remains valid.

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-02-03 19:40 UTC, rarkins requested changes
These are migrations and intended to go away. Not intended to allow "lazy" syntax passing. I think you'll find the behavior differs based on order

2023-02-03 19:44 UTC, jessehouwing commented
Was afraid this might be the case ;). Let me dig through the config parser instead then...

2023-02-03 20:04 UTC, jessehouwing commented
@rarkins I tried to figure out what's going on and there is a special case that causes an issue, which is what I was trying to work around.

When I call

```
npx renovate --include-forked jessehouwing/renovate
```

I get an error:

```
renovate --include-forks jessehouwing/renovatebot
FATAL: Fatal error: Invalid boolean value: expected 'true' or 'false', but got 'jessehouwing/renovatebot'
       "err": {
         "message": "Invalid boolean value: expected 'true' or 'false', but got 'jessehouwing/renovatebot'",
         "stack": "Error: Invalid boolean value: expected 'true' or 'false', but got 'jessehouwing/renovatebot'\n    at Option.boolean [as parseArg] (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\lib\\workers\\global\\config\\parse\\coersions.ts:12:11)\n    at handleOptionValue (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\node_modules\\commander\\lib\\command.js:539:24)\n    at Command.<anonymous> (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\node_modules\\commander\\lib\\command.js:566:7)\n    at Command.emit (node:events:513:28)\n    at Command.emit (node:domain:489:12)\n    at Command.parseOptions (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\node_modules\\commander\\lib\\command.js:1461:18)\n    at Command._parseCommand (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\node_modules\\commander\\lib\\command.js:1240:25)\n    at Command.parse (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\node_modules\\commander\\lib\\command.js:909:10)\n    at Object.getConfig (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\lib\\workers\\global\\config\\parse\\cli.ts:115:6)\n    at parseConfigs (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\lib\\workers\\global\\config\\parse\\index.ts:22:31)\n    at C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\lib\\workers\\global\\index.ts:122:16\n    at start (C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\lib\\workers\\global\\index.ts:120:5)\n    at C:\\Users\\JesseHouwing\\AppData\\Roaming\\fnm\\node-versions\\v18.12.1\\installation\\node_modules\\renovate\\lib\\renovate.ts:18:22"
       }
```

It looks like other booleans don't suffer this fate:

```
renovate --include-forks --dry-run jessehouwing/renovate
```

Works just fine, possibly **because** `--dry-run` is auto migrated to `--dry-run=true`.

I'm not at all sure how to fix this.

2023-02-04 13:44 UTC, rarkins commented
I think we should update our docs to make it clear that you should not do e.g.
- `--include-forks`
- `--include-forks true`

And instead only like `--include-forks=true`. This goes for all params, and not just boolean.

That said, many will miss the docs. I think the easiest would be if we removed the option for `--param value` in a major release and instead support only `--param=value` or implicitly `--param` means `=true`. But I'm not sure our CLI library supports that.

2023-02-04 14:05 UTC, jessehouwing commented
Those migration tricks make it work ;). But yeah, fixing the format would
be ideal. In the meantime, it would have helped me if the docs had said

```
--include-forks=(true|false)
```

Though it's confusing that `--dry-run` and `--autodiscover` do work,
probably because of these migration fixes.

It looks like the library is too flexible, allowing all of these

```
--flag
--flag=value
--flag value
```

And it getting lost in what is truly causing the issue.

If it were more opinionated, there things would be easier. Or if the
floating value weren't a bool, it could assume `true`.



On Sat, 4 Feb 2023, 14:44 Rhys Arkins, ***@***.***> wrote:

> I think we should update our docs to make it clear that you should not do
> e.g.
>
>    - --include-forks
>    - --include-forks true
>
> And instead only like --include-forks=true. This goes for all params, and
> not just boolean.
>
> That said, many will miss the docs. I think the easiest would be if we
> removed the option for --param value in a major release and instead
> support only --param=value or implicitly --param means =true. But I'm not
> sure our CLI library supports that.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/renovatebot/renovate/pull/20206#issuecomment-1416755815>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA724S7TMNYIZYFKZASJGTLWVZMMHANCNFSM6AAAAAAUQTR5DQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-04 14:23 UTC, rarkins commented
Another possibility is we enforce listing `--repositories=`

2023-02-04 14:31 UTC, rarkins commented
Sorry, I'm going to close this because it also *breaks* a valid input. `renovate --include-forks true foo/bar` fails after this PR because Renovate tries to process the repo `true` before `foo/bar`.

2023-02-04 14:32 UTC, closed without merging