docs: gomod artifacts hostRules
renovatebot/renovate pull request #20222
Opened 2023-02-04 09:04 UTC by rarkins

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-02-04 09:28 UTC, HonkingGoose requested changes

2023-02-04 09:28 UTC, HonkingGoose commented on lib/modules/manager/gomod/readme.md
> +Rules from this list will be converted to environment variable directives it they matchy any of the following characteristics:
```suggestion
Rules from this list are converted to environment variable directives if they match _any_ of the following characteristics:
```

2023-02-04 09:28 UTC, HonkingGoose commented on lib/modules/manager/gomod/readme.md
> + - hostType is `go`, or
```suggestion
 - `hostType` is `go`, or
```

2023-02-04 09:28 UTC, HonkingGoose commented on lib/modules/manager/gomod/readme.md
> + - hostType is a platform (`github`, `gitlab`, `azure`, etc.)
```suggestion
 - `hostType` is a platform (`github`, `gitlab`, `azure`, etc.)
```

2023-02-04 09:28 UTC, HonkingGoose commented on lib/modules/manager/gomod/readme.md
> + - No hostType is defined, or
```suggestion
 - No `hostType` is defined, or
```

2023-02-04 09:28 UTC, HonkingGoose commented on lib/modules/manager/gomod/readme.md
> +Next, all hostRules with both a token and matchHost will be fetched, except for any github.com one from above.
```suggestion
Next, all `hostRules` with both a token and `matchHost` will be fetched, except for any github.com one from above.
```

2023-02-04 09:28 UTC, HonkingGoose commented on lib/modules/manager/gomod/readme.md
> +Before executing `go` commands to update the `go.sum`, Renovate will export `git` [`insteadOf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf) directives in en
```suggestion
Before running the `go` commands to update the `go.sum`, Renovate exports `git` [`insteadOf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf) directives in environment variables.
```

2023-02-04 09:28 UTC, HonkingGoose commented on lib/modules/manager/gomod/readme.md
> +For those running against `github.com`, this will be the default platform token.
For me it's not clear at a glance what _this_ points at. Maybe you can explain what _this_ is?

2023-03-04 06:06 UTC, rarkins commented on lib/modules/manager/gomod/readme.md
> +For those running against `github.com`, this will be the default platform token.
```suggestion
For those running against `github.com`, this token will be the default platform token.
```

2023-03-04 06:38 UTC, merged

2023-03-04 09:34 UTC, renovate-release commented
:tada: This PR is included in version 34.155.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.155.0)
- `34.155.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: