feat(presets): add automergeSchedule presets
renovatebot/renovate pull request #20305
Opened 2023-02-08 23:54 UTC by DuncanCasteleyn

## Changes
I have made a copy of the schedule presets and modified the code so the same presets are available for automergeSchedules.

## Context
I think it would be useful to have the same schedule presets that exist for schedule, would also exist for automergeSchedule.

## Documentation

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

If I saw correctly presets are already tested and I ran this test, I also checked if the new md file for the automergeSchedule is generated for the docs.

2023-02-09 04:05 UTC, rarkins requested changes
Ideally we could keep it within the existing "schedule:" prefix

2023-02-09 07:52 UTC, DuncanCasteleyn commented
> Ideally we could keep it within the existing "schedule:" prefix

Would you sugest they are prefixed with `:automerge`?

2023-02-09 08:30 UTC, DuncanCasteleyn commented
Since none of the previous changes persist, force pushed.

2023-02-10 10:41 UTC, rarkins approved these changes

2023-02-10 10:55 UTC, viceice commented on lib/config/presets/internal/schedule.ts
> +const yearly = ['every 12 months on the first day of the month'];
should we use cron syntax? 🤔

2023-02-10 11:05 UTC, secustor approved these changes

2023-02-10 11:32 UTC, merged

2023-02-10 11:33 UTC, viceice approved these changes

2023-02-10 12:15 UTC, renovate-release commented
:tada: This PR is included in version 34.129.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.129.0)
- `34.129.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: