feat(presets): Group for Spock Framework packages
renovatebot/renovate pull request #20358
Opened 2023-02-12 11:01 UTC by szpak

## Changes

[Several](https://search.maven.org/search?q=g:org.spockframework) Spock Framework packages should be updates at the same time.

## Context

When a dedicated prperty is not used, multiple modules of Spock used in the same projects could be updated in separate MRs, which doesn't make sense.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-02-12 11:04 UTC, szpak commented
(force push to fix typo in the commit message...)

2023-02-12 16:24 UTC, viceice requested changes
please checkout monorepo.ts for better grouping.

2023-02-12 21:51 UTC, szpak commented
@viceice I made the changes. Is it something you expected?

Unfortunately, I don't know how to test it (the regex) in practice (without rebuilding Renovate locally)? Should I write a test case in `monorepo.spec.ts` or "it should be already covered"?

2023-02-12 21:55 UTC, szpak commented
Btw, if the `monorepo.ts` is a recommended place to handle those cases, maybe it would be good to put a comment in the `group.ts` to redirect people modifying that file to the "new" one?

2023-02-13 06:10 UTC, viceice commented on lib/config/presets/internal/monorepo.ts
> +  spock: '^org.spockframework:spock-',
```suggestion
  spock: '^org\\.spockframework:spock-',
```
escape the dot

2023-02-13 06:11 UTC, viceice approved these changes

2023-02-13 06:33 UTC, merged

2023-02-13 07:12 UTC, renovate-release commented
:tada: This PR is included in version 34.134.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.134.0)
- `34.134.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: