feat(cargo): support private registry index env var
renovatebot/renovate pull request #20379
Opened 2023-02-13 16:18 UTC by tofay

## Changes

Cargo supports defining private registry index URLs in environment variables rather than `.cargo/config[.toml]`. This PR adds support for determining registry URLs from the same variable. 

## Context

I have many Rust projects that use a private registry. We define this in Cargo's home directory of our build environment, rather than in a project-local file. I'm running renovate self-hosted.

This PR enables Renovate to discover the registry URL without adding the cargo configuration file to all projects.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

I've been running this self-hosted against multiple private repositories and renovate has successfully determined the registry URLs.

2023-02-13 22:43 UTC, viceice reviewed
you can already override the registry url via renovate config, so I think we shouldn't implement it this way.

instead renovate should convert the registry url to the ENV value before calling cargo to update the lockfile.

2023-02-13 22:43 UTC, viceice commented on lib/modules/manager/cargo/extract.spec.ts
> +      expect(res?.deps).toMatchSnapshot();
no snapshots, read our dev best practices guide

2023-02-14 09:08 UTC, tofay commented
> you can already override the registry url via renovate config, so I think we shouldn't implement it this way.

I'm not trying to override the default registry URL here, but provide a URL for an additional index.
Renovate also needs to associate the registry name as specified in Cargo.toml with the index URL - I can't see how to that from the docs but if it's possible then I agree this PR can be discarded (https://docs.renovatebot.com/rust/ doesn't mention a `registryUrls` field unlike  other managers e.g pip/maven)

2023-02-22 09:16 UTC, HonkingGoose requested changes

2023-02-22 09:16 UTC, HonkingGoose commented on docs/usage/rust.md
> +1. Renovate looks up Cargo configuration to discover index URLs for private registries.
```suggestion
1. Renovate looks up Cargo configuration to find index URLs for private registries
```

We don't use punctuation at the end of a list item. I like `find` better than `discover`.

2023-02-22 09:16 UTC, HonkingGoose commented on docs/usage/rust.md
> +Renovate can determine private registry URLs from a `.cargo/config.toml` (or the legacy `.cargo/config`) Cargo configuration file.
```suggestion
Renovate can find private registry URLs in these Cargo configuration files:

- `.cargo/config.toml`
- `.cargo/config` (legacy)
```

Changes:

- Put config files in a list
- Replace `determine` with the simple word `find`
- Rewrite the sentence a little bit

2023-02-22 09:16 UTC, HonkingGoose commented on docs/usage/rust.md
> +Renovate can also detect private registry URLs via a `CARGO_REGISTRIES_<name>_INDEX` [environment variable](https://doc.rust-lang.org/cargo/reference/environment-variables.html#configuration-environm
```suggestion
Renovate can also find private registry URLs via a `CARGO_REGISTRIES_<name>_INDEX` environment variable.
Read the [Rust environment variables docs](https://doc.rust-lang.org/cargo/reference/environment-variables.html#configuration-environment-variables) to learn more.
```

How about this:

- replace `detect` with the simple word `find`
- Split the sentence into two parts
- Use a better name for the link to the Rust docs for the environment variable

2023-02-22 09:27 UTC, HonkingGoose commented on docs/usage/rust.md
> +Renovate can also find private registry URLs via a `CARGO_REGISTRIES_<name>_INDEX` environment variable.
```suggestion

Renovate can also find private registry URLs via a `CARGO_REGISTRIES_<name>_INDEX` environment variable.
```

2023-02-22 11:58 UTC, secustor requested changes

2023-02-22 11:58 UTC, secustor commented on lib/modules/manager/cargo/extract.ts
> +          }
```suggestion
          const registryUrl = cargoRegistries[registryName] ?? getCargoIndexEnv(registryName);
```
Same as above and nested if clause has no effect.

2023-02-22 11:58 UTC, secustor commented on lib/modules/manager/cargo/extract.ts
> +}
```suggestion
function getCargoIndexEnv(registryName: string): string | null {
  const registry = registryName.toUpperCase().replaceAll('-', '_');
  return process.env[`CARGO_REGISTRIES_${registry}_INDEX`] ?? null;
}
```
Use camelCase and improve readability.

2023-02-22 17:41 UTC, secustor approved these changes, later dismissed

2023-02-22 19:57 UTC, HonkingGoose approved these changes, later dismissed
I'm happy with the docs.

2023-02-28 07:34 UTC, secustor approved these changes

2023-04-18 08:49 UTC, viceice approved these changes

2023-04-18 09:12 UTC, merged

2023-04-18 10:11 UTC, renovate-release commented
:tada: This PR is included in version 35.53.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.53.0)
- `35.53.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: