feat(presets): add vitest to jsUnitTest
renovatebot/renovate pull request #20389
Opened 2023-02-14 04:25 UTC by Mister-Hope

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

## See https://vitest.dev/

2023-02-14 04:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=20389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=20389) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=20389) it.</sub>

2023-02-14 04:28 UTC, Mister-Hope commented
Also, vitest is popular because more and more projects are using vite, vitest itself is a monorepo and has packages like `@vitest/coverage-c8`, if you agree that it's been a popular pacakge, then we can also create a monorepo preset for it.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/33315834/218639503-56e4e8e7-baa7-4b60-8ca1-a2ac80bf4b68.png">

2023-02-14 05:22 UTC, rarkins submitted a review, later dismissed

2023-02-14 06:33 UTC, viceice approved these changes

2023-02-14 06:35 UTC, viceice requested changes

2023-02-14 06:35 UTC, viceice commented on lib/config/presets/internal/packages.ts
> +      'vitest',
if the packages are scoped to `@vitest/`, you should add that prefix below too

2023-04-19 04:24 UTC, JamieMagee commented on lib/config/presets/internal/packages.ts
>        '@testing-library',
```suggestion
      '@testing-library',
      '@vitest',
```

2023-04-19 13:50 UTC, JamieMagee approved these changes

2023-04-19 16:21 UTC, viceice approved these changes

2023-04-19 16:53 UTC, merged

2023-04-19 17:30 UTC, renovate-release commented
:tada: This PR is included in version 35.54.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.54.0)
- `35.54.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: