docs: explain Renovate config for GitHub Merge Queue
renovatebot/renovate pull request #20452
Opened 2023-02-16 13:09 UTC by HonkingGoose

## Changes

- Add new sections in the Key Concepts, Automerge page to explain how to get Renovate working with GitHub's Merge Queue
- Link to the new sections from the `platformAutomerge` docs

## Context

Closes #20321.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-02-16 14:20 UTC, viceice approved these changes, later dismissed
like it, we probably should add a note that it's a beta feature?

2023-02-16 17:10 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +To learn how to use GitHub's Merge Queue feature with Renovate, read the [Key Concepts page, GitHub Merge Queue](./key-concepts/automerge.md#github-merge-queue) page.
```suggestion
To learn how to use GitHub's Merge Queue feature with Renovate, read our [Key Concepts, Automerge, GitHub Merge Queue](./key-concepts/automerge.md#github-merge-queue) docs.
```

2023-02-16 17:18 UTC, HonkingGoose commented
I've added a note that says GitHub's Merge Queue is labeled as beta by GitHub. 😉

2023-02-16 18:30 UTC, viceice submitted a review, later dismissed

2023-02-17 01:31 UTC, vchernin commented
For me this feature didn't work unless [Auto Merge was allowed in repository settings](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository#managing-auto-merge). Maybe that is worth mentioning in the docs too?

2023-02-17 05:51 UTC, rarkins requested changes

2023-02-17 05:51 UTC, rarkins commented on docs/usage/key-concepts/automerge.md
> +   }
```suggestion
   {
     "platformAutomerge": true,
     "packageRules": [{
       "description": "Automerge non-major updates",
       "matchUpdateTypes": ["minor", "patch"],
       "automerge": true
     }]
   }
```

Recommending automerge=true at root level is not a good idea!

2023-02-17 05:51 UTC, rarkins commented on docs/usage/key-concepts/automerge.md
> +   ```
```suggestion
1. Allow Renovate to automerge by setting `automerge=true` and `platformAutomerge=true` in your Renovate config file (see earlier example)
   ```
```

2023-02-17 11:33 UTC, HonkingGoose commented
> **build / lint (pull_request)** Cancelled after 14m 

It took nearly 15 minutes for the _Set up Node.js 18_ step, and then the whole thing timed-out. Looks like there's a problem with downloading the Node.js cached files. At first the download is fast, but it drops to 0.1 mb/s quickly. Logs: https://github.com/renovatebot/renovate/actions/runs/4203138015/jobs/7292162459

2023-02-17 13:18 UTC, rarkins approved these changes

2023-02-18 20:05 UTC, HonkingGoose commented
I think we're good to go now. 😉

2023-02-18 22:46 UTC, merged

2023-02-19 19:50 UTC, renovate-release commented
:tada: This PR is included in version 34.146.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.146.1)
- `34.146.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: