refactor: PackageFile types
renovatebot/renovate pull request #20498
Opened 2023-02-18 12:17 UTC by rarkins

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-02-18 12:31 UTC, RahulGautamSingh requested changes
Some Todos not needed anymore

2023-02-18 12:31 UTC, RahulGautamSingh commented on lib/workers/repository/onboarding/pr/index.ts
>          // TODO: types (#7154)
```suggestion
```

2023-02-18 12:31 UTC, RahulGautamSingh commented on lib/workers/repository/package-files.ts
>            // TODO: types (#7154)
```suggestion
```

2023-02-18 16:05 UTC, rarkins commented
Blocked by #20502

2023-02-20 07:34 UTC, viceice reviewed
more later

2023-02-20 07:34 UTC, viceice commented on lib/modules/manager/maven/extract.ts
> +): PackageFile<Record<string, any>> | null {
```suggestion
): PackageFile | null {
```
remove default type

2023-02-20 07:34 UTC, viceice commented on lib/modules/manager/maven/extract.ts
> +): PackageFile<Record<string, any>>[] {
```suggestion
): PackageFile[] {
```

2023-02-20 08:40 UTC, viceice reviewed
otherwise LGTM

2023-02-20 09:17 UTC, viceice reviewed
otherwise LGTM

2023-02-20 09:17 UTC, viceice commented on lib/modules/manager/maven/extract.ts
> +): PackageFile | null {
needs prettifying

2023-02-20 09:41 UTC, viceice submitted a review, later dismissed

2023-02-20 14:43 UTC, viceice approved these changes

2023-02-20 14:54 UTC, secustor approved these changes

2023-02-20 15:29 UTC, merged

2023-02-20 16:04 UTC, renovate-release commented
:tada: This PR is included in version 34.146.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.146.3)
- `34.146.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: