refactor: postUpgradeCommandsExecutor
renovatebot/renovate pull request #20571
Opened 2023-02-22 13:00 UTC by damien-danglard

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-02-23 09:02 UTC, viceice commented on lib/workers/repository/update/branch/execute-upgrade-commands.ts
> +        'Executing ' + taskType.toLowerCase() + ' task'
```suggestion
        `Executing ${taskType.toLowerCase()} task'
```
use string template

2023-02-23 09:02 UTC, viceice commented on lib/workers/repository/update/branch/execute-upgrade-commands.ts
> +        'Executed ' + taskType.toLowerCase() + ' task'
same

2023-02-23 09:02 UTC, viceice commented on lib/workers/repository/update/branch/execute-upgrade-commands.ts
> +      taskType + ' task did not match any on allowedPostUpgradeCommands list'
same

2023-02-23 09:02 UTC, viceice commented on lib/workers/repository/update/branch/execute-upgrade-commands.ts
> +        logger.debug({ file: relativePath, pattern }, taskType + ' file saved');
same

2023-02-23 09:02 UTC, viceice commented on lib/workers/repository/update/branch/execute-upgrade-commands.ts
> +          taskType + ' file removed'
same

2023-02-26 10:02 UTC, viceice commented on lib/workers/repository/update/branch/execute-upgrade-commands.ts
> +  const commands = upgradeTask?.commands ?? [];
we should validate allowed commands here, so we can skip file persisting if no allowed commands are available.

2023-03-26 17:40 UTC, viceice requested changes

2023-03-26 17:40 UTC, viceice commented on lib/workers/repository/update/branch/execute-post-upgrade-commands.ts
> +    artifactErrors = [...artifactErrors, ...result.artifactErrors];
we should pass the array to the called function and add results directly, so we don't need to clone it in each iteration.

2023-03-26 17:40 UTC, viceice commented on lib/workers/repository/update/branch/execute-upgrade-commands.ts
> +      artifactErrors = [...artifactErrors, ...commandError];
use push instead, so we don't clone the array on each iteration .

i think we should better pass the existing array and push in called function to have less clones

2023-09-16 07:50 UTC, rarkins commented
Closing due to inactivity. Reopening or re-raising are welcome!

2023-09-16 07:50 UTC, closed without merging