Failed automerge commenting
renovatebot/renovate pull request #2058
Opened 2018-06-01 15:52 UTC by dragomirt

This PR adds the feature of commenting on a failed automerge.

Closes #1934

2018-06-01 16:19 UTC, rarkins commented on lib/workers/branch/index.js
> +      (async () => {
can we avoid this by having the full function be async instead?

2018-06-04 12:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovateapp/renovate?pullRequest=2058) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/renovateapp/renovate?pullRequest=2058) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dragomirt<br/>:x: Dragomir Țurcanu<br/><hr/>**Dragomir Țurcanu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovateapp/renovate?pullRequest=2058) it.</sub>

2018-06-04 14:16 UTC, dragomirt commented
It works fine on GitHub, but as it seems, there is no `ensureComment` function for GitLab (https://github.com/renovateapp/renovate/blob/9fbaf9a3ca313429c9fc0d29ae892306d89559ff/lib/platform/gitlab/index.js#L384). Working on that.

2018-06-04 15:49 UTC, rarkins commented
If you add ensureComment for GitLab, please make it a separate PR that we merge first. It would be useful

2018-06-04 18:47 UTC, rarkins commented on lib/workers/branch/index.js
> +      const branchPr = await platform.getBranchPr(config.branchName);
On the first run through, this PR won't exist yet

2018-06-04 18:50 UTC, rarkins requested changes
Needs a change in logic/location to happen after initial PR creation.

2018-06-05 06:58 UTC, rarkins commented on lib/workers/branch/index.js
> +        // istanbul ignore if
No, this needs to be in PR, not branch. It should be run after the createPr

2018-06-07 12:28 UTC, rarkins approved these changes

2018-06-07 12:42 UTC, merged