feat(github-tags): use merge registryStrategy
renovatebot/renovate pull request #20617
Opened 2023-02-24 20:49 UTC by mgoodness

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-02-24 20:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=20617) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=20617) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=20617) it.</sub>

2023-02-24 20:53 UTC, rarkins commented
Why?

2023-02-24 20:54 UTC, mgoodness commented
> Why?

Sorry, this is admittedly premature. Context [here](https://github.com/renovatebot/renovate/issues/10178#issuecomment-1444463032).

2023-02-25 07:26 UTC, viceice requested changes
no, too risky

2023-02-25 15:47 UTC, closed without merging