feat(docker): match Containerfile
renovatebot/renovate pull request #20804
Opened 2023-03-08 07:56 UTC by lmilbaum

docker manager matches files named: Containerfile

2023-03-08 20:59 UTC, viceice approved these changes, later dismissed

2023-03-09 04:59 UTC, rarkins requested changes

2023-03-09 04:59 UTC, rarkins commented on lib/modules/manager/dockerfile/readme.md
> +The default container images versioning for container images datasources treats suffixes as "compatibility", for example: `-alpine`.
```suggestion
The default `docker` versioning for container image datasources treats suffixes as "compatibility", for example: `-alpine`.
```

2023-03-09 04:59 UTC, rarkins commented on lib/modules/manager/dockerfile/readme.md
> +Extracts all parent images in a `Dockerfile` and/or `Containerfile`.
```suggestion
Extracts image references in a `Dockerfile` and/or `Containerfile`.
```

2023-03-10 04:52 UTC, viceice approved these changes

2023-03-10 05:37 UTC, rarkins approved these changes

2023-03-10 06:20 UTC, merged

2023-03-10 07:31 UTC, renovate-release commented
:tada: This PR is included in version 34.160.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/34.160.0)
- `34.160.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: