Feat/18715 php filter releases
renovatebot/renovate pull request #20842
Opened 2023-03-10 10:21 UTC by Lctrs

## Changes

- Adds an optional method subset to VersioningApi interface that returns true if first argument is a subset of second argument, false otherwise
- Adds implementations for it in npm, composer, and python versioning
- Uses it in releases filtering in strict constraints mode with fallback to matching

## Context

- Revival of #20217 following branch `v35` merge
- Closes #8476
- Closes #18715
- Closes #19851 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2023-03-11 05:23 UTC, rarkins requested changes
Needs coverage update

2023-03-12 12:53 UTC, rarkins commented
Missing coverage:

![image](https://user-images.githubusercontent.com/6311784/224545947-6c5afd3b-e5b5-4766-9693-14a90210dff1.png)

2023-03-12 19:21 UTC, viceice submitted a review, later dismissed

2023-03-13 19:29 UTC, rarkins commented
@Lctrs have you done any recent sanity test on a real repo?

2023-03-13 22:55 UTC, Lctrs commented
@rarkins just did it in https://github.com/Lctrs/playground/pull/2. Still works well.

2023-03-14 05:27 UTC, rarkins requested changes

2023-03-14 05:27 UTC, rarkins commented on docs/usage/configuration-options.md
> +This feature is limited to `composer`, `npm`, `pypi` and `poetry` datasources.
```suggestion
This feature is limited to `packagist`, `npm`, and `pypi` datasources.
```

2023-03-15 06:11 UTC, rarkins approved these changes

2023-03-15 07:30 UTC, merged

2023-03-15 08:46 UTC, renovate-release commented
:tada: This PR is included in version 35.7.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.7.0)
- `35.7.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: