fix(platform/github): detect pr-edited if target changed
renovatebot/renovate pull request #21026
Opened 2023-03-18 11:24 UTC by RahulGautamSingh

## Changes
- Add `targetBranch` to the list of returned fields after the PR info is coerced

## Context
- Closes: https://github.com/renovatebot/renovate/issues/20915

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2023-03-18 13:39 UTC, rarkins requested changes

2023-03-18 13:39 UTC, rarkins commented on lib/modules/platform/github/common.ts
> +  if (pr.base) {
```suggestion
  if (pr.base?.ref) {
```

2023-03-18 14:44 UTC, rarkins approved these changes, later dismissed

2023-03-19 16:08 UTC, viceice approved these changes, later dismissed

2023-03-19 16:23 UTC, RahulGautamSingh commented
@viceice  Sorry I had to make a change to the test. The test was working but it was testing a different case than intended.

2023-03-19 16:24 UTC, viceice approved these changes

2023-03-19 16:31 UTC, merged

2023-03-19 17:19 UTC, renovate-release commented
:tada: This PR is included in version 35.14.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.14.1)
- `35.14.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: