fix(platform/github): don't retry merge when blocked by required status check
renovatebot/renovate pull request #21063
Opened 2023-03-21 08:49 UTC by viceice

## Changes
Don't try other merge methods when blocked by required status checks

## Context
- closes #17782

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-03-21 11:56 UTC, rarkins requested changes

2023-03-21 11:56 UTC, rarkins commented on lib/modules/platform/github/index.ts
> +          logger.warn(
I don't think a warn is necessary here

2023-03-21 20:39 UTC, viceice commented on lib/modules/platform/github/index.ts
> +          logger.warn(
```suggestion
          logger.debug(
```
use debug?

2023-03-22 13:59 UTC, secustor approved these changes

2023-03-23 08:17 UTC, rarkins approved these changes

2023-03-23 08:43 UTC, merged

2023-03-23 09:14 UTC, renovate-release commented
:tada: This PR is included in version 35.18.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.18.1)
- `35.18.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: