feat(datasource): rename `node` -> `node-version`
renovatebot/renovate pull request #21149
Opened 2023-03-25 11:12 UTC by RahulGautamSingh

## Changes
- rename `node` -> `node-version`

## Context
- Closes: https://github.com/renovatebot/renovate/issues/20844

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-03-25 11:59 UTC, RahulGautamSingh commented
@viceice Do we need to migrate `datasourceTemplate` as well?
eg.
```json
"regexManagers": [
    {
      "fileMatch": ["^main.yml$"],
      "matchStringsStrategy": "combination",
      "matchStrings": [
        "prometheus_image:\\s*\"(?<depName>.*)\"\\s*//",
        "prometheus_version:\\s*\"(?<currentValue>.*)\"\\s*//"
      ],
      "datasourceTemplate": "docker"
    }
]
```

2023-03-25 12:57 UTC, viceice requested changes
we need to migrate `hostType` 😱

@rarkins we haven't done it for other renames and until yet nobody complained 🤔

2023-04-12 02:32 UTC, RahulGautamSingh commented
We don't have to migrate `datasourceTemplate` separately.

Here we can see that both `datasource` and `datasourceTemplate` value are sent to updateDependecy fn.
Note that `field` value in both cases is `datasource`.
https://github.com/renovatebot/renovate/blob/0d000aea1d3dc70eb6f0c5453b854fa519e71f46/lib/modules/manager/regex/utils.ts#L60-L76

And we migrate datasource:
https://github.com/renovatebot/renovate/blob/0d000aea1d3dc70eb6f0c5453b854fa519e71f46/lib/modules/manager/regex/utils.ts#L41

2023-04-12 02:38 UTC, RahulGautamSingh commented
> we need to migrate hostType 😱
> @rarkins we haven't done it for other renames and until yet nobody complained 🤔

Maybe cause the affected datasources aren't used as hostType or the option itself is less used.

2023-04-12 04:07 UTC, viceice commented on lib/config/presets/internal/regex-managers.spec.ts
> +          # renovate: datasource=node-version depName=node versioning=node
shouldn't we leave it to validate migration?

2023-04-12 10:48 UTC, viceice commented on lib/config/presets/internal/regex-managers.spec.ts
> +                  node: \${{ env.NODE_VERSION }}
this change is wrong

2023-04-12 12:25 UTC, RahulGautamSingh commented on lib/config/presets/internal/regex-managers.spec.ts
> +                  node: \${{ env.NODE_VERSION }}
```suggestion
                  node-version: \${{ env.NODE_VERSION }}
```

2023-04-12 13:43 UTC, viceice approved these changes

2023-04-12 14:36 UTC, merged

2023-04-12 15:22 UTC, renovate-release commented
:tada: This PR is included in version 35.43.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.43.0)
- `35.43.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: