docs(pull requests): rewrite
renovatebot/renovate pull request #21440
Opened 2023-04-12 08:20 UTC by HonkingGoose

## Changes

- Use ordered lists for complex explanations
- Use simple words and phrases

## Context

Drive-by PR, not closing any issue with this.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-04-12 10:59 UTC, rarkins requested changes

2023-04-12 10:59 UTC, rarkins commented on docs/usage/key-concepts/pull-requests.md
> +Renovate does not keep any database/state about open or closed Pull Requests.
```suggestion
Renovate does not need to maintain any database/state about open or closed Pull Requests.
```

We do kind of keep state with repositoryCache, so I want to loosen the wording a little

2023-04-12 12:23 UTC, rarkins approved these changes

2023-04-13 08:04 UTC, HonkingGoose commented
@rarkins can you add this to the Merge Queue?

2023-04-13 09:10 UTC, merged

2023-04-13 10:02 UTC, renovate-release commented
:tada: This PR is included in version 35.46.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.46.1)
- `35.46.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: