feat: support depth URL argument in Terragrunt modules
renovatebot/renovate pull request #21494
Opened 2023-04-13 14:53 UTC by emil2k

## Changes

Add Support for renovating Terraform Modules from Git repositories using shallow clone URL argument by expanding the Regex

## Context

Similar to https://github.com/renovatebot/renovate/pull/21287 but for Terragrunt.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-04-15 17:52 UTC, secustor requested changes

2023-04-15 17:52 UTC, secustor commented on lib/modules/manager/terragrunt/extract.spec.ts
> +      expect(res).toMatchSnapshot();
Do not use `toMatchSnapshot` rather use `toEqual`

We have newer code style guides https://github.com/renovatebot/renovate/blob/main/docs/development/best-practices.md#unit-testing

2023-04-15 17:52 UTC, secustor commented on lib/modules/manager/terragrunt/extract.spec.ts
> +      expect(res).toMatchSnapshot();
Do not use `toMatchSnapshot` rather use `toEqual`

2023-04-15 17:52 UTC, secustor commented on lib/modules/manager/terragrunt/extract.spec.ts
> +      const res = extractPackageFile(Fixtures?.get('4.hcl'));
I don't think the optional chaining is necessary.

2023-04-17 09:26 UTC, secustor commented on lib/modules/manager/terragrunt/__fixtures__/4.hcl
> +#ip
This is not Ip.

2023-04-17 09:26 UTC, secustor commented on lib/modules/manager/terragrunt/modules.ts
> +  /github\.com([/:])(?<project>[^/]+\/[a-z0-9-_.]+).*\?(depth=\d+&)?ref=(?<tag>.*?)(&depth=\d+)?$$/i
```suggestion
  /github\.com([/:])(?<project>[^/]+\/[a-z0-9-_.]+).*\?(depth=\d+&)?ref=(?<tag>.*?)(&depth=\d+)?$/i
```
Why the double dollar sign?

2023-04-17 09:26 UTC, secustor commented on lib/modules/manager/terragrunt/modules.ts
> +  /(?:git::)?(?<url>(?:http|https|ssh):\/\/(?:.*@)?(?<path>.*.*\/(?<project>.*\/.*)))\?(depth=\d+&)?ref=(?<tag>.*?)(&depth=\d+)?$$/
Same here.

2023-04-17 10:45 UTC, emil2k commented on lib/modules/manager/terragrunt/__fixtures__/4.hcl
> +}
This is basically taken from the preexisting fixture, but I could make the change.

2023-04-17 12:00 UTC, viceice reviewed
Do we really need so many fixtures?

2023-04-17 22:02 UTC, secustor approved these changes

2023-04-18 05:25 UTC, merged

2023-04-18 06:02 UTC, renovate-release commented
:tada: This PR is included in version 35.52.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.52.0)
- `35.52.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: