docs(config options): rewrite `matchPaths` and `matchFiles`
renovatebot/renovate pull request #21582
Opened 2023-04-18 14:39 UTC by HonkingGoose

## Changes

- Add admonition to deprecated partial matches for `matchPaths`
- Monospace the word `minimatch`
- Convert paragraph to `tip` admonition
- General rewrite
- Add link to `matchPaths` or `matchFiles` headings where helpful
- Convert plain codeblock to correct JSON

## Context

Follow-up after discussion: #21573.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-04-19 09:52 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +!!! caution
```suggestion
!!! warning
```

I'm using `warning` here, as `caution` is no longer supported by Material for MkDocs.

2023-04-23 06:57 UTC, rarkins requested changes

2023-04-23 06:57 UTC, rarkins commented on docs/usage/configuration-options.md
> +If you wish to limit Renovate to apply configuration rules to certain files in the root repository directory, you have to use `matchPaths` with a `minimatch` pattern or use [`matchFiles`](#matchfiles
```suggestion
If you wish to limit Renovate to apply configuration rules to certain files in the root repository directory, you have to use `matchPaths` with a `minimatch` pattern or use [`matchFiles`](#matchfiles) with an exact match.
```

2023-04-23 06:57 UTC, rarkins commented on docs/usage/configuration-options.md
>  ```json
It should instead be `"matchFiles": ["package.json"],` instead of the `matchPaths` example

2023-04-24 06:27 UTC, viceice approved these changes

2023-04-26 17:20 UTC, rarkins approved these changes

2023-04-26 17:53 UTC, merged

2023-04-27 06:23 UTC, renovate-release commented
:tada: This PR is included in version 35.62.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.62.0)
- `35.62.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: