refactor(manager/gradle): Dismiss `ANNOYING_METHODS` approach
renovatebot/renovate pull request #21753
Opened 2023-04-22 16:07 UTC by zharinov

## Changes

- Dismiss `foo('bar', 'baz', '<...>')` dependencies based on whether third argument contains any numeric characters or not
- Remove blocklist of methods that were leading to `ignored` skip reason

## Context

- Ref: https://github.com/renovatebot/renovate/issues/19226#issuecomment-1513604572

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-04-22 16:09 UTC, viceice approved these changes, later dismissed

2023-04-22 16:21 UTC, Churro approved these changes, later dismissed

2023-04-22 16:21 UTC, Churro commented on lib/modules/manager/gradle/parser.spec.ts
> +      ${'createXmlValueRemover("defaults", "integer", "integer")'} | ${null}
As the check is now done on the version value and not the method name anymore, these tests are somewhat redundant. I'd suggest to reduce the list to just one sample, e.g. `listOf("foo", "bar", "baz")`. WDYT?

2023-04-22 16:36 UTC, zharinov commented
I think it's logically consistent to fix both cases in single PR, and close the original issue

2023-04-22 16:54 UTC, Churro requested changes

2023-04-22 16:54 UTC, Churro commented on lib/modules/manager/gradle/parser/handlers.ts
> +  if (!regEx(/\d/).test(version)) {
With 0fe94e7003311be2e393e213cfafa4b5b0e3734e, this check should be redundant here. The subsequent execution flow is: 

`parseDependencyString()` -> `isDependencyString()` -> `versionLikeSubstring()`

2023-04-22 19:29 UTC, Churro approved these changes

2023-04-23 06:33 UTC, merged

2023-04-23 08:47 UTC, renovate-release commented
:tada: This PR is included in version 35.57.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.57.2)
- `35.57.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: