feat: MergeBranch function for GitLab wrapper
renovatebot/renovate pull request #2178
Opened 2018-06-26 14:37 UTC by dragomirt

This PR adds `mergeBranch` and `getBranchCommit` functions to GitLab's wrapper. **Still in testing**

2018-06-26 14:52 UTC, rarkins commented on lib/platform/gitlab/index.js
> +  if (mergeType === 'branch-push') {
Now “branch” only

2018-06-26 19:18 UTC, rarkins requested changes

2018-06-26 19:18 UTC, rarkins commented on lib/platform/gitlab/index.js
> +  if (config.pushProtection) {
We don't yet have this field in GitLab so this if statement can be removed

2018-06-26 19:18 UTC, rarkins commented on lib/platform/gitlab/index.js
> +      throw new Error('branch-push failed');
We should align this with GitHub

2018-06-26 19:18 UTC, rarkins commented on lib/platform/gitlab/index.js
> +    const sha = await getBranchCommit(branchName);
Can't we just use the branch name instead of looking up `sha`?

2018-06-26 19:18 UTC, rarkins commented on lib/platform/gitlab/index.js
> +async function getBranchCommit(branchName) {
We may still need this to determine if a branch is up to date with `master`

2018-06-28 13:17 UTC, dragomirt commented on lib/platform/gitlab/index.js
> -  checkCompatibility,
`checkCompatibility` should be exported because it's used in the tests.

2018-06-28 13:28 UTC, rarkins commented
The exports of each platform need to be the same , so it cannot be exported and instead needs to be tested as part of mergeBranch

2018-07-02 08:33 UTC, rarkins commented
@dragomirt I have removed the unnecessary code, could you update the tests?

2018-07-02 09:25 UTC, rarkins approved these changes

2018-07-02 09:27 UTC, merged