feat!: v36
renovatebot/renovate pull request #21810
Opened 2023-04-26 06:15 UTC by rarkins

2023-04-26 08:23 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +If you have enabled `automerge` and set `automergeType=pr` in the Renovate config, then leaving `platformAutomerge` as `true` speeds up merging via the platform's native automerge functionality.
```suggestion
If you have enabled `automerge` _and_ set `automergeType=pr` in the Renovate config, then leaving `platformAutomerge` as `true` speeds up merging via the platform's native automerge functionality.
```

Maybe we should emphasize the _and_ part of the sentence? You need both conditions to be true for the rest of the sentence to apply.

2023-04-27 19:46 UTC, viceice commented
the gitlab comment commit probably needs a message fix-up

2023-06-18 10:36 UTC, viceice requested changes
☺️

2023-07-04 17:21 UTC, merged

2023-07-04 18:22 UTC, renovate-release commented
:tada: This PR is included in version 36.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/36.0.0)
- `36.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: