feat(npm)!: disable rollbackPrs for npm by default
renovatebot/renovate pull request #21970
Opened 2023-05-04 10:22 UTC by rarkins

## Changes

Disables rollbackPrs by default for npm

## Context

I think there's too many false positives here that outweigh the benefits. This means that users can opt-in if they see a need.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-05-04 20:14 UTC, HonkingGoose requested changes

2023-05-04 20:14 UTC, HonkingGoose commented on lib/modules/manager/npm/index.ts
> -  rollbackPrs: true,
You'll need to change the docs for this change. 😉 Quote from the `rollbackPrs` config option docs:

> Renovate does not create these rollback PRs by default, with one exception: npm packages get a rollback PR if needed.

2023-05-05 07:03 UTC, HonkingGoose approved these changes

2023-05-05 17:47 UTC, viceice approved these changes

2023-05-05 17:47 UTC, merged