ignoreApprovals add check for existingAnyApproverRule
renovatebot/renovate pull request #22237
Opened 2023-05-15 16:04 UTC by fredrondina

## Changes

Update gitlab ignoreApprovals option to not break if there is an existing rule of type 'any_approver'

## Context

https://github.com/renovatebot/renovate/discussions/22063

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2023-05-15 18:07 UTC, rarkins approved these changes, later dismissed

2023-05-15 18:14 UTC, viceice requested changes, later dismissed

2023-05-15 18:14 UTC, viceice commented on lib/modules/platform/gitlab/index.spec.ts
> +      ).toMatchInlineSnapshot(`
please use toEquals

2023-05-15 20:25 UTC, fredrondina commented on lib/modules/platform/gitlab/index.spec.ts
> +      ).toMatchInlineSnapshot(`
updated to use toStrictEqual

2023-05-16 12:29 UTC, a1flecke commented
@fredrondina   Thanks for doing this.  These changes look good

2023-05-16 12:29 UTC, a1flecke approved these changes

2023-05-16 12:53 UTC, rarkins approved these changes

2023-05-16 13:21 UTC, merged