fix(github): try push branch if rebase fails
renovatebot/renovate pull request #22376
Opened 2023-05-23 14:14 UTC by rarkins

## Changes

Catches and retries a branch rebase when it seems the branch does not exist.

## Context

Closes #22366

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-05-23 14:27 UTC, secustor commented on lib/modules/platform/github/index.ts
> +        );
```suggestion
        );
        return;
```
I guess you do not want to continue here?

2023-05-23 15:07 UTC, zharinov approved these changes

2023-05-23 15:36 UTC, zharinov requested changes

2023-05-23 15:36 UTC, zharinov commented on lib/modules/platform/github/index.ts
>    const refUrl = `/repos/${config.repository}/git/refs/heads/${branchName}`;
Let's also check for commit existence:

```suggestion
  const commitUrl = `/repos/${config.repository}/git/commits/sha`;
  await githubApi.head(commitUrl, { memCache: false });

  const refUrl = `/repos/${config.repository}/git/refs/heads/${branchName}`;
```

2023-05-23 15:53 UTC, zharinov commented on lib/modules/platform/github/index.ts
>    const refUrl = `/repos/${config.repository}/git/refs/heads/${branchName}`;
I've reproduced 422 by trying to patch existing branch with non-existent commit SHA. This explains why people suffer in both `PATCH` and `POST` branches of execution. Probably we needed to check the commit existence in the first place, when created `ensureBranchSha`.

2023-05-25 13:15 UTC, merged

2023-05-25 13:55 UTC, renovate-release commented
:tada: This PR is included in version 35.101.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.101.0)
- `35.101.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: