feat(manager/pep621): uses required-python to set constraint
renovatebot/renovate pull request #22456
Opened 2023-05-27 14:15 UTC by secustor

## Changes
Extracts the `requires-python` field and uses it to set tool constraint. 

## Context
https://github.com/renovatebot/renovate/pull/22441#discussion_r1207118704

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-05-27 14:31 UTC, rarkins requested changes

2023-05-27 14:31 UTC, rarkins commented on lib/modules/manager/pep621/processors/pdm.ts
> +          def?.project?.['requires-python'] ?? config.constraints?.python,
Normally configured constraints take precedence unless the package itself is part of the branch updates

2023-05-27 14:31 UTC, rarkins commented on lib/modules/manager/pep621/extract.ts
Consider adding python to extractedConstraints so that it can be take into consideration for constraintsFiltering=strict

2023-05-27 15:58 UTC, viceice commented on lib/modules/manager/pep621/processors/pdm.ts
> +      const def = parsePyProject(packageFileName, newPackageFileContent);
we should avoid to parse the file more that once while extract or artifacts update

2023-05-28 05:09 UTC, rarkins approved these changes

2023-05-28 08:19 UTC, rarkins commented
@viceice please merge when ready

2023-05-28 08:30 UTC, viceice approved these changes

2023-05-28 08:52 UTC, merged

2023-05-28 09:31 UTC, renovate-release commented
:tada: This PR is included in version 35.103.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.103.0)
- `35.103.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: