Fix: Replace default constants with default factories
renovatebot/renovate pull request #22587
Opened 2023-06-05 14:50 UTC by mdaniline

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-06-05 14:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=22587) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=22587) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=22587) it.</sub>

2023-06-05 15:19 UTC, viceice approved these changes

2023-06-05 16:03 UTC, viceice reviewed
needs tests to resolve failing code coverage

2023-06-06 17:32 UTC, viceice requested changes
needs test for code coverage

2023-06-29 16:14 UTC, viceice reviewed
I think just handling the array issue instead of changing all is a much simpler and better solution.

@secustor @rarkins WDYT?

2023-06-29 16:14 UTC, viceice commented on lib/config/defaults.spec.ts
> +});
missing trailing newline, run prettier

2023-06-29 16:21 UTC, mdaniline commented
FWIW I wrote it this way to avoid having specialised logic per type - it's pretty obvious what happens without needing to worry about edge cases. Also it leaves this future-proofed in case we ever want to return `{}` instead of `null` for objects.

2023-06-29 16:23 UTC, mdaniline commented on lib/config/defaults.spec.ts
> +});
Done

2023-06-30 08:32 UTC, viceice submitted a review, later dismissed

2023-06-30 19:49 UTC, secustor commented on lib/config/defaults.spec.ts
> +        expect(val).toBe(null);
```suggestion
        expect(val).toBeNull();
```

2023-06-30 19:49 UTC, secustor commented on lib/config/defaults.spec.ts
> +    ['string', 'object', 'integer'].forEach((type: unknown) => {
```suggestion
    ['string', 'object', 'integer'].forEach((type: string) => {
```

2023-06-30 19:53 UTC, secustor approved these changes

2023-06-30 20:03 UTC, merged

2023-06-30 20:17 UTC, renovate-release commented
:tada: This PR is included in version 35.151.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.151.0)
- `35.151.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-01 08:30 UTC, viceice commented on lib/config/defaults.spec.ts
> +    ['string', 'object', 'integer'].forEach((type: string) => {
@zharinov can you convert to jest each function instead?