feat(presets): add tfvarsVersions preset
renovatebot/renovate pull request #22595
Opened 2023-06-06 10:33 UTC by morremeyer

## Changes

This adds a `tfvarsVersions` preset as discussed in https://github.com/renovatebot/renovate/pull/21994#discussion_r1188303503.

## Context

This change will make it easier to update versions in `.tfvars` files.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-06-06 11:29 UTC, HonkingGoose requested changes

2023-06-06 11:29 UTC, HonkingGoose commented on lib/config/presets/internal/regex-managers.ts
> +    description: 'Update `*_version` variables in `.tfvars` files',
```suggestion
    description: 'Update `*_version` variables in `.tfvars` files.',
```

Let's end the sentence with a full stop.

I'll let the maintainers review the code. 🙂

2023-06-06 14:27 UTC, HonkingGoose approved these changes
I'm happy with the description now. I'll leave the code review to the maintainers.

2023-06-08 09:21 UTC, rarkins approved these changes

2023-06-08 09:47 UTC, merged

2023-06-08 10:21 UTC, renovate-release commented
:tada: This PR is included in version 35.115.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.115.0)
- `35.115.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: