fix(gitlab): gitLabIgnoreApprovals works with multiple approval rules
renovatebot/renovate pull request #22693
Opened 2023-06-12 11:00 UTC by t-kulmburg

## Changes

Currently `gitLabIgnoreApprovals` sets the `approvals_required` parameter to 0 only for the default `any_approver` rule.
If additional custom approval rules are in place in the project configuration, automerge is not working anymore since GitLab 1.16 because of this: https://gitlab.com/gitlab-org/gitlab/-/issues/388140

## Context

Simpler fix compared to https://github.com/renovatebot/renovate/pull/22306, without adding an additional config option.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2023-06-12 21:57 UTC, cjpearson commented
I also don't see the use case for the config option and think it's fine to remove. My preference would be to remove approval rules instead of setting the approver count to zero, but I don't know if that makes a difference in practice. I just think it makes renovate's behavior more obvious and I wasn't sure if resetting the count would work for all types of approval rules.

Also, are we sure every MR would have at least one `any_approver` rule?

2023-06-13 04:19 UTC, viceice requested changes

2023-06-13 04:19 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +          body: { ...existingAnyApproverRule, approvals_required: 0 },
this seems wrong, you're overwriting the rule with an any approver rule, so you would finally have multiple of them, which isn't allowed on gitlab.

i think we should simply delete all rules when `gitLabIgnoreApprovals=true`

2023-06-13 09:55 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +      })
use `all` from `util/promises`to limit concurrency.

https://github.com/renovatebot/renovate/blob/45c2d13f8a1dfffe432e3cc02892119cca7131ef/lib/util/promises.ts#L38-L52

2023-06-13 09:56 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +      existingRegularApproverRules?.map(async (rule) => {
`Promise.all(undefined)` rejects, so add a condition to only do `if existingRegularApproverRules?.length`

2023-06-13 19:57 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +    if (existingRegularApproverRules.length) {
```suggestion
    if (existingRegularApproverRules?.length) {
```
will fix cannot read length of undefined 🙃

2023-06-16 07:32 UTC, viceice approved these changes

2023-06-16 07:32 UTC, viceice commented
like to have some second 👀

2023-06-16 08:02 UTC, merged

2023-06-16 08:24 UTC, renovate-release commented
:tada: This PR is included in version 35.121.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/35.121.0)
- `35.121.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: