feat: replace `dockerImagePrefix` with `sidecarImage`
renovatebot/renovate pull request #22708
Opened 2023-06-12 15:54 UTC by RahulGautamSingh

## Changes
- replace `dockerImagePrefix` with `sidecarImage`

## Context
- Closes: https://github.com/renovatebot/renovate/issues/21217

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-06-12 16:03 UTC, rarkins requested changes

2023-06-12 16:35 UTC, RahulGautamSingh commented on lib/util/exec/docker/index.spec.ts
> +    const image = dockerSidecarImage;
```suggestion
    const image = sideCarImage;
```

2023-06-12 17:43 UTC, viceice reviewed
needs migration, so old prefix gets joined with `sidecar` and assigned to new option to not break existing users.

2023-06-12 17:43 UTC, viceice commented on renovate.json
> +      "depNameTemplate": "containerbase/sidecar",
```suggestion
        "default: '(?<depName>ghcr.io/containerbase/sidecar):(?<currentValue>.*)'"
      ]
```
published times are different, so we should same image as renovate source. also made it simpler.

2023-06-12 18:53 UTC, rarkins commented
@viceice let's just make this one breaking? It only applies to self-hosted users

2023-06-13 19:00 UTC, viceice commented on lib/modules/manager/bundler/artifacts.spec.ts
> +  dockerSidecarImage: 'ghcr.io/containerbase/sidecar:8.0.2',
```suggestion
  dockerSidecarImage: 'ghcr.io/containerbase/sidecar',
```
i would prefer this to reduce test changes

2023-06-16 14:40 UTC, rarkins approved these changes

2023-06-16 17:55 UTC, viceice approved these changes

2023-06-17 07:19 UTC, merged