fix(gradle-wrapper): Show release notes in PR
renovatebot/renovate pull request #23133
Opened 2023-07-04 14:22 UTC by zharinov

## Changes

- Add `gitRef` field which is necessary for release notes fetching

## Context

- Ref: #23097

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2023-07-04 14:24 UTC, zharinov commented
Example: https://github.com/renovate-testing/test-23097-gradle-changelog/pull/2

2023-07-04 15:01 UTC, rarkins approved these changes

2023-07-04 15:01 UTC, rarkins reviewed
Let's defer until after v36

2023-07-04 15:13 UTC, viceice approved these changes

2023-07-04 15:14 UTC, viceice requested changes
defer

2023-07-07 08:11 UTC, merged

2023-07-07 08:24 UTC, renovate-release commented
:tada: This PR is included in version 36.2.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/36.2.1)
- `36.2.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: