feat(datasource): implement custom datasource
renovatebot/renovate pull request #23147
Opened 2023-07-04 21:36 UTC by secustor

## Changes
Implements a custom datasource which currently supports json http endpoints and transformations with jsonata

## Context
Supersedes https://github.com/renovatebot/renovate/pull/20753
Closes https://github.com/renovatebot/renovate/issues/10622

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

https://github.com/secustor/renovate-generic-datasource

2023-07-04 21:46 UTC, secustor commented
The coverage seems to be reported falsely again. Locally the tests pass.

2023-07-05 09:52 UTC, rarkins requested changes
I'm happy to get this merged and available as experimental as soon as we can

2023-07-05 09:52 UTC, rarkins commented on docs/usage/configuration-options.md
> +Defines which format the API is returning. Available values: `json`
```suggestion
Defines which format the API is returning.
Only `json` is supported, but more are planned for future.
```

2023-07-05 09:52 UTC, rarkins commented on lib/config/options/index.ts
> +    parent: 'customDatasources',
Good! This way we can get it out there and experiment/iterate

2023-07-10 16:41 UTC, rarkins approved these changes

2023-07-10 18:42 UTC, merged

2023-07-10 19:06 UTC, renovate-release commented
:tada: This PR is included in version 36.7.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/36.7.0)
- `36.7.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: