Fix(conan): continue on error during fetching conan package url
renovatebot/renovate pull request #23391
Opened 2023-07-15 14:00 UTC by MartijnLeijssen-TomTom

## Changes
Ignore errors during fetching package url of a conan package when using jfrog artifactory

## Context
Fixes issue #23373

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ X] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [X] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-07-17 06:56 UTC, viceice commented on lib/modules/datasource/conan/index.ts
> +            logger.warn(`Couldn't determine conan package url ${err}`);
```suggestion
            logger.debug({ err }, `Couldn't determine conan package url`);
```
this error isn't Essential

2023-07-17 07:49 UTC, viceice submitted a review, later dismissed

2023-07-17 08:13 UTC, HonkingGoose requested changes

2023-07-17 08:13 UTC, HonkingGoose commented on lib/modules/datasource/conan/index.spec.ts
> +
This PR does not yet automatically close the relevant issue?

Correct syntax is: `Fixes #23373`

2023-07-17 10:23 UTC, HonkingGoose requested changes
The PR will now close the correct issue.

Maybe one small style fix and we're good to go, from my end, at least.

2023-07-17 10:23 UTC, HonkingGoose commented on lib/modules/datasource/conan/index.ts
> +            logger.debug({ err }, "Couldn't determine conan package url");
```suggestion
            logger.debug({ err }, "Couldn't determine Conan package url");
```

I think we should capitalize the proper noun Conan here?

2023-07-17 11:05 UTC, HonkingGoose approved these changes
I'm happy with this. I'll let the maintainers review it further.

2023-07-17 12:08 UTC, viceice approved these changes

2023-07-21 19:16 UTC, merged

2023-07-21 19:31 UTC, renovate-release commented
:tada: This PR is included in version 36.18.4 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/36.18.4)
- `36.18.4`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: