Docker registry authentication
renovatebot/renovate pull request #2339
Opened 2018-08-02 15:30 UTC by mxey

I tried my hand at implementing authentication for Docker registries. This works for me with the Gitlab registry, and didn't break access to the public Docker Hub.

Since `config.endpoints` already exited internally, I added it to the config definitions so it would be merged with what's created by `config/env.js`.

I hardly speak JavaScript, so I'm wondering if this approach makes sense at all.

Closes #798

2018-08-04 06:38 UTC, rarkins commented
@kayoub5 could you take a look at this and if it fits in with your plans for `endpoints`?

2018-08-04 10:23 UTC, kayoub5 approved these changes
Looks good to me

2018-08-04 16:19 UTC, rarkins requested changes

2018-08-04 16:36 UTC, kayoub5 commented on lib/datasource/docker.js
> +    const opts = endpoints.find({ platform: 'docker', host }, { json: true });
in `endpoints` the keys `platform` and `host` are treated as identifiers, for the endpoint, however they could be renamed to something more generic like `type` and `host`.

2018-08-05 05:03 UTC, rarkins commented on lib/datasource/docker.js
> +    const opts = endpoints.find({ platform: 'docker', host }, { json: true });
OK. I'll merge this first and get you to do the renaming later

2018-08-05 05:24 UTC, rarkins approved these changes

2018-08-05 05:25 UTC, merged