feat(datasource/helm): add digest to release
renovatebot/renovate pull request #23432
Opened 2023-07-18 15:46 UTC by scmeli

## Changes

Add support for the digest of a chart archive within the helm datasource.

## Context

[discussion#23430](https://github.com/renovatebot/renovate/discussions/23430)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-07-18 17:21 UTC, viceice requested changes
nope, doesn't work like this.

2023-07-18 21:44 UTC, scmeli commented
> nope, doesn't work like this.

Thanks for the response. I updated the snapshot to fix the test cases. Can you elaborate if this is not what you meant? This change allows the regex manager to also update the digest for a helm datasource.

2023-08-24 16:42 UTC, scmeli commented
@viceice Hi, can you provide more details? These changes work in my local environment so not sure what is broken. My use case involves updating the version/digest of a helm archive within a bazel http_file rule. This PR adds the digest to the helm datasource so I can use it with a regex manager. The digest is in the index.yaml which is already parsed by the helm datasource, but is not captured since it is missing from the HelmRelease type.

2023-08-25 07:39 UTC, viceice commented on lib/modules/datasource/helm/index.ts
> +            newDigest: release.digest ?? null,
```suggestion
            newDigest: release.digest,
```
null isn't allowed on `newDigest` type

2023-08-25 07:40 UTC, viceice approved these changes

2023-08-25 08:00 UTC, merged

2023-08-25 08:11 UTC, renovate-release commented
:tada: This PR is included in version 36.58.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/36.58.0)
- `36.58.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: