Refactor github git API into its own file
renovatebot/renovate pull request #2346
Opened 2018-08-04 13:56 UTC by kayoub5

Related to #2323 and #1925

2018-08-04 18:43 UTC, rarkins requested changes
getFile still needs to use a file list to reduce API queries

2018-08-04 18:43 UTC, rarkins commented on lib/platform/github/index.js
> -    if (!config.fileList.includes(filePath)) {
With this missing, we now hit GitHub for lots of files we don't need to (and get 404 responses). e.g. renovating a `package.json` gets this output:

```
 INFO: getFile 404 (repository=renovate-tests/preset)
       "filePath": "yarn.lock",
       "branchName": undefined
 INFO: getFile 404 (repository=renovate-tests/preset)
       "filePath": "package-lock.json",
       "branchName": undefined
 INFO: getFile 404 (repository=renovate-tests/preset)
       "filePath": "npm-shrinkwrap.json",
       "branchName": undefined
 INFO: getFile 404 (repository=renovate-tests/preset)
       "filePath": "shrinkwrap.yaml",
       "branchName": undefined
 INFO: getFile 404 (repository=renovate-tests/preset)
       "filePath": ".npmrc",
       "branchName": undefined
 INFO: getFile 404 (repository=renovate-tests/preset)
       "filePath": ".yarnrc",
       "branchName": undefined
 INFO: getFile 404 (repository=renovate-tests/preset)
       "filePath": "lerna.json",
       "branchName": undefined
```

2018-08-05 12:28 UTC, kayoub5 commented
@rarkins requested changes done

2018-08-06 07:03 UTC, rarkins approved these changes

2018-08-06 07:04 UTC, merged