feat(platform/gitlab): support autoApprove option
renovatebot/renovate pull request #23460
Opened 2023-07-19 18:53 UTC by cjpearson

## Changes

Adds `autoApprove` support for the GitLab platform

## Context

https://docs.renovatebot.com/configuration-options/#autoapprove

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-07-19 19:41 UTC, viceice requested changes

2023-07-19 19:41 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +  } catch (err) /* istanbul ignore next */ {
please create a test case instead

2023-07-31 19:53 UTC, viceice approved these changes

2023-08-01 06:02 UTC, secustor approved these changes

2023-08-01 06:48 UTC, merged

2023-08-01 07:02 UTC, renovate-release commented
:tada: This PR is included in version 36.27.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/36.27.0)
- `36.27.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: