Add clarification for gitAuthor format to avoid obscure errors during commits.
renovatebot/renovate pull request #23543
Opened 2023-07-24 16:11 UTC by slonim-greg

## Changes
Add documentation clarification for `gitAuthor` config option.
Closes #23538 

## Context

The context for this change is documented in [Issue 23538](https://github.com/renovatebot/renovate/discussions/23538).
#### Bottom line:
If one supplies `gitAuthor` or overrides `RENOVATE_GIT_AUTHOR `, it is often important to supply both NAME and EMAIL according to RFC-5322.

## Documentation (please check one with an [x])

- [x] I have updated the documentation

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-07-24 16:20 UTC, rarkins reviewed
I'm not sure every platform requires both name and email

2023-07-24 16:23 UTC, slonim-greg commented
It would not hurt to include, however, to avoid similar problems, even when a platform does not require it, right?

2023-07-24 17:15 UTC, rarkins commented
I prefer not to tell something is required if it's only required for edge cases or a subset of platforms

2023-07-24 17:22 UTC, slonim-greg commented
It was a problem for our repository; Moreover, the default setting in the "standard issue" Renovate Runner repo has the name [there](https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/.gitlab-ci.yml#L6). 
We can change the docs language to say that if one encounters the problem I saw, this is what they should do. 
In reality though, this is a pretty low hanging fruit and seems pretty innocuous to include if one overrides this config value. 
Thoughts?

2023-07-24 20:09 UTC, rarkins requested changes

2023-07-24 20:09 UTC, rarkins commented on docs/usage/configuration-options.md
> +Specifically, make sure to include a name followed by an email address, e.g.
```suggestion
It's recommended to include a name followed by an email address, e.g.
```

2023-07-25 11:07 UTC, rarkins approved these changes, later dismissed

2023-07-25 12:05 UTC, rarkins submitted a review, later dismissed

2023-07-25 13:17 UTC, rarkins approved these changes

2023-07-25 13:32 UTC, merged