Fix Docker library images
renovatebot/renovate pull request #2360
Opened 2018-08-07 14:19 UTC by mxey

The default prefix is library/. Using amd64/ as the prefix created weird
issues with pinning to digests that matched no images.

2018-08-07 14:35 UTC, rarkins commented
Hi @mxey please provide some examples of the "weird issues". I would only make this change if I'm certain there is no alternative.

Background info is here: https://github.com/nodejs/docker-node/issues/718#issuecomment-387235963

2018-08-07 14:36 UTC, rarkins requested changes

2018-08-07 14:36 UTC, rarkins commented on lib/datasource/docker.js
> +  return pkgName.includes('/') ? pkgName : `library/${pkgName}`;
This needs justification as it will lead to a lot more digest churn

2018-08-07 14:41 UTC, mxey commented
Interesting background.

Renovate pinned my `golang:1.10.2` to `golang:1.10.2@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3`. 

`amd64/golang:1.10.2@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3` exists, but `library/golang:1.10.2@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3` does not. 

```
$ docker pull amd64/golang:1.10.2@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3
sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3: Pulling from amd64/golang
Digest: sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3
Status: Image is up to date for amd64/golang@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3

$ docker pull library/golang:1.10.2@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3
Error response from daemon: manifest for golang@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3 not found
```

At the least, interpreting the image name differently from Docker is very confusing.

2018-08-07 14:46 UTC, mxey commented
Hardcoding `amd64` in particular also prevents somebody from using other architectures. 

If somebody wants to prevent that particular churn, I think explicitly using `amd64` in the respective FROM would be a better option. 

Ideally, base Docker image should have a lot fewer operating system parts. This is a general problem with the Docker Library images, but see https://github.com/GoogleContainerTools/distroless/blob/master/experimental/nodejs/README.md as a counterexample.

2018-08-07 14:49 UTC, rarkins commented
The important point is that this seems to fail:

```
❯ docker pull golang:1.10.2@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3
Error response from daemon: manifest for golang@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3 not found

~
❯ docker pull golang@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3
Error response from daemon: manifest for golang@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3 not found
```

while this works:

```
❯ docker pull amd64/golang@sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3
sha256:3cb4a1c0286776da98c411f7205fed5d44a32a394d04edcfb46f199183876fc3: Pulling from amd64/golang
cc1a78bfd46b: Pulling fs layer
d2c05365ee2a: Pulling fs layer
231cb0e216d3: Pulling fs layer
```

This seems to violate the assumptions in the discussion I linked to so for now I think it's best to accept this PR until there's time to look into this further.

Cc @yosifkit in case he's watching his mentions - I think you'd be interested in this.

2018-08-07 14:50 UTC, rarkins approved these changes

2018-08-07 14:51 UTC, merged

2018-08-13 23:43 UTC, yosifkit commented
So that others can see the response as to why the sha256 from `amd64/golang` doesn't always work in `library/golang`: https://github.com/docker-library/official-images/issues/4700#issuecomment-412698799