feat(manager/helmsman): Add OCI support
renovatebot/renovate pull request #24183
Opened 2023-08-31 11:45 UTC by domolitom

## Changes

With these changes, the helmsman manager is able to scan OCI registries.

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

https://github.com/domolitom/renovate_oci_test

2023-08-31 13:25 UTC, viceice requested changes
Please sign the CLA

2023-09-04 14:15 UTC, viceice commented on lib/modules/manager/helmsman/extract.ts
> +    dep.registryUrls = [ociRegistryUrl];
you can simply pass the full image name to packageName without the OCI prefix. makes code simpler

2023-09-04 15:03 UTC, viceice commented on lib/modules/manager/helmsman/extract.ts
> +    dep.registryUrls = [ociRegistryUrl];
```suggestion
```
not needed for docker datasource as it's embedded

2023-09-04 15:03 UTC, viceice commented on lib/modules/manager/helmsman/extract.ts
> +    dep.packageName = ociRegexResult.input.replace('oci://', '');
```suggestion
    dep.packageName = anApp.chart.replace('oci://', '');
```
we know it's not null.

2023-09-04 15:03 UTC, viceice commented on lib/modules/manager/helmsman/extract.ts
> +    }
we don't need the regex groups

2023-09-04 15:03 UTC, viceice commented on lib/modules/manager/helmsman/extract.ts
> +  const ociRegexResult = anApp.chart ? ociChartRegex.exec(anApp.chart) : null;
```suggestion
  const isOci = anApp?.chart.startsWith('oci://');
```

2023-09-04 15:03 UTC, viceice commented on lib/modules/manager/helmsman/extract.ts
> +  if (ociRegexResult?.groups) {
```suggestion
  if (isOci) {
```

2023-09-04 15:48 UTC, viceice commented on lib/modules/manager/helmsman/extract.ts
> +  const ociRegexResult = anApp.chart ? ociChartRegex.exec(anApp.chart) : null;
just the starts with

2023-09-05 11:08 UTC, viceice approved these changes, later dismissed

2023-09-05 11:19 UTC, domolitom commented on lib/modules/manager/helmsman/extract.ts
> +    dep.packageName = anApp.chart?.replace('oci://', '');
The compiler requires anApp.chart to be optional. That was the reason why it failed.

2023-09-05 12:05 UTC, viceice commented on lib/modules/manager/helmsman/extract.ts
> +    dep.packageName = anApp.chart?.replace('oci://', '');
```suggestion
    dep.packageName = anApp.chart!.replace('oci://', '');
```
we know it's there here

2023-09-05 13:10 UTC, viceice submitted a review, later dismissed

2023-09-05 20:16 UTC, viceice commented
still coverage issues

2023-09-07 18:26 UTC, viceice commented on lib/modules/manager/helmsman/__fixtures__/missingApps.yaml
> +namespaces:
can't we simply use an empty string as test case and inline? so we don't need this fixture?

2023-09-07 18:26 UTC, viceice commented on lib/modules/manager/helmsman/__fixtures__/validHelmsfile.yaml
> +    version: 6.4.0
I don't think we need these cases for coverage. please revert.

2023-09-08 22:12 UTC, viceice approved these changes

2023-09-08 22:21 UTC, merged

2023-09-08 22:32 UTC, renovate-release commented
:tada: This PR is included in version 36.89.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/36.89.0)
- `36.89.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: