Allows azure-got-wrapper to retry requests following connection failures
renovatebot/renovate pull request #24348
Opened 2023-09-11 09:49 UTC by ccopsey

## Changes

Allows `azure-got-wrapper` to retry requests in the event of a connection failure.  A maximum of 2 retries is defined, giving a maximum of 3 requests in total.

## Context

- #24315 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

I run renovate via docker in production.  For the last 4 days I have run a manually updated docker image with the above change applied.  It is impossible to say that the this change works as it is a very flakey failure mode, but I can say that I haven't seen any errors and that this change hasn't caused new issues within renovate.

2023-09-11 10:32 UTC, rarkins approved these changes, later dismissed

2023-09-11 15:25 UTC, viceice requested changes

2023-09-11 15:25 UTC, viceice commented on lib/modules/platform/azure/azure-got-wrapper.ts
> +  let options: IRequestOptions = <IRequestOptions>{};
```suggestion
  let options: IRequestOptions = {};
```

2023-09-11 15:25 UTC, viceice commented on lib/modules/platform/azure/azure-got-wrapper.ts
> +function getRequestOptions() : IRequestOptions {
please inline this function, no benefits

2023-09-11 19:36 UTC, viceice approved these changes

2023-09-12 01:19 UTC, merged

2023-09-12 01:29 UTC, renovate-release commented
:tada: This PR is included in version 36.93.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/36.93.0)
- `36.93.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-22 07:47 UTC, ccopsey commented
For posterity:10 days since this was merged and I haven't suffered any ECONNRESET failures since.