Add PHP linters to preset
renovatebot/renovate pull request #25072
Opened 2023-10-06 07:27 UTC by Jean85

## Changes

This maps the 3 most used linters in the PHP ecosystem, so that presets like `:automergeLinters` work for them too.

## Context

Related discussion: https://github.com/renovatebot/renovate/discussions/24978

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-10-06 16:44 UTC, HonkingGoose requested changes

2023-10-07 21:26 UTC, Jean85 commented on lib/config/presets/internal/packages.ts
> +  }
Thanks for the fix!

2023-10-08 03:04 UTC, rarkins approved these changes

2023-10-08 03:05 UTC, rarkins approved these changes

2023-10-08 03:12 UTC, merged

2023-10-08 03:21 UTC, renovate-release commented
:tada: This PR is included in version 37.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.8.0)
- `37.8.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: