fix(azure): exclude disabled repositories when discovering
renovatebot/renovate pull request #25104
Opened 2023-10-09 15:30 UTC by wterpstra

## Changes

Excludes any disabled repositories found in Azure DevOps

## Context

Based on discussion #25100

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-10-09 15:46 UTC, rarkins requested changes

2023-10-09 15:46 UTC, rarkins commented on lib/modules/platform/azure/index.ts
> +    .filter((repo) => repo.isDisabled === false)
```suggestion
    .filter((repo) => repo.isDisabled !== true)
```

This is more defensive

2023-10-09 16:22 UTC, rarkins approved these changes

2023-10-09 16:44 UTC, viceice approved these changes

2023-11-02 13:02 UTC, Squixx commented
@JamieMagee  care to review?

2023-11-02 13:13 UTC, rarkins approved these changes

2023-11-11 08:40 UTC, merged

2023-11-11 08:51 UTC, renovate-release commented
:tada: This PR is included in version 37.56.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.56.3)
- `37.56.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-11 08:54 UTC, wterpstra commented
Thanks for merging!