feat(manager/pep621): support hatch environments
renovatebot/renovate pull request #25211
Opened 2023-10-15 06:26 UTC by jonathanberthias

## Changes

This PR extends the PEP621 manager to add support for updating dependencies specified in [`hatch` environments](https://hatch.pypa.io/latest/config/environment/overview/#dependencies).

This work builds on top of #22082 by adding a new processor. Note that `hatch` does not have lock files.

## Context

Closes #24956.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-10-15 06:58 UTC, secustor reviewed
LGTM outside of the lint errors

2023-10-15 07:40 UTC, secustor requested changes
Run `pnpm test` to do a full acceptance test

2023-10-15 07:40 UTC, secustor commented on lib/modules/manager/pep621/processors/hatch.ts
> +    return await null;
```suggestion
    return Promise.resolve(null);
```

2023-10-15 07:47 UTC, jonathanberthias commented
> Run `pnpm test` to do a full acceptance test

For some reason it gets stuck forever at the `eslint` step 🤷

2023-10-16 06:52 UTC, viceice commented on lib/modules/manager/pep621/extract.spec.ts
> +const hatchPyProject = Fixtures.get('pyproject_with_hatch.toml');
move to test, it's only used once

2023-10-16 06:52 UTC, viceice commented on lib/modules/manager/pep621/processors/hatch.ts
> +  return `tool.hatch.envs.${envName}`;
inline this

2023-10-16 06:52 UTC, viceice commented on lib/modules/manager/pep621/processors/hatch.ts
> +    updateArtifact: UpdateArtifact<Record<string, unknown>>,
```suggestion
    updateArtifact: UpdateArtifact,
```
it's the default, so no need to explicit define

2023-10-16 13:46 UTC, secustor approved these changes

2023-10-16 15:41 UTC, viceice approved these changes

2023-10-16 15:51 UTC, merged

2023-10-16 16:01 UTC, renovate-release commented
:tada: This PR is included in version 37.23.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.23.0)
- `37.23.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: