feat(jenkins-plugins): Add support for custom registries
renovatebot/renovate pull request #25358
Opened 2023-10-24 05:00 UTC by Nicolas-M

## Changes

* Update the `jenkins-plugins` datasource to use custom registries
* Add README describing how a `jenkins-plugins` datasource works

## Context

* Provide more flexibility for pulling updates for Jenkins plugins, especially in cases where the update site is mirrored elsewhere. 

## Documentation (please check one with an [x])

- [X] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [X] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-10-24 05:31 UTC, rarkins submitted a review, later dismissed

2023-10-24 11:09 UTC, HonkingGoose requested changes

2023-10-24 11:09 UTC, HonkingGoose commented on lib/modules/datasource/jenkins-plugins/readme.md
> +Custom registries defined via `registryUrl` are expected to follow the [update site layout](https://github.com/jenkins-infra/update-center2/blob/master/site/LAYOUT.md).
```suggestion
When you define a custom registry with the `registryUrl` config option, you must follow [Jenkins' update site layout](https://github.com/jenkins-infra/update-center2/blob/master/site/LAYOUT.md).
```

We should use the word `must` to indicate things that you must do, or Renovate must have to work.

Also, we should say _who_ does _what_. I think in this example the user would set a custom registry, and then must follow some rules from Jenkin's for Renovate to work.

I've also updated the link name so it's clear where you'll end up.

2023-10-24 11:09 UTC, HonkingGoose commented on lib/modules/datasource/jenkins-plugins/readme.md
> +Renovate expects `update-center.actual.json` and `plugin-versions.json` to be available under the `current` path (e.g., `https://custom.registry.renovatebot.com/current`).
```suggestion
The `update-center.actual.json` and `plugin-versions.json` files must be in the `current` path, so Renovate can find them.
For example, the files could be put in the `https://custom.registry.renovatebot.com/current` directory.
```

2023-10-24 11:09 UTC, HonkingGoose commented on lib/modules/manager/jenkins/readme.md
> +Versions from the main [Jenkins update center](https://updates.jenkins.io/) are used by default.
```suggestion
By default, Renovate gets the versions from the main [Jenkins update center](https://updates.jenkins.io/).
```

2023-10-24 12:12 UTC, viceice reviewed
this isn't enough, you need to override custom registry support flag from datasource base class

2023-10-24 14:49 UTC, viceice approved these changes

2023-10-25 08:04 UTC, HonkingGoose approved these changes

2023-10-25 09:11 UTC, merged

2023-10-25 09:23 UTC, renovate-release commented
:tada: This PR is included in version 37.33.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.33.0)
- `37.33.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: