chore: expand label-actions about one topic and no mentions
renovatebot/renovate pull request #25416
Opened 2023-10-25 13:21 UTC by rarkins

## Changes

Adds two new label actions

## Context

These are frequent problems we should automate

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-10-25 14:38 UTC, viceice submitted a review, later dismissed

2023-10-25 18:22 UTC, HonkingGoose requested changes

2023-10-25 18:22 UTC, HonkingGoose commented on .github/label-actions.yml
> +    This is to benefit future users who may search and find this discussion and not be confused because there's multiple questions and answers within. One question and answer per Discussion works bes
```suggestion
    This prevents future users from finding this discussion and getting confused by multiple questions and answers. One question and answer per Discussion works best.
```

2023-10-25 18:22 UTC, HonkingGoose commented on .github/label-actions.yml
> +    Please do not unnecessarily `@` maintainers like `@rarkins` or `@viceice`. Doing so causes annoying notifications and make maintaining a repo of this size difficult.
```suggestion
    Please do not unnecessarily `@` mention maintainers like `@rarkins` or `@viceice`. Doing so causes annoying notifications and makes it harder to maintain this repository.
```

2023-10-25 18:22 UTC, HonkingGoose commented on .github/label-actions.yml
> +    For example, never `@` mention a maintainer when you are creating a discussion if your desire is to get attention. This is inconsiderate behavior, just like shouting out your coffee order in a St
```suggestion
    For example, never `@` mention a maintainer when you are creating a discussion if your desire is to get attention. This is rude behavior, just like shouting out your coffee order in a Starbucks before it's your turn.
```

`Inconsiderate` is a difficult word, I think `rude` or `bad` is easier to understand.

2023-10-25 18:22 UTC, HonkingGoose commented on .github/label-actions.yml
> +    If there's an existing issue or discussion which you were hoping for a follow-up to but multiple days or weeks have elapsed, it's ok for you to comment, but please still do not `@` people. The ma
```suggestion
    It's OK to comment in an issue or discussion after multiple days or weeks. But please, still don't `@` mention people. The maintainers try to answer most discussions, but they can't answer all discussions. If you're still not getting an answer, take a look at the information you've given us and see if you can improve it.
```

The current text is hard to understand, how about this?

2023-10-25 18:24 UTC, HonkingGoose commented on .github/label-actions.yml
>      Thanks, the Renovate team
The two new comments should have the `Thanks, the Renovate team` ending as well. 😉

2023-10-26 08:11 UTC, merged

2023-10-26 12:03 UTC, renovate-release commented
:tada: This PR is included in version 37.33.4 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.33.4)
- `37.33.4`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: