Update contributing.md
renovatebot/renovate pull request #25480
Opened 2023-10-28 08:29 UTC by azro352

## Changes

Add some helper commands for local testing, to help contributers

## Context

#25459

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-10-28 10:55 UTC, HonkingGoose requested changes

2023-10-28 10:55 UTC, HonkingGoose commented on .github/contributing.md
> +To help you execute your tests, here are some helper commands:
```suggestion
Use these commands to help run your tests:
```

2023-10-28 10:55 UTC, HonkingGoose commented on .github/contributing.md
> +- to execute a single test file
```suggestion
- To run a single test file
```

2023-10-28 10:55 UTC, HonkingGoose commented on .github/contributing.md
> +- to execute a single test batch, the `-t` value should be part of the `describe` value of the test batch
```suggestion
- To run a single test batch, the `-t` value must be part of the `describe` value of the test batch
```

2023-10-28 10:55 UTC, HonkingGoose commented on .github/contributing.md
> +- to execute a single test, the `-t` value should be part of the `it` value of the test batch
```suggestion
- To run a single test, the `-t` value must be part of the `it` value of the test batch
```

2023-10-28 13:44 UTC, rarkins requested changes
Simplified command

2023-10-28 13:44 UTC, rarkins commented on .github/contributing.md
> +  pnpm run jest ./lib/modules/platform/gitlab/index.spec.ts
```suggestion
  pnpm jest platform/gitlab/index
```

2023-10-28 13:44 UTC, rarkins commented on .github/contributing.md
> +  pnpm run jest ./lib/modules/platform/gitlab/index.spec.ts -t "getJsonFile"
```suggestion
  pnpm run jest platform/gitlab/index -t "getJsonFile"
```

2023-10-28 13:44 UTC, rarkins commented on .github/contributing.md
> +  pnpm run jest ./lib/modules/platform/gitlab/index.spec.ts -t "returns file content from given repo"
```suggestion
  pnpm jest platform/gitlab/index -t "returns file content from given repo"
```

2023-10-28 13:51 UTC, rarkins commented on .github/contributing.md
> +- To run a single test file
```suggestion
- To run a single test folder
  ```bash
  pnpm jest platform/gitlab
  ```
- To run a single test file
```

2023-10-28 13:52 UTC, rarkins commented on .github/contributing.md
> +  ```
```suggestion
- To run a single test folder
  ```bash
  pnpm jest platform/gitlab
  ```
- to run against a single test file
  ```bash
  pnpm jest platform/gitlab/index
  ```
```

2023-10-28 14:08 UTC, azro352 commented on .github/contributing.md
> +  pnpm run jest platform/gitlab/index -t "getJsonFile"
```suggestion
  pnpm jest platform/gitlab/index -t "getJsonFile"
```

2023-10-28 15:11 UTC, rarkins approved these changes, later dismissed

2023-10-29 04:59 UTC, rarkins approved these changes

2023-10-29 05:10 UTC, merged

2023-10-29 06:54 UTC, renovate-release commented
:tada: This PR is included in version 37.35.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.35.1)
- `37.35.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: