feat: Added AWS SDK Monorepo preset
renovatebot/renovate pull request #25508
Opened 2023-10-31 00:02 UTC by Isawan

## Changes

Adds support for AWS SDK monorepo grouping for rust projects

## Context

AWS has multiple SDKs which are frequently updated together, this allows the AWS SDK updates to be grouped together. This is equivalent to the current functionality implemented for the .NET and javascript SDK.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

Note: I'm [upstreaming a similar config](https://github.com/Isawan/terrashine/blob/main/renovate.json5) I currently use on a project of mine. [Example PR](https://github.com/Isawan/terrashine/pull/86)

2023-11-01 11:07 UTC, HonkingGoose requested changes

2023-11-01 21:19 UTC, Isawan commented on lib/config/presets/internal/monorepo.ts
> +  'aws-sdk-rust': [
Fixed.

2023-11-01 21:41 UTC, HonkingGoose commented
@Isawan I see you're making this change on your fork's `main` branch. The next time, you should create a _new_ branch on your fork [^1], and put your work in there.

_After_ your PR is reviewed and merged, you can fix your fork's `main` branch by using the _Sync fork_ button [^2] in the GitHub UI.

[^1]: [GitHub Docs, Creating a branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository)

[^2]: [GitHub Docs, syncing a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)

2023-11-02 00:40 UTC, Isawan commented
Are we ok to continue with this PR? I'll reset my main branch once this is merged. Alternatively, I can re-open the PR from a separate branch.

2023-11-02 12:45 UTC, rarkins approved these changes

2023-11-02 12:58 UTC, merged

2023-11-02 13:10 UTC, renovate-release commented
:tada: This PR is included in version 37.43.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.43.0)
- `37.43.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: