feat(datasource/custom): allow to fetch from YAML data endpoint
renovatebot/renovate pull request #25695
Opened 2023-11-10 16:58 UTC by nSimonFR

## Changes

### feat(datasource/custom): allow to fetch from YAML data endpoint 

## Context

Closes #25634
 
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-11-10 17:01 UTC, maximeancellin approved these changes

2023-11-10 17:14 UTC, maximeancellin approved these changes
LGTM ! ✅

2023-11-10 17:20 UTC, maximeancellin approved these changes

2023-11-10 17:20 UTC, maximeancellin approved these changes

2023-11-10 18:03 UTC, viceice commented on lib/config/types.ts
> +
please avoid such changes

2023-11-10 18:03 UTC, viceice commented on lib/modules/datasource/custom/formats/yaml.ts
> +  return yaml.load(response.body.replace(newlineRegex, '\n')) as ReleaseResult;
why replace the newline? the yaml parser should handle windows newlines.

2023-11-10 18:09 UTC, nSimonFR commented on lib/modules/datasource/custom/index.spec.ts
> +import expect from 'expect';
Self-reviewing: unwanted ? My vscode auto imported them

2023-11-10 19:00 UTC, secustor requested changes
Thanks for contributing!

2023-11-10 19:04 UTC, secustor commented
Also needs [prettier-fix](https://github.com/renovatebot/renovate/blob/main/package.json#L45)

2023-11-13 10:45 UTC, secustor requested changes

2023-11-13 10:45 UTC, secustor commented on lib/modules/datasource/custom/index.spec.ts
> +      const yaml = `releases:\n  - version: 1.0.0\n  - version: 2.0.0\n  - version: 3.0.0`;
Use a codeblock to make this more readable https://github.com/renovatebot/renovate/blob/2ce4fc5b06055a08108fbb5c5437f522d8371097/lib/util/exec/hermit.spec.ts#L65

2023-11-13 10:45 UTC, secustor commented on lib/modules/datasource/custom/readme.md
> +If `yaml` is used, response is processed by the `ts-yaml` library and then is converted into JSON.
```suggestion
If `yaml` is used, response is parsed and converted into JSON for further processing.
```

2023-11-13 10:58 UTC, secustor approved these changes

2023-11-13 11:02 UTC, viceice approved these changes

2023-11-13 11:08 UTC, merged

2023-11-13 11:17 UTC, renovate-release commented
:tada: This PR is included in version 37.57.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.57.0)
- `37.57.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-20 15:51 UTC, astellingwerf commented on lib/modules/datasource/custom/readme.md
> +### Yaml
This should be at h4 instead of h3 to be on the same as JSON and plain