feat(presets): Add release-it group
renovatebot/renovate pull request #25785
Opened 2023-11-14 20:06 UTC by k2snowman69

## Changes

Adding a group for release-it packages

## Context

Currently release-it PRs are created separately so when there is a major breaking change, neither PR is able to merge cleanly. This requires manual intervention each time.

As of creating this PR, this repo has an example of the issue:
https://github.com/snowcoders/sortier/pulls?q=is%3Apr+is%3Aopen+release-it

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-11-14 21:23 UTC, viceice requested changes
group via source url but inside monorepo.ts

2023-11-14 21:29 UTC, k2snowman69 commented
> group via source url but inside monorepo.ts

I'm not sure I understand, I thought `monorepo.ts` is for repos that hold multiple packages in a single repo. Release-it doesn't use monorepos, each package has it's own repo.

2023-11-15 09:30 UTC, rarkins commented
Why should these be grouped together? Is it:
1. Because they break unless they are upgraded at the same time, or
2. It makes sense because they're related

If it's (2), that doesn't mean it should be in config:recommended

2023-11-16 05:45 UTC, k2snowman69 commented
> Why should these be grouped together? Is it:
> 
>     1. Because they break unless they are upgraded at the same time, or
> 
>     2. It makes sense because they're related
> 
> 
> If it's (2), that doesn't mean it should be in config:recommended

Typically they break individually but this is due to the choices of the developer I believe. There is [a peer-dependency](https://github.com/release-it/keep-a-changelog/blob/main/package.json#L40) which since it's pinned to the major version causes npm to fail the peer dependency check for any packages published under release-it.

So does it break unless they are upgraded together - yes. I saw this happen with the v4 and the v5 major releases

This said, based on your phrasing I don't think this is what you meant... which in that case feel free to close this PR without merging

2023-11-16 11:03 UTC, rarkins commented
I don't mind adding it to the recommended groupings and we see if later anyone thinks it's better without

2023-11-17 06:55 UTC, viceice commented
> > group via source url but inside monorepo.ts
> 
> I'm not sure I understand, I thought `monorepo.ts` is for repos that hold multiple packages in a single repo. Release-it doesn't use monorepos, each package has it's own repo.

please add the url here

https://github.com/renovatebot/renovate/blob/8ea53c8465a8be183f01ecd813180223ed8878d4/lib/config/presets/internal/monorepo.ts#L486

2024-05-07 05:12 UTC, closed without merging