docs: create Renovate and changelogs page
renovatebot/renovate pull request #25982
Opened 2023-11-27 11:13 UTC by HonkingGoose

## Changes

- Create "Renovate and changelogs page" that should explain:
  - How Renovate fetches changelogs
  - How maintainers can ensure Renovate sees their changelogs, for the commonly used package ecosystems
  - Troubleshooting missing changelogs
  - Relevant config options to configure changelog fetching behavior

## Context

Closes #25874.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-11-27 11:16 UTC, HonkingGoose commented on docs/usage/key-concepts/changelogs.md
> +Explain how to get Ruby (gem) changelogs here.
```suggestion
### Rust package maintainers

Explain how to get Rust changelogs here.

### Nuget package maintainers

Explain how to get Nuget changelogs here.

### Go package maintainers

Explain how to get Go changelogs here.

### Ruby package maintainers

Explain how to get Ruby (gem) changelogs here.
```

2023-11-27 11:27 UTC, HonkingGoose commented on docs/usage/key-concepts/changelogs.md
> +Renovate can apparently read `changelog.json` files, I don't know how that works.
Context:

- https://github.com/renovatebot/renovate/discussions/25828

2023-12-15 10:27 UTC, rarkins reviewed
@HonkingGoose I have made my edits directly to the PR. Please review and correct anything you see, and let's get it published!

2023-12-15 12:45 UTC, HonkingGoose reviewed
We use `it` and `this` in the lists, but it's hard for me to understand what those words refer to in some cases.

Can you suggest changes so it's clear what we really mean?

2023-12-15 12:45 UTC, HonkingGoose commented on docs/usage/key-concepts/changelogs.md
> +   - If the registry provides source URLs but Renovate does not support it yet, then raise a feature request with examples, or better yet a Pull Request to implement it yourself
What does `Renovate does not support it yet,` mean here? Same question with `a Pull Request to implement it yourself`.

2023-12-15 12:45 UTC, HonkingGoose commented on docs/usage/key-concepts/changelogs.md
> +1. The package does not provide this information to the registry.
What does `this information` mean here?

2023-12-15 12:45 UTC, HonkingGoose commented on docs/usage/key-concepts/changelogs.md
> +   - In this case an enhancement to Renovate might be needed to better detect the releases/formats, assuming it's got a reasonable convention to follow
Same question about `assuming it's got a reasonable convention to follow`. I guess you really mean something like this?

> assuming the upstream package/ecosystem has a reasonable convention that Renovate can follow

2023-12-15 13:48 UTC, rarkins requested changes

2023-12-15 13:48 UTC, rarkins commented on docs/usage/key-concepts/changelogs.md
> +   - If the registry provides source URLs but Renovate does not support it yet, then raise a feature request with examples, or better yet a Pull Request to implement it yourself
```suggestion
   - If the registry provides source URLs in its response but Renovate does not understand the required fields, then raise a feature request with examples, or better yet a Pull Request to implement support for the source URL parsing/mapping yourself
```

2023-12-15 13:48 UTC, rarkins commented on docs/usage/key-concepts/changelogs.md
> +1. The package does not provide this information to the registry.
```suggestion
1. The package was published without source URL information being included.
```

2023-12-15 13:48 UTC, rarkins commented on docs/usage/key-concepts/changelogs.md
> +   - In this case an enhancement to Renovate might be needed to better detect the releases/formats, assuming it's got a reasonable convention to follow
```suggestion
   - In this case an enhancement to Renovate might be needed to better detect the releases/formats, assuming the package/repository has a reasonable convention to follow
```

2023-12-19 08:51 UTC, rarkins approved these changes

2023-12-19 09:02 UTC, merged

2023-12-19 09:12 UTC, renovate-release commented
:tada: This PR is included in version 37.103.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.103.0)
- `37.103.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: