Deplyoment jobs support
renovatebot/renovate pull request #26048
Opened 2023-11-29 19:22 UTC by jabbera

## Changes

Azure Devops has the concept of deployment jobs that are not covered by rennovate. This PR adds support for these jobs. I'm open to another approach for testing these changes as the # of fixture has exploded.

Microsoft Docs on Deployment Jobs: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#runonce-deployment-strategy 

## Context

Explained above

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ X] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [X] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-11-29 19:41 UTC, viceice reviewed
please convert types to zod schema validation

2023-11-29 19:41 UTC, viceice commented on lib/modules/manager/azure-pipelines/__fixtures__/azure-pipelines-canary.yaml
> +jobs:
please inline those fixtures

2023-11-30 01:32 UTC, jabbera commented
> please convert types to zod schema validation

This was a rabbit hole. I raised some comments where I made changes and why they were made.

2023-11-30 21:12 UTC, viceice commented on lib/modules/manager/azure-pipelines/extract.ts
> +): PackageDependency<Record<string, any>>[] {
```suggestion
function extractDeploy(
  deploy: Deploy | undefined,
): PackageDependency[] {
```

2023-12-05 20:25 UTC, jabbera commented
Hi. This PR now needs to be rebased. @viceice should I wait until you comment on my above question or rebase now?

2023-12-08 06:10 UTC, rarkins requested changes, later dismissed
Needs de-conflicting

2023-12-11 14:20 UTC, viceice approved these changes

2023-12-11 15:33 UTC, merged

2023-12-11 15:42 UTC, renovate-release commented
:tada: This PR is included in version 37.91.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.91.0)
- `37.91.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-12-11 22:59 UTC, jabbera commented
Thanks all!