fix(manager/nuget): use environment variables required by NuGet on Windows
renovatebot/renovate pull request #26056
Opened 2023-11-30 11:51 UTC by reduckted

## Changes

Specific environment variables that are used by NuGet on Windows are now automatically included when executing `dotnet restore`.

## Context

When running Renovate on Windows, updating NuGet lock files fails with an error because specific environment variables that NuGet uses on Windows are not passed through by Renovate. This PR passes those environment variables through.

See #25583 for the discussion.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2023-11-30 15:42 UTC, viceice requested changes

2023-11-30 15:42 UTC, viceice commented on lib/modules/manager/nuget/artifacts.ts
> +  );
add them to this list instead
https://github.com/renovatebot/renovate/blob/638deae3d0da4b6a978775c3607f2d06bef3d77e/lib/util/exec/env.ts#L3

2023-12-01 10:02 UTC, rarkins approved these changes

2023-12-01 10:05 UTC, viceice approved these changes

2023-12-01 11:17 UTC, merged

2023-12-01 11:26 UTC, renovate-release commented
:tada: This PR is included in version 37.79.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.79.1)
- `37.79.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: