feat: add gitlab openssf scorecards
renovatebot/renovate pull request #26167
Opened 2023-12-06 12:44 UTC by adam-moss

## Changes

Adds OpenSSF scorecard reporting for GitLab.

## Context

Adding following testing as part of https://github.com/renovatebot/renovate/discussions/25125#discussioncomment-7769281

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [X] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-12-06 12:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=26167) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=26167) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=26167) it.</sub>

2023-12-06 13:07 UTC, secustor requested changes

2023-12-06 13:07 UTC, secustor commented on lib/config/presets/internal/security.ts
> +            '[![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/{{platform}}.com/{{sourceRepo}}/badge)](https://securityscorecards.dev/viewer/?uri={{platform}}.com/{{sourceRepo}})',
`platform` returns the platform against which Renovate is run and not where the source of the dependency is located

2023-12-06 17:57 UTC, adam-moss commented
<img width="1304" alt="Screenshot 2023-12-06 at 17 47 59" src="https://github.com/renovatebot/renovate/assets/2951486/618a32e7-ef2b-4a53-87ae-75c79b689f37">


Tested against a private repository.  Seems the OpenSSF api has a challenge with /group/subgroup/project urls.  I wonder if there is something nicer we could do rather than having a broken image link?

Example:
https://gitlab.com/gitlab-org/ruby/gems/gitlab-triage
https://api.securityscorecards.dev/projects/gitlab.com/gitlab-org/ruby/gems/gitlab-triage/badge

2023-12-06 20:19 UTC, adam-moss commented
Indeed, I have raised https://github.com/ossf/scorecard-webapp/issues/511

2024-03-18 21:40 UTC, rarkins commented
What's the next step here?

2024-03-19 09:17 UTC, secustor commented
It's not actionable by us right now and blocked by OSSF scorecards API server implementation

2024-03-19 09:46 UTC, rarkins commented
OK, please feel free to reopen this as soon as it's actionable. We have 60+ open PRs right now so would like to close anything non-actionable and stalled.

2024-03-19 09:46 UTC, closed without merging