Support digest in custom datasource
renovatebot/renovate pull request #26299
Opened 2023-12-14 16:24 UTC by fstehle

## Changes

To support digests a datasource has to implement the `getDigest` method. 
This PR implements the method returning a null promise.
The value itself can be provided in the getReleases method.

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-12-15 08:16 UTC, secustor requested changes
Not fond of this solution, tough a better fix would need bigger changes.

2023-12-15 08:21 UTC, viceice commented
why do we need this? that function shouldn't be called when the digest is already returned in releases.

2023-12-15 08:21 UTC, fstehle commented
> Not fond of this solution, tough a better fix would need bigger changes.

Yes, absolutely. Would you suggest to modify `supportsDigests` in https://github.com/renovatebot/renovate/blob/6884d83a0573ebd40210cf0717c1814afd68a649/lib/modules/datasource/index.ts#L392 instead?

2023-12-15 08:23 UTC, fstehle commented
> why do we need this? that function shouldn't be called when the digest is already returned in releases.

That is not what I observed, `supportsDigests` returns false and no digest update is made.

See the following lines for that:
* https://github.com/renovatebot/renovate/blob/6884d83a0573ebd40210cf0717c1814afd68a649/lib/modules/datasource/index.ts#L392)
* https://github.com/renovatebot/renovate/blob/6884d83a0573ebd40210cf0717c1814afd68a649/lib/workers/repository/process/lookup/index.ts#L417-L545

2023-12-17 23:24 UTC, secustor requested changes

2023-12-17 23:24 UTC, secustor commented on lib/modules/datasource/custom/index.ts
> +    });
```suggestion
    // istanbul ignore next
    return Promise.resolve(null)
```

2023-12-17 23:24 UTC, secustor commented on lib/workers/repository/process/lookup/__snapshots__/index.spec.ts.snap
The snapshot is with the latest change obsolete. 
You can remove it with `pnpm run jest -u`

2023-12-17 23:32 UTC, secustor commented
> > Not fond of this solution, tough a better fix would need bigger changes.
> 
> Yes, absolutely. Would you suggest to modify `supportsDigests` in
> 
> https://github.com/renovatebot/renovate/blob/6884d83a0573ebd40210cf0717c1814afd68a649/lib/modules/datasource/index.ts#L392
> instead?

The logic in `lookup/index.ts` would need to modified, which needs extensive testing on real repos.

2024-03-18 21:08 UTC, rarkins requested changes
Needs deconflicting and continuing

2024-04-29 21:21 UTC, acortelyou commented
This PR would resolve request for help discussion #28343.

I hope we can find a way to get this code moving again.

It looks like the suggestions from the review were just nits: if @fstehle doesn't have bandwidth to revisit, perhaps the maintainers can update the PR with their fixes or an interested party (myself) could fork the PR.

2024-04-30 04:06 UTC, rarkins commented
The latter

2024-04-30 09:51 UTC, fstehle commented
Currently quite busy, would be great if you could create a fork PR

2024-04-30 10:35 UTC, rarkins reviewed
Fixed conflicts, but now I defer to @secustor

2024-04-30 13:30 UTC, viceice commented on lib/modules/datasource/custom/index.ts
> +    // istanbul ignore next
should be removed, it seems there's a test for it

2024-04-30 21:12 UTC, secustor reviewed
Needs test fix and removal of ignore statement, else LGTM

2024-04-30 23:18 UTC, acortelyou commented
See linked PR for commits to address outstanding items.

Either cherry-pick the commits on to here (i don't have permissions) or publish that one and merge from there.

Thanks!

2024-04-30 23:22 UTC, acortelyou approved these changes

2024-04-30 23:22 UTC, acortelyou commented on lib/modules/datasource/custom/index.ts
> +    // istanbul ignore next
```suggestion
```

2024-05-01 07:45 UTC, ivankatliarchuk commented
Does anyone know whether or not these changes will support Gitlab MD5 https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.25/index.html?

2024-05-01 08:02 UTC, secustor commented
> Does anyone know whether or not these changes will support Gitlab MD5 https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.25/index.html?

No.

Closing as this has been implemented in the linked PR.

2024-05-01 08:02 UTC, closed without merging