(test dont merge)feat: add configuration to use redis prefixes
renovatebot/renovate pull request #26398
Opened 2023-12-21 14:28 UTC by monwolf

don't merge it's just a test

2023-12-21 14:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=26398) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=26398) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=26398) it.</sub>

2023-12-22 10:27 UTC, rarkins requested changes

2023-12-22 10:27 UTC, rarkins commented on docs/usage/self-hosted-configuration.md
> +If this value is set then Renovate will add this string to the name of all Redis cache entries used in Renovate. It's only used if `redisUrl` is configured.
```suggestion
If this value is set then Renovate will prepend this string to the name of all Redis cache entries used in Renovate.
It's only used if `redisUrl` is configured.
```

2023-12-22 10:27 UTC, rarkins commented on lib/config/options/index.ts
> +    description: 'If set, this will be the prefix used in all cache entries.',
```suggestion
    description: 'Key prefix for redis cache entries.',
```

2023-12-22 10:27 UTC, rarkins commented on lib/util/cache/package/redis.ts
> +  return `${rprefix}:${namespace}-${key}`;
```suggestion
  return `${rprefix}${namespace}-${key}`;
```

If you need a colon then add it as part of redisPrefix

2023-12-22 10:27 UTC, rarkins commented on lib/config/options/index.ts
> +    default: '',
```suggestion
```

2023-12-22 10:27 UTC, rarkins commented on lib/util/cache/package/redis.ts
> +  rprefix = prefix;
```suggestion
  rprefix = prefix ?? '';
```

2023-12-22 11:27 UTC, rarkins approved these changes, later dismissed

2024-01-01 20:45 UTC, monwolf commented
@rarkins is there anything extra I have to change in order to be merged?

2024-01-02 11:42 UTC, zharinov approved these changes

2024-01-02 11:42 UTC, zharinov commented on lib/util/cache/package/redis.ts
> +let rprefix: string | undefined;
Just `prefix` is also ok

2024-01-02 22:10 UTC, rarkins approved these changes

2024-01-02 22:19 UTC, merged

2024-01-02 22:29 UTC, renovate-release commented
:tada: This PR is included in version 37.117.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.117.0)
- `37.117.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: