feat(helm-values): Add support for bumpVersion
renovatebot/renovate pull request #26441
Opened 2023-12-27 22:21 UTC by kvanzuijlen

## Changes
Adds support for `bumpVersion` to the helm-values manager.

## Context
Closes #4728

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2023-12-27 23:24 UTC, kvanzuijlen reviewed
@rarkins I could reuse most parts from #8240. I was able to reproduce the behavior that caused it to be reverted.

Do you want to include helm-requirements in the same PR or should that (optionally) be added in a separate PR? I don't think it's really necessary, as helmv3 has long been the standard already and as far as I understand, helm-requirements is for Chart dependencies in helmv2 (correct?).

2023-12-27 23:24 UTC, kvanzuijlen commented on lib/workers/repository/update/branch/get-updated.ts
> +            }
This is the biggest difference; I included this part in the if-statement.

2023-12-28 07:16 UTC, viceice commented on lib/modules/manager/helm-values/update.spec.ts
> +      fs.readLocalFile = jest.fn();
wrong, please checkout other tests for how to mock fs

2023-12-28 07:16 UTC, viceice commented on lib/modules/manager/helm-values/update.spec.ts
> +      expect(bumpedFile.newContent).toMatchSnapshot();
no snapshots

2023-12-28 07:16 UTC, viceice commented on lib/modules/manager/helm-values/util.ts
> +    const chart = yaml.load(chartContents, { json: true }) as any;
use our yaml utils and zod schema validation

2023-12-28 08:15 UTC, rarkins commented
Different managers can be done separately

2023-12-28 14:57 UTC, kvanzuijlen commented
Thanks for taking the time to review my PR @viceice. I hope my changes are correct. Let me know if I need to change anything else!

2023-12-28 20:05 UTC, viceice commented on lib/modules/manager/helm-values/util.ts
> +    const chart = parseSingleYaml(chartContents) as ChartDefinition;
please also use zod schema validation

2023-12-28 21:05 UTC, secustor commented on lib/workers/repository/update/branch/get-updated.ts
> +            if (bumpedPackageFiles) {
I agree changes are here are risky and should be on a separate PR.

2024-01-01 21:54 UTC, kvanzuijlen commented on lib/workers/repository/update/branch/get-updated.ts
> +            if (bumpedPackageFiles) {
Somehow I was under the impression that this piece of code was needed to make it all work. Tried running Renovate against a real repository though and found out that it's not needed at all. Going to revert the changes to get-updated.ts (and its tests) and zod parsing shortly.

2024-01-03 19:33 UTC, viceice commented on lib/modules/manager/helm-values/update.spec.ts
> +      jest.resetAllMocks();
I think this should be removed

2024-01-03 19:33 UTC, viceice commented on lib/modules/manager/helm-values/types.ts
> +  })
remove the regex, we don't need to be so strict here. a wrong version will be catched on bump version.

2024-01-03 19:33 UTC, viceice commented on lib/modules/manager/helm-values/types.ts
> +export const ChartDefinition = z
we prefer to have zod schema definitions in a schema.ts file, so please move

2024-01-03 19:48 UTC, viceice commented on lib/workers/repository/update/branch/get-updated.ts
> +async function getFileContent(
these changes should be done before in separate PR

2024-01-03 20:09 UTC, kvanzuijlen commented
Thanks for all your patience @rarkins. I made the requested changes.

2024-01-03 20:28 UTC, viceice commented on lib/modules/manager/helm-values/update.spec.ts
> +      fs.readLocalFile.mockRejectedValueOnce(null);
you just need to reset the read local file mock

2024-01-03 20:28 UTC, viceice commented on lib/workers/repository/update/branch/get-updated.ts
> +              packageFile,
still a change which should be in a separate PR

2024-01-03 20:28 UTC, viceice commented on lib/workers/repository/update/branch/get-updated.ts
> +          packageFile,
too

2024-01-08 16:42 UTC, viceice requested changes
blocked by refactor PR

2024-01-17 08:45 UTC, viceice approved these changes

2024-01-17 08:54 UTC, merged

2024-01-17 09:04 UTC, renovate-release commented
:tada: This PR is included in version 37.138.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.138.0)
- `37.138.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: