helm v3: add --force-update when adding a repo
renovatebot/renovate pull request #26512
Opened 2024-01-05 09:00 UTC by gaelgatelement

## Changes

We add [`--force-update`](https://helm.sh/docs/helm/helm_repo_add/) to overwrite any existing repo with the same name.

## Context

When using renovate to update helm lock files in a monorepo, we encounter the following error when a helm chart is present in multiple Chart.yaml : 

```
The artifact failure details are included below:

Command failed: helm repo add <name> <url>
Error: repository name (<name>) already exists, please specify a different name
```

Using [`--force-update`](https://helm.sh/docs/helm/helm_repo_add/) works around this behaviour by overwriting any existing repo with the same name.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [X] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-01-05 11:00 UTC, viceice reviewed
Please sign the CLA, otherwise LGTM

2024-01-06 08:00 UTC, viceice approved these changes

2024-01-06 08:00 UTC, viceice requested changes
needs cla signing

2024-01-08 07:47 UTC, gaelgatelement commented
I signed the CLA.

2024-01-08 08:09 UTC, viceice approved these changes

2024-01-08 08:17 UTC, merged

2024-01-08 08:26 UTC, renovate-release commented
:tada: This PR is included in version 37.126.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.126.3)
- `37.126.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: