Recommend npx to run validator
renovatebot/renovate pull request #26628
Opened 2024-01-13 11:17 UTC by TWiStErRob

## Changes

Using `npx` has all the same benefits as `--global` (e.g. caching), except it does not pollute the global namespace and installed dependencies.

This also works better on CI, shared environments, and for aliasing, because it's a simple one-liner.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-01-13 13:23 UTC, rarkins approved these changes, later dismissed

2024-01-15 19:56 UTC, HonkingGoose requested changes

2024-01-15 19:56 UTC, HonkingGoose commented on docs/usage/config-validation.md
> +You can pass the `--strict` flag to make it fail if a scanned config needs migration:
```suggestion
You can pass the `--strict` flag to make it fail if a scanned config needs migration:

```

This should fix the `lint-docs` test complaining. :smile:

2024-01-18 09:04 UTC, HonkingGoose requested changes

2024-01-18 09:04 UTC, HonkingGoose commented on docs/usage/config-validation.md
> +```console
```suggestion
```console title="Strict mode leads to validation failure if config needs migration"
```

How about a nice "title" for the codeblock? See: [Material for MkDocs manual, adding a title to a codeblock](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-a-title).

2024-02-18 15:52 UTC, rarkins approved these changes

2024-02-18 16:08 UTC, merged

2024-02-18 16:50 UTC, renovate-release commented
:tada: This PR is included in version 37.197.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.197.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.197.0)
- `37.197.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: