fix(workers/pr)/smart dedpulicate
renovatebot/renovate pull request #26771
Opened 2024-01-21 05:17 UTC by RahulGautamSingh

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-01-21 05:20 UTC, RahulGautamSingh commented
Test Run: https://github.com/RahulGautamSingh-testing/26073/pull/2

2024-01-21 08:43 UTC, viceice reviewed
missing coverage

2024-01-21 08:43 UTC, viceice commented on lib/workers/repository/update/pr/body/updates-table.ts
> +  const tableValues = uniqueUpgrades
```suggestion
  const tableValues = filterDuplicateUpgrades(config.upgrades)
```

2024-01-22 08:22 UTC, viceice reviewed
🤔 this can cause dropping rows with more information. 

so for the reproduction sample, if the regex manager would come first, the compare link would be gone.

@rarkins I think this needs to be feature flagged. I don't want to filter those in my PR.

maybe we need to merge those rows instead of simply dropping.

2024-01-22 09:03 UTC, rarkins commented
What if instead of this, we add logic to _enrich_ rows which are "duplicates" but lacking in metadata? Then they will deduplicate themselves in a later step. Either that or picking the row which has most metadata.

I don't want to feature flag this - it's too trivial to deserve that

2024-01-22 17:28 UTC, viceice requested changes
needs rework

2024-01-26 08:22 UTC, RahulGautamSingh commented
I don't think any other combination of managers will create duplicate deps unless one of them is the regex manager. Therefore, we can just filter regex manager's row in cases of duplicate rows.

2024-01-26 20:24 UTC, viceice reviewed
as discussed this still causes bad usability, eg npm and nodeenv manager

2024-01-30 07:48 UTC, viceice approved these changes

2024-01-30 08:27 UTC, merged

2024-01-30 10:15 UTC, renovate-release commented
:tada: This PR is included in version 37.161.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.161.0)
- `37.161.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: