fix(terraform): Replace All matched values in constraint with new value
renovatebot/renovate pull request #26867
Opened 2024-01-26 10:19 UTC by dali546

## Changes

Terraform constraints can mention the version multiple times in a constraint. This does a `replaceAll` instead of `replace` to replace all occurrences

eg. Terraform hashicorp/aws provider update didn't update the last occurrence of `5.31.0`

```hcl
provider "registry.opentofu.org/hashicorp/aws" {
  version     = "5.31.0"
  constraints = ">= 2.49.0, >= 3.29.0, >= 3.75.0, >= 4.0.0, >= 4.9.0, >= 4.40.0, >= 4.42.0, >= 4.66.1, >= 5.26.0, >= 5.31.0, 5.31.0"
  version     = "5.34.0"
  constraints = ">= 2.49.0, >= 3.29.0, >= 3.75.0, >= 4.0.0, >= 4.9.0, >= 4.40.0, >= 4.42.0, >= 4.66.1, >= 5.26.0, >= 5.34.0, 5.31.0"
```

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-01-26 13:30 UTC, rarkins requested changes
Please add a test

2024-01-26 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=26867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=26867) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dali546<br/>:x: Muhammed Ali<br/><hr/>**Muhammed Ali** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=26867) it.</sub>

2024-01-26 17:43 UTC, secustor reviewed
What is your reasoning that you want to have changed multiple ranges?

Terraform does not use this field and we try to keep the diff to a minimum.

2024-01-26 22:50 UTC, dali546 commented
@secustor The lockfile example I gave is an extract of a lockfile that Terraform generated. The terraform workspace has required providers, but also many modules in use, which also define their own provider constraints.

`terraform init` (or `tofu init`) will generate a lockfile with constraints like this.

2024-01-26 23:09 UTC, dali546 commented
@secustor 

Here is a minimal terraform file to reproduce
```hcl
terraform {
  required_version = "~> 1.6.0"
  required_providers {
    name = {
      source  = "hashicorp/aws"
      version = "5.31.0"
    }
  }
}

module "nlb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "9.4.1"
}
```
This will produce a lockfile with multiple ranges

2024-01-27 09:24 UTC, secustor commented
I'm aware of that tough we can not know what the constraints of the modules are. 

Therefore we only look at the constraint of the `required_provider` block, but as I said this is only cosmetic as Terraform does not use the constraints field.

2024-01-29 08:55 UTC, dali546 commented
@secustor Terraform does indeed look at the `constraints` field when doing `terraform init`. Our CI checks fail because the Terraform dependency updates cannot find a suitable provider version to install

2024-01-29 08:57 UTC, dali546 commented
@secustor How about I fix this then. Instead of matching the first match of the version, (in this case there is `>= 4.31.0` and `4.31.0`

The second `4.31.0` constraint is set by the `required_provider` ... Is it better to split by `,` and replace the string exact match?

2024-01-29 10:34 UTC, secustor commented
Your terraform init error is probably not coming from the lock file but rather because the module you are depending on is requesting this. 

Take look at this discussion for some context: https://github.com/renovatebot/renovate/discussions/24879#discussioncomment-7261513

`@apparentlymart`, a maintainer of Terraform give his insight there too. 

Further please do not ping maintainers, this is considered to be rude.

2024-01-29 12:25 UTC, dali546 commented
https://github.com/dali546/terraform-renovate-bug

Apologies for the mentioning you, Here is a repo reproducing the issue. Take a look at the CI checks to show Simple terraform pipeline failing

2024-01-30 12:48 UTC, secustor commented
Looking at the error message, it rather looks like that Terraform expects now that this string is order in ascending order of the version 🤔 

It also writes out the string it expects:
https://github.com/dali546/terraform-renovate-bug/actions/runs/7695970828/job/20969958070?pr=1#step:4:14

2024-01-30 14:35 UTC, dali546 commented
I have manually updated it locally, and the order of the constraints doesn't matter (it doesn't need to be in ascending order). As long as the constraint it valid. 

https://github.com/dali546/terraform-renovate-bug/pull/4

2024-01-30 21:58 UTC, secustor reviewed
Else lgtm

2024-01-30 21:58 UTC, secustor commented on lib/modules/manager/terraform/lockfile/index.spec.ts
> +    });
Add an additional test where the fixed constraint is in the middle.

2024-01-31 07:24 UTC, secustor commented on lib/modules/manager/terraform/lockfile/index.spec.ts
> +      ).toBe('>= 2.41.0, <= 2.46.0, >= 2');
```suggestion
          '>= 2.41.0, <= 2.41.0, >= 2.0.0',
        ),
      ).toBe('>= 2.41.0, <= 2.46.0, >= 2.0.0');
```
Versions in Terraform lockfiles have to be full semver versions

2024-01-31 09:26 UTC, secustor approved these changes

2024-02-01 20:31 UTC, dali546 commented
@rarkins can you review this PR so it can get merged?

2024-02-01 20:35 UTC, rarkins approved these changes

2024-02-01 20:42 UTC, merged

2024-02-01 20:51 UTC, renovate-release commented
:tada: This PR is included in version 37.165.4 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.165.4)
- `37.165.4`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: