chore: Update artifact actions
renovatebot/renovate pull request #27268
Opened 2024-02-13 16:27 UTC by zharinov

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-02-13 16:28 UTC, zharinov commented
https://github.com/zharinov/renovate/actions/runs/7889557679

2024-02-13 16:29 UTC, viceice requested changes

2024-02-13 16:29 UTC, viceice commented on .github/workflows/build.yml
> +        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
you need to change the parameters here, checkout the breaking changes

2024-02-13 16:29 UTC, viceice commented on .github/workflows/build.yml
> +        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
here too

2024-02-13 16:30 UTC, viceice commented on .github/workflows/build.yml
>            name: coverage
you can no longer have artifacts with same name, but download can use wildcards and merge

2024-02-13 17:22 UTC, viceice commented on .github/workflows/build.yml
> +          overwrite: true
this shouldn't needed

2024-02-13 17:52 UTC, viceice submitted a review, later dismissed

2024-02-13 17:54 UTC, viceice commented
🤔 codecov isn't reporting, there's an error. see action

2024-02-13 18:09 UTC, zharinov commented
> 🤔 codecov isn't reporting, there's an error. see action

- Introduced in #27236

2024-02-13 22:34 UTC, zharinov commented
Okay, let's go with artifact actions only here. Codecov is the separate problem.

2024-02-14 08:36 UTC, viceice approved these changes

2024-02-14 08:44 UTC, merged

2024-02-14 09:49 UTC, renovate-release commented
:tada: This PR is included in version 37.188.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.188.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.188.0)
- `37.188.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: