Add manual changelog URLs for logback and slf4j
renovatebot/renovate pull request #27373
Opened 2024-02-17 03:30 UTC by exoego

## Changes

Added manual changelog URLs for 
- https://www.slf4j.org/
- https://logback.qos.ch/

Both are widely adopted logging library in JVM world.

## Context

Implements a feature discussed in https://github.com/renovatebot/renovate/discussions/22893

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-02-17 05:44 UTC, rarkins requested changes
Must be proper full maven package names

2024-02-17 06:18 UTC, exoego commented
@rarkins Sorry, added full maven package names in https://github.com/renovatebot/renovate/pull/27373/commits/0e7ed5f69759a7a46112ed3302ad4b6725a16458

2024-02-17 11:53 UTC, rarkins approved these changes

2024-02-28 23:08 UTC, exoego commented
Could you merge this?
Logback 1.5.1 was released on Feb 28th.

2024-02-29 05:35 UTC, merged

2024-02-29 06:19 UTC, renovate-release commented
:tada: This PR is included in version 37.220.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.220.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.220.0)
- `37.220.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: