feat(platform/bitbucket): autodiscoverProjects
renovatebot/renovate pull request #27845
Opened 2024-03-11 11:44 UTC by RahulGautamSingh

## Changes
- Add new config option `autodiscoverProjects` for the bitbucket platform which will filter the list of autodiscovered repositories 
- It can be used to both include/exclude projects 

## Context
Closes: https://github.com/renovatebot/renovate/issues/27661

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository (tested locally)

2024-03-11 11:50 UTC, RahulGautamSingh commented
Unfortunately, tokens which provide access to all projects is only avaiable to premium users so I tested using repository access tokens. In the two tests I performed, I used a repo token to fetch the said test-repo and then use `autodiscoverProjects` filter to  once allow the project the repo belonged to and once disallow, I have pasted the logs below for both cases:

Test repo name: rahugautamsingh/ignore/test-repo

**When project: ignore was allowed**
```
DEBUG: Combined config
       "config": {
         "forkProcessing": true,
         "token": "***********",
         "endpoint": "https://api.bitbucket.org/",
         "platform": "bitbucket",
         "autodiscover": true,
         "hostRules": [{"matchHost": "https://api.github.com", "token": "***********"}]
       }
       ---
DEBUG: Autodiscovering Bitbucket Cloud repositories
DEBUG: hostRules: applying Bearer authentication for api.bitbucket.org
DEBUG: Autodiscovered 1 repositories
 INFO: Autodiscovered repositories
       "length": 1,
       "repositories": ["rahulgautamsingh/test-repo"]
```

When the project wasn't allowed
```
DEBUG: Combined config
       "config": {
         "forkProcessing": true,
         "token": "***********",
         "endpoint": "https://api.bitbucket.org/",
         "platform": "bitbucket",
         "autodiscover": true,
         "autodiscoverProjects": ["!ignore"],
         "hostRules": [{"matchHost": "https://api.github.com", "token": "***********"}]
       }
       ---
DEBUG: Applying autodiscoverProjects filter
       "autodiscoverProjects": ["!ignore"]
DEBUG: No repositories were autodiscovered
```

2024-03-11 13:23 UTC, rarkins commented
@FHannes @setchy for your review if you have time

2024-03-11 15:02 UTC, HonkingGoose requested changes

2024-03-11 15:02 UTC, HonkingGoose commented on docs/usage/self-hosted-configuration.md
> +The `autodiscoverProjects` config option takes an array of minimatch-compatible globs or re2-compatible regex strings.
```suggestion
The `autodiscoverProjects` config option takes an array of minimatch-compatible globs or RE2-compatible regex strings.
```

2024-03-11 15:02 UTC, HonkingGoose commented on docs/usage/self-hosted-configuration.md
> +You can use this option to filter the list of autodiscovered repositories by project names.
I would like a extra line explaining _why_ this can be handy, and/or _what_ the intended use is.

2024-03-11 17:18 UTC, HonkingGoose approved these changes

2024-03-11 17:34 UTC, viceice commented on lib/modules/platform/bitbucket/index.ts
> +        matchRegexOrGlobList(repo.project.name, config.projects!),
```suggestion
        matchRegexOrGlobList(repo.project.name, config.projects),
```
you already validate above

2024-03-11 17:34 UTC, viceice commented on lib/modules/platform/bitbucket/index.ts
> +export async function getRepos(config?: AutodiscoverConfig): Promise<string[]> {
```suggestion
export async function getRepos(config: AutodiscoverConfig): Promise<string[]> {
```
I think it's not optional and will always be passed from worker, so needs test updates.

2024-03-12 06:58 UTC, RahulGautamSingh commented on lib/modules/platform/bitbucket/index.ts
> +        matchRegexOrGlobList(repo.project.name, config.projects!),
TS throws errors for some reason :)

2024-03-12 13:18 UTC, FHannes commented
@rarkins The implementation looks to meet my requirements for the feature. Given there's no artifacts for this and I deploy Renovate as a container, it's a bit tricky for me to actually test the functionality at this time though.

2024-03-14 09:49 UTC, viceice approved these changes

2024-03-14 09:55 UTC, merged

2024-03-14 10:27 UTC, renovate-release commented
:tada: This PR is included in version 37.246.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.246.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.246.0)
- `37.246.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-16 14:30 UTC, FHannes commented
I was able to test this and it looks to be working as described.