feat(bitbucket-server): perform blobless clone
renovatebot/renovate pull request #27892
Opened 2024-03-12 19:35 UTC by phaldan

## Changes

Perform blobless clone with Atlassian Bitbucket Server / DataCenter

## Context

Closes #27853

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-03-12 19:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=27892) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=27892) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=27892) it.</sub>

2024-03-13 05:14 UTC, rarkins requested changes
@phaldan I have become aware recently that some companies are using very old versions of Bitbucket Server still, and this change would mean they can't keep using latest Renovate.

If we want to merge this change now, we need to detect the version of Bitbucket and adjust fullClone on/off based on that.

Alternatively we can change behavior in the next major release as long as there's an option to change it back for those users on old versions.

2024-03-13 05:57 UTC, viceice reviewed
if the version is not easily detectable, then we can use an experimental environment variable to slow flipping that flag.

2024-03-13 06:04 UTC, rarkins commented
Yes, if not easily detectable then:
- Add a flag in this major version to turn on blobless cloning
- Switch it in next major version to be a different flag to turn off blobless (i.e. change defaults)

2024-03-21 14:26 UTC, closed without merging