feat: allow packageScope in template compilation and add packageScope in maven datasource
renovatebot/renovate pull request #27925
Opened 2024-03-14 00:47 UTC by lyonlai

## Changes
This PR allows `packageScope` to be compiled in template module and adds packageScope in `maven` datasource.

This feature makes `maven` datasource to be able to pickup artifact `groupId` as the `packageScope` and allows the `packageScope` to be used in `groupName` so that we could group maven artifact update by its group name. 

example configuration

```json5
{
  packageRules: [
    {
       matchManagers: [
          'gradle'
       ],
       groupName: "{{packageScope}}"
    }
  ]
}
```

## Context

https://github.com/renovatebot/renovate/discussions/27721

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [X] Both unit tests + ran on a real repository

2024-03-14 03:05 UTC, rarkins requested changes
Would ideally support npm too!

2024-03-14 03:05 UTC, rarkins commented on lib/util/template/index.ts
> +  packageScope: 'The scope of the package name',
```suggestion
  packageScope: 'The scope of the package name. Supports Maven group ID only',
```

2024-03-15 05:09 UTC, rarkins approved these changes

2024-03-15 07:40 UTC, viceice approved these changes

2024-03-15 08:57 UTC, merged

2024-03-15 09:56 UTC, renovate-release commented
:tada: This PR is included in version 37.247.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.247.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.247.0)
- `37.247.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: