docs(nuget): add hint for protocol version in NuGet.config
renovatebot/renovate pull request #27933
Opened 2024-03-14 10:27 UTC by fgreinacher

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-03-15 18:21 UTC, viceice submitted a review, later dismissed

2024-03-15 21:16 UTC, HonkingGoose requested changes

2024-03-15 21:16 UTC, HonkingGoose commented on docs/usage/nuget.md
> +If a `v3` feed URL does not end with `index.json`, you must specify the version explicitely.
```suggestion
If a `v3` feed URL does not end with `index.json`, you must specify the version explicitly.
```

2024-03-18 17:48 UTC, fgreinacher commented on docs/usage/nuget.md
> +If a `v3` feed URL does not end with `index.json`, you must specify the version explicitely.
Thanks 😊

2024-03-18 17:49 UTC, viceice approved these changes

2024-03-18 18:41 UTC, HonkingGoose reviewed
I'm happy with the docs and layout. I'll let the maintainers review for technical accuracy.

2024-03-18 19:59 UTC, merged

2024-03-18 21:12 UTC, renovate-release commented
:tada: This PR is included in version 37.255.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.255.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.255.0)
- `37.255.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: