refactor: typos and correct spelling
renovatebot/renovate pull request #28215
Opened 2024-04-03 04:36 UTC by RahulGautamSingh

As per American English

## Changes
- fixed some typos in comments 
- `behaviour` -> `behavior` 
- replaced `ise` in some words with `ize`

## Context

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-04-03 06:29 UTC, viceice submitted a review, later dismissed

2024-04-03 20:57 UTC, HonkingGoose requested changes

2024-04-03 20:57 UTC, HonkingGoose commented on tools/jest.mjs
> + * Sadly there is no way to suppress `SECURITY WARNING: Reverting CVE-2023-46809: Marvin attack on PKCS#1 padding` warning
```suggestion
 * Sadly there is no way to suppress this warning: `SECURITY WARNING: Reverting CVE-2023-46809: Marvin attack on PKCS#1 padding`
```

2024-04-04 06:08 UTC, viceice approved these changes

2024-04-04 07:04 UTC, HonkingGoose approved these changes

2024-04-04 07:22 UTC, merged