feat: add datasource for AWS Lambda Layers
renovatebot/renovate pull request #28251
Opened 2024-04-05 16:31 UTC by kayman-mk

## Changes

This PR adds a new datasource to update the versioned layer arns for AWS Lambda Layers.

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-04-05 16:39 UTC, kayman-mk commented
Reopens #19081

I stopped working on that PR because I found out that you usually do not have the `lambda:listLayerVersions` policy for layers you do not own. So I thought this whole datasource does not make any sense. But in fact it is useful as we found out in a team internal discussion today:
- you can use it to update lambda layers you own
- you can ask the maintainer of the layer you do not own to add the respective permission so Renovate can list the version numbers as well
```shell
aws lambda add-layer-version-permission \
    --layer-name my-layer \
    --statement-id xaccount \
    --action lambda:ListLayerVersions  \
    --principal 123456789012 \
    --version-number 1
```

2024-04-05 16:40 UTC, kayman-mk commented
Still have to work on the documentation

2024-04-05 21:14 UTC, kayman-mk commented
Todo: test this on a real repository

2024-04-22 15:43 UTC, viceice requested changes

2024-07-23 11:14 UTC, rarkins commented
@kayman-mk do you have the time to resume this PR, or should we close it?

2024-08-04 06:40 UTC, kayman-mk commented
Let me try to fix the issues. Would be nice to have Lambda Layers supported.

2024-08-08 10:47 UTC, kayman-mk commented
review fixed, tests fixed, but I should better run this against a real repo first.

2024-08-10 08:32 UTC, kayman-mk commented
Manual test against a GitHub repository is successful: https://github.com/kayman-mk/renovate-test/pull/13

2024-08-10 09:03 UTC, kayman-mk commented
Testing done. Looks good to me.

2024-08-11 13:45 UTC, kayman-mk commented
Tests fixed again.

@rarkins @viceice Where can I see which branches are not covered?

2024-08-16 06:56 UTC, rarkins commented
@kayman-mk Every time you update the branch it resets (disables) the CI approvals. It's best you don't commit to this branch unless you have changes or need to resolve a conflict

2024-08-16 07:30 UTC, kayman-mk commented
Ah, ok. Thought it needs to be on the HEAD to be merged. Sorry.

2024-08-16 08:18 UTC, rarkins commented
GitHub's merge queue ensures that it's tested against the latest main commit before merging so we don't need to update PRs individually unless there's a conflict or a high chance that another PR broke the open one

2024-08-19 09:54 UTC, viceice commented on lib/modules/datasource/aws-lambda-layer/__fixtures__/layer-filter-no-architecture.json
> +{
inline those small fixtures

2024-08-19 09:54 UTC, viceice commented on lib/modules/datasource/aws-lambda-layer/index.ts
> +      CompatibleRuntime: runtime as Runtime,
what happens if they're undefined?

2024-08-19 09:54 UTC, viceice commented on lib/modules/datasource/aws-lambda-layer/index.ts
> +      AwsLambdaLayerFilterMetadata,
use our `Json.pipe` helper 

https://github.com/renovatebot/renovate/blob/49c0e6a2a1b058d47e79246cd66862fb65674d91/lib/util/schema-utils.ts#L200


https://github.com/renovatebot/renovate/blob/49c0e6a2a1b058d47e79246cd66862fb65674d91/lib/util/schema-utils.spec.ts#L143

2024-08-19 09:54 UTC, viceice commented on lib/modules/datasource/aws-lambda-layer/schema.ts
> +});
```suggestion
});

export const FilterParser = Json.pipe(AwsLambdaLayerFilterMetadata);
```

2024-08-22 14:24 UTC, viceice commented on lib/modules/datasource/aws-lambda-layer/index.ts
> +      CompatibleRuntime: runtime as Runtime,
sounds good

2024-08-26 09:41 UTC, viceice commented on lib/modules/datasource/aws-lambda-layer/index.spec.ts
> +import { AwsLambdaLayerDataSource } from './index';
```suggestion
import { AwsLambdaLayerDataSource } from '.';
```

2024-08-26 09:41 UTC, viceice commented on lib/modules/datasource/aws-lambda-layer/schema.spec.ts
> +      const metadata = AwsLambdaLayerFilterMetadata.parse(
use the filter parser here too

2024-08-27 17:41 UTC, kayman-mk commented
Still struggeling with the `pnpm-lock.yaml`. How can I regenerate the file so it includes my changes?

2024-08-29 07:27 UTC, kayman-mk commented on lib/modules/datasource/aws-lambda-layer/index.spec.ts
> +    it('should throw an exception if the filter criteria does not match the schema', async () => {
@viceice Is this assumption correct? If not: how to catch this error?

```
try {
  FilterParser.parse(xxxx);
} catch (e) {
  // log error and return null
}
```

Looks ugly and I guess there is a better option. Checking the existing source, I didn't find any.

2025-04-27 07:14 UTC, closed without merging