feat(http): Cleanup for HTTP cache
renovatebot/renovate pull request #28381
Opened 2024-04-12 19:01 UTC by zharinov

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2024-04-12 19:17 UTC, rarkins requested changes

2024-04-12 19:17 UTC, rarkins commented on lib/config/options/index.ts
> +    default: 90 * 24 * 60,
```suggestion
    default: 90,
```

2024-04-12 19:17 UTC, rarkins commented on lib/util/cache/repository/http-cache.ts
> +    logger.trace('cleanupHttpCache: invalid cache data');
```suggestion
    logger.warn('cleanupHttpCache: invalid cache data');
```

Isn't this a rare and unlikely event? (if you exclude empty/null cacheData)

2024-04-13 07:18 UTC, viceice submitted a review, later dismissed

2024-04-14 07:15 UTC, viceice submitted a review, later dismissed

2024-04-14 07:17 UTC, rarkins requested changes

2024-04-14 07:17 UTC, rarkins commented on lib/config/options/index.ts
> +      'Maximum duration in days to keep HTTP cache entries. Set to `0` to disable HTTP cache.',
```suggestion
      'Maximum duration in days to keep HTTP cache entries.',
```

2024-04-14 07:17 UTC, rarkins commented on lib/config/options/index.ts
> +      'Maximum duration in days to keep HTTP cache entries. Set to `0` to disable HTTP cache.',
Details are already in the markdown

2024-04-14 07:17 UTC, rarkins submitted a review, later dismissed

2024-04-14 14:16 UTC, viceice approved these changes

2024-04-14 14:24 UTC, merged

2024-04-14 15:00 UTC, renovate-release commented
:tada: This PR is included in version 37.295.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.295.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.295.0)
- `37.295.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-04-16 09:46 UTC, mjnowen commented
I believe this PR has introduced a bug. I have a Renovate MR in self-hosted GitLab with a >90 day http cache. Instead of it rotating (purging) my cache by default, it just prints a WARN message and returns.
[ cleanupHttpCache](https://github.com/renovatebot/renovate/blob/main/lib/util/cache/repository/http-cache.ts#L9)

I would expect >90 day http cache (by default=90) to not just `return` but actually purge my cache, but as the code is currently written, I never get to this line: https://github.com/renovatebot/renovate/blob/main/lib/util/cache/repository/http-cache.ts#L9