refactor(host-rules): Simplify ordering and matching
renovatebot/renovate pull request #28512
Opened 2024-04-18 18:53 UTC by zharinov

## Changes

## Context

- Ref: #28375

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-04-18 19:03 UTC, rarkins requested changes

2024-04-18 19:04 UTC, rarkins approved these changes, later dismissed

2024-04-19 07:20 UTC, viceice requested changes

2024-04-19 07:20 UTC, viceice commented on lib/util/host-rules.ts
> +  const res: HostRule = Object.assign({}, ...matchedRules);
we need to deep clone because we've sub objects like headers

2024-04-21 05:59 UTC, viceice approved these changes

2024-04-21 06:39 UTC, merged

2024-04-21 09:45 UTC, renovate-release commented
:tada: This PR is included in version 37.314.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.314.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.314.0)
- `37.314.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: