fix(autoReplace): Correct digest resolution when the replacementName and replacementVersion options are defined
renovatebot/renovate pull request #28655
Opened 2024-04-25 13:58 UTC by ssegato81

## Changes

* The getDigestConfig variable uses the correct lookupName when it's running a replacement and the replacementName is set

## Context

Discussion https://github.com/renovatebot/renovate/discussions/27728
Closes https://github.com/renovatebot/renovate/issues/20304

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2024-04-26 10:44 UTC, viceice requested changes
needs tests

2024-04-26 10:44 UTC, viceice commented on lib/workers/repository/process/lookup/index.ts
> +            getDigestConfig.lookupName = config.replacementName.substring(config.replacementName.indexOf("/") + 1);
this looks wrong to me. why the `substring` ?

2024-04-26 15:59 UTC, ssegato81 commented
> needs tests



> needs tests

It already has a test case for that part of the code. You can see it here https://github.com/renovatebot/renovate/blob/376a2a517b1f1bcc8f0ba4606c91b8d014d0ac02/lib/workers/repository/process/lookup/index.spec.ts#L4143

I'm only improving one part of the code that fails when the replacementName option points to another image different from the original one. The test case didn't detect that error/unexpected result because it happens when the lookupUpdates function calls the getDigestConfig one with the wrong values and you are mocking that answer. I don't know if you are expecting something different.

2024-04-29 13:21 UTC, viceice commented
you can do expectations on the function call, so it's called with the right parameters.

2024-05-16 17:28 UTC, closed without merging