feat(fvm): Support v3 config file
renovatebot/renovate pull request #28665
Opened 2024-04-25 20:08 UTC by Laennart

## Changes

Adds support for the new FVM config file structure that was introduced in v3. The new file is located at `.fvmrc`.

## Context

I'm aware that there already is another [open pull request](https://github.com/renovatebot/renovate/pull/27216) implementing this functionality but it's been over a month since the last comment/changes.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-04-26 05:09 UTC, rarkins commented on lib/modules/manager/fvm/extract.ts
> +      { contents: content },
Logging the whole file seems too much. How big is it usually?

2024-04-26 09:48 UTC, viceice requested changes

2024-04-26 09:48 UTC, viceice commented on lib/modules/manager/fvm/extract.ts
> +    const config = FvmConfig.parse(JSON.parse(content));
use JSON pipe from schema util

2024-04-26 17:52 UTC, rarkins approved these changes

2024-04-29 13:09 UTC, viceice approved these changes

2024-04-29 13:16 UTC, merged

2024-04-29 14:15 UTC, renovate-release commented
:tada: This PR is included in version 37.328.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.328.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.328.0)
- `37.328.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: