Suppress notification config has been added to the definitions.js.
renovatebot/renovate pull request #2906
Opened 2018-12-06 19:08 UTC by rtaum

Supress notifications logic has been added to the corresponding places.

Closes #

2018-12-06 19:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=2906) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=2906) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=2906) it.</sub>

2018-12-06 19:24 UTC, rarkins submitted a review, later dismissed

2018-12-06 19:46 UTC, rtaum commented on lib/workers/branch/index.js
> +        if (!config.suppressNotifications.includes('prIgnoreNotification')) {
Sure.

2018-12-07 11:25 UTC, rarkins requested changes
Needs confirmation of manual testing before merge

2018-12-08 05:49 UTC, rarkins approved these changes

2018-12-08 11:42 UTC, merged