docs(config): add note about GnuPG v2.4 usage
renovatebot/renovate pull request #29067
Opened 2024-05-14 13:29 UTC by viceice

## Changes
Add a note to disable the `AEAD` GnuPG v2.4 extensions.

## Context
- https://github.com/renovatebot/renovate/discussions/28934#discussioncomment-9419010

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-05-14 13:36 UTC, viceice commented on docs/usage/self-hosted-configuration.md
> +Really update the preferences? (y/N) y
```suggestion
Really update the preferences? (y/N) y
gpg> save
```

Not sure if the save is required. maybe better add this to be explicit.

2024-05-14 13:41 UTC, HonkingGoose requested changes

2024-05-14 13:41 UTC, HonkingGoose commented on docs/usage/self-hosted-configuration.md
> +    If you use gnupg v2.4 or newer to generate the key, then you need to disable `AEAD` preferences.
```suggestion
    If you use GnuPG `v2.4` (or newer) to generate the key, then you must disable `AEAD` preferences.
```

2024-05-14 13:41 UTC, HonkingGoose commented on docs/usage/self-hosted-configuration.md
> +    Otherwise Renovate can't decrypt the encrypted values.
```suggestion
    This is needed to allow  Renovate to decrypt the encrypted values.
```

2024-05-14 13:41 UTC, HonkingGoose commented on docs/usage/self-hosted-configuration.md
> +```
```suggestion
```bash
```

Maybe CLI styling the code looks nicer?

2024-05-14 13:56 UTC, rarkins approved these changes

2024-05-15 11:49 UTC, merged

2024-05-15 12:37 UTC, renovate-release commented
:tada: This PR is included in version 37.363.9 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.363.9)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.363.9)
- `37.363.9`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: