docs: fix link to nix usage docs
renovatebot/renovate pull request #29153
Opened 2024-05-19 08:28 UTC by robjtede

## Changes

Docs. Link fix.

## Context

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-05-19 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=29153) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=29153) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=29153) it.</sub>

2024-05-19 08:44 UTC, rarkins requested changes
Links need to work when hosted on docs.renovatebot.com too

2024-05-21 21:13 UTC, viceice requested changes
please update PR description why this link needs to be changed.

you shouldn't use the source docs from the repo because we generate the real docs as build steps.

2024-05-21 21:24 UTC, closed without merging

2024-05-21 21:25 UTC, robjtede commented
I clearly was wrong about the relative link setup.