fix(presets): replace `matchPackagePrefix/Patterns` with `matchPackageNames`
renovatebot/renovate pull request #29159
Opened 2024-05-19 17:46 UTC by RahulGautamSingh

## Changes
- replace `matchPackagePrefix/Patterns` with `matchPackageNames`

## Context
- Fix the failing test

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-05-19 19:07 UTC, rarkins requested changes
None of these are correct. Regex patterns need /.../. Prefixes need  /**

2024-05-20 04:07 UTC, rarkins approved these changes

2024-05-21 07:05 UTC, rarkins approved these changes

2024-05-21 20:18 UTC, viceice approved these changes

2024-05-22 06:00 UTC, merged