feat(manager/copier): Implement manager
renovatebot/renovate pull request #29215
Opened 2024-05-22 16:43 UTC by lkubb

## Changes
* Adds support for updating [Copier](https://copier.readthedocs.io/en/latest/) templates
* Adds one self-hosted (`copierTrust`) and one repository configuration (`copierOptions`, with several children)

## Context
Closes #25556 

* This implementation does not support `git@github.com:some/repo`-style URLs (I don't think they are used widely though)
* It does not fail when the smart update algorithm results in merge conflicts, they are not always reliable. It adds a warning when a file is reported to have conflicts though.

Note: This is my first PR to a TypeScript project in general and I have limited prior experience with Renovate. I read the contribution guidelines and tried to follow existing examples, but `copier` is not a regular manager, so I hope this is how it should be done.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2024-05-22 20:37 UTC, viceice reviewed
why do we need so many new config options? we don't have it for any other managers

2024-05-22 22:17 UTC, lkubb commented
> why do we need so many new config options? we don't have it for any other managers

I'd argue that Copier is somewhat different from other managers because it can impact each file in the repository in relatively dynamic ways. Also honestly, I tend to lean towards providing more configurability to users when it does not add significant complexity, but am not married to most of the options.

I believe `copierTrust` (without this, some templates are unmanageable), `data` (for centrally updating some variables) and likely `recopy` (if merge conflicts should be avoided at all cost) are essential.

Options like `skip` and `exclude` can help address specific annoying quirks (in some generated projects, example files are re-added even if they have been removed from the repository or can cause merge conflicts). `dataFile` and `skipTasks` are probably expendable and could be removed if we want to simplify the configuration.

2024-05-23 05:27 UTC, rarkins commented
We need to go back to the discussion for all of this. It's undesirable to bloat the configs with so many new options so we should discuss them one by one and reach agreement chest.

2024-07-01 09:24 UTC, viceice requested changes
Blocked by https://github.com/containerbase/base/issues/2870

2024-07-01 09:24 UTC, viceice commented on lib/modules/manager/types.ts
> +  allowScripts?: boolean;
Wrong, not passed there.

2024-07-01 09:24 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +  if (config?.allowScripts) {
```suggestion
  if (!GlobalConfig.get('allowScripts') || config.ignoreScripts) {
```

2024-07-01 09:24 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +    logger.error({ err }, `Failed to update copier template: ${err.message}`);
```suggestion
    logger.debug({ err }, `Failed to update copier template: ${err.message}`);
```

2024-07-01 09:24 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +    logger.warn({ packageFileName, depName: updatedDeps[0]?.depName }, msg);
```suggestion
    logger.debug({ packageFileName, depName: updatedDeps[0]?.depName }, msg);
```

2024-07-01 09:24 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +    await exec(command);
Needs dynamic install support

2024-08-05 10:26 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +
move to `./utils.ts`, will be replaced by our detect env tool soon

2024-08-05 10:26 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +  if (python) {
```suggestion
  if (is.nonEmptyString(python)) {
```

2024-08-05 10:26 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +  if (is.string(copier)) {
see above

2024-08-05 10:26 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +  const copierConstraint = getCopierVersionConstraint(config);
inline variable

2024-08-05 11:45 UTC, viceice commented on lib/modules/manager/copier/artifacts.spec.ts
> +    GlobalConfig.reset();
```suggestion
```

set above will override all

2024-08-05 11:45 UTC, viceice commented on lib/modules/manager/copier/artifacts.spec.ts
> +      expect(execSnapshots).toMatchObject([]);
```suggestion
      expect(execSnapshots).toEqual([]);
```

2024-08-05 11:45 UTC, viceice commented on lib/modules/manager/copier/artifacts.spec.ts
> +      expect(execSnapshots).toMatchObject([]);
```suggestion
      expect(execSnapshots).toEqual([]);
```

2024-08-05 11:45 UTC, viceice commented on lib/modules/manager/copier/artifacts.spec.ts
> +    it.each([
use string template style

2024-08-05 11:45 UTC, viceice commented on lib/modules/manager/copier/artifacts.spec.ts
> +          { cmd: 'install-tool copier ' + (copierConstraint ?? '9.2.0') },
use string template

2024-08-05 12:46 UTC, viceice approved these changes

2024-08-06 08:14 UTC, merged

2024-08-06 08:29 UTC, renovate-release commented
:tada: This issue has been resolved in version 38.19.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.19.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.19.0)
- `38.19.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: