fix(cargo): Correct bump of non-range values
renovatebot/renovate pull request #29388
Opened 2024-06-02 22:46 UTC by zharinov

## Changes

I've noticed Renovate doesn't perform updates for some dependencies released during last month.

The reason is the regression introduced recently, which led to incorrect `getNewValue(...)` calculation.

This PR makes sure `update-lockfile` just bumps the input value, if it isn't range.

## Context

- Ref: #28826

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2024-06-02 22:47 UTC, zharinov commented on lib/modules/versioning/cargo/index.spec.ts
> +    ${'0.6.7'}               | ${'update-lockfile'} | ${'0.6.7'}     | ${'0.6.9'}      | ${'0.6.9'}
This single line was added

2024-06-03 04:39 UTC, rarkins reviewed
If we're updating lock file then shouldn't the package file value remain unchanged if the update is "in range"?

2024-06-03 04:40 UTC, rarkins commented
In Cargo 0.6.7 means ~0.6.7, which covers 0.6.9

2024-06-03 07:35 UTC, zharinov commented
Hm, I see, but also I expect the package [`winnow`](https://crates.io/crates/winnow/versions) to be updated here in the project [without lockfile](https://github.com/zharinov/verver/blob/main/Cargo.toml#L11) 🤔

2024-06-03 14:06 UTC, zharinov commented
I think it's correct for projects with lockfiles, but without lockfile it isn't obvious why there is no updates. If it was bump for such cases, maybe it would be better, though now I'm not sure.

2024-06-03 15:25 UTC, viceice approved these changes

2024-06-03 16:24 UTC, rarkins requested changes
When updating lock file I don't think we should narrow ranges in the cargo toml

2024-06-03 16:39 UTC, closed without merging