massage and validate hostRules.matchHost
renovatebot/renovate pull request #29487
Opened 2024-06-06 15:30 UTC by RahulGautamSingh

## Changes
- Prefix `matchHost` url which contain `:` or `/` with `htps://` (migrated as well)
- Validate `matchHost` urls
   1. if its an empty string
   2. check is it is a valid url 

## Context
Part of: https://github.com/renovatebot/renovate/issues/29425

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-06-06 15:49 UTC, rarkins commented on lib/config/validation.spec.ts
> +        hostRules: [
Please add one with a missing matchHost to make sure that _doesn't_ error. e.g. have hostType and token only

2024-06-06 16:44 UTC, rarkins commented on lib/config/migrations/custom/host-rules-migration.spec.ts
> +          { host: 'some.domain.com:8080', token: '123test' },
```suggestion
          { matchHost: 'some.domain.com:8080', token: '123test' },
```

2024-06-06 16:46 UTC, rarkins requested changes

2024-06-06 16:46 UTC, rarkins commented on lib/config/validation.ts
> +            }
Use parseUrl() from utils instead, then no need to try/catch

2024-06-06 18:54 UTC, rarkins commented
Please test for both global and repo config

2024-06-06 21:25 UTC, RahulGautamSingh commented
> Please test for both global and repo config

Done ☑️

2024-06-07 06:09 UTC, rarkins approved these changes, later dismissed

2024-06-17 12:50 UTC, viceice reviewed
otherwise LGTM

2024-06-17 12:50 UTC, viceice commented on lib/config/validation.ts
> +            if (is.null_(parseUrl(rule.matchHost))) {
```suggestion
            if (null === parseUrl(rule.matchHost)) {
```
looks simpler than the `null_` function 🤔

2024-06-19 04:05 UTC, RahulGautamSingh commented on lib/config/validation.ts
> +            if (is.null_(parseUrl(rule.matchHost))) {
```suggestion
            if (parseUrl(rule.matchHost) === null) {
```

2024-06-23 08:57 UTC, viceice reviewed
otherwise LGTM

2024-06-23 08:57 UTC, viceice commented on lib/config/migrations/custom/host-rules-migration.ts
>  function massageUrl(url: string): string {
we should use a single shared function here and inside host rules

2024-06-23 20:52 UTC, RahulGautamSingh commented
When I export the `massageHostUrl` fn from `util/host-rules` and import it in `host-rules-migration.ts` the `util/sanitize` module doesn't get mocked properly in the `datasource/npm/npmrc.spec.ts` file. I am not sure what is the cause & the fix here.

If I only export the `massageHostUrl` fn from `util/host-rules` but do not import it in `host-rules-migration.ts` the `util/sanitize` module is mocked.

@viceice any suggestions?

2024-06-24 05:27 UTC, rarkins approved these changes

2024-06-28 07:19 UTC, viceice approved these changes

2024-06-28 07:26 UTC, merged

2024-06-29 07:11 UTC, renovate-release commented
:tada: This PR is included in version 37.421.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.421.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.421.0)
- `37.421.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: