fix(datasource/galaxy): support multiple results
renovatebot/renovate pull request #29664
Opened 2024-06-13 20:11 UTC by rarkins

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-06-13 21:19 UTC, viceice commented on lib/modules/datasource/galaxy/index.ts
> +      const githubUsernames = body.results.map((result) => result.github_user);
I would filter here and warn if the filtered result is empty. that way we only have to iterate once.

2024-06-13 21:29 UTC, secustor requested changes, later dismissed

2024-06-13 21:29 UTC, secustor commented on lib/modules/datasource/galaxy/index.ts
```suggestion
     body.results = body.results.filter((result) => result.github_user === username)
```

2024-06-13 21:29 UTC, secustor commented on lib/modules/datasource/galaxy/index.ts
> +      }
```suggestion
      logger.warn(
        { dependency: packageName },
        `Received multiple results from ${galaxyAPIUrl}`,
      );
      return null;
```

2024-09-22 07:40 UTC, rarkins commented on lib/modules/datasource/galaxy/index.ts
> +     body.results = body.results.filter((result) => result.github_user === username)
```suggestion
    body.results = body.results.filter((result) => result.github_user === username)
```

2024-09-23 06:16 UTC, viceice approved these changes

2024-09-23 06:52 UTC, merged

2024-09-23 07:06 UTC, renovate-release commented
:tada: This PR is included in version 38.93.4 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.93.4)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.93.4)
- `38.93.4`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: