Feat/add image support in helm values manager
renovatebot/renovate pull request #29828
Opened 2024-06-24 22:39 UTC by KyriosGN0

## Changes
This PR adds the `image` as viable option in helm-values manager 

## Context
Closes #7010 

## Documentation (please check one with an [x])

- [X] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [X] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-06-25 20:41 UTC, viceice requested changes
1. remove the closes keyword, this PR doesn't resolve that issue.

2. please add a use case to the PR description.

2024-06-25 20:41 UTC, viceice commented on lib/modules/manager/helm-values/extract.ts
> +        logger.debug('repository and image are both undefined');
add a return to break here

2024-06-25 20:41 UTC, viceice commented on lib/modules/manager/helm-values/readme.md
> +
```suggestion
```

2024-06-25 21:22 UTC, KyriosGN0 commented on lib/modules/manager/helm-values/extract.ts
> +        logger.debug('repository and image are both undefined');
added

2024-06-25 21:23 UTC, KyriosGN0 commented
@viceice why does this PR doesn't close #7010 ? 
what is it i am missing ?

2024-06-25 21:59 UTC, secustor commented
> @viceice why does this PR doesn't close #7010 ? what is it i am missing ?

You are implementing support for `image` and the issue is about `name`.

2024-06-26 06:29 UTC, KyriosGN0 commented
@secustor fixed that!

2024-07-01 09:16 UTC, viceice commented on lib/modules/manager/helm-values/__fixtures__/values_with_image_instead_of_repo.yaml
> +# Default values for test-chart.
Reduce to minimal size and inline to test

2024-07-01 09:16 UTC, viceice commented on lib/modules/manager/helm-values/extract.spec.ts
> +
inline to test

2024-07-01 09:16 UTC, viceice commented on lib/modules/manager/helm-values/extract.ts
> +        return null;
needs a test

2024-08-21 09:59 UTC, rarkins commented
@KyriosGN0 do you have time to continue this PR?

2024-08-21 10:57 UTC, KyriosGN0 commented
@rarkins, yes i just don't understand what is it i should change ?

2024-08-21 11:36 UTC, rarkins commented
> @rarkins, yes i just don't understand what is it i should change ?

Removed the added fixture _files_. Instead reduce the content as much as possible, and then inline it in the spec.ts file using `codeBlock` syntax. Here's an example of one: https://github.com/renovatebot/renovate/blob/fa8d3ff693ea3822d3598fd116714829e6da4b8b/lib/modules/manager/leiningen/extract.spec.ts#L149-L161

2024-08-22 18:43 UTC, viceice commented on lib/modules/manager/helm-values/__fixtures__/values_with_image_instead_of_repo.yaml
> +# Default values for test-chart.
yes

2024-09-22 08:15 UTC, KyriosGN0 commented
sorry, but i can't find time to work on this.

2024-09-22 08:15 UTC, closed without merging