feat(manager): add bun-version manager
renovatebot/renovate pull request #29998
Opened 2024-07-02 19:42 UTC by ghislainpiot

## Changes

This PR adds a new manager : `bun-version`

## Context

The `bun` manager was already quite complex, so I created a new one. However, if needed, I can try to merge my modifications in it.

Closes #29941

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2024-07-03 05:50 UTC, rarkins commented on lib/modules/manager/bun-version/index.ts
> +  fileMatch: ['^.bun-version$'],
Are you sure it can't be in a subdirectory?

2024-07-07 19:27 UTC, secustor requested changes

2024-07-07 19:27 UTC, secustor commented on lib/modules/manager/bun-version/index.spec.ts
> +      const res = extractPackageFile('1.0\n');
Add some test cases for malformed contents of `.bun-version`. 
There should be at least: 
- no new line at the end of the first line
- empty file
- multiple lines

2024-07-07 19:27 UTC, secustor commented on lib/modules/manager/bun-version/index.spec.ts
> +          currentValue: '1.0',
That would not work with `semver` versioning as it only contains two digits. Use `semver-coerced` instead.

2024-07-07 19:27 UTC, secustor commented on lib/modules/manager/bun-version/index.ts
> +    commitMessageTopic: 'Bun',
```suggestion
```
This shouldn't be needed.

2024-07-07 19:27 UTC, secustor commented on lib/modules/manager/bun-version/index.ts
> +    currentValue: content.trim(),
Add a `skipReason` if the file content is malformed.

2024-08-20 20:15 UTC, secustor requested changes

2024-09-07 16:11 UTC, secustor approved these changes
Thanks for your contribution

2024-09-07 16:18 UTC, merged

2024-09-07 16:31 UTC, renovate-release commented
:tada: This issue has been resolved in version 38.72.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.72.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.72.0)
- `38.72.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-09-08 08:19 UTC, viceice commented on lib/modules/manager/bun-version/index.ts
> +  versioning: id,
this should be removed, it's datasource default.
```suggestion
```