build!: require node v20
renovatebot/renovate pull request #30291
Opened 2024-07-22 08:56 UTC by viceice

## Changes
Require node v20 or v22 (with latest security fixes)

## Context
- #27992

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-07-22 09:35 UTC, secustor approved these changes

2024-07-22 09:46 UTC, rarkins requested changes

2024-07-22 09:46 UTC, rarkins commented on docs/development/local-development.md
> +- Node.js `^20.15.1 || >=22.5.1`
```suggestion
- Node.js `^20.15.1`
```

2024-07-22 09:46 UTC, rarkins commented on package.json
> +    "node": "^20.15.1 || >=22.5.1",
```suggestion
    "node": "^20.15.1",
```

2024-07-22 09:53 UTC, rarkins approved these changes

2024-07-22 10:05 UTC, merged

2024-08-22 17:30 UTC, SamyDgz approved these changes

2024-08-26 04:13 UTC, Goop-arsh reviewed
Run

2024-08-26 04:14 UTC, Goop-arsh commented
R