docs: fix `changelogUrl` description
renovatebot/renovate pull request #30305
Opened 2024-07-22 15:22 UTC by RahulGautamSingh

## Changes
- rectify the description for `changelogUrl` 

## Context
Ref: https://github.com/renovatebot/renovate/discussions/30299
I think this was missed during migration from `customChangelogUrl` -> `changelogUrl`

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-07-22 15:37 UTC, rarkins commented
Do we fetch it though?

2024-07-22 16:08 UTC, RahulGautamSingh commented
> Do we fetch it though?

no, just add a link like we do for `source`. reversed the docs.

2024-07-22 16:27 UTC, viceice submitted a review, later dismissed

2024-07-22 16:28 UTC, RahulGautamSingh commented
> Do we fetch it though?

no, only link it like we do for source. fixed

2024-07-22 20:37 UTC, HonkingGoose requested changes

2024-07-22 20:37 UTC, HonkingGoose commented on lib/config/options/index.ts
> +      'Allows you to specify a custom URL for the changelog, which Renovate will include in PR descriptions for easy access.',
```suggestion
      'Set a custom URL for the changelog. Renovate will put this URL in the PR body text.',
```

2024-07-22 20:37 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +This doesn't help with _fetching_ the changelogs, but if you configure it then Renovate will include a link to this URL in the PR body, so users can click through to read the changelog.
```suggestion
Sometimes Renovate does not show the correct changelog for a package.
As a workaround for this problem, you can give Renovate the URL to the changelog with the `changelogUrl` config option.
When set, Renovate will put a _link_ to the changelogs in the Renovate PR body.

Renovate does _not_ show the complete changelogs from the `changelogUrl` in its PR body text, you only get the URL from Renovate.
To read the changelogs you must use the link.
```

My goals with this text are to explain that:

- `changelogUrl` is a workaround for missing changelogs
- you only get a _link_ to the changelog, not the full changelogs

We already have a note admonition below after the codeblock to explain that setting `changelogUrl` does not help Renovate _fetch_ the changelogs. So I'm dropping that bit of info in my rewrite.

2024-07-22 21:23 UTC, RahulGautamSingh commented on lib/config/options/index.ts
> +      'Allows you to specify a custom URL for the changelog, which Renovate will include in PR descriptions for easy access.',
```suggestion
      'Set a custom URL for the changelog. Renovate will put this URL in the PR body text.',
```

2024-07-22 21:23 UTC, RahulGautamSingh commented on lib/config/options/index.ts
> +      'Allows you to specify a custom URL for the changelog, which Renovate will include in PR descriptions for easy access.',
```suggestion
      'Set a custom URL for the changelog. Renovate will put this URL in the PR body text.',
```

2024-07-23 06:04 UTC, rarkins approved these changes

2024-07-23 06:10 UTC, merged

2024-07-23 10:29 UTC, renovate-release commented
:tada: This issue has been resolved in version 37.440.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/37.440.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/37.440.1)
- `37.440.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: