fix: check for explicit preset during onboarding
renovatebot/renovate pull request #30350
Opened 2024-07-24 12:29 UTC by LukasAuerbeck

## Changes
Updates the onboarding handling to ensure explicitly set `onboardingConfig.extends` in the renovate `config.js` don't get overwritten by the default renovate-config repo lookup. See https://github.com/renovatebot/renovate/discussions/30202#discussioncomment-10064964 for more detailed discussion about the expected behaviour.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-07-25 07:28 UTC, rarkins commented
Why not make the logic higher-level?

In my opinion, if any `onboardingConfig` is set at all (even empty), then we shouldn't hunt for any default extends

2024-07-25 09:02 UTC, LukasAuerbeck commented
Yea, I agree it makes most sense to skip the lookups. Initially opted for the easiest option to prevent the overwriting.

2024-08-01 07:31 UTC, LukasAuerbeck commented
Is there anything open for this PR to be ready to merge/anything left on my side to do? In my last commit I changed the implementation to check for a user-defined preset before renovate attempts to find a repo that can be used as a default.

2024-08-01 17:30 UTC, viceice requested changes
@rarkins my expectation is the opposite. I like to use the default org config to be preferred over the onboarding config from admin config as it is now. if this will be changed, then we should have a flag to flip.

2024-08-01 17:30 UTC, viceice commented on lib/workers/repository/onboarding/branch/config.ts
> +async function searchDefaultOnboardingPreset(
please do this refactor in a separate PR

2024-08-02 08:02 UTC, LukasAuerbeck commented
Moved the `searchDefaultOnboardingPreset` refactor into a dedicated PR and had to do some force-pushing/rebasing to clean my fork's main branch.

I think adding an additional option for admins to configure `onboardingRepositoryLookup` (or similar) also makes sense and enables a few more complex configurations.

What comes to my mind is a situation in an org with these repos:
- `org/org-unit-1/renovate-config`
- `org/org-unit-2/renovate-config`

Where `org-unit-1` operates the renovate for the whole `org` group. They may have a config.js like this:

```js
{
  onboardingConfig: {
    extends: [
      "local>org/org-unit-1/renovate-config#v1.23.2"
    ]
  }
}
```

## PR in org-unit-1 group

With option `onboardingRepositoryLookup` set to false, my assumption would be that renovate skips the repo lookups and generates this config:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>org/org-unit-1/renovate-config#v1.23.2"
  ]
}
```

With `onboardingRepositoryLookup` set to true, I would assume renovate attempts to do the repo lookups, finds the `org/org-unit-1/renovate-config` repo, but since the admin configured preset is more specific (since it contains the pinned version) I would still assume that the onboarding PR has this config:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>org/org-unit-1/renovate-config#v1.23.2"
  ]
}
```

## PR in org-unit-2 group

With `onboardingRepositoryLookup` false I would assume the same onboarding config as in `org-unit-1` with an extends to `local>org/org-unit-1/renovate-config#v1.23.2`

With `onboardingRepositoryLookup` set to true, I would assume renovate attempts to do the repo lookups, finds the `org/org-unit-2/renovate-config` repo and creates this PR:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>org/org-unit-2/renovate-config"
  ]
}
```

2024-08-02 10:30 UTC, viceice commented
that's why you should not use main branch as source for a PR. we've a precommit check which should error out and disallow main

2024-08-08 18:49 UTC, LukasAuerbeck commented
For future PRs I will use a dedicated branch in the forked repo, since I can't change the PR and I don't think it's that important to close the PR and create a new one. For now I will just manually rebase and force push the rebased commits. If I change anything in the actual implementation I will use a new commit to make re-reviewing easier.

What are your opinions on my suggestion in https://github.com/renovatebot/renovate/pull/30350#issuecomment-2264806790 to make the handling more flexible by adding an additional flag? Would handling it this way be in-line with both of your expectations @rarkins, @viceice?

2024-08-19 05:57 UTC, rarkins commented on lib/workers/repository/onboarding/branch/config.ts
> +
```suggestion
  if (hasPredefinedPreset) {
    logger.debug('Predefined onboardingConfig.extends found, so default org presets won't be used');
  }
```

2024-08-21 09:46 UTC, rarkins approved these changes

2024-08-21 12:30 UTC, viceice requested changes
i still need a config option to reverse the logic change because our org presets have higher prio than our default onboarding config.

2024-08-24 06:52 UTC, rarkins commented
@viceice so your use case is "if an org preset exists, then add it to onboarding config" and you run on multiple orgs, some which don't have one?

2024-08-26 10:46 UTC, viceice commented
> @viceice so your use case is "if an org preset exists, then add it to onboarding config" and you run on multiple orgs, some which don't have one?

yes

2025-02-07 06:44 UTC, closed without merging