feat: Log descriptive cron schedules
renovatebot/renovate pull request #30472
Opened 2024-07-30 06:56 UTC by Sukhdev2002

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-07-30 06:59 UTC, rarkins requested changes
Needs tests, including if an invalid cron string is passed

2024-07-30 09:15 UTC, Sukhdev2002 commented
> Needs tests, including if an invalid cron string is passed

test case already written for invalid string types

2024-07-30 09:26 UTC, rarkins commented
You had tests before but they're missing now

2024-07-30 10:10 UTC, Sukhdev2002 commented
However, all the scenarios have already been covered in the previous test cases. Additionally, the test cases I added earlier will not run for the function where I made the changes.

2024-07-30 11:07 UTC, rarkins commented
We don't add features without tests to verify that the feature works

2024-07-30 11:32 UTC, Sukhdev2002 commented
> We don't add features without tests to verify that the feature works

added please check

2024-07-30 20:29 UTC, rarkins requested changes

2024-07-30 20:29 UTC, rarkins commented on lib/workers/repository/update/branch/schedule.spec.ts
> +  describe('cronstrue', () => {
Needs a test for an invalid value

2024-07-31 12:32 UTC, Sukhdev2002 commented on lib/workers/repository/update/branch/schedule.spec.ts
> +  describe('cronstrue', () => {
ok

2024-07-31 12:38 UTC, Sukhdev2002 commented on lib/workers/repository/update/branch/schedule.spec.ts
> +  describe('cronstrue', () => {
> Needs a test for an invalid value

Invalid test case is added

2024-07-31 12:45 UTC, rarkins requested changes

2024-07-31 13:33 UTC, Sukhdev2002 commented on lib/workers/repository/update/branch/schedule.spec.ts
> +        cronstrue.toString("* * */2 6#1");
> Use throwExceptionOnParseError=false like in the actual code

added

2024-07-31 16:09 UTC, rarkins approved these changes

2024-07-31 16:22 UTC, merged

2024-07-31 16:36 UTC, renovate-release commented
:tada: This issue has been resolved in version 38.16.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.16.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.16.0)
- `38.16.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-08-02 10:19 UTC, viceice commented on lib/workers/repository/update/branch/schedule.ts
> +    logger.debug(`Human-readable summary for cron:: ${cronScheduleSummary}`);
this causes a weird debug message for all later based strings as we try to parse as cron first 😕

2024-08-02 10:19 UTC, viceice commented on lib/workers/repository/update/branch/schedule.ts
> +    logger.debug(`Human-readable summary for cron:: ${cronScheduleSummary}`);
@rarkins we should refactor to only log if it's a cron expression and not a later expression.

2024-08-02 10:20 UTC, viceice commented on lib/workers/repository/update/branch/schedule.ts
> +    logger.debug(`Human-readable summary for cron:: ${cronScheduleSummary}`);
this message is also logged multiple times (for each branch)