fixed comment length bug
renovatebot/renovate pull request #30580
Opened 2024-08-04 15:58 UTC by amishk783

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-08-04 15:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=30580) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=30580) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=30580) it.</sub>

2024-08-04 17:22 UTC, RahulGautamSingh requested changes
Trunacate the body content before we compute commentNeedsUpdating. Else, we will compare full body content with comment body we fetch from api. And, the fetched body will be truncated whereas full body (from fn param) won't. 

This will cause the comment to be updated each time.

2024-08-08 09:33 UTC, viceice requested changes
See conversation

2024-08-08 15:50 UTC, amishk783 commented
Hi Rahul, Thanks for the guidance. I’ve moved smartTruncate(body, maxBodyLength()) before the commentNeedsUpdating check in the if-else case and will push the changes shortly.

2024-09-19 21:31 UTC, henry-fn commented
Thanks @amishk783 for the fix, anything blocking this being merged in?

2024-09-20 04:41 UTC, viceice commented
> Thanks @amishk783 for the fix, anything blocking this being merged in?

required changes are not pushed. also CI falls, so merge isn't an option.

2024-09-20 13:32 UTC, amishk783 commented
> > Thanks @amishk783 for the fix, anything blocking this being merged in?
> 
> required changes are not pushed. also CI falls, so merge isn't an option.

Hey, sorry for the delay. it completely slipped my mind. I've pushed the changes and addressed the feedback. Now truncating the body before checking commentNeedsUpdating

2024-09-23 16:17 UTC, henry-fn commented
> > > Thanks @amishk783 for the fix, anything blocking this being merged in?
> > 
> > 
> > required changes are not pushed. also CI falls, so merge isn't an option.
> 
> Hey, sorry for the delay. it completely slipped my mind. I've pushed the changes and addressed the feedback. Now truncating the body before checking commentNeedsUpdating

Just in case you missed it, I think there is still one linting test failing https://github.com/renovatebot/renovate/actions/runs/10960183807/job/30434310107?pr=30580

2024-10-04 16:38 UTC, henry-fn commented
@amishk783 poke on formatting here?

2024-10-09 19:27 UTC, rarkins approved these changes

2024-11-04 19:02 UTC, henry-fn commented
Anything blocking merging here?

2024-11-05 06:51 UTC, rarkins commented
@viceice please review

2024-11-18 14:00 UTC, henry-fn commented
Checking in again here

2024-11-18 17:07 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +    body = smartTruncate(body, maxBodyLength());
```suggestion
    body = smartTruncate(`${sanitizedContent}`, maxBodyLength());
```

2024-11-18 17:07 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +    body = smartTruncate(body, maxBodyLength());
```suggestion
     body = smartTruncate(body
       .replace(regEx(/Pull Request/g), 'Merge Request')
       .replace(regEx(/PR/g), maxBodyLength());
```
needs prettifying

2024-12-23 16:08 UTC, jwilliams-fn commented
@amishk783 poking here for _hopefully_ the final time 😅

2024-12-31 09:25 UTC, RahulGautamSingh commented
Replacement PR: https://github.com/renovatebot/renovate/pull/33348

2024-12-31 09:25 UTC, closed without merging