Fix: copier path error when update templates which are not in root of the repo
renovatebot/renovate pull request #30708
Opened 2024-08-12 08:13 UTC by PJ-Schulz

## Changes

I fixed the behavior described in #30684 where the update from a copier dependency takes place in the wrong path. I changed the function where the `copier update` command is created. I split up the path to the `.copier-answers` file give with `packageFileName` at the last separator and use the path to the answer file as destination and the last part as name for the `copy-answers` file

## Context

#30684 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-08-12 09:15 UTC, HonkingGoose requested changes

2024-08-12 09:15 UTC, HonkingGoose commented on lib/modules/manager/copier/artifacts.ts
> +  // Only push destination if it is not an empty string
```suggestion
  // Only push to destination if the string has content
```

2024-08-12 09:56 UTC, HonkingGoose requested changes
Not 100% sure on the correct PR title, but this should be better than what we have now. 😄

2024-08-12 09:56 UTC, HonkingGoose commented on lib/modules/manager/copier/artifacts.spec.ts
> +    it('invokes copier update with nested destination and answer file', async () => {
Please change the PR title to:

`fix(manager/copier): process update templates outside repository root`

2024-08-12 19:47 UTC, viceice requested changes
you can also pass package file name to exec options, so the exec function, so it will use it as cwd

2024-08-12 19:47 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +    answersFile = packageFileName.slice(lastSeparatorIndex + 1);
use `upath` module functions to split path from filename

2024-08-13 06:54 UTC, PJ-Schulz commented
I changed it to use upath and put the destination as cwd to the execOptions, but I do not know how to test it now. Do you have a suggestion?

2024-08-13 12:51 UTC, PJ-Schulz commented
I've added a test for checking `cmd` on execOptions. Can I test it this way, or should I test it another way?

2024-08-13 16:24 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +    cwd: dirname(packageFileName),
```suggestion
    cwdFile‎: packageFileName,
```
even simpler 😉

2024-08-13 16:24 UTC, viceice commented on lib/modules/manager/copier/artifacts.ts
> +import { basename, dirname } from 'upath';
```suggestion
import upath from 'upath';
```
otherwise we'll get esm import issues later

2024-08-15 09:54 UTC, viceice commented on lib/modules/manager/copier/artifacts.spec.ts
> +      );
```suggestion
          options: {
            cwd: '/tmp/github/some/repo/apps/my-app',
          }
        },
      ]);
```

use a single matcher

2024-08-15 10:55 UTC, viceice approved these changes

2024-08-15 11:07 UTC, merged

2024-08-15 11:21 UTC, renovate-release commented
:tada: This issue has been resolved in version 38.33.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.33.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.33.1)
- `38.33.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: