Create sdkman manager
renovatebot/renovate pull request #30780
Opened 2024-08-14 15:18 UTC by momosetkn

## Changes

support SDKMAN!

## Context

https://github.com/renovatebot/renovate/discussions/18835

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-08-15 00:30 UTC, momosetkn commented
sorry, I don't know how to check the operation, and not supported other than java and build-tool.

i submitted pull-request. but, I want will close this PR, because, Node.js is not my specialty, I think it would be better to have someone else who is knowledgeable about renovate + Node.js do it.

2024-08-15 12:05 UTC, viceice requested changes

2024-08-15 12:05 UTC, viceice commented on lib/modules/manager/sdkman/datasources.ts
> +      return ivyVersioning.id;
wrong, don't use versioning as datasource

2024-08-15 12:05 UTC, viceice commented on lib/modules/manager/sdkman/datasources.ts
> +import { GradleVersionDatasource } from '../../datasource/gradle-version';
rename file to `util`

2024-08-15 12:05 UTC, viceice commented on lib/modules/manager/sdkman/__fixtures__/unknown-dep.sdkmanrc
> +unknown=1.2.3
inline to test and use `codeBlock`, search codebase for samples

2024-08-15 12:05 UTC, viceice commented on lib/modules/manager/sdkman/extract.spec.ts
> +            depName: 'sbt',
```suggestion
            datasource: 'github-releases',
            depName: 'sbt',
            packageName: 'sbt/sbt',
```

2024-08-15 12:05 UTC, viceice commented on lib/modules/manager/sdkman/extract.spec.ts
> +            depName: 'maven',
```suggestion
            depName: 'maven',
            packageName: 'org.apache.maven:maven',
```

2024-08-15 12:05 UTC, viceice commented on lib/modules/manager/sdkman/extract.spec.ts
> +            currentValue: '21.0.3-tem',
this value is not supported by the java-version datasource

2024-08-18 12:34 UTC, momosetkn commented
@viceice 
Thank you very much for teaching.
I close ( or Temporarily close). because, renovate-datasource etc...It will needs major revision and Since the work needs to be done as we research, it will take time and the renovations cannot be completed immediately.

2024-08-18 12:34 UTC, closed without merging