feat(http): Limit Gradle Plugin repository
renovatebot/renovate pull request #30792
Opened 2024-08-14 20:41 UTC by zharinov

## Changes

- Ref: #27802

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-08-14 21:10 UTC, rarkins requested changes

2024-08-14 21:10 UTC, rarkins commented on lib/util/http/rate-limits.ts
> +    throttleMs: 2,
Please add a comment referencing how this was calculated. I think for the hosted app it will need to be much higher (less requests)

2024-08-15 06:07 UTC, rarkins approved these changes

2024-08-15 06:08 UTC, rarkins commented
@zharinov is this limit configurable (to less reportable second) through config? @nabeelsaabna will need to lower it because all app hosts share the same public IP and therefore rate limit

2024-08-15 07:21 UTC, viceice approved these changes

2024-08-15 07:27 UTC, merged

2024-08-15 07:40 UTC, renovate-release commented
:tada: This issue has been resolved in version 38.33.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.33.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.33.0)
- `38.33.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: