Parse bundler files via ruby parser
renovatebot/renovate pull request #3083
Opened 2019-01-18 12:38 UTC by sleekybadger

Closes #2983 

Hi. This should help with parsing Gemfiles. It works pretty well even for really complex cases and fetches all meta information that is passed via block or `gem` attributes.

```ruby
ruby '2.5.3'

source 'https://rubygems.org'

group :test do
  gem 'minitest-bisect'
  gem 'minitest-retry', '>= 1.0.0', '< 5', group: :development

  platforms :mri do
    gem 'byebug', source: 'https://external.com'
    gem 'stackprof'
  end

  source 'https://another-external.com' do
    gem 'benchmark-ips'
  end
end
```

```console
{
  "deps": [
    {
      "currentValue": null,
      "depName": "minitest-bisect",
      "depTypes": [
        "test"
      ],
      "lineNumber": [
        6
      ],
      "platforms": [],
      "registryUrls": [
        "https://rubygems.org/"
      ],
      "skipReason": "no-version"
    },
    {
      "currentValue": "< 5, >= 1.0.0",
      "depName": "minitest-retry",
      "depTypes": [
        "test",
        "development"
      ],
      "lineNumber": [
        7
      ],
      "platforms": [],
      "purl": "pkg:rubygems/minitest-retry",
      "registryUrls": [
        "https://rubygems.org/"
      ],
    },
    {
      "currentValue": null,
      "depName": "byebug",
      "depTypes": [
        "test"
      ],
      "lineNumber": [
        10
      ],
      "platforms": [
        "mri"
      ],
      "registryUrls": [
        "https://external.com/"
      ],
      "skipReason": "no-version"
    },
    {
      "currentValue": null,
      "depName": "stackprof",
      "depTypes": [
        "test"
      ],
      "lineNumber": [
        11
      ],
      "platforms": [
        "mri"
      ],
      "registryUrls": [
        "https://rubygems.org/"
      ],
      "skipReason": "no-version"
    },
    {
      "currentValue": null,
      "depName": "benchmark-ips"
      "depTypes": [
        "test"
      ],
      "lineNumber": [
        15
      ],
      "platforms": [],
      "registryUrls": [
        "https://another-external.com/"
      ],
      "skipReason": "no-version"
    },
  ],
  "registryUrls": [
    "https://rubygems.org/",
    "https://external.com/",
    "https://another-external.com/"
  ],
  "rubyVersion": "2.5.3"
}
```

The only thing that bothers me it is conditions inside Gemfile. For example from rails Gemfile:

```ruby
platforms :jruby do
  if ENV["AR_JDBC"]
    gem "activerecord-jdbcsqlite3-adapter", github: "jruby/activerecord-jdbc-adapter", branch: "master"
    group :db do
      gem "activerecord-jdbcmysql-adapter", github: "jruby/activerecord-jdbc-adapter", branch: "master"
      gem "activerecord-jdbcpostgresql-adapter", github: "jruby/activerecord-jdbc-adapter", branch: "master"
    end
  else
    gem "activerecord-jdbcsqlite3-adapter", ">= 1.3.0"
    group :db do
      gem "activerecord-jdbcmysql-adapter", ">= 1.3.0"
      gem "activerecord-jdbcpostgresql-adapter", ">= 1.3.0"
    end
  end
end
```

We can't access `activerecord-jdbcsqlite3-adapter`, `activerecord-jdbcmysql-adapter`, `activerecord-jdbcpostgresql-adapter` gems cause they are inside condition which is controlled via `AR_JDBC` environment variable. The only thing that I was able to come up with is to wrap ENV object and run parsing phaze two times. First time all environment variables handled as true, second time as false then merge results and remove duplicates, but this solution doesn't handle cases where condition will be controlled not via boolean type, for example:

```console
if ENV['RAILS_ENV'] == 'development'
  gem 'pry'
  gem 'web-console'
end
```

2019-01-18 12:58 UTC, rarkins commented
Funny thing is that a "dumb" parser like I did in JS doesn't care about the IF statements and goes right past them to collect every gem.

You could parse twice like this maybe:

- Replace every 'if x' statement with 'if true or x'
- Replace every 'if x' statement with 'if false or x'

But even then you would miss out if there's more than just if/else. e.g. `if X, else if Y, else ...`

2019-01-18 17:54 UTC, rarkins commented
This does sound like a difficult problem though. We definitely want every single gem line no matter how many conditional lines there are

2019-01-21 14:15 UTC, rarkins commented
@sleekybadger I've made some updates to the JS-based parsing to extract both the Ruby and Bundler versions/constraints if present, and to pick the right Docker image and install the exact Bundler version before updating `Gemfile.lock`. Your PR will also need some brief updates to match. Ruby and Bundler versions should be put into `compatibility.ruby` and `compatibility.bundler` and you can check the new tests cases for an example.

I also fixed the update function in this PR so that it handles multiple line numbers and updates all.

Before merging this PR we'll need to work out how to run the parsing (extract) via Docker too.

2019-02-09 10:20 UTC, sleekybadger commented
@rarkins updated

I successfully run it locally against of some my Ruby repos but didn't have a lot of time to verify the correctness of suggested dependencies, so it would be awesome if you can recheck this.

Also, I would like to refactor `bundler/artifacts.js` and `bundler/update.js` files if you don't mind, but I think this can be done in separate PR 😉

2019-02-14 11:21 UTC, rarkins commented
@sleekybadger could you make sure that we have a test to confirm we parse multi-line dependencies like this?

```
gem 'xxxx',
    git: 'xxxx',
    branch: 'feature/app'
```

2019-02-15 10:10 UTC, rarkins requested changes

2019-02-15 10:10 UTC, rarkins commented on lib/manager/bundler/extract.js
> +  const { stdout } = await exec(`${bin} ${args}`, { cwd, shell, env });
TODO: if binarySource === 'docker' then call out to Docker rather than the code directly

2019-02-15 19:41 UTC, sleekybadger commented
Sure)

2019-03-07 13:21 UTC, rarkins commented
TODO:
- [ ] Support binarySource=docker
- [ ] Extract Ruby version (as is done in master)
- [ ] Extract Bundler version (as is done in master)

2019-03-19 14:07 UTC, Scritik commented
Any news? :)

2019-07-29 13:10 UTC, closed without merging