Feat/bazel module maven
renovatebot/renovate pull request #30884
Opened 2024-08-19 11:55 UTC by al-babych-fivetran

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-08-19 11:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=30884) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=30884) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=30884) it.</sub>

2024-08-21 18:58 UTC, zharinov requested changes
Maven-related parsing should live in the separate file, see #30945

2024-08-21 18:58 UTC, zharinov commented on lib/modules/manager/bazel-module/maven.ts
> +export const mavenVariableRegex = /^maven.*/;
For this and other regex usages, please:

```suggestion
export const mavenVariableRegex = regEx(/^maven.*/);
```

2024-08-21 18:58 UTC, zharinov commented on lib/modules/manager/bazel-module/parser.ts
> +  .opt(q.op('.'))
Maven-specific matcher should be extracted into `mavenRules` and composed with the `moduleRules` via `alt()` (see `const rule = q.alt<Ctx>(moduleRlues);`).

2024-08-21 18:58 UTC, zharinov commented on lib/modules/manager/bazel-module/parser.ts
> +}
Maybe just put it to the `mavenRules`, once it's separated from `moduleRules`

2024-08-22 13:08 UTC, zharinov approved these changes

2024-08-22 13:15 UTC, rarkins approved these changes

2024-08-22 13:23 UTC, merged

2024-08-22 13:58 UTC, renovate-release commented
:tada: This issue has been resolved in version 38.49.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.49.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.49.0)
- `38.49.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: