docs(docker): Specify authType in code example
renovatebot/renovate pull request #30970
Opened 2024-08-22 19:18 UTC by bmaximuml

## Changes

Documentation update: While basic auth is mentioned above, the code example doesn't include that. My experimentation has shown that this auth doesn't work without specifying the authType as basic

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-08-22 19:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=30970) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=30970) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=30970) it.</sub>

2024-08-23 10:22 UTC, rarkins requested changes
Renovate defaults to authType=Basic whenever username/password is used, so I don't think this is good to add to the example

2024-08-23 10:27 UTC, bmaximuml commented
> Renovate defaults to authType=Basic whenever username/password is used, so I don't think this is good to add to the example

Does that include when it's using `encrypted`?
Found this:
` } else if (options.password !== undefined) {`
https://github.com/renovatebot/renovate/blob/745978f11ffbc2585be20f005fdbe854b19b466c/lib/util/http/auth.ts#L76

Not sure how `options.password` is being populated, ie if it'll get populated by encrypted or if that's just pulling straight from what's set in the config.

Fwiw I'm using google artifact registry as below, and kept seeing an auth error until explicitly setting the auth type to Basic.

```json
    {
      "matchHost": "eu.gcr.io",
      "username": "_json_key_base64",
      "authType": "Basic",
      "encrypted": {
        "password": "<password>"
      }
    }
```

2024-08-23 10:51 UTC, rarkins commented
The `encrypted` field is decrypted at the very beginning after config is loaded, so by the time that logic you referenced is executed then there should only be username/password in the host rule

2025-05-21 08:21 UTC, closed without merging