feat(manager/gleam): extract locked versions
renovatebot/renovate pull request #31000
Opened 2024-08-25 01:18 UTC by SnakeDoc

## Changes

Adds Gleam manager support for extracting locked versions from `manifest.toml`.

## Context

The Gleam manager does not extract `manifest.toml`.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2024-08-25 07:01 UTC, rarkins requested changes

2024-08-25 07:01 UTC, rarkins commented on lib/modules/manager/gleam/extract.ts
> +    gleamToml = GleamToml.parse(content);
Is this preferred over safeParse?

2024-08-26 07:12 UTC, viceice commented on lib/modules/manager/gleam/extract.ts
> +      { err: result.error },
```suggestion
      { err: result.error, packageFile },
```

2024-08-26 07:12 UTC, viceice commented on lib/modules/manager/gleam/extract.ts
> +    );
```suggestion
```
you already log it inside the called function

2024-08-26 09:06 UTC, viceice approved these changes

2024-08-26 09:21 UTC, rarkins approved these changes

2024-08-26 09:28 UTC, merged

2024-08-26 09:46 UTC, renovate-release commented
:tada: This issue has been resolved in version 38.54.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.54.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.54.0)
- `38.54.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: