fix(vulnerability-alerts): allow `null` for `first_patched_version`
renovatebot/renovate pull request #31123
Opened 2024-08-30 12:46 UTC by Betree

## Changes

Follow-up on https://github.com/renovatebot/renovate/pull/27378, which refactored Github vulnerability alerts to REST API. In the PR, `first_patched_version` has been introduced as an optional field but not `nullable`, which [fails zod validations](https://zod-playground.vercel.app?appdata=N4IgzgxgFgpgtgQxALhALwHQHsBGArGCAFwApgAdAOwAJbqAzASwCcwiB9ABwSOhgBN2ANxitGWSsmqZcBYmWqN%2BMSkUZNRUzG2aNKAcxIBKagF8j2TmokIANsYA0VWuZAOQQuwFcYYFAG0QYCZWDm5eWEERMQkpSi9bW1M3IOSAXXdosHFKFBAAZgwAJkKADhBTIA).

## Context

While investigating missing PRs for security vulnerabilities, I stumbled upon this message:

```
DEBUG: Vulnerability Alert: Failed to parse some alerts
{
  "error": {
    "message": "Schema error",
    "stack": "ZodError: Schema error\n    at Object.transform (/usr/local/renovate/lib/util/schema-utils.ts:66:21)\n    at /usr/local/renovate/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:3236:51\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ZodEffects.safeParseAsync (/usr/local/renovate/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:199:24)\n    at ZodEffects.parseAsync (/usr/local/renovate/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:180:24)\n    at GithubHttp.requestJson (/usr/local/renovate/lib/util/http/index.ts:297:16)\n    at Proxy.getVulnerabilityAlerts (/usr/local/renovate/lib/modules/platform/github/index.ts:1973:7)\n    at detectVulnerabilityAlerts (/usr/local/renovate/lib/workers/repository/init/vulnerability.ts:68:18)\n    at initRepo (/usr/local/renovate/lib/workers/repository/init/index.ts:67:12)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:64:14)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:202:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:187:7)\n    at /usr/local/renovate/lib/renovate.ts:18:22",
    "issues": {
      "0": {
        "security_vulnerability": {
          "first_patched_version": "Expected object, received null"
        }
      },
      "1": {
        "security_vulnerability": {
          "first_patched_version": "Expected object, received null"
        }
      },
      "6": {
        "security_vulnerability": {
          "first_patched_version": "Expected object, received null"
        }
      },
      "___": "... 1 more"
    }
  }
}
```

## Documentation (please check one with an [x])

- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-08-30 12:55 UTC, rarkins commented
What's the expectation for the behavior now that `first_patched_version` will be null? e.g. Renovate might report more vulnerabilities, although they won't have fixes?

2024-08-30 16:57 UTC, viceice requested changes
needs more changes and tests

2024-09-16 20:57 UTC, Churro commented
I ran into the same issue. Reproducer: https://github.com/renovate-demo/31123-github-first_patched_version 

Example:
```json
         "security_vulnerability": {
           "first_patched_version": null,
           "package": {"ecosystem": "maven", "name": "com.hazelcast:hazelcast"},
           "vulnerable_version_range": ">= 4.0, <= 4.0.6"
         }
```

renovate currently skips alerts without explicit fix version:
https://github.com/renovatebot/renovate/blob/ffe2b4c1882f6d96b62396bb96c29666cb9875ee/lib/workers/repository/init/vulnerability.ts#L90-L96

`vulnerable_version_range` is currently not considered at all but a fallback for such cases could be to form a constraint from the upper bound, e.g. `> 4.0.6`.

2025-02-07 12:54 UTC, Betree commented
I'm sorry, I don't have any more time to investigate this. Feel free to re-use my code if you intend to fix the issue.

2025-02-07 12:54 UTC, closed without merging