FIX #30312 All items in the urls array are wrapped between []() character.
renovatebot/renovate pull request #31161
Opened 2024-09-02 15:06 UTC by babyJesus12

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-09-02 15:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=31161) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=31161) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=31161) it.</sub>

2024-09-03 04:49 UTC, rarkins commented
Does this already work if merged, or needs some changes to our docs generation first?

2024-09-04 11:57 UTC, HonkingGoose requested changes
See my comment in the PR for more info, to summarize:

- The docs build should pass
- The docs should have a list with human-readable links

2024-09-08 08:21 UTC, viceice approved these changes

2025-02-17 08:49 UTC, closed without merging