feat: pr options [wip]
renovatebot/renovate pull request #31381
Opened 2024-09-13 14:30 UTC by RahulGautamSingh

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-09-14 19:51 UTC, HonkingGoose requested changes

2024-09-14 19:51 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +You can use these options:
```suggestion
You can use these configuration options within `prOptions`:

- `azureWorkItemId`
- `bbUseDefaultReviewers`
- `gitLabIgnoreApprovals`
```

Explain that we mean you can use these options within `prOptions`, and list the options.

Even better would be to autogenerate a table of allowed options within `prOptions`. That way, when we later add new options, the docs are updated automatically. I think we already do this for other bits of the docs.

2024-09-14 19:51 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +Creating a work item in Azure DevOps is beyond the scope of Renovate, but Renovate can link an already existing work item when creating PRs.
```suggestion
Renovate will not create a work item in Azure DevOps, this is beyond the scope of Renovate.
But Renovate can _link_ to an existing work item when Renovate creates a PR.
```

Split up sentence into two parts.

Can you configure a `azureWorkItemId` and then forget about it, as it just works? Or do you need to update the `azureWorkItemId` later?

2024-09-14 19:51 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +Configuring this to `true` means that Renovate will detect and apply the default reviewers rules to PRs (Bitbucket only).
```suggestion
If `bbUseDefaultReviewers` is set to `true`, Renovate detects and applies the default reviewers rules to its PRs (Bitbucket only).
```

2024-09-14 19:51 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +Ignore the default project level approval(s), so that Renovate bot can automerge its merge requests, without needing approval(s).
```suggestion
Ignore the default project level approval(s), to allow Renovate to automerge its Merge Requests, without needing approval(s).
```

2024-09-14 19:51 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +Under the hood, it creates a MR-level approval rule where `approvals_required` is set to `0`.
```suggestion
Under the hood, it creates a MR-level approval rule, where `approvals_required` is set to `0`.
```

2024-09-14 19:51 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +This option works only when `automerge=true` and either `automergeType=pr` or `automergeType=branch`.
```suggestion
For `gitLabIgnoreApprovals` to work you must set `automerge=true`, and either set `automergeType=pr` _or_ set `automergeType=branch`.
```

2024-09-14 19:51 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +Also, approval rules overriding should not be [prevented in GitLab settings](https://docs.gitlab.com/ee/user/project/merge_requests/approvals/settings.html#prevent-editing-approval-rules-in-merge-req
```suggestion
Also, approval rules overriding should _not_ be [prevented in GitLab settings](https://docs.gitlab.com/ee/user/project/merge_requests/approvals/settings.html#prevent-editing-approval-rules-in-merge-requests).
```

2024-09-16 06:08 UTC, rarkins requested changes
I'm not sure this is right for Renovate config. Nesting is normally for a reason, and in this case it's being used purely because "these config options relate to similar things".

2024-09-16 11:04 UTC, RahulGautamSingh commented
I agree with yout point, this might be a bit early for this option as there aren't as any pr-specific options.

But, I think it is good have them collected under one parent. The internal logic flow is distinct now that we have a parent, and adding a new pr-specific options will require less effort/time. And, in future if more pr-specific options are added then users will find it easier documented at one place.

2024-09-16 11:38 UTC, rarkins commented
I don't find this argument to be compelling. Such change in config approach is significant and wouldn't end here

2024-09-16 14:29 UTC, closed without merging

2024-09-16 14:29 UTC, RahulGautamSingh commented
Okay. I will close this in that case.