docs(usage): clarify that `packageRules` must have a selector
renovatebot/renovate pull request #31512
Opened 2024-09-21 03:27 UTC by jftanner

## Changes
Per [this discussion](https://github.com/renovatebot/renovate/discussions/31509), I updated the documentation to match the behavior and "selector" terminology consistent with `packageRules` validation.

## Context
See the linked discussion.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-09-21 06:40 UTC, rarkins requested changes
We no longer have "excludeX" in packageRules so I would prefer to use the terminology "matcher" instead of "selector" everywhere which I think is more intuitive

2024-09-21 15:16 UTC, jftanner commented
> We no longer have "excludeX" in packageRules 

I didn't even notice that! I'll switch it back to "matcher" and remove the pre-existing references to `exclude...`

2024-09-21 17:05 UTC, jftanner commented
I spend some time reviewing the underlying code to make sure I _really_ understand the actual behavior. It took me a few minutes to figure out properly, but I really appreciate the elegance of it. Very intuititive.

Alas, I'm not a technical writer by trade, but I did the best I could. I started with the intent of changing as little as possible, but wound up largely rewriting the whole list. If you'd prefer it go back to how it was, with only the second bullet updated, I can do that.

I also took out the list at the end of the last bullet. It seems to me like it's a subset of the total list, but that those particular matchers don't behave any differently. So, I removed it in favor of letting the table-of-contents speak for itself. Of course, if I'm misunderstanding something, I can put it back.

2024-09-22 07:16 UTC, rarkins commented on docs/usage/configuration-options.md
> +- A package rule matches a dependency if it is included by every matcher (they're AND-ed together).
```suggestion
- Each package rule must include at least one `match...` matcher.
- If multiple matchers are included in one package rule, all of them must match.
- Each matcher must contain at least one pattern. Some matchers allow both positive and negative patterns.
- If a matcher includes any positive patterns, it must match at least one of them.
- A matcher returns `false` if it matches _any_ negative pattern, even if a positive match also occurred.
```

2024-09-22 07:17 UTC, rarkins approved these changes

2024-09-22 07:27 UTC, merged

2024-09-22 08:02 UTC, renovate-release commented
:tada: This PR is included in version 38.93.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.93.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.93.1)
- `38.93.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-09-22 15:21 UTC, jftanner commented
I like your wording better. Thanks!

2024-09-23 10:26 UTC, HonkingGoose reviewed
Looks good to me!