fixed providers, as much as i understood , do let me know if did something wrong
renovatebot/renovate pull request #31754
Opened 2024-10-02 16:54 UTC by Ashmithelps

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-10-02 16:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=31754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=31754) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=31754) it.</sub>

2024-10-02 16:58 UTC, Ashmithelps commented
can anyone help me , i cant figure out where i am failing

2024-10-02 20:25 UTC, secustor commented
You need have PR title which follows [conventional commit conventions](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-10-02 20:28 UTC, secustor requested changes

2024-10-02 20:28 UTC, secustor commented on lib/modules/manager/npm/__fixtures__/lockfile-parsing/package-lock.json
Revert all these changes. 

Only changes in `lib/modules/manager/ocb` are necessary

2024-10-02 20:28 UTC, secustor commented on lib/modules/manager/ocb/extract.ts
Add tests to cover the providers too.

2024-10-02 20:28 UTC, secustor commented on lib/modules/manager/ocb/extract.ts
> +  deps.push(...processModule(definition.providers,'providers'));
```suggestion
  deps.push(...processModule(definition.providers,'providers'));

```

2024-10-03 04:42 UTC, Ashmithelps commented on lib/modules/manager/npm/__fixtures__/lockfile-parsing/package-lock.json
i just made the changes in , extract.ts and schema.ts , but how come these many changes have been made

2024-10-04 14:23 UTC, viceice commented on lib/modules/manager/npm/__fixtures__/lockfile-parsing/package-lock.json
you probably worked on wrong base branch.

2024-10-28 20:59 UTC, srikotu commented
@secustor wondering if there is a TTL on unworked PRs? 💭 
Was hoping to avoid manual "fix" to the PR for the next otel-collector release 😿

2024-10-29 10:22 UTC, secustor commented
There are no TTL, this PR needs fixes implement and a new review requested. 

See the [code of conduct](https://github.com/renovatebot/renovate/blob/main/CODE_OF_CONDUCT.md#if-you-have-urgent-work)

2025-07-02 13:59 UTC, closed without merging