feat(manager/maven): provide warning log if pom contains windows line ending
renovatebot/renovate pull request #31858
Opened 2024-10-08 15:07 UTC by sebtiem

## Changes

As discussed in [19090](https://github.com/renovatebot/renovate/discussions/19090), I added a warning log message if windows line endings are present when extracting the contents of a maven pom.xml.

## Context

See discussion [19090](https://github.com/renovatebot/renovate/discussions/19090).

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2024-10-08 16:01 UTC, rarkins requested changes

2024-10-08 16:01 UTC, rarkins commented on lib/modules/manager/maven/__fixtures__/simple.pom.crlf.xml
Reduce this to the minimum possible and inline it in the test file instead of as a fixture

2024-10-08 16:01 UTC, rarkins commented on lib/modules/manager/maven/__fixtures__/.gitattributes
Is this file necessary?

2024-10-09 07:52 UTC, sebtiem commented on lib/modules/manager/maven/__fixtures__/.gitattributes
We need to have the information to tell github not to switch to lf-endings. There already is a .gitattributes file at root  folder but to me, it feels more suitable to put this setting here as it is only for this specific file.

2024-10-09 10:02 UTC, rarkins commented on lib/modules/manager/maven/__fixtures__/.gitattributes
Do your tests fail if this file is removed?

2024-10-09 11:32 UTC, rarkins commented on lib/modules/manager/maven/__fixtures__/.gitattributes
Can this test file be inlined instead, e.g. using `\r\n` as part of the string?

2024-10-09 13:19 UTC, sebtiem commented on lib/modules/manager/maven/__fixtures__/.gitattributes
Sounds good.

2024-10-09 13:50 UTC, rarkins approved these changes

2024-10-15 10:12 UTC, merged

2024-10-15 10:45 UTC, renovate-release commented
:tada: This PR is included in version 38.124.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.124.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.124.0)
- `38.124.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: