feat(versioning): isBreaking
renovatebot/renovate pull request #31859
Opened 2024-10-08 15:18 UTC by rarkins

## Changes

Adds new concept `isBreaking`

## Context

Should be ready to be used with `matchJsonata` as an alternative to `matchUpdateTypes=major`.

Closes #24513

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-10-09 08:48 UTC, rarkins commented on lib/workers/repository/process/lookup/generate.ts
> +    // This versioning scheme does not have breaking awareness - assume only major updates are breaking
```suggestion
    // This versioning scheme does not have breaking awareness - assume only major updates are breaking
    // Updates from or to unstable releases should be treated as breaking too, but we should not add that as default behavior until we stop treating non-LTS 
```

2024-10-11 14:25 UTC, HonkingGoose requested changes

2024-10-11 14:25 UTC, HonkingGoose commented on lib/workers/repository/process/lookup/generate.ts
> +    // Updates from or to unstable releases should be treated as breaking too, but we should not add that as default behavior until we stop treating non-LTS
```suggestion
    // Updates from, or to, unstable releases should be treated as breaking too.
    // But we should not add that as default behavior until we stop treating non-LTS versions ...INSERT EXPLANATION HERE...
```

Let's split this into two sentences, and add some commas to help read the first sentence.

I think the last sentence is missing information about what needs to change to `non-LTS`, before you can "treat updates from, or to unstable releases as breaking". So I've added some placeholder text for you to fill out. :wink:

2024-12-18 20:43 UTC, HonkingGoose commented on lib/workers/repository/process/lookup/generate.ts
> +    // But we should not add that as default behavior until we stop treating non-LTS versions ...INSERT EXPLANATION HERE...
Placeholder for the maintainer to fill out. 🙂

2025-04-26 06:15 UTC, secustor submitted a review, later dismissed
LGTM, but we should add docs what the functions are for on versioning. Just like we have for managers.

2025-04-26 06:51 UTC, viceice commented on lib/modules/versioning/cargo/index.ts
> +
```suggestion
```

2025-04-26 06:51 UTC, viceice commented on lib/modules/versioning/cargo/index.ts
> +const { major: getMajor, minor: getMinor } = semver;
why not doing this as part of the import?

2025-04-26 06:51 UTC, viceice commented on lib/modules/versioning/cargo/index.ts
> +  if (!isStable(version) || !isStable(current)) {
can this throw somehow? do we validate single version somewhere before?

2025-04-26 06:51 UTC, viceice commented on lib/modules/versioning/semver-coerced/index.ts
> +  const coercedCurrent = semver.coerce(current)?.toString();
```suggestion
  const coercedVersion = semver.coerce(version);
  const coercedCurrent = semver.coerce(current);
```
why the `toString`?

2025-04-26 06:51 UTC, viceice commented on lib/workers/repository/process/lookup/generate.ts
> +    // But we should not add that as default behavior until we stop treating non-LTS versions ...INSERT EXPLANATION HERE...
☝️

2025-04-27 07:51 UTC, rarkins commented on lib/modules/versioning/cargo/index.ts
> +  if (!isStable(version) || !isStable(current)) {
Yes, we only call this if we have a valid update, which implies it was valid versions

2025-04-27 07:51 UTC, rarkins commented on lib/modules/versioning/cargo/index.ts
> +const { major: getMajor, minor: getMinor } = semver;
Done

2025-04-27 07:54 UTC, rarkins commented on lib/workers/repository/process/lookup/generate.ts
> +    // But we should not add that as default behavior until we stop treating non-LTS versions ...INSERT EXPLANATION HERE...
```suggestion
    // But we should not add that as default behavior until we stop treating non-LTS versions as unstable first
```

2025-04-27 07:56 UTC, rarkins commented on lib/modules/versioning/semver-coerced/index.ts
> +  const coercedCurrent = semver.coerce(current)?.toString();
Because it returns type `Semver | null`

2025-04-28 08:00 UTC, viceice approved these changes, later dismissed

2025-04-30 05:40 UTC, secustor approved these changes, later dismissed

2025-04-30 11:09 UTC, HonkingGoose requested changes
Some docs improvements. 😉

2025-04-30 11:09 UTC, HonkingGoose commented on docs/usage/modules/versioning/index.md
> +In most ecosystems, especially SemVer, major upgrades are synonymous with breaking changes.
```suggestion
In most ecosystems, especially SemVer, major upgrades are treated as breaking changes.
```

2025-04-30 11:09 UTC, HonkingGoose commented on docs/usage/modules/versioning/index.md
> +However, there are other cases too:
```suggestion
But other updates may have breaking changes too, for example:
```

2025-04-30 11:09 UTC, HonkingGoose commented on docs/usage/modules/versioning/index.md
> +      "description": "Group together non-breaking updates",
```suggestion
      "description": "Group non-breaking updates",
```

2025-05-04 12:13 UTC, viceice approved these changes, later dismissed
LGTM, but would love to include the docs improvements

2025-05-09 08:17 UTC, viceice approved these changes

2025-05-09 08:24 UTC, merged

2025-05-09 08:51 UTC, renovate-release commented
:tada: This PR is included in version 40.11.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/40.11.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/40.11.0)
- `40.11.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: