docs(onboarding): mention `onboardingRebaseCheckbox`
renovatebot/renovate pull request #31888
Opened 2024-10-10 06:05 UTC by RahulGautamSingh

## Changes

## Context

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-10-11 14:28 UTC, HonkingGoose requested changes

2024-10-11 14:28 UTC, HonkingGoose commented on docs/usage/getting-started/installing-onboarding.md
> +    For self-hosted users who want to add the rebase/retry checkbox to their onboarding PRs, they need to enable [onboardingRebaseCheckbox](https://docs.renovatebot.com/self-hosted-configuration/#onb
```suggestion
    If you self-host Renovate, and want to add the rebase/retry checkbox to Renovate's onboarding PRs: enable the [`onboardingRebaseCheckbox` config option](https://docs.renovatebot.com/self-hosted-configuration/#onboardingrebasecheckbox) first.
```

2024-10-14 08:14 UTC, HonkingGoose requested changes

2024-10-14 08:14 UTC, HonkingGoose commented on docs/usage/getting-started/installing-onboarding.md
> +    If you self-host Renovate, and want to add the rebase/retry checkbox to Renovate's onboarding PRs: enable the [`onboardingRebaseCheckbox` config option](https://docs.renovatebot.com/self-hosted-c
I think we want a relative link here? Right now we're linking to the docs domain (`https://docs.renovatebot.com`).

I always mess up the links, so I'll let a maintainer suggest the correct link. 🙃

2024-10-17 08:05 UTC, rarkins approved these changes

2024-10-17 08:16 UTC, merged

2024-10-17 08:30 UTC, renovate-release commented
:tada: This PR is included in version 38.124.4 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.124.4)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.124.4)
- `38.124.4`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: