Add support of Gitlab's sections for CODEOWNERS (#29202)
renovatebot/renovate pull request #32061
Opened 2024-10-21 18:15 UTC by MaximeMorille

## Changes

Add support for Gitlab's sections in CODEOWNERS files, notably their default approver feature.

## Context

Closes #29202 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required (not so sure about that, but I didn't find a part worthy of update)

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-10-22 05:42 UTC, rarkins reviewed
Does GitLab's approach _conflict_ with other platforms, particularly GitHub? This change is in lib/workers which means it will apply to all platforms

2024-10-22 18:13 UTC, MaximeMorille commented
Good point, it does conflict with [Gitea format](https://docs.gitea.com/usage/code-owners).

I will take a look at the platform folder to see if there is a way to implement this only for Gitlab.

2024-12-10 13:26 UTC, declension commented
Any progress on this? As heavy users of Renovate and Gitlab (and now CODEOWNERS) we'd love to have this feature :crossed_fingers:

2024-12-11 07:12 UTC, MaximeMorille commented
Hello @declension, thanks for the reminder, I forgot this PR...

I am quite busy right now, I pushed the current state of my rework but I don't know when I will be able to complete it (I think tests may be improved). I should have some time to work on it in a few weeks.

Feel free to push a new PR to fix this issue, you can take any part of my work if needed :slightly_smiling_face:

2025-01-23 05:56 UTC, MaximeMorille commented on lib/workers/repository/update/pr/code-owners.spec.ts
> +    it.failing('does not parse Gitea regex as Gitlab sections', async () => {
According to [Gitea's documentation](https://docs.gitea.com/usage/code-owners), we should be able to use regex patterns to identify files in a CODEOWNERS file, which may conflict with GitLab's section.

The regex parsing is currently failing on the main branch as well.

2025-04-30 04:33 UTC, rarkins requested changes

2025-04-30 04:33 UTC, rarkins commented on lib/workers/repository/update/pr/code-owners.ts
> +      .filter(is.nonEmptyString)
Deduplicate this logic into a common function

2025-04-30 04:33 UTC, rarkins commented on lib/workers/repository/update/pr/code-owners.ts
> +      .filter(is.nonEmptyString)
It seems it previously was in a location where it could have been deduplicated

2025-05-08 08:14 UTC, viceice commented on lib/modules/platform/gitlab/code-owners.spec.ts
> +      lines.forEach((line) => parser.parseLine(line));
use for-of loop

2025-05-08 08:14 UTC, viceice commented on lib/modules/platform/gitlab/code-owners.spec.ts
> +      lines.forEach((line) => parser.parseLine(line));
same

2025-05-08 08:14 UTC, viceice commented on lib/modules/platform/gitlab/code-owners.ts
> +  private addRule(rule: FileOwnerRule): void {
please inline this function, no benefit for a one liner which is only called on one place (perf)

2025-05-08 08:14 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +  for (const line of cleanedLines) {
wouldn't this make more sense to include to the parser directly? so you don't need the weird section state?

2025-05-09 07:14 UTC, MaximeMorille commented on lib/modules/platform/gitlab/index.ts
> +  for (const line of cleanedLines) {
I ended rewriting the whole class as functions, there is no need for any internal state :slightly_smiling_face:

2025-06-04 11:57 UTC, viceice commented on lib/workers/repository/update/pr/code-owners.ts
> +      : cleanedLines.map(extractOwnersFromLine);
```suggestion
    const fileOwnerRules = platform.extractRulesFromCodeOwnersLines?.extractRulesFromCodeOwnersLines(cleanedLines) ??cleanedLines.map(extractOwnersFromLine);
```

2025-06-05 14:19 UTC, MaximeMorille commented on lib/workers/repository/update/pr/code-owners.ts
> +      : cleanedLines.map(extractOwnersFromLine);
I made a little change to your suggestion to fix a small mistake: 2e6346781e143c7face62070e703c46721e53ea3

2025-06-06 07:48 UTC, viceice approved these changes

2025-06-07 09:08 UTC, rarkins approved these changes

2025-06-07 09:14 UTC, merged

2025-06-07 09:29 UTC, renovate-release commented
:tada: This PR is included in version 40.47.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/40.47.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/40.47.0)
- `40.47.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: