docs(manager/dockerfile): Document supported dependencies for Dockerfile manager
renovatebot/renovate pull request #32288
Opened 2024-11-01 23:35 UTC by malmor

## Changes

This pull requests adds a `Supported dependencies` section to the `Dockerfile` manager documentation.

## Context

The `Dockerfile` manager supports many different types of dependencies out of the box. This pull requests adds them to the documentation. I tested the different types of updates (`FROM`, `COPY --from`, `syntax`) and ensured they actually work as expected.

This pull request also fixes a small code highlighting issue in the `Flux` manager documentation (`'` was being used instead of `` ` `` for two of the resources).

Closes #29872 

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-02 06:12 UTC, rarkins requested changes

2024-11-02 06:12 UTC, rarkins commented on lib/modules/manager/flux/readme.md
> +4. Flux [system](https://fluxcd.io/docs/installation) manifests
We keep ordered list unnumbered intentionally - please revert this change

2024-11-02 19:49 UTC, HonkingGoose requested changes
Changes:

- Use a plain list.
- One sentence per line.
- Rewrite to shorten sentences, and use simpler words.

Good catch on the bad `code` styling in the other docs page!

2024-11-02 19:49 UTC, HonkingGoose commented on lib/modules/manager/dockerfile/readme.md
> +1. [`FROM`](https://docs.docker.com/reference/dockerfile/#from) images
```suggestion
- [`FROM`](https://docs.docker.com/reference/dockerfile/#from) images
```

2024-11-02 19:49 UTC, HonkingGoose commented on lib/modules/manager/dockerfile/readme.md
> +1. [`COPY --from`](https://docs.docker.com/reference/dockerfile/#copy---from) images
```suggestion
- [`COPY --from`](https://docs.docker.com/reference/dockerfile/#copy---from) images
```

2024-11-02 19:49 UTC, HonkingGoose commented on lib/modules/manager/dockerfile/readme.md
> +1. [`syntax`](https://docs.docker.com/reference/dockerfile/#syntax) images
```suggestion
- [`syntax`](https://docs.docker.com/reference/dockerfile/#syntax) images
```

2024-11-02 19:49 UTC, HonkingGoose commented on lib/modules/manager/dockerfile/readme.md
> +Renovate can update images referenced in `FROM` directives. This also works for multi stage builds where multiple `FROM` directives are being used in a single `Dockerfile`.
```suggestion
Renovate can update images referenced in `FROM` directives.
This even works for multi-stage builds with many `FROM` directives in one Dockerfile.
```

2024-11-02 19:49 UTC, HonkingGoose commented on lib/modules/manager/dockerfile/readme.md
> +Also variables and [`ARG` directives](https://docs.docker.com/reference/dockerfile/#understand-how-arg-and-from-interact) will automatically be expanded:
```suggestion
Also, Renovate will automatically expand variables and [`ARG` directives](https://docs.docker.com/reference/dockerfile/#understand-how-arg-and-from-interact):
```

2024-11-03 17:51 UTC, rarkins approved these changes

2024-11-03 17:59 UTC, merged

2024-11-04 09:55 UTC, renovate-release commented
:tada: This PR is included in version 38.142.6 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.142.6)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.142.6)
- `38.142.6`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: