chore: add new label actions
renovatebot/renovate pull request #32282
Opened 2024-11-01 15:17 UTC by rarkins

## Changes

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-01 16:49 UTC, HonkingGoose requested changes

2024-11-01 16:49 UTC, HonkingGoose commented on .github/label-actions.yml
> +    You've redacted too much information from your config or logs, making it too difficult to pinpoint the problem.
```suggestion
    You redacted too much information from your config or logs. This makes it hard for us to pinpoint the problem.
```

2024-11-01 16:49 UTC, HonkingGoose commented on .github/label-actions.yml
> +    Please only redact truly sensitive information, or consider an enterprise support contract if Open Source support is not suitable for you.
```suggestion
    Please only redact truly sensitive information. Or consider an enterprise support contract, if Open Source support does not suit you.
```

2024-11-01 16:49 UTC, HonkingGoose commented on .github/label-actions.yml
> +    Please provide a meaningful title for your discussion. This helps others understand what your discussion is about, and increases the chances of getting help.
```suggestion
    Please give your discussion a meaningful title. This helps others understand what your discussion is about, and increases the chances of getting help.
```

2024-11-01 16:49 UTC, HonkingGoose commented on .github/label-actions.yml
> +    Do not use titles like "Need config help", "Renovate is not working", etc. Instead, use a title that describes the specifics of your problem or question.
```suggestion
    Do not use titles like "Need config help", "Renovate is not working", etc. Try to summarize the specifics of your problem or question in the title.
```

2024-11-01 16:49 UTC, HonkingGoose commented on .github/label-actions.yml
> +    We appreciate the effort you put into creating a reproduction, but it's not minimal yet, or it doesn't include the fields we ask for in our template.
```suggestion
    We appreciate the effort you put into creating a reproduction. But your reproduction is not minimal yet, or is missing fields we ask for in our template.
```

2024-11-01 16:49 UTC, HonkingGoose commented on .github/label-actions.yml
> +    Please re-read the steps and documentation shared in the previous message, and try again to create a minimal reproduction.
```suggestion
    Please re-read the steps and documentation given in the previous message, and try again to create a minimal reproduction.
```

2024-11-04 09:00 UTC, viceice approved these changes

2024-11-04 09:03 UTC, HonkingGoose approved these changes

2024-11-04 09:13 UTC, merged

2024-11-04 09:55 UTC, renovate-release commented
:tada: This PR is included in version 38.142.6 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/38.142.6)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/38.142.6)
- `38.142.6`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: