feat(bitbucket): Add more logging to the PR cache
renovatebot/renovate pull request #32339
Opened 2024-11-05 13:14 UTC by zharinov

## Changes

## Context

- Closes #32329

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-05 13:18 UTC, rarkins requested changes

2024-11-05 13:18 UTC, rarkins commented on lib/modules/platform/bitbucket/pr-cache.ts
> +      logger.debug('Initializing new PR cache at repository cache');
Let's log these two separate cases

2024-11-05 13:18 UTC, rarkins commented on lib/modules/platform/bitbucket/pr-cache.ts
> +    this.reconcile(items);
If we have a faulty cache (somehow), and we are not self-healing through the reconcile command, would this logging be enough to catch it?

2024-11-05 20:59 UTC, viceice commented on lib/modules/platform/bitbucket/pr-cache.ts
> +    const oldCache = clone(this.cache.items);
needs to be before reconcile, otherwise it's the already updated cache.

2024-11-06 13:27 UTC, viceice approved these changes

2024-11-06 13:54 UTC, rarkins approved these changes

2024-11-06 14:04 UTC, merged

2024-11-06 14:43 UTC, renovate-release commented
:tada: This PR is included in version 39.6.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/39.6.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/39.6.0)
- `39.6.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: