fix(presets): include other kiota repos
renovatebot/renovate pull request #32437
Opened 2024-11-10 23:07 UTC by melotic

## Changes

Added other kiota repositories to the `kiota` monorepo preset.

## Context

#32164 added the `kiota` repository, but it also spans multiple repos for each language it supports.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-11 05:22 UTC, rarkins requested changes
Are the versions between repos kept in-sync? If not then this is probably not right for a monorepo grouping and instead might be part of group:recommended, or just a standalone grouping of its own

2024-11-11 16:49 UTC, melotic commented
> Are the versions between repos kept in-sync? If not then this is probably not right for a monorepo grouping and instead might be part of group:recommended, or just a standalone grouping of its own

They are not, only the version in each repo are in sync. I'll port this over to `group:recommended`.

2024-11-11 18:16 UTC, viceice requested changes
I don't like this new default grouping.

those packages should be grouped by their monorepo when the repo published them with the same version.

the other groups should be fully optional and opt-in, because they create immortal PRs.

2024-11-11 19:51 UTC, melotic commented
> I don't like this new default grouping.
> 
> those packages should be grouped by their monorepo when the repo published them with the same version.
> 
> the other groups should be fully optional and opt-in, because they create immortal PRs.

Is what you're saying define multiple monorepos for each Kiota repo and an optional group to group all the monorepos? That makes sense. 

For context, each kiota repo publishes multiple packages, versioned together, but the versions are not the same across repos. (_i.e_., the .NET packages are at `1.14.0`, while the NPM ones are at `1.0.0-preview.75`)

2024-11-12 19:31 UTC, viceice commented
i think most user are only using one tech stack, eg npm or dotnet on a single repo

2024-11-13 19:48 UTC, melotic commented
Hard to say exactly, Kiota is fiarly new. I would guesstimate that 50% of users have a dependency on the Kiota library itself (`microsoft/kiota`) to generate OpenAPI schemas & bindings, and then those bindings have a dependency on say `microosft/kiota-typescript` or `microsoft/kiota-dotnet`. The other half are just consumers without a need to generate bindings.

Most would only have one language like @viceice mentioned for the bindings. In my case, it's a C# backend with a TypeScript frontend.

There's an argument that any updates to the generation code (`microsoft/kiota`) should also cause an update to the code generated `microsoft/kiota-typscript`. 

But I as a user would be okay with the default behavior for 2 PRs, one for the actual generation kiota libraries, and another for the bindings.

2024-11-13 22:57 UTC, astellingwerf commented
Doesn't this change technically demand for a migration step? Folks might reference "monorepo:kiota", but it won't resolve any longer.

2025-04-27 07:13 UTC, closed without merging