feat(nodejs-lambda-versioning): Add a NodeJS Lambda Versioning module
renovatebot/renovate pull request #32480
Opened 2024-11-12 15:00 UTC by Garethp

## Changes

This PR adds a versioning module for NodeJS Lambda Runtimes provided by AWS

## Context

As discussed in [this discussion](https://github.com/renovatebot/renovate/discussions/32313), I want to keep versions of Node in with the release schedule of AWS Lambdas. AWS NodeJS Lambdas release within a month or two after a NodeJS version goes LTS so there is a period of time where a version of Node is LTS but not available as a Lambda Runtime. To keep a project's node dependency on the same version as the Runtime it will run on, I need to be able to set those dependencies (nvmrc, docker etc...) to follow the Lambda Runtime release schedule rather than the NodeJS release schedule.

Since this is meant to be a drop-in replacement for any packages that follow `node` versioning, I've re-used most of the functions provided by the `node` versioning module and only changed the `isStable` function.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2024-11-21 16:22 UTC, viceice reviewed
needs code coverage 

https://github.com/renovatebot/renovate/actions/runs/11800328119/job/33317532023#step:6:22

2025-02-17 17:08 UTC, Garethp commented
@viceice, I've removed the unused code and changed how I'm mocking the data. I've also mocked out `dataFiles` so that I can test some of the if conditions that are based on unstable data from the datasource. Let me know if this is the appropriate way of testing that instability.

2025-03-12 16:54 UTC, Garethp commented
@rarkins, @viceice, could I please get a re-review on this and an approval to run the tests for this MR?

2025-03-12 16:56 UTC, viceice commented
you should use the re-request review button

2025-03-17 09:20 UTC, viceice requested changes

2025-03-17 09:20 UTC, viceice commented on tools/static-data/generate-lambda-node-schedule.mjs
> +  const { body } = await got(lambdaDataUrl);
use builtin fetch, see

https://github.com/renovatebot/renovate/blob/6dc2b37be1c3a3f8924ecb45caa850a877cc5631/tools/static-data/generate-node-schedule.mjs#L8

2025-03-17 09:20 UTC, viceice commented on tools/static-data/generate-lambda-node-schedule.mjs
> +    .reduce((schedule, lambda) => {
use for-of loop

2025-03-17 09:20 UTC, viceice commented on package.json
> +    "update-static-data:lambda-node-schedule": "node tools/static-data/generate-lambda-node-schedule.mjs"
sort alphanumeric

2025-03-17 09:20 UTC, viceice commented on lib/modules/versioning/node/index.ts
> +      return DateTime.now() > DateTime.fromISO(schedule.lts);
why this change? should be in a separate PR

2025-03-17 09:20 UTC, viceice commented on lib/modules/versioning/node/index.spec.ts
> +    jest.spyOn(Settings, 'now').mockReturnValue(time.valueOf());
use vitest fake timer instead

2025-03-17 09:20 UTC, viceice commented on lib/modules/versioning/lambda-node/index.spec.ts
> +jest.spyOn(dataFiles, 'get').mockImplementation((fileName) => {
we're now using vitest

2025-04-01 12:42 UTC, viceice commented on lib/modules/versioning/lambda-node/index.spec.ts
> +
drop it

2025-04-01 12:42 UTC, viceice commented on lib/modules/versioning/lambda-node/index.spec.ts
> +    vi.useFakeTimers();
move to before all

2025-04-01 12:42 UTC, viceice commented on lib/modules/versioning/lambda-node/schedule.ts
> +  const majorVersionMatch = /^v?([0-9]+)\./.exec(version);
```suggestion
  const majorVersionMatch = regEx(/^v?([0-9]+)\./).exec(version);
```
move below condition (perf)

2025-04-01 12:42 UTC, viceice commented on lib/modules/versioning/lambda-node/schedule.ts
> +  return lambdaSchedule[majorVersionMatch![1]] ?? null;
are you sure it always matched when coming here?

2025-04-01 12:52 UTC, viceice commented on tools/static-data/generate-lambda-node-schedule.mjs
> +    response.json(),
```suggestion
    if (!response.ok) {
      console.error(`Failed to fetch ${lambdaDataUrl}`, response);
      process.exit(1);
    }
    response.json(),
```

catch download errors

2025-04-01 12:55 UTC, viceice commented on lib/modules/versioning/lambda-node/index.spec.ts
> +  const dataFiles = (await importOriginal<{ default: Map<DataFile, string> }>())
```suggestion
  const dataFiles = (await importOriginal<typeof import('../../../data-files.generated')>())
```

2025-04-01 12:56 UTC, viceice commented on lib/modules/versioning/lambda-node/index.ts
> +    return DateTime.now() < DateTime.fromISO(schedule.support);
```suggestion
    return DateTime.local() < DateTime.fromISO(schedule.support);
```

use local time for comparison like we do in node versioning

2025-04-04 14:25 UTC, Garethp commented on lib/modules/versioning/lambda-node/schedule.ts
> +  return lambdaSchedule[majorVersionMatch![1]] ?? null;
If it's not matched, the `isStable(version)` check will fail first and return null. But good point, that's non-obvious and not within this function. I've  added a check to see if it was matched and verified that there's already a test `isStable("Iron")` that hits that return and is testing it

2025-04-16 09:30 UTC, viceice commented on lib/modules/versioning/node/index.ts
> +export function getNewValue({
why not using it from the `api` export?

2025-04-16 09:30 UTC, viceice commented on tools/static-data/generate-lambda-node-schedule.mjs
> + *                                      will end. 0.10.x is a sole exception which has `false` and will be filtered out.
maybe create a zod schema instead? 🤔

2025-04-22 10:39 UTC, Garethp commented on tools/static-data/generate-lambda-node-schedule.mjs
> +  const nodeRuntimes = z.record(z.string(), RuntimesSchema.element).parse({});
I had to do a `.parse()` here because typescript is still inferring a type, even in JS, and `nodeRuntimes[versionMatch[1]] = lambda;` wanted `nodeRuntimes` to be better typed. Before I was using the JSDocs parameters, but moving to zod I couldn't find a better public interface for getting the output type. This lets typescript infer the correct typing of this record

2025-05-05 09:21 UTC, Garethp commented
@viceice, are there any other changes you think need to be made before this is ready to be merged in?

2025-05-06 11:54 UTC, viceice reviewed
otherwise lgtm

2025-05-06 11:54 UTC, viceice commented on tools/static-data/generate-lambda-node-schedule.mjs
> +  const nodeRuntimes = z.record(z.string(), RuntimesSchema.element).parse({});
what about this?
```suggestion
  /** @type {Record<string,RuntimesSchema>} */
  const nodeRuntimes = {};
```

2025-05-06 12:29 UTC, Garethp commented on tools/static-data/generate-lambda-node-schedule.mjs
> +  const nodeRuntimes = z.record(z.string(), RuntimesSchema.element).parse({});
That was the first thing I tried and it doesn't work. `nodeRuntimes[versionMatch[1]] = lambda;` ends up complaining because it expects `lambda` to match the `ZodObject` typing, which contains extra properties. I couldn't figure out a way to get it to type-hint against the original shape that zod is wrapping instead of the `ZodObject` type. Here's the type error when I try it:

```
error TS2740: Type '{ support: string | boolean; cycle: string; }' is missing the following properties from type 'ZodObject<{ cycle: ZodString; support: ZodUnion<[ZodBoolean, ZodString]>; }, "strip", ZodTypeAny, { support: string | boolean; cycle: string; }, { ...; }>': _cached, _getCached, _parse, shape, and 52 more.
```

2025-05-06 12:35 UTC, viceice commented on tools/static-data/generate-lambda-node-schedule.mjs
> +);
```suggestion
const RuntimesSchema =
  z.object({
    cycle: z.string().describe('The ID of the Runtime'),
    support: z
      .union([z.boolean(), z.string()])
      .describe(
        'Either `true` if in support, or a string denoting when support for this Runtime will end. 0.10.x is a sole exception which has a value of `false` and will be filtered out',
      ),
  });
const RuntimesArraySchema = z.array(RuntimesSchema);
```

2025-05-06 12:35 UTC, viceice commented on tools/static-data/generate-lambda-node-schedule.mjs
> +    return RuntimesSchema.parseAsync(await response.json());
```suggestion
    return RuntimesArraySchema.parseAsync(await response.json());
```

2025-05-06 12:35 UTC, viceice commented on tools/static-data/generate-lambda-node-schedule.mjs
> +  const nodeRuntimes = z.record(z.string(), RuntimesSchema.element).parse({});
and what about this? (needs other change above)
```suggestion
  /** @type {Record<string, z.infer<RuntimesSchema>>} */
  const nodeRuntimes = {};
```

2025-05-06 13:16 UTC, viceice approved these changes

2025-05-06 18:35 UTC, rarkins approved these changes

2025-05-06 21:57 UTC, merged

2025-05-06 22:15 UTC, renovate-release commented
:tada: This PR is included in version 40.7.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/40.7.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/40.7.0)
- `40.7.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: