docs: add documentation for the Developer Portal host rules credentials
renovatebot/renovate pull request #32542
Opened 2024-11-14 15:23 UTC by justo-mend

## Changes

Update docs in the Mend-hosted Apps section to show how to use the Host Rules UI in Developer Portal credentials settings.

## Context

Developer Portal for Mend-hosted apps now provides the ability for users to specify host rules.
This PR includes updates to the documentation to describe the new feature.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-14 15:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=32542) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=32542) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: justo-mend<br/>:x: justcla<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=32542) it.</sub>

2024-11-14 16:01 UTC, HonkingGoose requested changes

2024-11-19 13:41 UTC, justo-mend commented on docs/usage/mend-hosted/credentials.md
> +### Adding a host rule through the UI
Thanks for the suggestion. I'm happy to merge the PR as is - without introducing collapsible blocks. It's important we get this information up on the site ASAP, and would rather not delay it any further with tweaks for collapsibility.

2024-11-19 13:47 UTC, rarkins approved these changes

2024-11-19 13:56 UTC, merged

2024-11-19 19:07 UTC, HonkingGoose commented on docs/usage/mend-hosted/credentials.md
> +### Adding a host rule through the UI
I apologize for the confusion! I wrongly assumed that you replaced text with an image. 

But you actually _added_ text... I got myself confused with the GitHib diff view....