feat(poetry): support GCloud credentials for Google Artifact Registry when locking
renovatebot/renovate pull request #32586
Opened 2024-11-17 20:29 UTC by maxbrunet

## Changes

Detect Google Artifact Registry URL and pass GCloud Oauth credentials via `POETRY_HTTP_BASIC_*` environment variables when running `poetry lock`

## Context

Similar to #32545 for uv

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-18 21:03 UTC, viceice requested changes, later dismissed

2024-11-18 21:03 UTC, viceice commented on lib/modules/manager/poetry/artifacts.spec.ts
> +          newPackageFileContent: pyproject10toml,
please use a small inline fixture instead of extending an existing.

2024-11-18 21:03 UTC, viceice commented on lib/modules/manager/poetry/artifacts.ts
> -function getPoetrySources(content: string, fileName: string): PoetrySource[] {
nope, this should be logged when file parsing failed, so users know which file can't be parsed.

btw: this variable is used!

2024-12-18 13:40 UTC, maxbrunet commented
An other review for this one? :pray:

2024-12-18 13:50 UTC, rarkins requested changes

2024-12-18 13:50 UTC, rarkins commented on lib/modules/manager/poetry/artifacts.ts
> +    logger.once.debug({ url }, 'Failed to parse URL');
```suggestion
    logger.once.debug(`Failed to parse URL ${url}`);
```

2024-12-18 14:39 UTC, rarkins approved these changes

2025-01-02 13:04 UTC, maxbrunet commented
Kindly asking for extra reviews or a merge 🙂🙏

2025-01-08 12:35 UTC, merged