feat(gitlab): add branch status check attemps
renovatebot/renovate pull request #32692
Opened 2024-11-23 15:48 UTC by philippe-granet

## Changes

* Add branch status check attemps before trying to add status check
* Allow overriding the branch status check attempts via experimental env `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPS`.

## Context

* https://github.com/renovatebot/renovate/discussions/27111
* https://github.com/renovatebot/renovate/pull/23239
* https://github.com/renovatebot/renovate/issues/5743

## Documentation (please check one with an [x])

- [X] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-24 11:19 UTC, mikaello commented on docs/usage/self-hosted-experimental.md
> +## `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPS`
```suggestion
## `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPTS`
```

Remember to fix all places

2024-11-24 11:33 UTC, philippe-granet commented on docs/usage/self-hosted-experimental.md
> +## `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPS`
Done

2024-11-25 10:47 UTC, rarkins requested changes

2024-11-27 10:00 UTC, viceice commented on lib/modules/platform/gitlab/index.ts
> +  for (let attempt = 1; attempt <= retryTimes; attempt += 1) {
the whole loop should have a try catch and early return on failures from gitlab API

2024-11-27 10:33 UTC, philippe-granet commented
> Could this instead be default functionality, with a large number of attempts, e.g. 10?

This will penalize projects that do not have defined pipelines, this will systematically wait 10s

2024-12-11 23:19 UTC, philippe-granet commented
> > > Could this instead be default functionality, with a large number of attempts, e.g. 10?
> > 
> > 
> > This will penalize projects that do not have defined pipelines, this will systematically wait 10s and slow down the renovate analyzes
> 
> Thanks for the info. I think I missed this from the various conversations before. Could make sure this info of when this is setting is applicable and when it's not is captured in the markdown doc in this PR? I will then decide if it needs to be a first-class option or brainstorm if we have a clever way to detect this. If this is a common problem we prefer that users don't need to set obscure experimental options.

Done in this commit :[`5a3f6d3` (#32692)](https://github.com/renovatebot/renovate/pull/32692/commits/5a3f6d304a017351f478dbcc41707c6add33b4f1)

2024-12-16 06:36 UTC, rarkins commented on lib/modules/platform/gitlab/index.ts
> +    for (let attempt = 1; attempt <= retryTimes; attempt += 1) {
Is this intended to skip the for loop if the value is unset (value 0)?

It's kind of a confusing way to do this, I'd prefer it is more explicit/obvious for future maintainability

2025-01-27 17:53 UTC, philippe-granet commented on docs/usage/self-hosted-experimental.md
> +!!! warning Increasing this value too much penalizes projects that do not have defined pipelines, Renovate will systematically wait `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPTS * RENOVATE_X_GITLAB
"do not have defined pipelines" means projects without `.gitlab-ci.yml` or with a Gitlab pipeline where all jobs are desactivated, for example with [rules](https://docs.gitlab.com/ee/ci/jobs/job_rules.html) that desactivate Gitlab pipeline on Renovate branch.

2025-01-27 18:11 UTC, rarkins commented on docs/usage/self-hosted-experimental.md
> +!!! warning Increasing this value too much penalizes projects that do not have defined pipelines, Renovate will systematically wait `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPTS * RENOVATE_X_GITLAB
Neither of those sound like common or best practice. Shouldn't we optimize for the normal way?

2025-01-27 19:22 UTC, philippe-granet commented on docs/usage/self-hosted-experimental.md
> +!!! warning Increasing this value too much penalizes projects that do not have defined pipelines, Renovate will systematically wait `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPTS * RENOVATE_X_GITLAB
For normal projects, with a pipeline/tests, before this MR, Renovate waits by default 1s before checking branch status, and most of time, it fails retrieving status because pipeline is often launched 1s after branch created.
With this MR, Renovate retry to check branch status 2 more times, which on my Gitlab On premise instance is sufficient. And on a very slow Gitlab instance, you can increase numbers of retry. I ran this MR on more than 100 projects for weeks on our Gitlab instance, and it works very well.

2025-01-27 19:36 UTC, rarkins commented on docs/usage/self-hosted-experimental.md
> +!!! warning Increasing this value too much penalizes projects that do not have defined pipelines, Renovate will systematically wait `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPTS * RENOVATE_X_GITLAB
So in your opinion this is already a reasonable compromise?

2025-01-27 20:03 UTC, philippe-granet commented on docs/usage/self-hosted-experimental.md
> +!!! warning Increasing this value too much penalizes projects that do not have defined pipelines, Renovate will systematically wait `RENOVATE_X_GITLAB_BRANCH_STATUS_CHECK_ATTEMPTS * RENOVATE_X_GITLAB
Yes, on projects with no pipelines/tests (a very bad practice), theses retries will only add 2 more seconds for each Renovate branch. For example, with 20 projects and 5 dependencies to update, it adds 20*5*2=200s , which I think is reasonable.

2025-01-28 12:00 UTC, rarkins commented on lib/modules/platform/gitlab/index.ts
> +      logger.debug(`Pipeline not yet created. Retrying ${attempt}`);
Does this print the first time "Retrying 0"?

2025-01-30 07:57 UTC, viceice commented on lib/modules/platform/gitlab/index.spec.ts
> +        )
```suggestion
        .times(3)
```

simplify 😉

2025-01-30 07:57 UTC, viceice commented on lib/modules/platform/gitlab/index.spec.ts
> +        )
```suggestion
        .times(3)
```

2025-01-30 07:57 UTC, viceice commented on lib/modules/platform/gitlab/index.spec.ts
>          .reply(200, { last_pipeline: { id: 123 } });
wait, you should not return an array if it expects an object. please fix test accordingly to return right type

2025-01-31 07:59 UTC, viceice approved these changes

2025-01-31 08:11 UTC, rarkins approved these changes

2025-01-31 08:21 UTC, merged

2025-01-31 08:37 UTC, renovate-release commented
:tada: This PR is included in version 39.148.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/39.148.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/39.148.0)
- `39.148.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: