feat(manager/pep621): add support for uv index configuration
renovatebot/renovate pull request #32771
Opened 2024-11-27 15:23 UTC by bschoenmaeckers

## Changes

Add support for `tool.uv.index` configurations and pinning dependencies to them.

## Context

fixes #32265 

- https://docs.astral.sh/uv/configuration/indexes/
- https://docs.astral.sh/uv/concepts/projects/dependencies/#index

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-27 15:58 UTC, bschoenmaeckers commented
Sorry for the CI spam, should be fixed now. So please review.

2024-11-28 06:15 UTC, rarkins requested changes

2024-11-28 06:15 UTC, rarkins commented on lib/modules/manager/pep621/processors/uv.ts
> +          /* istanbul ignore else  */
```suggestion
```

This case should be able to be tested

2024-11-28 12:17 UTC, bschoenmaeckers commented on lib/modules/manager/pep621/processors/uv.ts
> +              dep.registryUrls ?? 'https://pypi.org/pypi/',
Where is this field defined?

2024-11-28 12:23 UTC, secustor commented on lib/modules/manager/pep621/processors/uv.ts
> +              dep.registryUrls ?? 'https://pypi.org/pypi/',
In the pypi datasource

2024-11-28 12:28 UTC, rarkins commented on lib/modules/manager/pep621/processors/uv.ts
> +    const implicitIndexes = uv.index
implicitIndexUrls

2024-11-28 12:48 UTC, bschoenmaeckers commented on lib/modules/manager/pep621/processors/uv.ts
> +      (index) => index.default && !index.explicit,
It will use the first one.

ref https://github.com/astral-sh/uv/blob/main/crates/uv-distribution-types/src/index_url.rs

2024-11-28 13:24 UTC, secustor commented on lib/modules/manager/pep621/processors/uv.ts
> +              dep.registryUrls ?? 'https://pypi.org/pypi/',
Create an exporter variable instead of creating a new datasource instance, but else yes.

2024-11-29 08:42 UTC, secustor approved these changes

2024-11-29 08:49 UTC, rarkins approved these changes

2024-11-29 08:59 UTC, merged