fix(manager/pep621): remove pinned indexes from `UV_EXTRA_INDEX_URL`
renovatebot/renovate pull request #32819
Opened 2024-11-29 23:56 UTC by bschoenmaeckers

## Changes

We should not add the configured indexes from pyproject.toml again in `UV_EXTRA_INDEX_URL`. 

## Context

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [X] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-11-30 05:52 UTC, rarkins requested changes
Needs a test

2024-12-03 06:30 UTC, rarkins approved these changes

2024-12-03 21:58 UTC, secustor approved these changes

2024-12-03 22:07 UTC, merged

2024-12-03 22:24 UTC, renovate-release commented
:tada: This PR is included in version 39.48.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/39.48.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/39.48.1)
- `39.48.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: