fix(schedule): use and logic to handle dow+dom
renovatebot/renovate pull request #32903
Opened 2024-12-04 14:02 UTC by RahulGautamSingh

## Changes
Use the `legacyMode:false` option so the `Cron` job is scheduled when both DOM and DOW match and not when either matches.

## Context
- Ref: https://github.com/renovatebot/renovate/discussions/32879

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-12-05 15:15 UTC, HonkingGoose requested changes

2024-12-05 15:15 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +    `* * 1-7 * 4` this schedule will be triggered on a Thursday which falls in the first week of the month.
```suggestion
    If both the day of the week _and_ the day of the month are restricted in the schedule, then Renovate only runs when both the day of the month _and_ day of the week match!
    For example: `* * 1-7 * 4` means Renovate only runs on the _first_ Thursday of the month.
```

How about this?

2024-12-05 15:15 UTC, HonkingGoose commented on lib/workers/repository/update/branch/schedule.spec.ts
> +    describe('handles schedule with DOM and DOW using AND logic', () => {
```suggestion
    describe('handles schedule with Day Of Month and Day Of Week using AND logic', () => {
```

Expanding the abbreviation is easier to read.

2024-12-08 08:07 UTC, rarkins approved these changes

2024-12-08 08:15 UTC, merged

2024-12-08 08:29 UTC, renovate-release commented
:tada: This PR is included in version 39.57.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/39.57.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/39.57.2)
- `39.57.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: