fix(gitea): use configured endpoint in PR cache (#32825)
renovatebot/renovate pull request #33121
Opened 2024-12-15 13:37 UTC by javiertury

## Changes

Ensure that gitea PR cache uses the endpoint configured by the user

## Context

As detailed in issue https://github.com/renovatebot/renovate/discussions/32825, renovate paginates using the url returned by gitea, which may change the endpoint. This causes authentication failures since tokens are not attached to the request or a network error if the returned url is not accesible from within the network. Also a gitea instance configured with a `http` public url would remove transport encryption even if renovate was configured with a `https` endpoint.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-12-15 17:12 UTC, viceice requested changes
implement `RENOVATE_X_REBASE_PAGINATION_LINKS` like GitHub 

https://github.com/renovatebot/renovate/blob/d0c0aa7333b0c00582dfc8cc2dbebe7e4f80d0e7/lib/util/http/github.ts#L338

2024-12-15 17:29 UTC, javiertury commented
What is the advantage of `RENOVATE_X_REBASE_PAGINATION_LINKS` over the proposed solution? We can address the root of the problem if we eliminate the need to rebase in the first place.

According to gitea docs, the [pulls endpoint](https://demo.gitea.com/api/swagger#/repository/repoListPullRequests) works with limit-offset pagination and `next.url` just increases the page counter so both methods are equivalent. It is not the case that `next.url` uses stateless cursor pagination or something more performant, and even if it was the case my guess is that gitea would provide a well-designed API such that we can pass the cursor through query parameters.

2024-12-15 20:54 UTC, viceice commented
we did the decision some time ago, there where more discussions about it. so please do it like we suggest.

2024-12-17 08:52 UTC, viceice commented
- #26876

2025-02-04 20:39 UTC, closed without merging

2025-02-04 20:55 UTC, renovate-release commented
:tada: This PR is included in version 39.160.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/39.160.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/39.160.1)
- `39.160.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: