feat(config/toml) Support jinja templates in toml files
renovatebot/renovate pull request #33123
Opened 2024-12-15 15:51 UTC by jiaweikho

## Changes

- Massage toml content before parsing by removing jinja delimiters according to the specification: [jinja](https://jinja.palletsprojects.com/en/stable/templates/#synopsis)
- Add `removeTemplate` option to the `parseToml` function
- Add `removeTemplate: true` config to `poetry` and `pep621` `pyproject.toml` parsers.

## Context

This addresses the feature request raised in https://github.com/renovatebot/renovate/discussions/33105 by applying a similar method in the `yaml` parser in https://github.com/renovatebot/renovate/pull/26682.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-12-15 17:06 UTC, viceice commented on lib/util/toml.ts
> +interface TomlOptions {
```suggestion
export interface TomlOptions {
```

2024-12-15 17:06 UTC, viceice commented on lib/util/toml.ts
> +      .replace(regEx(/{#.+?#}/gs), '');
```suggestion
      .replaceAll(regEx(/{%.+?%}/s), '')
      .replaceAll(regEx(/{{.+?}}/s), '')
      .replaceAll(regEx(/{#.+?#}/s), '');
```

2024-12-15 17:51 UTC, jiaweikho commented
@viceice thanks for the review. I haven't documented this new functionality yet. Do you think I should add a note in the [poetry](https://docs.renovatebot.com/modules/manager/poetry/)/[pep621](https://docs.renovatebot.com/modules/manager/pep621/) docs about jinja templates?

2024-12-16 10:46 UTC, jiaweikho commented
@viceice I've added tests for the `pep621` and `poetry` managers based on the CI coverage feedback. I've tried my best to follow the precedent but the style of `extract.spec.ts` in `pep621` and `poetry` are quite different so you may notice some style differences between them.

2024-12-17 06:04 UTC, rarkins requested changes
Please inline the fixtures as part of the tests

2024-12-23 12:13 UTC, jiaweikho commented
Hi @viceice @rarkins, is there anything else you would like me to do before this PR can be merged?

2024-12-23 12:17 UTC, viceice reviewed
we're currently not merging features because all maintainer are in Christmas holiday and we don't want to break anything now.

2024-12-23 12:27 UTC, jiaweikho commented
> we're currently not merging features because all maintainer are in Christmas holiday and we don't want to break anything now.

Thanks for letting me know. Have a wonderful holiday!

2025-01-15 17:12 UTC, sigma67 commented
Is this still being considered? Seems it got lost over New Year's

2025-01-17 21:34 UTC, jiaweikho commented
@viceice could you please have another look at this and let me know if I can help in any way.

2025-01-31 09:01 UTC, viceice commented on lib/util/schema-utils.ts
> +    return parseToml(str, { removeTemplates: true });
I don't like to do this by default. @zharinov how to best handle such options 🤔 

Maybe we should export a `toml` function which allows to pass parder options? would this help for yaml on gitlab too?

2025-02-24 08:34 UTC, sigma67 commented
How can we proceed here? Is this waiting for response from @zharinov ?

2025-02-24 20:13 UTC, zharinov commented on lib/util/schema-utils.ts
> +    return parseToml(str, { removeTemplates: true });
I think it isn't necessary to couple with TOML parsing.

Let's use `stripTemplates(parseToml(...))` or `StripTemplates.pipe(Toml).pipe(z.object(...))` instead.

2025-02-24 22:19 UTC, zharinov commented on lib/util/schema-utils.ts
> +    return parseToml(str, { removeTemplates: true });
Yes, these transforms could lead to errors that are hard to detect.
Let's keep it localized to the Python ecosystem:
- https://github.com/renovatebot/renovate/pull/34447

2025-02-25 11:26 UTC, zharinov commented
- Superseded by #34447

2025-02-25 13:08 UTC, sigma67 commented
@zharinov I tried latest renovate with our pyproject.toml.jinja file, but unfortunately it still fails

```json
{
    "err":
    {
        "column": 1,
        "index": 709,
        "lineNumber": 39,
        "message": "Unexpected token",
        "stack": "SyntaxError: Unexpected token
		    at Context.reportParseError (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/toml-eslint-parser/lib/toml-parser/context.js:114:15)
		    at TOMLParser.TABLE (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/toml-eslint-parser/lib/toml-parser/index.js:107:20)
		    at TOMLParser.parse (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/toml-eslint-parser/lib/toml-parser/index.js:77:51)
		    at parseForESLint (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/toml-eslint-parser/lib/parser.js:11:24)
		    at parseTOML (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/toml-eslint-parser/lib/index.js:46:40)
		    at parse (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/util/toml.ts:4:24)
		    at parsePyProject (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/modules/manager/pep621/utils.ts:140:30)
		    at Object.extractPackageFile (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/modules/manager/pep621/extract.ts:25:29)
		    at extractPackageFile (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/modules/manager/index.ts:75:9)
		    at getManagerPackageFiles (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:58:43)
		    at /opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/workers/repository/extract/index.ts:57:28
		    at async Promise.all (index 3)
		    at extractAllDependencies (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/workers/repository/extract/index.ts:54:26)
		    at extract (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/workers/repository/process/extract-update.ts:160:28)
		    at extractDependencies (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/workers/repository/process/index.ts:158:26)
		    at Object.renovateRepository (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/workers/repository/index.ts:71:9)
		    at attributes.repository (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/workers/global/index.ts:206:11)
		    at start (/opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/workers/global/index.ts:191:7)
		    at /opt/containerbase/tools/renovate/39.180.2/22.11.0/node_modules/renovate/lib/renovate.ts:19:22"
    },
    "hostname": "runner-cqva6w8oe-project-1694-concurrent-0",
    "level": 20,
    "logContext": "XBuHFJk1JOOxotnc2vNXs",
    "msg": "Failed to parse and validate pyproject file",
    "name": "renovate",
    "packageFile": "templates/pyproject.toml.jinja",
    "pid": 17,
    "repository": "pes/common/pes-python-module-template",
    "time": "2025-02-25T12:58:37.776Z",
    "v": 0
}
```

this is the file

```toml
[project]
name = "{{ distribution_pkg_name }}"
dynamic = ["version"]
description = "{{ module_short_description }}"
readme = "README.md"
keywords = [
    "python",
    "module"
]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
maintainers = [
    {name = "{{ author_first_name }} {{ author_surname }}", email = "{{ author_mail }}"},
]
authors = [
    {name = "{{ author_first_name }} {{ author_surname }}", email = "{{ author_mail }}"},
]
license = {file = "LICENSE"}

dependencies = [
    "vector-logger>=3.0.0",
    {%- if is_application %}
    "click>=8.1.7",
    {%- endif %}
]
requires-python = ">=3.10"

[project.urls]
Repository = "{{ gitlab_url }}"
{%- if is_application %}

[project.scripts]
{{ distribution_pkg_name }} = "{{ import_pkg_name }}.__main__:cli"
{%- endif %}

[build-system]
requires = ["pdm-backend==2.3.3", "pdm-build-locked==0.3.2"]
build-backend = "pdm.backend"


#########
# TOOLS #
#########

[tool.pdm.version]
source = "scm"

[tool.pdm]
plugins = [
    "pdm-build-locked"
]

[tool.pdm.build]
package-dir = "src"
excludes = ["tests/_temp"]
{%- if is_application %}
locked = true
{%- endif %}
```

2025-03-03 20:30 UTC, sigma67 commented
Fixed with 39.185.6

2025-03-04 06:09 UTC, closed without merging