feat(bun): Add support for updating text-format lockfile when package.json changes
renovatebot/renovate pull request #33189
Opened 2024-12-18 12:44 UTC by nathankleyn

## Changes

Bun 1.2.x will introduce and switch by default to a text-format verison of the lockfile. Where currently they use a binary version named `bun.lockb`, this will become `bun.lock` and be plaintext:

https://bun.sh/blog/bun-lock-text-lockfile

This can be switched on by default in-advance since Bun 1.1.40 and so will appear in the wild as of now:

https://bun.sh/blog/bun-v1.1.40#new-install-savetextlockfile-in-bunfig-toml

This commit adds support for both lockfile formats by supporting by file-suffixes.

## Context

As of Bun 1.1.40, this feature can be opted-in and Renovate no longer works for Bun without it.

As of Bun 1.2.x this feature will be on by default.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

The docs that would be affected are auto-generated ones

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

Tested and run on https://github.com/nathankleyn/bun-renovate-text-lockfile-test, where you can see a PR at which correctly detected and changed the new-style lockfile: https://github.com/nathankleyn/bun-renovate-text-lockfile-test/pull/2

2024-12-18 12:49 UTC, rarkins requested changes
Needs testing on a real repo with text lockfile format

2024-12-18 12:49 UTC, rarkins commented on lib/modules/manager/bun/index.ts
> +  fileMatch: ['(^|/)bun\\.lockb$', '(^|/)bun\\.lock$'],
```suggestion
  fileMatch: ['(^|/)bun\\.lockb?$'],
```

2024-12-18 14:22 UTC, nathankleyn commented
@rarkins Thanks so much for super-fast review — I've made that fix to simplify the regex, and I've created a public repository where I've run Renovate with the changes at https://github.com/nathankleyn/bun-renovate-text-lockfile-test — you can see a PR at which correctly detected and changed the new-style lockfile: https://github.com/nathankleyn/bun-renovate-text-lockfile-test/pull/2

2024-12-18 14:23 UTC, rarkins approved these changes, later dismissed

2024-12-18 14:25 UTC, rarkins commented
@nathankleyn thanks for your PR! I'm surprised/delighted to discover that this started working with very little logic change.

2024-12-18 14:26 UTC, rarkins approved these changes

2024-12-18 14:48 UTC, merged

2024-12-18 15:05 UTC, renovate-release commented
:tada: This PR is included in version 39.74.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/39.74.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/39.74.0)
- `39.74.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-07 13:49 UTC, glensc commented
`verison` typo in pr body