feat(versioning): aws-eks-addon versioning added
renovatebot/renovate pull request #33301
Opened 2024-12-27 10:21 UTC by ivankatliarchuk

## Changes

Added aws-eks-addon versioning

## Context

- relates https://github.com/renovatebot/renovate/pull/33272

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2025-01-02 17:08 UTC, viceice requested changes

2025-01-02 17:08 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/index.ts
> +    const parsed2: GenericVersion | null = this._parse(current);
```suggestion
    const parsed1 = this._parse(version);
    const parsed2 = this._parse(current);
```

2025-01-02 17:08 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/index.ts
> +    const matches: RegExpExecArray | null = versionPattern.exec(version);
```suggestion
    const matches = versionPattern.exec(version);
```

2025-01-02 17:08 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/index.ts
> +  '^[vV]?(\\d+(?:\\.\\d+)*)(?<metadata>-eksbuild\\.\\d+)?$',
```suggestion
  '^v?(\\d+(?:\\.\\d+)*)(?<metadata>-eksbuild\\.\\d+)?$',
```

why support upper case `V` ? This regex is also too loose. you should use `semver` module to parse instead of regex. at least add matching named capture groups like for regex versioning.

2025-01-02 21:43 UTC, ivankatliarchuk commented on lib/modules/versioning/aws-eks-addon/index.ts
> +  '^[vV]?(\\d+(?:\\.\\d+)*)(?<metadata>-eksbuild\\.\\d+)?$',
Updated regex to capture all groups. 

And I have tried I have tried to `semver-coreced`, as this is the closest versioning.

```js
import { api as semverCoerced } from '../semver-coerced';

and did something like 

export const api: VersioningApi = {
  ...semverCoerced,
  isValid,
  isVersion,
  isCompatible,
  isGreaterThan
};

function isValid(input: string): boolean {
  if (semverCoerced.isValid(input)) {
    if (input.includes('-eksbuild.')) {
      return true;
    }
    return false;
  } else {
    return false;
  }
}

function isVersion(version: string): boolean {
  return isValid(version);
}

function isCompatible(version: string, current: string): boolean {
  return isVersion(version) && isVersion(current);
}

function isGreaterThan(version: string, other: string): boolean {
   // needs override
  return needs override;
}
```

The issue with this approach, it constantly require direct methods override. 

I have no preference, please suggest best practice and I follow.

2025-01-08 12:06 UTC, rarkins submitted a review, later dismissed

2025-01-17 14:35 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/index.ts
> +    const release = [Number(major), Number(minor), Number(patch)];
```suggestion
    const release = [parseInt((major, 19), parseInt(minor, 10), parseInt(patch, 10)];
```

2025-01-17 14:35 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/readme.md
> +At the moment every ESK Addon that matches the regex `^[vV]?(\d+(?:\.\d+)*)(-eksbuild\.\d+)?$` is considered a valid "release".
```suggestion
At the moment every ESK Addon that matches the regex `^[v]?(\d+(?:\.\d+)*)(-eksbuild\.\d+)?$` is considered a valid "release".
```

2025-01-17 14:35 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/index.ts
> +export class AwsEKSAddonVersioningApi extends GenericVersioningApi {
Consider using `RegExpVersioningApi` as base class, it would simplifify things

https://github.com/renovatebot/renovate/blob/abe61227b6c7f57cc49a79cd821a55e7f1e5556c/lib/modules/versioning/hermit/index.ts#L13-L21

2025-01-17 18:05 UTC, ivankatliarchuk commented on lib/modules/versioning/aws-eks-addon/index.ts
> +export class AwsEKSAddonVersioningApi extends GenericVersioningApi {
Gotcha. Looks like code simplified.

2025-01-22 11:40 UTC, ivankatliarchuk commented
Hi @viceice . Would you be able to guide me what next if changes ok now?

2025-01-22 19:06 UTC, viceice commented
will try to review tomorrow

2025-01-24 11:54 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/index.ts
> +    '^v?(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(?<prerelease>-eksbuild\\.\\d+)$';
```suggestion
    '^v?(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(?<compatibility>-eksbuild\\.)(?<build>\\d+)$';
```

`prerelease` would force all versions to be unstable, so we use forth version part instead

https://github.com/renovatebot/renovate/blob/68ce0ed2ad7068a7214bf3a5edf81f54701a75e7/lib/modules/versioning/generic.ts#L87-L90

2025-01-24 11:55 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/index.spec.ts
> +      ${'v1.11.7-eksbuild.1'} | ${'v1.11.7-eksbuild.0'} | ${true}
```suggestion
      ${'v1.11.7-eksbuild.1'} | ${'v1.11.7-eksbuild.0'} | ${true}
      ${'v1.11.7-eksbuild.11'} | ${'v1.11.7-eksbuild.1'} | ${true}
```

2025-01-30 08:21 UTC, viceice reviewed
otherwise lgtm

2025-01-30 08:21 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/index.ts
> +
```suggestion
```

no need to export empty urls, they are optional.

2025-01-30 08:23 UTC, viceice commented on lib/modules/versioning/aws-eks-addon/readme.md
> +At the moment every ESK Addon that matches the regex `^[v]?(\d+(?:\.\d+)*)(-eksbuild\.\d+)$` is considered a valid "release".
```suggestion
At the moment every ESK Addon that matches the regex `^v?\d+\.\d+\.\d+-eksbuild\.\d+$` is considered a valid "release".
```

2025-01-30 08:24 UTC, viceice approved these changes, later dismissed

2025-01-30 18:32 UTC, ivankatliarchuk commented
I tried different tricks, url is required, either need to be exported, defined or test relaxed. I might be missing some obvious things from the framework.

Shell I
```
export * from  '../regex';
```

or put back

```
export const url = []
```

![Screenshot 2025-01-30 at 17 51 56](https://github.com/user-attachments/assets/2b44e49e-acc9-4d09-adf9-23af2c7a16ef)
![Screenshot 2025-01-30 at 18 06 29](https://github.com/user-attachments/assets/f2f01beb-0ed4-4e07-b786-b8d30b85c74e)
![Screenshot 2025-01-30 at 18 10 26](https://github.com/user-attachments/assets/dafcc17d-432e-4db5-90d8-2530a49045dc)

2025-01-30 18:37 UTC, ivankatliarchuk commented
I've added back in for now `export const urls = []`

My understanding, at this time  the urls constant is not automatically exported if we export RegExpVersioningApi. And we need to explicitly export urls if we want it to be available outside the module, as it's currently mandatory attribute.

![Screenshot 2025-01-30 at 18 35 22](https://github.com/user-attachments/assets/bf67555d-aedc-4f49-8e00-869f48380618)

2025-01-30 18:47 UTC, ivankatliarchuk commented on lib/modules/versioning/aws-eks-addon/index.ts
> +
Added back. Explained below

2025-01-30 22:40 UTC, viceice approved these changes
thanks, sorry for the confusion. thd interface marks it as optional but the test  makes it required. will fix the interface or test soon.

2025-01-31 08:06 UTC, viceice commented
> thanks, sorry for the confusion. thd interface marks it as optional but the test makes it required. will fix the interface or test soon.

- #33958

2025-01-31 08:06 UTC, viceice approved these changes

2025-01-31 08:15 UTC, merged

2025-01-31 08:37 UTC, renovate-release commented
:tada: This PR is included in version 39.148.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/39.148.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate/v/39.148.0)
- `39.148.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: