Auto merge failure comment
renovatebot/renovate pull request #33337
Opened 2024-12-30 14:19 UTC by wSimsT

## Changes

This PR intends to implement a PR Comment in case automerge fails, letting the users know that the automerge has failed and that they need to attend to this issue.

## Context
 This PR is based off of issue 31869 "Add PR comment if automerge attempt fails".
 - #31869 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2024-12-30 14:38 UTC, rarkins requested changes

2024-12-30 14:38 UTC, rarkins commented on lib/config/options/index.ts
> +    default: 'never',
Set allowedValues

2024-12-30 14:38 UTC, rarkins commented on lib/config/types.ts
> +  autoMergeFailureComment?: string;
Use an enum type

2024-12-30 14:38 UTC, rarkins commented on lib/modules/platform/github/index.ts
> +      if (platformPrOptions.automergeFailureComment === 'on-error') {
Wrong file for implementation. This only works for GitHub, and even then only for GitHub- active automerge.

2024-12-30 14:38 UTC, rarkins commented on test/documentation.spec.ts
Unrelated changes

2025-01-20 08:27 UTC, viceice commented on lib/config/types.ts
> +  autoMergeFailureComment?: string;
```suggestion
  autoMergeFailureComment?: 'on-error' | 'never';
```
like this

2025-01-20 08:46 UTC, rarkins commented
Needs design discussion first

2025-01-20 08:46 UTC, closed without merging