feat(dart): Add support for Dart
renovatebot/renovate pull request #3468
Opened 2019-03-31 22:31 UTC by zharinov

It works for most of Dart pubfiles (except invalid YAML). Later maybe we should implement own "weaker" parser.

Closes #3301

2019-03-31 22:38 UTC, zharinov commented
@rarkins Please take a look at snapshots mismatch, not sure if I can update it right

2019-04-02 15:30 UTC, rarkins requested changes

2019-04-02 15:30 UTC, rarkins commented on lib/manager/pub/index.js
> +  } catch (e) {
Let's log here

2019-04-02 15:30 UTC, rarkins commented on lib/manager/pub/index.js
> +async function extractAllPackageFiles(config, packageFiles) {
I don't think we need this function - it should function without it

2019-04-02 15:32 UTC, rarkins commented
@zharinov snapshots updated/tests passing

Can you describe more about your update algorithm? Is it based on any of our existing managers, or something new?

2019-04-02 15:42 UTC, zharinov commented
I assume it uses npm algorithm since we're using its `versionSchema`

2019-04-02 15:44 UTC, rarkins commented
I meant your approach to iterating line by line and the various logic inside the for loop. I'm not sure we've done it that way before and how much testing it needs

2019-04-02 16:11 UTC, zharinov commented
> I meant your approach to iterating line by line and the various logic inside the for loop. I'm not sure we've done it that way before and how much testing it needs
> 
Yaml parser doesn’t support metadata, so i’ve done this ad-hoc way. At the other hand, parse-update-dump cycle produces lots of garbage in diffs. As I can see, some other yaml-based managers doing this too, though format differs.

2019-04-02 18:18 UTC, rarkins commented
Can you explain the metadata problem more?

2019-04-02 18:22 UTC, zharinov commented
Line and column numbers of parsed pubspec files can't collected by the library. For example, in maven we use `fileReplacePosition` field for this stuff, so it can be updated relatively easy.

2019-04-15 11:44 UTC, rarkins commented
@zharinov is this ready for merge, in your opinion?

2019-04-15 11:47 UTC, zharinov commented
I think yes, at least just to gather more feedback

2019-04-15 13:07 UTC, merged