feat: Add JSON5 parser (WIP)
renovatebot/renovate pull request #3555
Opened 2019-04-17 03:13 UTC by hassan23

Added support for `renovate.json5` filename. Now configuration can be parsed from a `json5` format file.

Closes #3484

2019-04-17 04:31 UTC, rarkins commented on yarn.lock
> -  integrity sha512-OfC2uemaknXr87bdLUkWog7nYuliM9Ij5HUcajsVcMCpQrcLmtxRbVFTIqmcSkSeYRBFBRxs2FiUqFJDLdiebA==
You are running with an old Yarn version

2019-04-17 04:32 UTC, rarkins commented on package.json
> +    "json5": "^2.1.0",
Exact versions only

2019-04-18 07:40 UTC, rarkins commented
@hassan23 ideally I'd like to reduce the diff size for changes like this, to make tracing code history easier later. But if that results in too much technical debt, the current approach is OK.

2019-04-18 07:40 UTC, rarkins commented
@hassan23 please confirm once you have tested using a json5 in a real repository too.

2019-04-18 07:40 UTC, rarkins requested changes

2019-04-18 07:40 UTC, rarkins commented on lib/workers/repository/init/config.js
> +    if (fileType !== '.json5') {
As a best practice, it's better to not use a negation in an if/else statement. i.e. write:

```
if (foo === bar) {
  // do something if true
} else {
  // do something if not true
}
```

And more confusing to write:
```
if (foo !== bar) {
  // do something if not true
} else {
  // do something if true
}
```

2019-04-19 02:36 UTC, hassan23 commented
@rarkins 
Added and checked JSON5 format on three repositories with the default configuration from local
- Test repo
- My real project repo
- Forked Repo

#### Process

- Add a `renovate.json5` with default config(for forked repo include `"includeForks": true`)
- Run `yarn start username/repo`

Received the **Pin dependency PR** and **dependency update PR** in the same way as we received from `renovate.json`

2019-04-19 05:19 UTC, hassan23 commented
> @hassan23 please confirm once you have tested using a json5 in a real repository too.

@rarkins please review

2019-04-19 06:39 UTC, merged

2019-12-05 21:08 UTC, felixfbecker commented
Can I use JSON5 for shared presets on GitHub too?

2019-12-05 22:10 UTC, rarkins commented
> Can I use JSON5 for shared presets on GitHub too?

No, but please add a feature request if you'd like it.