[WIP] feat: Add prcreation == approval
renovatebot/renovate pull request #4032
Opened 2019-07-09 02:15 UTC by praveshtora

* In pr worker checking for ` config.prCreation === 'approval' && !existingPr && masterIssueCheck !== 'approvePr'` and if true, flagging the branch.
* After this masterIssueApproval flag will create list of branches that have not been created yet while prCreation== approval will create list of branches which have been created but not raised a PR.
* The master issue looks something like this:

![Screenshot from 2019-07-09 07-42-53](https://user-images.githubusercontent.com/20622998/60854261-33e66800-a21d-11e9-9ff2-001e8d9a860e.png)

Closes #3928

2019-07-09 07:05 UTC, rarkins commented
We’ll need to rename/rephrase the master issue descriptions as we now have the possibility of both branch approval and PR approval as shown in your screenshot. I’ll work on those last

2019-07-09 12:44 UTC, praveshtora commented
@rarkins I have tested it manually, by setting masterIssueApproval=true and prCreation=approval. After that when I checked a branch in master Issue approval, I can see branches being created and no PRs of that branch and the branch can be seen in the PR approval section. Any other particular test case do I need to look into?

2019-07-09 13:00 UTC, rarkins commented
That sounds like a good start. When you tick the branch approval, does it open up the PR or stop at the branch? I would guess it creates the PR too (ie skips PR approval step)

2019-07-09 13:52 UTC, praveshtora commented
It stops at the branch. There is no PR. I am handling it in PR worker.

2019-07-09 13:54 UTC, rarkins commented
I would have expected that the PR worker thinks it's approved in master issue and goes ahead. How does it differentiate between a branch approval tick and a PR approval tick?

2019-07-09 15:50 UTC, praveshtora commented
It differentiates by the ``type``. In PR approval tick, the type is `approvePr` while in branch approval it just `approve`. While parsing the `issue` body, we use regex to get the type and then in pr worker I am matching it with this type to ensure PR.

2019-07-09 16:01 UTC, rarkins commented
Oh, great. I guess I forgot that code :D

2019-07-09 16:25 UTC, praveshtora commented
Are there any edge cases that I need to consider?

2019-07-09 17:03 UTC, rarkins commented
Looks good to me for now. I’ll test and try to think of any edge cases before merging.

2019-07-10 12:26 UTC, rarkins commented
@praveshtora I've tested it and made some edits to your branch. Can you update tests to get it passing on CI?

2019-07-11 08:13 UTC, rarkins commented on lib/workers/pr/index.js
> +    return 'needs-approval';
Let's make this 'needs-pr-approval' instead of 'needs-approval' from the very start so that we don't have to remap it.

2019-07-11 08:14 UTC, rarkins requested changes
Rename 'needs-approval' to 'needs-pr-approval', and update or remove screenshot in PR description as it's currently old/incorrect.

2019-07-11 11:48 UTC, merged