Add the ability to handle pip's --extra-index-url
renovatebot/renovate pull request #4056
Opened 2019-07-12 08:30 UTC by RmStorm

As specified in the docs here:
https://pip.pypa.io/en/stable/reference/pip_wheel/#extra-index-url
it's possible to define more index-urls in a single package by using
--extra-index-url this was not correctly handled by renovatebot.

Makes renovatebot correctly recognize --extra-index-url in pip requirements.txt files.

Closes #4035

2019-07-12 08:41 UTC, rarkins commented
@RmStorm thanks for the PR!

Can you verify that the following use case is handled?
- `--index-url` is *not* specified
- One or more `--extra-index-url` is specified

Based on previous discussions, I was under the impression that the default `pypi` registry should be tried first in such situation, but I think it will be missing from `registryUrls` in the current approach.

2019-07-12 08:49 UTC, RmStorm commented
> @RmStorm thanks for the PR!
> 
> Can you verify that the following use case is handled?
> 
>     * `--index-url` is _not_ specified
> 
>     * One or more `--extra-index-url` is specified
> 
> 
> Based on previous discussions, I was under the impression that the default `pypi` registry should be tried first in such situation, but I think it will be missing from `registryUrls` in the current approach.

Hi, so in the case that there is no --index-url specified do you think it would be best to simply add 'https://pypi.org/pypi/' to registryUrls in addition to the extra index? Or should it try to fetch the default that is specified in renovatebots configuration?

I'm not sure what the best approach is. I think adding pypi makes sense. But that is overwritable in pip config ourisde of repositories if I'm correct. I guess in that case people would to like to get the default and the --extra-index-url but I'm not sure if that's how it works.

2019-07-12 08:51 UTC, rarkins commented
I'm not an expert on it but that was the conclusion we reached here: https://github.com/renovatebot/renovate/issues/4035#issuecomment-509670014

2019-07-12 08:51 UTC, rarkins commented
i.e. if index-url is unspecified but extra-index-url is, then the user expects that the default pypi index is still used.

2019-07-12 08:58 UTC, RmStorm commented
Hmm, so am I correct in thinking that if a default repo is supplied to renovatebot in someway it is stored in process.env.PIP_INDEX_URL? Because in that case --index-url is currently ignored anyways in the case a different default is supplied [or so it seems](https://github.com/renovatebot/renovate/blob/cfaa33423660a5e4f7880933078c22513af94bc7/lib/datasource/pypi/index.js#L35)?

Can you explain me how an overwritten default is handled/passed by renovatebot? I am obviously unfamiliar with the codebase, sorry for that.

2019-07-12 09:06 UTC, rarkins commented
`process.env.PIP_INDEX_URL` is only relevant to self-hosted users. It's not used in the app.

2019-07-12 09:06 UTC, rarkins commented
In the app you need to configure via `registryUrls` using `packageRules`

2019-07-12 09:09 UTC, RmStorm commented
> In the app you need to configure via `registryUrls` using `packageRules`

Hmm, ok. But how is it used in the code? I assume after it's configured it should show up in [this function](https://github.com/renovatebot/renovate/blob/cfaa33423660a5e4f7880933078c22513af94bc7/lib/datasource/pypi/index.js#L30) somehow and overwrite the default [host_url here](https://github.com/renovatebot/renovate/blob/cfaa33423660a5e4f7880933078c22513af94bc7/lib/datasource/pypi/index.js#L31) right?

2019-07-12 09:41 UTC, RmStorm commented
I'm having a lot of trouble figuring out where the `registryUrls` created in [this function](https://github.com/renovatebot/renovate/blob/3d04c696fba297da91d860153f0c3b178c129fee/lib/manager/pip_requirements/extract.js#L19) is combined with the `registryUrls` defined in the config [here](https://github.com/renovatebot/renovate/blob/3d04c696fba297da91d860153f0c3b178c129fee/lib/config/definitions.js#L412).

Is it combined? or does one simply take precedence at some point before `registryUrls` is used [here](https://github.com/renovatebot/renovate/blob/cfaa33423660a5e4f7880933078c22513af94bc7/lib/datasource/pypi/index.js#L30)? I don't think I can spend a lot more time on this but I would really like to wrap this up.

2019-07-12 10:03 UTC, rarkins commented
They’re empty by default. If left empty then the pypi datasource will use the public pypi only. 

If custom URLs are to be used then they need to all be specified in registryUrls. If no custom URLs are necessary then it’s recommended not to set them during the extract function.

2019-07-12 10:05 UTC, rarkins commented
in that pypi datasource any non empty array takes precedence over the default registry.

2019-07-12 10:07 UTC, rarkins commented
In short: it needs to follow the logic mentioned in the issue this Pr is closing. Needs awareness of whether index-url is set or not

2019-07-12 11:33 UTC, RmStorm commented
> In short: it needs to follow the logic mentioned in the issue this Pr is closing. Needs awareness of whether index-url is set or not

Yes I understand. The issue was that it was quite difficult to figure out how to combine the registryUrls from the config with the new ones from the pip requirement file. Turns out that config is being passed into the extractPackageFile function. It was just not explicitly accepted in the case of the pip_requirements manager. I think it should be pretty good now. Let me know if something else needs to be changed before we can get this in.

2019-07-12 11:53 UTC, rarkins commented
Thanks, looks good to the eye. I’ll merge once I’ve done some manual testing

2019-07-13 05:55 UTC, rarkins requested changes
Pypi registries are checked sequentially in the order defined, so the "index url" needs to always be first:
- index-url should be put before extra-index-url in `registryUrls` even if they are not ordered that way in the requirements.txt (can that happen?)
- If no index url specified then the default URL should be put to the front of the array, not back

2019-07-13 05:55 UTC, rarkins commented on lib/manager/pip_requirements/extract.js
> +      registryUrls.push(...config.registryUrls);
```suggestion
      registryUrls.unshift(...config.registryUrls);
```

2019-07-13 05:55 UTC, rarkins commented on lib/manager/pip_requirements/extract.js
> +      registryUrls.push('https://pypi.org/pypi/');
```suggestion
      registryUrls.unshift('https://pypi.org/pypi/');
```

2019-07-13 05:55 UTC, rarkins commented on lib/manager/pip_requirements/extract.js
> +      registryUrls.push(registryUrl);
index-url should always be first in the array before extra-index-url. Do we need to worry about the case where the ordering is reversed in `requirements.txt`?

2019-07-15 20:36 UTC, merged