feat:Open new issue for invalid config
renovatebot/renovate pull request #4101
Opened 2019-07-16 15:29 UTC by praveshtora

Closes #4036

2019-07-17 07:20 UTC, rarkins requested changes

2019-07-17 07:20 UTC, rarkins commented on lib/platform/github/index.ts
> +  recreate = false
Maybe we should call this "reopen" instead of "recreate"? And default to `true` for `reopen` to match existing behaviour.

2019-07-17 07:20 UTC, rarkins commented on lib/workers/repository/error-config.js
> +      true
Let's define these as variables `once` and `reopen` before passing them into `ensureIssue`. That way it's more understandable.

2019-07-25 02:54 UTC, praveshtora commented
@rarkins I have made the required changes. Please review.

2019-07-25 05:48 UTC, rarkins commented
Thanks @praveshtora 

I'm still wondering how to handle this. In theory it's probably best for many to open a new issue to "get their attention", as requested in #4036. However in practice, we still get "false positives" quite often and I sleep better knowing that Renovate isn't creating a huge number of new issues.

Could you add a new config option "configWarningReuseIssue" defaulting to `true`? If true, config warnings will reopen any existing issue, while if set to false then a new issue will be opened each time. I think we can later deprecate this issue once we feel config warnings have stabilized.

2019-08-05 14:33 UTC, praveshtora commented
@rarkins Apologies for late work. I have made the suggested changes. Please review.

2019-08-15 05:41 UTC, merged