feat: Recognize branch-prefix while onboarding
renovatebot/renovate pull request #4302
Opened 2019-08-17 01:21 UTC by rakeshtembhurne

By default, onboarding creates a branch with the name `renovate/configure`.
With `--branch-prefix` CLI option or with `branchPrefix` configuration,
its onboarding branch can be prefixed with the text passed instead of
default `renovate/` prefix.

Closes: #3443

2019-08-19 13:22 UTC, rarkins commented
@rakeshtembhurne have you tested this against a live repository? e.g.

- Onboarding PR is raised with custom branch
- If onboarding PR is closed unmerged then Renovate doesn't create a new one to replace it

2019-08-19 20:43 UTC, rakeshtembhurne commented
> @rakeshtembhurne have you tested this against a live repository? e.g.
> 
> * Onboarding PR is raised with custom branch
Yes, I have tested that the onboarding PR is raised with the custom branch.
> * If onboarding PR is closed unmerged then Renovate doesn't create a new one to replace it
Yes, I tested with closed unmerged branch ass well. It does not create a new one to replace it.

2019-08-20 04:00 UTC, rarkins requested changes
Set `config.onboardingBranch` as part of the `checkOnboardingBranch` function, instead of adding the new `getOnboardingBranch` function.

2019-08-20 04:04 UTC, rakeshtembhurne commented on lib/workers/repository/onboarding/branch/index.js
> +  return onboardingBranch;
Okay, will make the changes.

2019-08-20 04:05 UTC, rakeshtembhurne commented on lib/workers/repository/init/index.js
> +  config.onboardingBranch = getOnboardingBranch(config);
It can be done from inside as well. Will make the changes.

2019-08-24 06:46 UTC, rakeshtembhurne commented on lib/workers/repository/init/index.js
> +  config.onboardingBranch = getOnboardingBranch(config);
The changes have been made.

2019-08-24 06:47 UTC, rakeshtembhurne commented on lib/workers/repository/onboarding/branch/index.js
> +  return onboardingBranch;
Changes have been made.

2019-08-28 08:21 UTC, rarkins commented
This still needs testing. The first scenario I tried (open an onboarding PR, close it, then run Renovate again) did not work - Renovate recreated the onboarding PR. I have fixed this, but there are still other scenarios to test, e.g. rebasing.

2019-08-29 08:38 UTC, rarkins commented
@martyganz are you able to test if this PR behaves as you'd expect?

2019-10-18 13:25 UTC, rarkins commented
Someone else will need to resume this later if they have a need for it

2019-10-18 13:25 UTC, closed without merging