feat: Improve GraphQL fetch strategy in Github platform
renovatebot/renovate pull request #4397
Opened 2019-08-28 10:31 UTC by zharinov

Closes #3826

2019-09-08 13:59 UTC, viceice requested changes

2019-09-08 13:59 UTC, ViceIce commented on lib/platform/github/index.ts
> +const Graphql = require('./gh-graphql-wrapper').default;
```suggestion
import Graphql from './gh-graphql-wrapper';
```

2019-09-08 13:59 UTC, ViceIce commented on lib/platform/github/gh-graphql-wrapper.ts
> +  async get(cursor = ''): Promise<any> {
Please add proper typings (extract type or interface) instead of any

2019-09-08 13:59 UTC, ViceIce commented on lib/platform/github/gh-graphql-wrapper.ts
> +  async getAll(): Promise<any> {
typings, see above

2019-09-08 13:59 UTC, ViceIce commented on lib/platform/github/index.ts
> +    gql.setRepoOwner(config.repositoryOwner);
Idea: use chainable setter functions (they return this), then the code looks much cleaner

2019-09-08 14:00 UTC, ViceIce commented
does this pr replace #3831?

2019-09-08 14:02 UTC, zharinov commented
Hi @ViceIce, thank for your code review. 
Yes, I planned to replace it, but now thinking about little bit more rework of this code.

2019-10-18 13:27 UTC, rarkins commented
@zharinov what's the next step here?

2019-10-18 16:46 UTC, zharinov commented
I wanted to replace class to decorator function which will search-and-replace countdown value in the original graphql query

2019-10-18 16:53 UTC, zharinov commented
But it should work, so it can be separated into other issue

2019-10-28 09:30 UTC, closed without merging