test: Use relativeFile over fileBasenameNoExtension in vscode launch configuration
renovatebot/renovate pull request #4411
Opened 2019-08-31 13:51 UTC by ikesyo

Just passing a file base name to Jest is too aggressive, e.g. if someone is testing `test/config/index.spec.ts` with "Jest Current File" configuration, all `test/**/index.spec.(ts|js)` files will be tested. That should be odd/wrong.

- https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables

The configuration was originally introduced in #3725.

2019-09-02 16:11 UTC, ViceIce commented
OK, i have to test it on windows. If i remember `relativeFile` uses backslash on windows, so here it won't work.

2019-09-02 16:34 UTC, ikesyo commented
Hmm I'm surprised that this won't work.

- https://github.com/microsoft/vscode-recipes/issues/205
- https://github.com/microsoft/vscode/issues/70050
- https://github.com/facebook/jest/issues/7914

2019-09-02 18:05 UTC, ViceIce commented
I'm trying to move to the new [remote dev feature](https://code.visualstudio.com/docs/remote/remote-overview) of vscode, so then the windows problems are gone for me. 

I'm running my production renovate bots as docker container on linux, so no problem there too.

2019-09-02 18:18 UTC, viceice approved these changes
LGTM

2019-09-02 18:18 UTC, ViceIce commented
@rarkins What do you think about windows debugging?

2019-09-02 18:20 UTC, viceice requested changes
We can use [Platform-specific properties](https://code.visualstudio.com/docs/editor/debugging#_platformspecific-properties) as current workaround.

2019-09-02 18:59 UTC, rarkins commented
I assume we’ll have plenty of one time or regular contributors who use Windows though. What would be our position? Just debugging doesn’t work did windows?

2019-09-02 19:07 UTC, ViceIce commented
It works on windows, but `relativeFile` does not work as jest filter. So we can simply add a new args override for windows, which uses the current filter behavior.

2019-09-02 19:09 UTC, ViceIce commented
https://github.com/renovatebot/renovate/blob/fae798f125b7fb00235bd86cce2dea4cc397cd87/.vscode/launch.json#L30-L32

2019-09-03 01:33 UTC, ikesyo commented
Just added the existing `args` to `windows`.

2019-09-03 04:18 UTC, rarkins commented
I'm happy with whatever you two agree on

2019-09-03 04:24 UTC, viceice requested changes

2019-09-03 04:24 UTC, ViceIce commented on .vscode/launch.json
> +      "args": ["--runInBand", "--collectCoverage=false", "${relativeFile}"],
Found a better solution: [`--runTestsByPath`](https://jestjs.io/docs/en/cli#runtestsbypath)
```suggestion
      "args": [
        "--runInBand",
        "--collectCoverage=false",
        "--runTestsByPath",
        "${relativeFile}"
      ],
```

2019-09-03 04:24 UTC, ViceIce commented on .vscode/launch.json
> +        "args": [
This can be reverted with the above change. 😅

2019-09-05 04:58 UTC, ViceIce commented
@ikesyo Any questions? Can you please make the requested changes?

2019-09-05 05:22 UTC, ikesyo commented
@ViceIce Thanks for the tip! I've just updated the pull request.

2019-09-05 05:24 UTC, viceice approved these changes
LGTM

2019-09-05 06:07 UTC, ViceIce commented
@rarkins Can you merge this?

2019-09-05 06:59 UTC, merged