feat(github): implement `requiredStatusChecks`
renovatebot/renovate pull request #4597
Opened 2019-10-07 08:25 UTC by sarunint

Closes #1853 (partially)

2019-10-07 10:03 UTC, rarkins commented
There are some obvious use cases here but also some less obvious.

1. If all required status checks are present and all passing: succeeded
2. If any required status checks are present and failed: failed
3. If only some of the status checks are present but all that are present are passing: pending?

The key question is: what to do if the user configures a required status check that fails to show up? I think we should probably be pending forever. What do you think?

2019-10-07 10:13 UTC, sarunint commented
Ha, I totally missed those cases.

2019-10-07 10:15 UTC, sarunint commented
Let me think for a while.

Also, should I do this for other platforms in this PR? Or should I separate them up?

2019-10-07 10:36 UTC, rarkins commented
Ideally we would implement this for all platforms that could support it. It's OK to note a feature is "platform X only" but it can confuse users even still, so ideally we don't do that.

2019-10-07 13:04 UTC, sarunint commented
@rarkins I ended up implement for both GitHub and GitLab.

2019-10-08 06:58 UTC, rarkins commented
@leipert could you glance at the GitLab part of this?

2019-10-08 07:18 UTC, viceice reviewed
Can we extract some util function for this? I see a lot duplicated code.

2019-10-12 14:37 UTC, sarunint commented on lib/platform/github/index.ts
>      checkRuns.some(run => run.conclusion === 'failed')
I'll see what I can do.

2019-10-14 11:21 UTC, rarkins requested changes
Check runs (github) support. Also, possible to de-duplicate the core logic between github and gitlab implementations?

2019-11-29 21:21 UTC, ViceIce commented
@sarunint any news? Are you planning any changes?

2019-11-29 21:54 UTC, ViceIce commented
This should be simple adaptable for `bitbucket` and `bitbucket-server`. 

azure would be more difficult.

https://github.com/renovatebot/renovate/blob/4adb0c00527ec3e25a4629ef15e8684663caf94b/lib/platform/azure/index.ts#L353

`branch.commit.statuses`

https://docs.microsoft.com/en-us/rest/api/azure/devops/git/statuses/list?view=azure-devops-rest-5.1
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20statuses/list?view=azure-devops-rest-5.1

2019-11-29 21:55 UTC, sarunint commented
@ViceIce Sorry, I've been very busy this month. I'll try to fix things up this weekend.

2019-11-29 22:05 UTC, ViceIce commented
aditional azure info

**GitBranchStatus** interface
https://github.com/microsoft/azure-devops-node-api/blob/d4b692556db58a418e5d7c2b01fb68978746b3b4/api/interfaces/GitInterfaces.ts#L736-L760

**GitCommitRef** interface
https://github.com/microsoft/azure-devops-node-api/blob/d4b692556db58a418e5d7c2b01fb68978746b3b4/api/interfaces/GitInterfaces.ts#L804-L864

**GitStatus** interface
https://github.com/microsoft/azure-devops-node-api/blob/d4b692556db58a418e5d7c2b01fb68978746b3b4/api/interfaces/GitInterfaces.ts#L2456-L2496

2019-12-05 20:45 UTC, viceice requested changes
Needs deconflicting

2019-12-19 16:53 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovateapp/renovate?pullRequest=4597) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovateapp/renovate?pullRequest=4597) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovateapp/renovate?pullRequest=4597) it.</sub>

2020-03-03 13:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovateapp/renovate?pullRequest=4597) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovateapp/renovate?pullRequest=4597) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovateapp/renovate?pullRequest=4597) it.</sub>

2020-08-05 07:15 UTC, closed without merging