feat(bundler): Extract github dependencies [WIP]
renovatebot/renovate pull request #4934
Opened 2019-12-05 18:12 UTC by zharinov

Closes #4789

2019-12-05 18:59 UTC, viceice reviewed
All existing tests are working, so it should be safe.

@zharinov Did you live tests to verify?

2019-12-06 15:23 UTC, zharinov reviewed
> All existing tests are working, so it should be safe.
> 
> @zharinov Did you live tests to verify?

I changed behavior such that it won't touch git deps except tagged, also added one more Gemfile (huge)

2019-12-06 16:23 UTC, zharinov commented
Should handle cases like this:
https://github.com/zharinov/manageiq-1/pull/41/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R16

2019-12-06 16:47 UTC, rarkins commented
>Should handle cases like this: ...

@zharinov this PR is wrong right now though, right?

2019-12-07 05:10 UTC, zharinov commented
> > Should handle cases like this: ...
> 
> @zharinov this PR is wrong right now though, right?

Extract function is okay I think, but it needs another `update` function for extracted values.

2019-12-07 05:12 UTC, zharinov commented
And yes, comparing to the first commit, now it affects git deps from another tests

2019-12-07 16:09 UTC, zharinov commented
Example repo: 
https://github.com/zharinov/manageiq-1/pulls

Interesting PRs: 
https://github.com/zharinov/manageiq-1/pull/27/files
https://github.com/zharinov/manageiq-1/pull/18/files
https://github.com/zharinov/manageiq-1/pull/25/files

2019-12-07 17:58 UTC, rarkins commented
Isn’t PR 18 incorrectly downgrading?

2019-12-07 18:06 UTC, zharinov commented
Although in this particular case it is, I think ruby versioning defines this notation as the shorthand for pre-releases (otherwise, why not just increment?). In this gem that's the first release using this form, earlier examples of pre-releases are like `v0.26.0b2`, etc.

2019-12-07 18:09 UTC, zharinov commented
Anyway, I'll double-check this

2019-12-08 18:47 UTC, zharinov commented
Found it: https://github.com/renovatebot/ruby-semver/blob/master/lib/ruby/version.ts#L254

2019-12-17 09:25 UTC, viceice requested changes
Missing coverage

2020-01-07 05:47 UTC, viceice requested changes
@zharinov Needs deconflicting

2020-01-07 05:47 UTC, ViceIce commented on lib/manager/bundler/extract.ts
> +  for (const [key] of Object.entries(parsed)) {
```suggestion
  for (const key of Object.keys(parsed)) {
```

2020-01-20 12:45 UTC, zharinov commented on lib/manager/bundler/extract.ts
> +      `,\\s*(:${key}\\s*=>|${key}\\s*:)\\s*(['"])(?<value>[^'"]+)\\2`
While named regex groups are optional, it's better to use numbered backreferences for quote characters, instead of code them separately.

2020-01-20 16:05 UTC, rarkins commented
@zharinov any updates needed to this now that we added Gemfile.lock parsing for `lockedVersion` ?

2020-01-20 16:08 UTC, zharinov commented
Hm, need to see commit details from @souravdasslg original PR

2020-01-21 10:23 UTC, zharinov commented
> @zharinov any updates needed to this now that we added Gemfile.lock parsing for `lockedVersion` ?

@rarkins it should be okay

2020-01-21 10:26 UTC, zharinov commented on test/manager/bundler/update.spec.ts
> +            newString: 'gem "foo", ">= 1.0.0", "< 1.1.0", tag: "1.2.0"',
Not sure on this behavior

2020-04-03 17:13 UTC, Scritik commented
Hi,

Any news on this?

Thx :)

2020-04-03 17:27 UTC, rarkins commented
@zharinov can you resolve the conflicts?

2020-04-03 17:29 UTC, zharinov commented
Let's see...

2020-05-01 11:14 UTC, rarkins commented
@zharinov this needs to be re-tested with autoReplace. Can you identify which example repo this can be tested against?

2020-05-01 11:20 UTC, zharinov commented
Here is hardcore example: https://github.com/ManageIQ/manageiq/
For quicker run, I would filtered out everything not related to git.

2020-06-18 09:38 UTC, rarkins commented
@zharinov could you refactor/resubmit this now that we have autoReplace and don't need the update function?

2020-06-18 09:38 UTC, closed without merging

2020-06-18 09:40 UTC, zharinov commented
Sure