fix: properly log pkgUrl in case of error
renovatebot/renovate pull request #4972
Opened 2019-12-11 14:48 UTC by bagage

Closes #

2019-12-11 17:13 UTC, rarkins commented
`pkgUrl` is not a special term for Renovate's logs so could we instead convert it in the top of the `catch` (e.g. `const failedUrl = pkgUrl.toString()`) and then reference that in the logs?

2019-12-13 06:47 UTC, viceice requested changes
@bagage Please carry out suggested changes

2019-12-13 08:43 UTC, bagage commented
I updated the code accordingly :).

2019-12-13 09:04 UTC, viceice requested changes
please run `yarn prettier-fix`

2019-12-13 09:26 UTC, merged

2019-12-13 09:34 UTC, renovate-release commented
:tada: This PR is included in version 19.81.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate)
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.81.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: