pipenv(pipenv): Use centralized docker execution
renovatebot/renovate pull request #5062
Opened 2019-12-24 16:54 UTC by zharinov

2020-01-07 06:07 UTC, viceice submitted a review, later dismissed

2020-01-07 06:16 UTC, ViceIce commented on lib/manager/pipenv/artifacts.ts
> +        envVars: ['LC_ALL', 'LANG', 'PIPENV_CACHE_DIR'],
@rarkins Shouldn't those env vars always passed to child process? 🤔

2020-01-27 15:01 UTC, rarkins requested changes

2020-01-27 15:01 UTC, rarkins commented on lib/manager/pipenv/artifacts.ts
> +        LANG: process.env.LANG,
Let's pass `LC_ALL` and `LANG` to child_process always, not just for pipenv

2020-02-09 12:26 UTC, rarkins approved these changes

2020-02-09 12:26 UTC, merged

2020-02-09 12:34 UTC, renovate-release commented
:tada: This PR is included in version 19.127.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate)
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.127.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: