refactor(docker): Use pre/post commands instead of wrapping
renovatebot/renovate pull request #5103
Opened 2020-01-05 13:19 UTC by zharinov

ref #2863

2020-01-05 13:21 UTC, zharinov commented on test/util/exec.spec.ts
> +      `docker run --rm -v "${cwd}":"${cwd}" -w "${cwd}" ${image} ${cmd}`,
When passing `cwd`, we always have to mount it too, aren't we?

2020-01-06 11:06 UTC, viceice requested changes

2020-01-06 11:06 UTC, ViceIce commented on lib/util/docker/index.ts
> +  let volumes = options.volumes || [];
```suggestion
  let volumes = new Set(options.volumes || []);
```

2020-01-06 11:06 UTC, ViceIce commented on lib/util/docker/index.ts
> +      ...uniq(volumes)
```suggestion
      ...Array.from(volumes)
```

2020-01-06 11:06 UTC, ViceIce commented on lib/util/docker/index.ts
> +      : `bash -l -c "${commands.join(' && ').replace(/"/g, '\\"')}"`;
Do we have proper escaping for all cases here?

2020-01-07 06:41 UTC, viceice approved these changes

2020-01-07 06:41 UTC, ViceIce commented on lib/util/docker/index.ts
> +  let volumes = options.volumes || [];
not required

2020-01-07 06:41 UTC, ViceIce commented on lib/util/docker/index.ts
> +      ...uniq(volumes)
ok to use `uniq`

2020-01-07 06:41 UTC, ViceIce commented on lib/util/docker/index.ts
> +      : `bash -l -c "${commands.join(' && ').replace(/"/g, '\\"')}"`;
We have to make sure that escaping quotes works for complicated calls.

2020-01-07 07:47 UTC, merged

2020-01-07 10:18 UTC, renovate-release commented
:tada: This PR is included in version 19.90.8 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate)
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.90.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: