refactor: EnsureIssueConfig function
renovatebot/renovate pull request #5107
Opened 2020-01-06 11:50 UTC by souravdasslg

1. New Interface is created named `EnsureIssueConfig`
2. Every function call is refactored.
3. Updated tests and snapshots accordingly.

#4996

2020-01-06 19:54 UTC, JamieMagee submitted a review, later dismissed

2020-01-07 05:21 UTC, viceice approved these changes

2020-01-07 10:01 UTC, viceice requested changes
needs deconflicting

2020-01-07 10:28 UTC, souravdasslg commented
> needs deconflicting

Done 💯

2020-01-07 10:31 UTC, viceice approved these changes

2020-01-07 10:40 UTC, merged

2020-01-08 08:48 UTC, renovate-release commented
:tada: This PR is included in version 19.91.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate)
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.91.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: