refactor: createPR function (#4996)
renovatebot/renovate pull request #5108
Opened 2020-01-06 13:05 UTC by souravdasslg

1. New Interface is created named CreatePRConfig
2. Every function call is refactored.
3. Updated tests and snapshots accordingly.

#4996

2020-01-06 19:57 UTC, JamieMagee submitted a review, later dismissed

2020-01-07 05:30 UTC, viceice requested changes

2020-01-07 05:30 UTC, ViceIce commented on lib/platform/bitbucket-server/index.ts
> +  labels: _labels,
```suggestion
```

2020-01-07 05:30 UTC, ViceIce commented on lib/platform/bitbucket/index.ts
> +  labels: _labels,
```suggestion
```

2020-01-07 05:59 UTC, souravdasslg commented on lib/platform/bitbucket-server/index.ts
> +  labels: _labels,
Removed as suggested.

2020-01-07 05:59 UTC, souravdasslg commented on lib/platform/bitbucket/index.ts
> +  labels: _labels,
Removed as suggested.

2020-01-07 06:00 UTC, viceice approved these changes

2020-01-07 10:00 UTC, viceice requested changes
needs deconflicting

2020-01-07 10:12 UTC, viceice approved these changes

2020-01-07 10:50 UTC, viceice requested changes
needs deconflicting again 😅

2020-01-07 11:14 UTC, souravdasslg commented
> needs deconflicting again 😅

Done. I was waiting for this :stuck_out_tongue:

2020-01-07 11:17 UTC, viceice approved these changes

2020-01-07 15:13 UTC, ViceIce commented
@rarkins Ready for merge

2020-01-07 15:33 UTC, merged

2020-01-08 08:48 UTC, renovate-release commented
:tada: This PR is included in version 19.91.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate)
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.91.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: