feature(java): use java 11 in favour of java 8.
renovatebot/renovate pull request #5138
Opened 2020-01-13 13:06 UTC by walschap

When running gradle using java 8 on a project that depends on libraries built with newer java versions, as of gradle 5.3 the renovate run breaks because of the "Automatic target JVM version" check. -->  https://docs.gradle.org/current/userguide/upgrading_version_5.html#changes_5.3

Closes #

2020-01-13 13:17 UTC, rarkins commented
Hi @walschap, are you using the self-hosted Renovate, or WhiteSource Renovate app? We need to update https://github.com/renovatebot/docker-gradle/blob/master/Dockerfile too

2020-01-13 13:23 UTC, ViceIce commented
Currently migrating to java11 would break android gradle projects, because there are some missing libs removed from java to external libs. 🤔

2020-01-13 13:23 UTC, walschap commented
Yes @rarkins , we're using the self-hosted renovate.

2020-01-13 13:46 UTC, ViceIce commented
@rarkins android already broken on app

https://github.com/ViceIce/android-samples
https://app.renovatebot.com/dashboard#github/ViceIce/android-samples/130730044

2020-01-13 13:57 UTC, ViceIce commented
strange, on my selfhosted `renovate:slim` i get the follwing:

```
DEBUG: Start gradle command (repository=proj/repo)
       "cmd": "docker run --rm -v \"/tmp/renovate/repos/gitlab/proj/repo\":\"/tmp/renovate/repos/gitlab/proj/repo\" -w \"/tmp/renovate/repos/gitlab/proj/repo\" renovate/gradle gradle --init-script renovate-plugin.gradle renovate"
DEBUG: To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html.
       Daemon will be stopped at the end of the build stopping after processing
       Configuration on demand is an incubating feature.
       > Task :app:renovate
       > Task :renovate
       
       BUILD SUCCESSFUL in 38s
       2 actionable tasks: 2 executed
        (repository=proj/repo)
 INFO: Gradle report complete (sitory=proj/repo)
```

2020-01-13 14:39 UTC, rarkins commented
@ViceIce any objections to moving to Java 11 for the fat Docker image here then?

2020-01-13 14:42 UTC, ViceIce commented
I'm just testing it now, maybe we can upgrade to java11 and update android projects without android sdk

2020-01-13 15:59 UTC, ViceIce commented
ok, i got it running. https://github.com/ViceIce/android-samples/pulls

I will try to run with java 11 now

2020-01-14 07:43 UTC, ViceIce commented
it's working fine, even with java 13

2020-01-14 07:44 UTC, ViceIce commented
@rarkins can we merge as feature, or does it need a breaking change 🤔 

Also we need to update `renovate/gradle` docker image. I'll send a pr

2020-01-14 07:48 UTC, ViceIce commented
`renovate/gradle` is already on java11

https://github.com/renovatebot/docker-java/blob/b0c3e3bcac1c8de7f7a1a9767df70c7a6c841892/Dockerfile#L5

we install [`default-jre-headless`](https://packages.ubuntu.com/bionic/default-jre-headless) which will  install java11, so it should be save to update the full image without breaking change.

2020-01-14 07:50 UTC, viceice requested changes

2020-01-14 07:50 UTC, ViceIce commented on Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends openjdk-11-jre-headless gradle && \
```suggestion
RUN apt-get update && apt-get install -y --no-install-recommends gradle && \
```

gradle installs latest stable java version (`default-jre-headless`)

2020-01-14 07:53 UTC, ViceIce commented
![image](https://user-images.githubusercontent.com/1798109/72324490-5e711c00-36ab-11ea-8128-1045a32b7a84.png)

2020-01-14 08:30 UTC, merged

2020-01-14 08:38 UTC, renovate-release commented
:tada: This PR is included in version 19.94.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate)
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.94.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: