Gradle Version Compatibility
renovatebot/renovate pull request #5431
Opened 2020-02-10 21:21 UTC by jGleitz

Fixes the use of a type that was introduces in Gradle 6.

Adds basic Gradle compatibility tests, more testing is needed! (#5408)

Closes #5424

2020-02-10 21:26 UTC, jGleitz commented
@JamieMagee @ViceIce we should settle for one implementation. Check for `URI` or for `MavenArtifactRepository`?

2020-02-10 21:27 UTC, jGleitz commented
Note that the code declares all dependencies to be maven dependencies, so checking for `MavenArtifactRepository` does not exclude any dependencies.

2020-02-10 21:42 UTC, ViceIce commented
I think we can go with `MavenArtifactRepository`. I don't know if there is any other repository type in the wild.

If there is, we can add it explicitly later.

2020-02-10 21:42 UTC, viceice submitted a review, later dismissed

2020-02-10 21:44 UTC, jGleitz commented
> I don't know if there is any other repository type in the wild.

There is: [`IvyArtifactRepository`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/IvyArtifactRepository.html). But since renovate can’t read from it, it doesn’t matter that we exclude it.

2020-02-10 22:00 UTC, ViceIce commented
Then we should open a new issue for ivy, just to remember it.

2020-02-10 22:23 UTC, jGleitz commented
I am a little stuck with this PR because I don’t know how to set up Java for Circle CI. Should I build and use a new Docker image?

Also, why is CircleCI still used in the first place? Most checking is done on GitHub, but one job is left on CircleCI.

2020-02-10 23:01 UTC, viceice requested changes

2020-02-10 23:01 UTC, ViceIce commented on .github/workflows/test.yml
> +          java-version: 8
We should use latest java lts (11), like our renovate:gradle images.

2020-02-10 23:02 UTC, ViceIce commented
We can skip circle java tests for now, as we plan to move to github actions soon

2020-02-10 23:22 UTC, jGleitz commented
Alright. I think this PR should be ready then.

2020-02-10 23:25 UTC, viceice submitted a review, later dismissed

2020-02-11 00:02 UTC, ViceIce commented
maybe we should also skip the java tests on windows.

2020-02-11 05:06 UTC, rarkins commented
Does this mean that Java is needed locally to pass `yarn test`? If so, we should probably update the docs about it.

2020-02-11 08:57 UTC, JamieMagee commented on lib/manager/gradle/gradle-updates-report.spec.ts
> +function parseJavaVersion(javaVersionOutput) {
```suggestion
function parseJavaVersion(javaVersionOutput: string) {
```

2020-02-11 09:20 UTC, JamieMagee approved these changes

2020-02-11 09:25 UTC, merged

2020-02-11 09:32 UTC, renovate-release commented
:tada: This PR is included in version 19.129.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/renovate)
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.129.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: