refactor: Extract test data for NPM and PEP440 version schemes
renovatebot/renovate pull request #5507
Opened 2020-02-18 12:44 UTC by zharinov

Ref #5213

2020-02-18 12:45 UTC, zharinov commented
So that we can merge it for `poetry`.

2020-02-21 17:59 UTC, viceice approved these changes
Just test code

2020-02-21 18:18 UTC, rarkins commented
@zharinov is this still required?

2020-02-21 18:18 UTC, rarkins requested changes

2020-02-21 18:18 UTC, rarkins commented on lib/versioning/pep440/index.ts
> +export const isValid = (input: string): string =>
Let's not change any pep440 behaviour

2020-05-30 05:20 UTC, closed without merging