feat: yarn 2
renovatebot/renovate pull request #5657
Opened 2020-03-06 11:37 UTC by christophehurpeau

See #5230

- use YARN_ENABLE_SCRIPTS=0 instead of --ignore-scripts
- disable yarn-deduplicate with warning

2020-03-06 11:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=5657) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=5657) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=5657) it.</sub>

2020-03-06 13:50 UTC, viceice requested changes
Needs test fixes too.

2020-03-06 13:50 UTC, viceice commented on lib/manager/npm/post-update/yarn.ts
> +      if (yarnMajorVersion < 2) {
move to outer scope, so `postUpdateOptions` re checked after major version.

2020-03-06 13:50 UTC, viceice commented on lib/manager/npm/post-update/yarn.ts
> +import * as semverVersioning from '../../../versioning/semver';
```suggestion
import { api as semver } from '../../../versioning/semver';
```

2020-03-06 13:50 UTC, viceice commented on lib/manager/npm/post-update/yarn.ts
> +    const yarnMajorVersion = semverVersioning.api.getMajor(yarnVersion);
```suggestion
    const yarnMajorVersion = semver.getMajor(yarnVersion);
```

2020-03-15 10:53 UTC, rarkins commented
@christophehurpeau thanks for your submission. Please complete the CLA so that I can take a look.

2020-04-04 11:49 UTC, christophehurpeau commented
Hello, I don't know how to fix or adapt the test. I'm guessing the error came from the version addition, but I can't find how I should mock it ? Can you help pointing in the right direction ?

2020-04-08 21:30 UTC, JamieMagee commented
@christophehurpeau I've fixed the tests. You can find the diff [here](https://gist.github.com/JamieMagee/235950f9c07e0a72ce71a2844432fc3f).

The issue was, we were mocking all `exec` calls, but your code uses `exec` to get the yarn version but we didn't provide a mocked value for it.

2020-04-09 12:27 UTC, christophehurpeau commented
Thank you @JamieMagee !! I've push your patch and updated the branch :)

2020-04-09 13:03 UTC, viceice submitted a review, later dismissed

2020-04-13 08:59 UTC, JamieMagee submitted a review, later dismissed

2020-04-13 09:01 UTC, JamieMagee approved these changes

2020-04-13 09:02 UTC, JamieMagee commented
I'll merge this once all checks pass.

2020-04-13 09:23 UTC, merged

2020-04-13 09:32 UTC, renovate-release commented
:tada: This PR is included in version 19.207.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.207.0)
- `19.207.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: