feat(gitlab-tags): Add support for "releaseTimestamp" for GitLab tags
renovatebot/renovate pull request #5712
Opened 2020-03-13 12:06 UTC by zharinov

Ref #4689

2020-03-13 13:11 UTC, rarkins commented on lib/datasource/gitlab-tags/index.ts
> +    releaseTimestamp: commit.created_at,
Is it definitely a mandatory field that's always present?

2020-03-13 17:11 UTC, viceice requested changes

2020-03-13 17:11 UTC, viceice commented on lib/datasource/gitlab-tags/index.spec.ts
> +          },
```suggestion
          commit: { },
```

for null testing

2020-03-13 17:11 UTC, viceice commented on lib/datasource/gitlab-tags/__snapshots__/index.spec.ts.snap
> +      "releaseTimestamp": "2020-03-04T12:12:13.000-06:00",
```suggestion
      "releaseTimestamp": undefined,
```

2020-03-13 17:11 UTC, viceice commented on lib/datasource/gitlab-tags/index.ts
> +    releaseTimestamp: commit && commit.created_at ? commit.created_at : null,
```suggestion
    releaseTimestamp: commit?.created_at,
```

2020-03-17 14:48 UTC, zharinov commented on lib/datasource/gitlab-tags/index.ts
> +    releaseTimestamp: commit && commit.created_at ? commit.created_at : null,
Love this feature so much!

2020-03-18 11:32 UTC, merged