refactor: Move Github platform to util/http
renovatebot/renovate pull request #5882
Opened 2020-04-05 14:07 UTC by zharinov

Ref: #5865

2020-04-05 14:09 UTC, zharinov commented
The main platform file requires other HTTP methods.
Can I add it on my on just like `postJson`, etc? @viceice

2020-04-05 14:14 UTC, rarkins commented
It’s ok to add to the existing http functions

2020-04-05 18:19 UTC, rarkins requested changes
A quick change to start - can you move the wrapper to be `util/http/github.ts`? As it is used by platforms, managers and datasources then I think it could belong here instead.

2020-04-05 18:25 UTC, rarkins commented on lib/util/http/index.ts
> +    const body = is.string(res.body) ? JSON.parse(res.body) : res.body;
I guess we can de-dupe this by adding a private function. like `this.requestJson()`?

2020-04-05 18:26 UTC, rarkins commented on lib/workers/pr/changelog/release-notes.ts
> +import * as api from '../../../platform/github/gh-http-wrapper';
Let's import it as `github` so that the call is `github.getJson`

2020-04-06 04:35 UTC, viceice requested changes

2020-04-06 04:35 UTC, viceice commented on lib/datasource/github-tags/index.ts
> +    digest = (await api.getJson(url)).body[0].sha;
```suggestion
    digest = (await api.getJson<{ sha: string }[]>(url)).body[0].sha;
```

2020-04-06 04:35 UTC, viceice commented on lib/datasource/pod/index.ts
>      }
```suggestion
    return await api.getJson<T>(url, { json }).body;
```

Http (got) never returns `null`

2020-04-06 04:35 UTC, viceice commented on lib/platform/github/gh-http-wrapper.ts
> +  options?: any,
We should add type here

2020-04-06 04:35 UTC, viceice commented on lib/platform/github/gh-http-wrapper.ts
> +import URL from 'url';
I think this file should be `lib/util/http/github` and export a class `GithubHttp` which extends and overrides the `Http` class.

2020-04-06 04:35 UTC, viceice commented on lib/platform/github/gh-http-wrapper.ts
> +        'https://github.com/renovatebot/renovate',
Shouldn't this be set for all renovate requests?

2020-04-10 15:49 UTC, zharinov commented
`platform/github/index.ts` and `platform/github/index.spec.ts` are pretty hard to refactor/modify in this single PR.
What if I will:
 - [1a] Commit my `util/http/github.ts` with `gh-got-wrapper` and `gh-graphql-wrapper` functionality,
- [1b] Port datasources and manager to use it, just like some existing ones use `util/http/index.ts`,
- [2a] Refactor `platform/github/index.spec.ts`, by (1) separating function-specific mocks and (2) snapshotting all HTTP call sequences similar to what we did for `util/exec`,
- [2b] Confidently switch `platform/github/index.ts` dependency to `util/http/github.ts`?

2020-04-10 16:47 UTC, rarkins commented
@zharinov sounds like a good plan. I always prefer incremental steps anyway.

2020-04-10 16:48 UTC, viceice commented
Yes, good plan. Do it. 🙃

2020-05-14 11:19 UTC, zharinov commented
Superseded by #6203

2020-05-14 11:19 UTC, closed without merging