feat: release date
renovatebot/renovate pull request #5960
Opened 2020-04-13 12:26 UTC by ViralRuparel

Adds releaseTimeStamp to the PR updates table.

Closes #5822

2020-04-13 12:33 UTC, ViralRuparel commented
Here is the result after adding timeStamp. @rarkins what so you think, should it be kept as show in the screenshot(in change column) or make a new column.(something like releaseTime).

![image](https://user-images.githubusercontent.com/21654339/79120573-d507dd80-7db0-11ea-827a-b9dede6577d8.png)

2020-04-13 12:37 UTC, rarkins commented
Shouldn’t be in any column by default yet and it needs to be formatted as discussed in the issue.

2020-04-13 12:38 UTC, rarkins commented
Looks like you need to update your prettier version too btw

2020-04-13 13:24 UTC, ViralRuparel commented
> Shouldn’t be in any column by default yet and it needs to be formatted as discussed in the issue.

Yeah I will format as we discussed to support all 4 formats, but just wanted to know the default placement of it in the PR(if not in any column of the table).

2020-04-13 13:51 UTC, rarkins commented
No default placement yes but add it to allowed template fields

2020-04-14 04:55 UTC, rarkins requested changes
- Do not make any changes to the default tables
- Instead, add a new field to upgrades called `releaseDate`, which is formatted like below:

If less than a year old, make it like `01-Jan`.
If more than a year old, make it like `01-Jan-2018`

2020-04-14 04:55 UTC, rarkins commented on lib/config/definitions.ts
> +      Change: '`{{{displayFrom}}}` -> `{{{displayTo}}}` {{{releaseTimestamp}}}',
```suggestion
      Change: '`{{{displayFrom}}}` -> `{{{displayTo}}}`',
```

revert

2020-04-14 04:55 UTC, rarkins commented on lib/manager/npm/index.ts
> +      "[{{#if displayFrom}}`{{{displayFrom}}}` -> {{else}}{{#if currentValue}}`{{{currentValue}}}` -> {{/if}}{{/if}}{{#if displayTo}}`{{{displayTo}}}`{{else}}`{{{newValue}}}`{{/if}}](https://renovate
revert this

2020-04-14 04:55 UTC, rarkins commented on lib/util/template/index.ts
> +  releaseTimestamp: 'The release timeStamp of the newer version',
```suggestion
  releaseDate: 'The release date of the newer version',
```

2020-04-14 04:55 UTC, rarkins commented on lib/workers/pr/body/index.ts
> +  config.upgrades.forEach(upgrade => {
Update your `prettier` (e.g. run `yarn` to update node_modules) and then run `yarn prettier-fix` to revert this change.

2020-04-14 04:55 UTC, rarkins commented on lib/workers/pr/body/updates-table.ts
> +
revert all changes in this file

2020-04-14 08:53 UTC, ViralRuparel commented on lib/config/definitions.ts
> +      Change: '`{{{displayFrom}}}` -> `{{{displayTo}}}` {{{releaseTimestamp}}}',
sure

2020-04-14 08:53 UTC, ViralRuparel commented on lib/manager/npm/index.ts
> +      "[{{#if displayFrom}}`{{{displayFrom}}}` -> {{else}}{{#if currentValue}}`{{{currentValue}}}` -> {{/if}}{{/if}}{{#if displayTo}}`{{{displayTo}}}`{{else}}`{{{newValue}}}`{{/if}}](https://renovate
okay

2020-05-01 11:16 UTC, closed without merging