5774 refactor move changelog retrieval to post lookup pre commit
renovatebot/renovate pull request #5966
Opened 2020-04-14 16:15 UTC by YuraBeznos

Refactor: move changelog retrieval to post-lookup / pre-commit (second try with fix)

Closes #5774

2020-04-15 10:25 UTC, rarkins commented
@YuraBeznos can you add us with write access to your fork so that we are able to do things like "Update branch"?

2020-04-15 10:34 UTC, YuraBeznos commented
@rarkins I've added you and @viceice with Write access, is it OK?

2020-04-16 15:36 UTC, YuraBeznos commented
So right now it is possible to have changelog in commit message something like this:
```
"commitBody": "{{#logJSON.versions}}{{version}} {{date}}\n{{releaseNotes.body}}{{/logJSON.versions}}"
```

2020-04-16 15:59 UTC, YuraBeznos commented
@rarkins , @viceice please have a look. Tests are fixed. Feature works as expected.

2020-04-17 08:04 UTC, viceice commented on lib/workers/repository/process/extract-update.ts
>  };
I think we should directly return  `WriteUpdateResult | undefined` and remove this wrapper completely

2020-04-17 08:07 UTC, viceice requested changes
Maybe needs test fixes after changes

2020-04-17 08:07 UTC, viceice commented on lib/workers/repository/process/extract-update.ts
> +): Promise<UpdateResult> {
```suggestion
): Promise<WriteUpdateResult | undefined> {
```

2020-04-17 08:07 UTC, viceice commented on lib/workers/repository/process/extract-update.ts
> +  return { res };
```suggestion
  return res;
```

2020-04-17 08:07 UTC, viceice commented on lib/workers/repository/process/extract-update.ts
>  };
```suggestion
```

2020-04-17 08:07 UTC, viceice commented on lib/workers/repository/process/index.ts
> +): Promise<UpdateResult> {
```suggestion
): Promise<WriteUpdateResult | undefined> {
```

2020-04-17 08:07 UTC, viceice commented on lib/workers/repository/index.ts
> +    const { res } = await updateRepo(
```suggestion
    const res = await updateRepo(
```

2020-04-17 08:58 UTC, YuraBeznos commented
@viceice thanks for suggestions. Everything fixed. Tests are fine.

2020-04-17 09:55 UTC, viceice approved these changes

2020-04-17 09:55 UTC, viceice commented
@YuraBeznos Have you done some real tests?

2020-04-17 10:20 UTC, YuraBeznos commented
@viceice 
Tested: https://github.com/YuraBeznos/sendgrid-nodejs/pulls
Looks good.

2020-04-18 13:36 UTC, merged

2020-04-18 13:47 UTC, renovate-release commented
:tada: This PR is included in version 19.213.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.213.0)
- `19.213.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: