fix(gradle-wrapper): docker java version downgrade to Java 8 to suppo…
renovatebot/renovate pull request #5975
Opened 2020-04-15 09:27 UTC by driver733

Closes #5974

2020-04-15 09:58 UTC, viceice commented
If we do this, we need to extend our ci to test for java8 too

2020-04-15 10:00 UTC, viceice commented
https://github.com/renovatebot/renovate/blob/e84528086e73dfc69e835e4fbc727c3efd3adb94/.github/workflows/build.yml#L46

2020-04-15 10:02 UTC, viceice requested changes
we need at least to enable tests on java 8 too. this would extend ci time, because of three new jobs 😢

2020-04-15 10:12 UTC, viceice commented on .github/workflows/build.yml
>              node-version: 10
```suggestion
            node-version: 10
          # exclude java 8 on node 10
          - java-version: 8
            node-version: 10
```

2020-04-15 10:13 UTC, rarkins commented on .github/workflows/build.yml
>              node-version: 10
I prefer not to add any more jobs

2020-04-15 10:18 UTC, driver733 commented
@viceice @rarkins I think we can simply replace `Java 11` with `Java 8` in CI build. What do you think?

2020-04-15 10:19 UTC, viceice commented on .github/workflows/build.yml
> +            node-version: 10
```suggestion
            node-version: 10
          # exclude java 11 on node 10
          - java-version: 11
            node-version: 10
```

2020-04-15 10:22 UTC, viceice commented on .github/workflows/build.yml
> +            node-version: 10
```suggestion
        java-version: [8]
        exclude:
          - os: windows-latest
            node-version: 10
```

2020-04-16 08:15 UTC, merged

2020-04-16 08:28 UTC, renovate-release commented
:tada: This PR is included in version 19.211.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.211.2)
- `19.211.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-04-17 13:29 UTC, ps-feng commented
I'm not sure if it's due to this change but since updating we're seeing this error with our Kotlin projects:
```
"Command failed: ./gradlew --init-script renovate-plugin.gradle renovate\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nExecution failed for task ':buildSrc:compileKotlin'.\n> Kotlin could not find the required JDK tools in the Java installation '/usr/lib/jvm/java-8-openjdk-amd64/jre' used by Gradle. Make sure Gradle is running on a JDK, not JRE.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 1s\n"
```
Do you know what could be the problem?

2020-04-17 13:32 UTC, viceice commented
@ps-feng the `:buildSrc:compileKotlin` task should not be called. Can you create a public repro and open a new issue?

2020-04-17 13:35 UTC, ps-feng commented
OK, please bear with me because I'll need to investigate how, as we're using a self-hosted runner within our private Github that auto-updates itself (currently on 19.212.1).

2020-04-17 13:55 UTC, ps-feng commented
@viceice Still don't have a public repo, but I can confirm that when you use the `kotlin-dsl` plugin it'll run `:buildSrc:compileKotlin`. That's probably because in `buildSrc` you can have custom Kotlin code and it needs to compile it. We use it to have dependency versions at the moment.

To check it I copied the plugin from [here](https://github.com/renovatebot/renovate/blob/4f59b62da40a653352c839b344cbfbbf9597f98a/lib/manager/gradle/gradle-updates-report.ts) and placed it in a `renovate-plugin.gradle` file. Then ran
```bash
 $ ./gradlew --init-script renovate-plugin.gradle renovate
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildSrc:compileKotlin
The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.3/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

BUILD SUCCESSFUL in 21s
15 actionable tasks: 15 executed
<-------------> 0% WAITING
> IDLE

```