refactor: remove repoCache global
renovatebot/renovate pull request #6098
Opened 2020-04-30 12:20 UTC by rarkins

2020-04-30 12:35 UTC, viceice requested changes
Some small suggestions. Finally another global removed

2020-04-30 12:35 UTC, viceice commented on lib/datasource/packagist/index.ts
> +  let repoCacheResult = getRepoCached(`packagist-${regUrl}`);
```suggestion
  let repoCacheResult = getRepoCached<Promise<AllPackages | null>>(`packagist-${regUrl}`);
```

2020-04-30 12:35 UTC, viceice commented on lib/datasource/packagist/index.ts
> +      repoCacheResult = getRepoCached(`packagist-${regUrl}`);
```suggestion
      repoCacheResult = getRepoCached<Promise<AllPackages | null>>(`packagist-${regUrl}`);
```

2020-04-30 12:35 UTC, viceice commented on lib/manager/bundler/artifacts.spec.ts
> +
```suggestion
```

2020-04-30 12:35 UTC, viceice commented on lib/manager/bundler/artifacts.ts
> +  const existingError = getRepoCached('bundlerArtifactsError');
```suggestion
  const existingError = getRepoCached<string>('bundlerArtifactsError');
```

2020-04-30 12:35 UTC, viceice commented on lib/util/got/cache-get.ts
> +      return getRepoCached(cacheKey).then((response) => ({
```suggestion
      return getRepoCached<Promise<any>>(cacheKey).then((response) => ({
```

2020-04-30 15:09 UTC, rarkins commented on lib/datasource/packagist/index.ts
> -    while (repoCacheResult === 'pending') {
This was really ugly..

2020-05-01 05:47 UTC, merged

2020-05-01 06:07 UTC, renovate-release commented
:tada: This PR is included in version 19.225.5 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/19.225.5)
- `19.225.5`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: