fix(gitlab): verify if MR is mergeable before setting automerge
renovatebot/renovate pull request #6250
Opened 2020-05-15 11:51 UTC by tyronedd

This polls the Gitlab Merge requests API for the required status that's needed before setting `merge_when_pipeline_succeeds` to `true`.

Closes #6248

2020-05-15 12:00 UTC, viceice requested changes
You need to mock `delay` in tests: `jest.mock('delay', () => Promise.resolve());`

2020-05-15 12:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=6250) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=6250) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tyronedd<br/>:x: Tyrone Meijn<br/><hr/>**Tyrone Meijn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=6250) it.</sub>

2020-05-15 12:34 UTC, tyronedd commented
@viceice Sorry I have little to no experience with testing. I tried to do what you suggested, but it still seems to fail. Can you help me out?

2020-05-15 12:47 UTC, viceice commented
ok, can you first fix your commits to use the right author

2020-05-15 12:52 UTC, viceice commented
You need to add the following after `describe('createPr(branchName, title, body)', () => {`.

line ~956

```js
    beforeEach(() => {
      api.get.mockResolvedValueOnce(
        partial<GotResponse>({
          body: {
            merge_status: 'can_be_merged',
            pipeline: {
              id: 29626725,
              sha: '2be7ddb704c7b6b83732fdd5b9f09d5a397b5f8f',
              ref: 'patch-28',
              status: 'success',
            },
          },
        })
      );
    });
```

2020-05-16 16:20 UTC, tyronedd commented
@viceice @rarkins Any pointers on how to proceed? It fails on code coverage, saying the `await delay` statement is not covered. Again, no experience with testing.

2020-05-28 05:18 UTC, viceice requested changes

2020-05-28 05:18 UTC, viceice commented on lib/platform/gitlab/index.spec.ts
> +      api.get.mockResolvedValueOnce(
```suggestion
      api.get.mockResolvedValueOnce({ body: {} });
      api.get.mockResolvedValueOnce(
```

2020-05-28 05:53 UTC, viceice approved these changes

2020-05-28 05:53 UTC, viceice commented on lib/platform/gitlab/index.spec.ts
> +
```suggestion
```

2020-05-28 06:24 UTC, rarkins commented
Why is this change necessary? It will slow down automerging for GitLab users.

2020-05-28 06:48 UTC, tyronedd commented
> Do you expect that in most cases the flag will still be set in the first run, or in a later run? Have you verified that the logic will still work on a later run?

So I'm on Renovate 19.76.3 and of these MRs:

![image](https://user-images.githubusercontent.com/17970041/83107260-36b0ac80-a0be-11ea-868d-3c0493bdc39e.png)

Log of the relevant job can by found here: https://pastebin.com/YHaZXhW7

all of them except protractor should've been Gitlab automerged by setting merge when pipeline succeeds. They were not however, they were merged by a second run of Renovate bot. You can see in the log they all returned 405 when trying to set the flag.

If you mean a later run of Renovate bot, I do not think Renovate as of 19.76.3 tries to set the merge when pipeline succeeds flag when a merge request is already created in a previous run.

Difficult thing is, I tried to reason about this as thorough as I could by going through the docs and issues in Gitlab, but I didn't hear anybody else here having this issue.

2020-05-28 06:54 UTC, merged

2020-05-28 07:03 UTC, renovate-release commented
:tada: This PR is included in version 20.8.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/20.8.2)
- `20.8.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: