refactor(gitlab): Use new http wrapper for Gitlab platform
renovatebot/renovate pull request #6275
Opened 2020-05-18 14:03 UTC by zharinov

Ref: #5865

2020-05-18 14:09 UTC, zharinov commented
Do we have good example repos to test against?

2020-05-18 20:16 UTC, zharinov commented
Probably, I can just push my existing test repo to new Gitlab remote

2020-05-20 05:00 UTC, rarkins requested changes

2020-05-20 13:07 UTC, zharinov commented
Seems to be working with test repo: https://gitlab.com/zharinov/renovate-test/-/merge_requests

2020-05-23 15:46 UTC, viceice reviewed
Some suggesttions. Maybe @zharinov can do the type optimizations in a later pr?

2020-05-23 15:46 UTC, viceice commented on lib/platform/gitlab/index.ts
> +      }[]
We sould extract a type for this

2020-05-23 15:46 UTC, viceice commented on lib/platform/gitlab/index.ts
> +    const res = await gitlabApi.getJson<{ iid: number; title: string }[]>(
Create a type for this. maybe we should move all gitlab api types to `./types.ts`

2020-05-23 15:46 UTC, viceice commented on lib/platform/gitlab/index.ts
> +      Pr & {
We should have a helper function for mapping Pr to have proper types, see comments below

2020-05-24 16:17 UTC, zharinov commented
> Some suggesttions. Maybe @zharinov can do the type optimizations in a later pr?

@viceice Sure, and for other platforms as well

2020-05-28 16:24 UTC, zharinov commented
Sample repo: https://gitlab.com/zharinov/renovate-test/-/merge_requests/

2020-05-29 05:52 UTC, merged

2020-05-29 06:52 UTC, renovate-release commented
:tada: This PR is included in version 20.11.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/20.11.0)
- `20.11.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: