refactor: pnpm lockfile updates use util/exec docker
renovatebot/renovate pull request #6282
Opened 2020-05-19 14:23 UTC by rarkins

2020-05-19 14:41 UTC, viceice requested changes
needs `NPM_CONFIG_CACHE` env mock

2020-05-19 14:53 UTC, zharinov commented
> needs `NPM_CONFIG_CACHE` env mock

Yes, something similar to `beforeEach` section in `lib/manager/cocoapods/artifacts.spec.ts` should fix it

2020-05-19 15:32 UTC, zharinov approved these changes

2020-05-19 16:11 UTC, merged

2020-05-20 07:37 UTC, renovate-release commented
:tada: This PR is included in version 20.0.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/20.0.2)
- `20.0.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: