feat: update yarn-deduplicate
renovatebot/renovate pull request #6326
Opened 2020-05-25 15:52 UTC by christophehurpeau

Update yarn-deduplicate to v2
I saw we had diffs on duplicated dependencies yarn.lock after some renovate prs were merged. After investigation, we don't have the same version, it could be related.

https://github.com/atlassian/yarn-deduplicate/blob/master/CHANGELOG.md

2020-05-25 16:55 UTC, viceice commented
@rarkins don't we have a refactor PR for this? 🤔

2020-05-25 17:00 UTC, rarkins commented
Yes, but it should be ok to merge and fix the conflict later

2020-05-25 17:05 UTC, viceice commented
Ok, so we prefer to remove the version, as we do in the other PR.

2020-05-25 19:25 UTC, christophehurpeau commented on lib/manager/npm/post-update/yarn.ts
> +        'npx yarn-deduplicate@2.0.0 --strategy fewer && yarn';
```suggestion
        'npx yarn-deduplicate --strategy fewer && yarn';
```

2020-05-25 19:25 UTC, christophehurpeau commented on lib/manager/npm/post-update/yarn.ts
> +        'npx yarn-deduplicate@2.0.0 --strategy highest && yarn';
```suggestion
        'npx yarn-deduplicate --strategy highest && yarn';
```

2020-05-25 19:25 UTC, christophehurpeau commented on lib/workers/branch/lock-files/__snapshots__/yarn.spec.ts.snap
> +    "cmd": "npx yarn-deduplicate@2.0.0 --strategy fewer && yarn",
```suggestion
    "cmd": "npx yarn-deduplicate --strategy fewer && yarn",
```

2020-05-25 19:25 UTC, christophehurpeau commented on lib/workers/branch/lock-files/__snapshots__/yarn.spec.ts.snap
> +    "cmd": "npx yarn-deduplicate@2.0.0 --strategy highest && yarn",
```suggestion
    "cmd": "npx yarn-deduplicate --strategy highest && yarn",
```

2020-05-26 07:03 UTC, christophehurpeau commented
@viceice @rarkins I removed the version as requested :) Let me know if you want other modifications ! Thanks :)

2020-05-26 07:20 UTC, viceice requested changes
need lint fix

2020-05-26 07:20 UTC, viceice commented on lib/manager/npm/post-update/yarn.ts
>        const dedupeCommand =
```suggestion
```

2020-05-26 07:20 UTC, viceice commented on lib/manager/npm/post-update/yarn.ts
> +        'npx yarn-deduplicate --strategy fewer && yarn';
```suggestion
      const dedupeCommand = 'npx yarn-deduplicate --strategy fewer && yarn';
```

2020-05-26 07:20 UTC, viceice commented on lib/manager/npm/post-update/yarn.ts
>        const dedupeCommand =
```suggestion
```

2020-05-26 07:20 UTC, viceice commented on lib/manager/npm/post-update/yarn.ts
> +        'npx yarn-deduplicate --strategy highest && yarn';
```suggestion
      const dedupeCommand = 'npx yarn-deduplicate --strategy highest && yarn';
```

2020-05-26 09:12 UTC, merged

2020-05-26 09:22 UTC, renovate-release commented
:tada: This PR is included in version 20.5.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/20.5.0)
- `20.5.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-05-26 15:30 UTC, christophehurpeau commented
Thank you !