fix(terraform): fix http and add ssh support
renovatebot/renovate pull request #6377
Opened 2020-05-29 20:49 UTC by TerrapinStation

adjusts regex in terraform manager to handle http and ssh

Closes #6376

2020-05-29 20:59 UTC, viceice requested changes

2020-05-29 21:03 UTC, TerrapinStation commented on lib/manager/terraform/__fixtures__/1.tf
> +}
sounds good. ill fix these issues

2020-05-30 09:03 UTC, viceice approved these changes

2020-05-30 09:34 UTC, merged

2020-05-30 09:44 UTC, renovate-release commented
:tada: This PR is included in version 20.15.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/20.15.0)
- `20.15.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: