fix(pip): fix compatibility with some simple pip indexes
renovatebot/renovate pull request #6649
Opened 2020-07-02 00:42 UTC by TheKevJames

Some "simple"-style pip indexes do not conform to the previous
assumption in this method, namely that they must end in `/+simple/` if
they provide only that style of API. Gemfury private indexes, for
example, are assigned as::

    pypi.fury.io/<username>

But offer only a simple API, eg. `pypi.fury.io/<username>/<pkg>/json`
will 404.

This changeset ensures Renovate works with indexes like this by adding a
fallback when the json API 404s to attempt the simple API. This is not
an optimal solution, but I could not find any way to be certain we can
determine whether the API will be json or simple in advance of querying
it.

2020-07-02 05:01 UTC, viceice requested changes

2020-07-02 05:01 UTC, viceice commented on lib/datasource/pypi/index.ts
> +    return Promise.resolve(releases);
```suggestion
    return releases;
```

2020-07-02 05:01 UTC, viceice commented on lib/datasource/pypi/index.ts
> +    logger_1.logger.trace(
```suggestion
    logger.trace(
```

2020-07-02 05:03 UTC, viceice requested changes
We need tests for it

2020-07-02 20:52 UTC, TheKevJames commented
@viceice sorry about that, should have opened this as a draft. Now ready for review!

2020-07-03 04:32 UTC, viceice commented on lib/datasource/pypi/index.ts
> +  } catch (e) {
Yes, good idea.

2020-07-07 02:43 UTC, TheKevJames commented on lib/datasource/pypi/index.ts
> +  } catch (e) {
Done

2020-07-07 04:39 UTC, viceice approved these changes

2020-07-07 04:56 UTC, merged