fix(cargo): Bump complex ranges
renovatebot/renovate pull request #6682
Opened 2020-07-05 15:39 UTC by zharinov

Closes #4765

2020-07-06 07:06 UTC, viceice reviewed
Doesn't this affect npm versioning too?

2020-07-06 07:26 UTC, rarkins commented
Does it really belong in npm or do we need to refactor cargo a little before fixing this?

2020-07-06 07:55 UTC, zharinov commented
Test can be translated to `npm`, then little modifications in `cargo` should finally resolve original issue

2020-07-06 08:58 UTC, rarkins requested changes

2020-07-06 08:58 UTC, rarkins commented on lib/versioning/npm/range.ts
> +      return versions.filter((x) => x !== null && x !== '').join(', ');
I think commas aren't valid in semver ranges, so this is incorrect to have in npm versioning

2020-07-08 14:06 UTC, rarkins commented
So will this fix some npm complex ranges too?

2020-07-08 14:09 UTC, zharinov commented
> So will this fix some npm complex ranges too?

Now should bump to the new result instead of `null`, but can you please provide more examples with what would you like to see?

2020-07-08 14:17 UTC, zharinov commented
Example repo: https://github.com/zharinov/fxa/pulls

2020-07-08 14:18 UTC, zharinov commented
It's current behavior is subject to discussion I think

2020-08-04 11:17 UTC, rarkins requested changes
Review invalid range tests

2020-08-04 11:17 UTC, rarkins commented on lib/versioning/npm/index.spec.ts
> +        currentValue: '>= 1.2.3 <= 1.0',
Isn't this test case invalid?

2020-08-04 11:17 UTC, rarkins commented on lib/versioning/npm/index.spec.ts
> +        currentValue: '>= 1.2.3 <= 1.0.0',
Also invalid?

2020-08-24 17:34 UTC, zharinov commented
With all these invalid test inputs I wanted to show it produces correct ranges from it anyway. But let's keep this simpler and just collect user feedback on edge-cases.

2020-08-25 11:25 UTC, merged

2020-08-25 11:38 UTC, renovate-release commented
:tada: This PR is included in version 23.0.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.0.1)
- `23.0.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: