feat(dependency-dashboard): show logged errors in Dependency Dashboard
renovatebot/renovate pull request #6952
Opened 2020-08-10 22:09 UTC by fgreinacher

Closes #6564

2020-08-10 22:09 UTC, fgreinacher commented
Happy to get some quick feedback whether this goes in the right direction!

2020-08-11 04:10 UTC, viceice reviewed
We need to be sure the values are sanitized, otherwise I like the idea

2020-08-11 05:46 UTC, rarkins commented
Aren't these errors stored per-run?

Also I'm not sure we're likely to see too many of error messages per-repo. It would be very useful to store warnings.

2020-08-11 17:08 UTC, fgreinacher commented
> Aren't these errors stored per-run?

Not sure what you mean. Can you elaborate a bit?

> Also I'm not sure we're likely to see too many of error messages per-repo. It would be very useful to store warnings.

Yes, I'll also store warnings.

2020-09-11 21:50 UTC, fgreinacher commented
OK - this is now finally ready for a "proper" review 👓

2020-09-11 21:51 UTC, fgreinacher commented
> We need to be sure the values are sanitized, otherwise I like the idea

They are. I added some tests to ensure that.

2020-09-11 21:52 UTC, fgreinacher commented
> Aren't these errors stored per-run?

@rarkins I don't understand what you mean by this question, could you rephrase please?

2020-09-18 07:13 UTC, rarkins commented
> > Aren't these errors stored per-run?
> 
> @rarkins I don't understand what you mean by this question, could you rephrase please?

I was referring to how you need to filter based on the message's `repository` instead of print all logs, but you've done that already.

2020-09-18 07:14 UTC, rarkins requested changes
Let's also de-dupe the printed messages. Example:

![image](https://user-images.githubusercontent.com/6311784/93567703-5af70880-f98f-11ea-952b-6771a62ac099.png)

2020-09-18 07:14 UTC, rarkins commented on lib/workers/repository/dependency-dashboard.ts
> +      issueBody += ` - ${nameFromLevel[repoProblem.level]}: ${
```suggestion
      issueBody += ` - ${nameFromLevel[repoProblem.level].toUpperCase()}: ${
```

2020-09-18 14:11 UTC, fgreinacher commented
> Let's also de-dupe the printed messages. Example:
> 
> ![image](https://user-images.githubusercontent.com/6311784/93567703-5af70880-f98f-11ea-952b-6771a62ac099.png)

Good point! Done with https://github.com/renovatebot/renovate/pull/6952/commits/5ac3f24c9eae614c2e7b69f6a65a2ae38833ed6b

2020-09-18 14:14 UTC, rarkins commented
One other thing - I think artifacts errors will print at least one WARN but then it will be erased the next run. We are probably best to filter them out from the dashboard and avoid unnecessary flapping because they are preserved in the PRs anyway using comments.

2020-09-18 15:38 UTC, fgreinacher commented
> One other thing - I think artifacts errors will print at least one WARN but then it will be erased the next run. We are probably best to filter them out from the dashboard and avoid unnecessary flapping because they are preserved in the PRs anyway using comments.

Sounds reasonable, done with https://github.com/renovatebot/renovate/pull/6952/commits/1ffe6ea7c7fbb881e366aa276c9b1b81b5587a5d.

2020-09-21 20:04 UTC, merged

2020-09-21 20:17 UTC, renovate-release commented
:tada: This PR is included in version 23.32.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.32.0)
- `23.32.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: