chore(jenkins): Add support for ignoring upgrade of specific Jenkins plugins
renovatebot/renovate pull request #6980
Opened 2020-08-14 15:32 UTC by maxdanilov

Closes #6979

2020-08-14 15:52 UTC, maxdanilov commented
I believe there's a problem on renovate/renovate:master where `yarn lint` is failing, hence this build also has the lining job failing.

2020-08-15 04:20 UTC, rarkins requested changes
I don't think we want to pass such comments or logic outside the jenkins manager itself. Instead, we can simply set dep.skipReason = ignored.

Please check out https://github.com/renovatebot/renovate/search?q=isskipcomment&unscoped_q=isskipcomment and see if you can align with that.

2020-08-15 04:20 UTC, rarkins commented on lib/manager/common.ts
> +  ignoreComments?: string[];
I don't see any immediate value in passing this "up".

2020-08-19 08:18 UTC, viceice commented
@maxdanilov Why not simply use a package rule to disable / ignore specific dependencies?

2020-08-19 08:28 UTC, maxdanilov commented
@viceice because regardless of whether one uses Renovate or not, they should be able to somehow mark the package version is pinned, and be able to also do it in the code itself.
I actually like the proposal of @rarkins to use a `skipComment`, will implement it when I have time.

2020-08-20 10:29 UTC, maxdanilov commented
@rarkins I've implemented your suggestion for using `isSkipComment` instead - it looks much better now indeed!

2020-08-26 13:26 UTC, merged

2020-08-26 13:40 UTC, renovate-release commented
:tada: This PR is included in version 23.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.3.0)
- `23.3.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: