fix(logger): serialize err.url
renovatebot/renovate pull request #7181
Opened 2020-09-04 08:59 UTC by rarkins

2020-09-04 09:18 UTC, viceice requested changes

2020-09-04 09:18 UTC, viceice commented on lib/logger/err-serializer.ts
> +  url?: unknown;
```suggestion
```

2020-09-04 09:18 UTC, viceice commented on lib/logger/err-serializer.ts
>      body?: unknown;
```suggestion
    body?: unknown;
    url?: unknown;
```

2020-09-04 09:18 UTC, viceice commented on lib/logger/err-serializer.ts
> +  }
```suggestion
  if (err.response?.url) {
    response.url = err.response?.url;
  }
```

2020-09-04 09:18 UTC, viceice commented
https://github.com/renovatebot/renovate/blob/master/lib/util/http/legacy.ts#L29-L33

2020-09-04 09:41 UTC, rarkins commented on lib/logger/err-serializer.ts
> +  url?: unknown;
![image](https://user-images.githubusercontent.com/6311784/92225505-94197e00-eea3-11ea-8bac-1bf55210ac31.png)
?

2020-09-04 09:43 UTC, rarkins commented on lib/logger/err-serializer.ts
> +    response.url = err.response?.url;
```suggestion
    response.url = err.response.url;
```

2020-09-04 09:46 UTC, viceice reviewed
L20: response need to get a explicit type like `Record<string, unknown>`

2020-09-04 11:54 UTC, viceice commented on lib/logger/err-serializer.ts
>    if (err.body) {
Wonder if we need this? as we do a flat copy above anyways. 🤔

2020-09-04 12:02 UTC, rarkins commented
I just wanted the URL to be printed by default when we log `err`. I think this is expanding things much further?

2020-09-04 12:17 UTC, viceice commented
we need to make some more changes

2020-09-04 15:02 UTC, viceice commented
@rarkins  What do you think about the current changes?

2020-09-07 06:07 UTC, viceice approved these changes

2020-09-07 06:34 UTC, merged

2020-09-07 07:01 UTC, renovate-release commented
:tada: This PR is included in version 23.19.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.19.0)
- `23.19.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: