fix: changelog/gitlab: Fix `files.length` condition
renovatebot/renovate pull request #7210
Opened 2020-09-08 08:10 UTC by Turbo87

After using `shift()` in the line above, the array is one item shorter than before. So to detect if there are multiple candidates we need to check if there are any items left in the array at all. If we compare using `> 1` we check if there are 3+ candidates, by changing it to `!== 0` we can check if there are 2+ candidates.

2020-09-08 10:00 UTC, rarkins commented
Is it a logical error or just impacting the logger statement? And won't now it always log that if the files length was 1 to begin with?

2020-09-08 10:28 UTC, viceice requested changes
Yes, the condition was wrong, we only log if more that two files are found. Now we log if more that one files is found

2020-09-08 10:28 UTC, viceice commented on lib/workers/pr/changelog/github/index.ts
> +  if (files.length !== 1) {
```suggestion
  if (files.length !== 0) {
```

2020-09-08 10:40 UTC, Turbo87 commented on lib/workers/pr/changelog/github/index.ts
> +  if (files.length !== 1) {
whoops, thanks 😅

2020-09-08 10:47 UTC, rarkins approved these changes

2020-09-08 11:00 UTC, viceice approved these changes

2020-09-08 11:20 UTC, merged

2020-09-09 04:48 UTC, renovate-release commented
:tada: This PR is included in version 23.20.1 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.20.1)
- `23.20.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: