feat(platform): Filter non-related PRs in "getPrList"
renovatebot/renovate pull request #7213
Opened 2020-09-08 12:40 UTC by zharinov

Closes #7205

2020-09-08 13:05 UTC, viceice requested changes
need fixes

2020-09-08 14:01 UTC, zharinov commented
🤷

2020-09-08 14:03 UTC, rarkins commented
@zharinov @viceice maybe a node modules cache corruption? Same error on `master`

![image](https://user-images.githubusercontent.com/6311784/92486839-d963e580-f1ec-11ea-9cc8-b0db192d2793.png)

2020-09-08 14:05 UTC, rarkins requested changes

2020-09-08 14:05 UTC, rarkins commented on lib/platform/azure/index.ts
> +  branchPrefix,
`branchPrefix` is configurable in the repo's config, so this won't work

2020-09-08 14:08 UTC, rarkins commented
Back to requirements, see https://github.com/renovatebot/renovate/issues/7205#issuecomment-688900982

2020-09-11 16:07 UTC, zharinov commented
Fixed on per-platform basis

2020-09-11 16:07 UTC, closed without merging