feat(git): Use "readdir" instead of "git-ls-tree" for file listing
renovatebot/renovate pull request #7277
Opened 2020-09-14 14:54 UTC by zharinov

2020-09-14 16:40 UTC, zharinov commented on lib/util/git/index.ts
> +    getSubmodules(),
Also we can parse `.gitmodules` directly, though not sure about edge-cases of doing so

2020-09-15 08:23 UTC, zharinov commented on lib/util/git/index.ts
> +    getSubmodules(),
Hm, maybe we can get rid of it, since submodules are meant to be directories and we filter them out

2020-09-15 08:24 UTC, zharinov commented on lib/util/git/index.ts
> +    fs.readdir(config.localDir, {
I don't think so, just needed `Dirent[]` result in order to filter out directory results without extra fs calls

2020-09-15 08:28 UTC, rarkins commented on lib/util/git/index.ts
> +    fs.readdir(config.localDir, {
Our file listing needs to include all files, so I was meaning to ask if readdir is only going to find root files or it it's going to find all nested files too?

2020-09-15 08:30 UTC, zharinov commented on lib/util/git/index.ts
> +    fs.readdir(config.localDir, {
As I understand, it was previously using only `100xxx`results from listing which means regular files

2020-09-15 08:31 UTC, zharinov commented on lib/util/git/index.ts
> +    fs.readdir(config.localDir, {
I'll double check for recursivity

2020-09-15 08:34 UTC, zharinov commented on lib/util/git/index.ts
> +    fs.readdir(config.localDir, {
Okay, I'll add recursion and tests for this too

2020-09-15 11:50 UTC, rarkins commented on lib/util/git/index.ts
> +  return fileList(config.localDir, ['.git', ...submodules]);
Do we think this is enough, or is there the possibility that we missed something_

2020-09-15 11:53 UTC, rarkins commented
@zharinov can you find a large repo to test this out on? I'd like to make sure it runs as fast or faster than the existing git approach.

2020-09-17 08:49 UTC, rarkins requested changes

2020-09-17 08:49 UTC, rarkins commented on lib/util/git/index.ts
> +  return fileList(config.localDir, ['.git', ...submodules]);
```suggestion
  const files = await fileList(config.localDir, ['.git', ...submodules]);
  return files.map((file) => file.replace(`${config.localDir}/`, ''));
```

2020-09-17 08:49 UTC, rarkins commented on lib/util/git/index.ts
> +}
```suggestion
async function fileList(
  directory: string,
  excludes: string[] = []
): Promise<string[]> {
  let list: string[] = [];

  const files = (await fs.readdir(directory)).filter((file) =>
    excludes.every(
      (exclude) => file !== exclude && !file.startsWith(`${exclude}/`)
    )
  );
  for (const file of files) {
    const p = join(directory, file);
    if ((await fs.stat(p)).isDirectory()) {
      list = [...list, ...(await fileList(p))];
    } else {
      list.push(p);
    }
  }

  return list;
}
```

2020-09-17 09:52 UTC, rarkins commented on lib/util/git/index.ts
> +      (exclude) => file !== exclude && !file.startsWith(`${exclude}/`)
I have a doubt in my code now. This may not filter correctly is the submodule is nested deeper than the top level directory

2020-09-21 15:00 UTC, rarkins commented
Needs Windows file path fix:

![image](https://user-images.githubusercontent.com/6311784/93783428-f6a4a500-fc2b-11ea-95b3-db1e936a858d.png)

2020-10-04 12:31 UTC, zharinov commented
Do we still need this, or #7349 gives us good enough performance?

2020-10-04 13:25 UTC, rarkins commented
We should still do this

2020-10-06 18:15 UTC, zharinov commented
In my machine, concurrency with queue size 2 worked faster, while increased size made no difference because of recursion.
But, `ls-tree` performs better for repository like this: https://github.com/zharinov/fake-repo-3
fs: 80ms
concurrent fs: 40ms
ls-tree: 32ms

2020-10-07 04:57 UTC, rarkins commented
I had assumed that an fs-based file listing would be more efficient than a `git`-based listing, but maybe that's wrong. Or maybe our fs approach is bad. @zharinov can you see if it's feasible to test with https://github.com/thecodrr/fdir instead?

2020-10-19 07:39 UTC, closed without merging