feat: add support for updating NuGet lock files
renovatebot/renovate pull request #7375
Opened 2020-09-28 21:25 UTC by fgreinacher

Resolves #6610

2020-10-02 20:15 UTC, fgreinacher commented
OK, this is ready for review now @viceice

2020-10-02 20:16 UTC, fgreinacher commented
(And I think we need to wait for the Docker image, right?)

2020-10-02 20:16 UTC, viceice commented
Yes, sorry.

2020-10-02 20:18 UTC, fgreinacher commented
> Yes, sorry.

Not meant as offense, just wasn't sure whether something happened that I have not noticed 🤣

2020-10-02 20:24 UTC, viceice commented
Yes, too much work on daily job happened. 🙈

2020-10-12 07:14 UTC, JamieMagee commented on lib/manager/nuget/artifacts.ts
> +  if (!/[cs|vb|fs]proj$/i.test(packageFileName)) {
```suggestion
  if (!/(?:cs|vb|fs)proj$/i.test(packageFileName)) {
```

Same as the filematch regex

https://github.com/renovatebot/renovate/blob/f52fe033de5fae6be0155c3b36fad1ec6f722f01/lib/manager/nuget/index.ts#L8-L12

2020-10-12 07:22 UTC, JamieMagee commented on lib/manager/nuget/artifacts.ts
> +    // project file to restore how to detmermine which lock files
```suggestion
    // project file to restore how to determine which lock files
```

2020-10-14 14:07 UTC, viceice reviewed
LGTM, but needs dotnet docker images to be published first

2020-10-15 18:26 UTC, viceice commented
https://hub.docker.com/r/renovate/dotnet/tags

🎉

2020-10-19 07:10 UTC, rarkins commented
Can someone verify that it works with Docker too?

2020-10-19 07:11 UTC, rarkins requested changes
Looks ok from a code review point of view, should be tested with Docker first before merging

2020-10-19 22:15 UTC, fgreinacher commented
> Looks ok from a code review point of view, should be tested with Docker first before merging

I'll take care!

2020-10-20 06:11 UTC, fgreinacher commented
> > Looks ok from a code review point of view, should be tested with Docker first before merging
> 
> I'll take care!

Found a bug (fixed with https://github.com/renovatebot/renovate/pull/7375/commits/68239c6ea99f0433298dda4476e6258567c87c11). 

Otherwise it's working with both [Global](https://github.com/fgreinacher/nuget-lockfile/pull/1/files) and [Docker](https://github.com/fgreinacher/nuget-lockfile-2/pull/1/files) binary sources.

2020-10-20 06:15 UTC, fgreinacher commented
(BTW: I first tried this on Windows, where I ran into several problems with the Docker binary source. I ignored this and switched to my Mac, assuming that it's OK like that. Tell me if this should actually work, I'd then dig a bitter deeper to see if I can write a proper issue)

2020-10-20 06:44 UTC, viceice commented
> (BTW: I first tried this on Windows, where I ran into several problems with the Docker binary source. I ignored this and switched to my Mac, assuming that it's OK like that. Tell me if this should actually work, I'd then dig a bitter deeper to see if I can write a proper issue)

This will never work on windows because the host and container path need to match. A workaround is to mounbt the local build into the renovate slim image and use that to run renovate in container. Then you are able to mount /tmp to renovate, which will be used as shared volume

2020-10-20 08:14 UTC, fgreinacher commented
> > (BTW: I first tried this on Windows, where I ran into several problems with the Docker binary source. I ignored this and switched to my Mac, assuming that it's OK like that. Tell me if this should actually work, I'd then dig a bitter deeper to see if I can write a proper issue)
> 
> This will never work on windows because the host and container path need to match. A workaround is to mounbt the local build into the renovate slim image and use that to run renovate in container. Then you are able to mount /tmp to renovate, which will be used as shared volume

Yeah, that's why I just switched to a proper machine 😁. Just wanted to make sure I didn't miss anything essential.

2020-10-20 08:17 UTC, viceice commented
Alternate would be to use wsl on windows 😉

2020-10-20 08:25 UTC, viceice approved these changes

2020-10-20 08:45 UTC, merged

2020-10-20 08:56 UTC, renovate-release commented
:tada: This PR is included in version 23.54.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.54.0)
- `23.54.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: