feat(worker): pass platform options to onboarding pr
renovatebot/renovate pull request #7614
Opened 2020-10-30 18:24 UTC by viceice

## Changes:

We now pass the platform pr options to the onboarding pr.

## Context:

closes #7613

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2020-11-03 10:24 UTC, viceice commented
@JamieMagee @rarkins Do you see any risks here?

2020-11-03 10:46 UTC, rarkins commented
There seems to be a small risk that we accidentally trigger GitLab's automerge on green feature. Even if it doesn't happen now, a refactoring in future would potentially trigger it?

2020-11-03 15:15 UTC, viceice commented
> There seems to be a small risk that we accidentally trigger GitLab's automerge on green feature. Even if it doesn't happen now, a refactoring in future would potentially trigger it?

Uhh, yes i think it can happen. Do we set `automerge=false` explicit for onboarding pr?

2020-11-04 07:41 UTC, JamieMagee approved these changes, later dismissed
Code changes look fine. Just the outstanding question around automerge of onboarding PRs for hosted Renovate

2020-11-04 09:18 UTC, rarkins requested changes
Disable autoMerge for onboarding

2020-11-04 09:55 UTC, viceice commented
> Disable autoMerge for onboarding

any hint where to add this flag? 🤔

2020-11-04 10:06 UTC, viceice commented
maybe here?
https://github.com/renovatebot/renovate/blob/80b691c807a6e2b6c98bcaab8198bf8932fcfa4e/lib/workers/repository/onboarding/branch/index.ts#L61

2020-11-04 10:07 UTC, rarkins requested changes

2020-11-04 10:07 UTC, rarkins commented on lib/workers/pr/index.ts
> +export function getPlafromPrOptions(
```suggestion
export function getPlatfromPrOptions(
```

2020-11-04 10:07 UTC, rarkins commented on lib/workers/pr/index.ts
> +          platformOptions: getPlafromPrOptions(config),
Maybe just mutate this result here, e.g. overriding `gitlabAutomerge` to set it to false?

2020-11-04 10:57 UTC, rarkins approved these changes

2020-11-04 14:18 UTC, merged

2020-11-04 14:30 UTC, renovate-release commented
:tada: This PR is included in version 23.71.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.71.0)
- `23.71.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: