feat(helmv3): Add support for bumpVersion
renovatebot/renovate pull request #7670
Opened 2020-11-06 15:54 UTC by mikebryant

## Changes:

Adds support for `bumpVersion` to the `helmv3` manager

## Context:

Closes #4728

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] Unit tests + ran on a real repository: https://github.com/mikebryant/renovate-test-helm-lock/pull/2/files

2020-11-06 19:58 UTC, mikebryant commented
The build is currently failing on test coverage - before I dig into trying to add some more tests, can I get a review of the feature itself etc please? :)

2020-11-10 12:52 UTC, rarkins requested changes
Looks good, can you demonstrate it against an npm example in a public repo to be safe?

2020-11-10 12:52 UTC, rarkins commented on lib/config/definitions.ts
> +    description: 'Bump the version in the package being updated',
```suggestion
    description: 'Bump the version in the package file being updated',
```

2020-11-10 12:59 UTC, mikebryant commented
> Looks good, can you demonstrate it against an npm example in a public repo to be safe?

Sure, done: https://github.com/mikebryant/renovate-test-helm-lock/pull/4/files

2020-11-10 21:06 UTC, merged

2020-11-10 21:19 UTC, renovate-release commented
:tada: This PR is included in version 23.77.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.77.0)
- `23.77.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: