docs: renew onboarding PR image
renovatebot/renovate pull request #7679
Opened 2020-11-08 11:30 UTC by HonkingGoose

## Changes:

- Renew the onboarding PR image

## Context:

The previous image uses old Renovate branding, and shows old welcoming text.
This PR uses the current branding and welcoming text.

Should I do something to get the filesize down?

| Old image filesize | New image filesize |
| :---: | :---: |
| 25.6 KB | 184.4 KB |

Closes #7527 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2020-11-08 17:26 UTC, rarkins commented
I recommend photopea.com as a great editor to try:

- Create new project
- Open existing PNG from computer
- File - Export As - PNG

And you can experiment with the quality setting there. Perhaps lower the quality, save to disk, then verify on the disk.

2020-11-08 17:26 UTC, rarkins requested changes
Try reducing image size

2020-11-08 19:15 UTC, HonkingGoose commented
Hi @rarkins! :wave: 

Thanks for the tips.

I've taken a new picture and used your tips to get the file size down.

Let me know what you think of this picture! :wink:

2020-11-11 10:19 UTC, merged

2020-11-11 11:51 UTC, renovate-release commented
:tada: This PR is included in version 23.78.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.78.0)
- `23.78.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: