docs: improve design decisions development documentation
renovatebot/renovate pull request #7709
Opened 2020-11-12 13:02 UTC by HonkingGoose

## Changes:

- Split long sentence into two parts
- Replace hard to understand sentence with a ordered list
- Small grammar fixes
- Use the active voice where possible

## Context:

Helps with issue #7626.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2020-11-12 13:06 UTC, HonkingGoose commented on docs/development/design-decisions.md
> +The script would even still work if you had it running from two different locations, as long as their configuration was the same.
The whole "State storage" thing is still worded in a confusing way to me. I don't know how I can rewrite this to be more clear... Do you have any ideas?

2020-11-12 13:06 UTC, HonkingGoose commented on docs/development/design-decisions.md
> +We use a cascading configuration.
I hope this is better than what we had. Please check my list if this is the right order.

2020-11-12 13:06 UTC, HonkingGoose commented on docs/development/design-decisions.md
> +That way it would be up to the users to determine which dependency upgrade(s) caused the build to fail.
I've tried to improve this sentence by splitting it up, but it still a bit of an passive voice construct.
Do you have ideas to get the same point accross in a more active style of voice?

2020-11-12 13:06 UTC, HonkingGoose commented on docs/development/design-decisions.md
> +Note: You can configure the branch names by using a string template.
Should we maybe say where this `string template` can be found?

2020-11-12 13:06 UTC, HonkingGoose commented on docs/development/design-decisions.md
> +This option is configurable. (WHERE/HOW???)
If we're only saying, this option is configurable, it's not very much help without saying where/how this can be configured, I think?

2020-11-12 15:39 UTC, rarkins requested changes

2020-11-12 15:39 UTC, rarkins commented on docs/development/design-decisions.md
> +By default, the script does not create a new PR if it finds an identical PR that's already closed.
```suggestion
By default, the script does not create a new PR if it finds a previously-closed PR with the same branch name and PR title (assuming the PR title has a version in it).
```

2020-11-12 15:39 UTC, rarkins commented on docs/development/design-decisions.md
> +This option is configurable. (WHERE/HOW???)
```suggestion
```

we can just remove this altogether

2020-11-13 05:37 UTC, merged

2020-11-13 13:54 UTC, renovate-release commented
:tada: This PR is included in version 23.83.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.83.0)
- `23.83.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: