fix(nuget): don't fail when updating lockfiles with private registries
renovatebot/renovate pull request #7779
Opened 2020-11-21 13:02 UTC by fgreinacher

## Changes:

We now create a temporary NuGet.config files to authenticate at private registries during lock file update. 

## Context:

Close #7769 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2020-11-21 13:17 UTC, fgreinacher commented
@viceice @rarkins Any idea what's going wrong here: https://github.com/renovatebot/renovate/pull/7779/checks?check_run_id=1435648957#step:11:28?

2020-11-21 16:25 UTC, viceice commented on lib/manager/nuget/artifacts.ts
> +import { fs } from '../../../test/util';
Wrong import. 😉

2020-11-21 17:38 UTC, fgreinacher commented on lib/manager/nuget/artifacts.ts
> +import { fs } from '../../../test/util';
Argh, thanks!

2020-11-21 17:50 UTC, viceice requested changes
You need to add the folder as a volume for docker mode

2020-11-21 17:54 UTC, fgreinacher commented
> You need to add the folder as a volume for docker mode

I [used `ensureCacheDir`](https://github.com/renovatebot/renovate/pull/7779/files#diff-983595d394c7e65d7e9afd380c9215a7aebfbd3d5e6f80fe8e31491dd4a7d72dR55) assuming the root cache dir would already be mounted. Not right?

2020-11-22 11:24 UTC, viceice approved these changes
You are right, cacheDir is already mounted.

2020-11-22 12:39 UTC, merged

2020-11-22 12:53 UTC, renovate-release commented
:tada: This PR is included in version 23.84.9 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.84.9)
- `23.84.9`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: