docs: fix broken link
renovatebot/renovate pull request #7804
Opened 2020-11-24 16:08 UTC by HonkingGoose

## Changes:

- Fix broken link

## Context:

The current fix works on the plain Markdown files in my code editor.
I'm not sure if this is what we want on the build, so please check my work.

I don't have the MkDocs site working on my end, so I cannot properly verify if this fixes the problem.

Closes #7803 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2020-11-24 16:20 UTC, rarkins approved these changes, later dismissed

2020-11-24 16:40 UTC, viceice requested changes
I don' think this works

2020-11-24 16:42 UTC, viceice commented on lib/manager/terragrunt/readme.md
> +You can create a custom [versioning config](/docs/usage/configuration-options.md#versioning) to support non-semver references.
```suggestion
You can create a custom [versioning config](/configuration-options.md#versioning) to support non-semver references.
```

2020-11-24 19:14 UTC, viceice approved these changes
🤞

2020-11-24 20:25 UTC, merged

2020-11-25 12:46 UTC, renovate-release commented
:tada: This PR is included in version 23.86.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.86.2)
- `23.86.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: