docs: improve Java documentation
renovatebot/renovate pull request #7821
Opened 2020-11-26 09:01 UTC by HonkingGoose

## Changes:

- Simplify sentence
- Fix grammar
- Split up long sentence into two parts
- Rewrite sentences to use active voice

## Context:

Helps with issue #7626.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2020-11-26 09:01 UTC, HonkingGoose commented on docs/usage/java.md
> +They are then looked up using Maven datasources and patched into PRs the usual way. (I think this needs some expanding on maybe?)
I need some help with expanding this section.

2020-12-02 14:56 UTC, rarkins requested changes

2020-12-02 14:56 UTC, rarkins commented on docs/usage/java.md
> +They are then looked up using Maven datasources and patched into PRs the usual way. (I think this needs some expanding on maybe?)
```suggestion
Once the Gradle plugin has detected the dependencies, lookups and updating will be performed like usual with datasources and direct patching of files.
```

2020-12-03 07:32 UTC, merged

2020-12-03 14:33 UTC, renovate-release commented
:tada: This PR is included in version 23.93.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.93.0)
- `23.93.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: