feat: ignorePrAuthor
renovatebot/renovate pull request #7853
Opened 2020-12-01 14:14 UTC by rarkins

## Changes:

Adds a new config option `ignorePrAuthor` that removes PR author filtering from platform `getPrList()`.

## Context:

This is needed if someone needs to migrate bot accounts, including from hosted app to self-hosted.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] Ran on a real repository (GitLab-only)

2020-12-01 14:49 UTC, zharinov commented
Not sure, but maybe something in `lib/util/git` may require changes. Or everything should be fine?

2020-12-01 14:52 UTC, JamieMagee commented on docs/usage/configuration-options.md
> +## ignorePrAuthor
Maybe add the example from the PR description as well (app to self-hosted).=

2020-12-01 14:58 UTC, JamieMagee commented
No changes on Azure + Gitea. Are they lacking the functionality right now?

2020-12-01 15:07 UTC, rarkins commented
> No changes on Azure + Gitea. Are they lacking the functionality right now?

Yeah, I couldn't see any place where they filter their PR list calls by author.

Azure: https://github.com/renovatebot/renovate/blob/e3ccc35d4a82feaa21c02cdedeaa6a3c4d2bce0e/lib/platform/azure/index.ts#L186-L193

Gitea: https://github.com/renovatebot/renovate/blob/e3ccc35d4a82feaa21c02cdedeaa6a3c4d2bce0e/lib/platform/gitea/index.ts#L408-L413

2020-12-01 15:12 UTC, viceice requested changes
some small changes

@JamieMagee Yes, the other platforms don't have such a filter (or we maybe aren't aware of, like gitlab scope)

2020-12-01 15:12 UTC, viceice commented on lib/platform/bitbucket-server/index.ts
>        'role.1': 'AUTHOR',
```suggestion
```

I think this needs to be removed too

2020-12-01 15:12 UTC, viceice commented on lib/platform/bitbucket-server/index.ts
> +      searchParams['username.1'] = config.username;
```suggestion
      searchParams['username.1'] = config.username;
      searchParams['role.1'] = 'AUTHOR';
```
and added here

2020-12-01 15:12 UTC, viceice commented on lib/platform/gitlab/index.ts
> +  }
```suggestion
  if (config.ignorePrAuthor) {
    // https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests
    // default: `scope=created_by_me`
    searchParams.scope = 'all';
  }
```

https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests

2020-12-01 15:13 UTC, JamieMagee commented
Okay, I'll take a look at the current state of the Azure DevOps API for this feature.

2020-12-02 07:41 UTC, viceice commented
what about issue filter?
https://github.com/renovatebot/renovate/blob/bffd90de6684eae8753ca234cb207139e4bd21f9/lib%2Fplatform%2Fgitlab%2Findex.ts#L684

2020-12-02 13:54 UTC, viceice approved these changes

2020-12-02 14:01 UTC, merged

2020-12-02 14:16 UTC, renovate-release commented
:tada: This PR is included in version 23.91.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.91.0)
- `23.91.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: