refactor(build): Pre-compile files imported from data folder
renovatebot/renovate pull request #7896
Opened 2020-12-07 09:20 UTC by zharinov

## Changes:

According to microsoft/TypeScript#10939, it would be tricky to just `import example from 'example.txt''`.
Thus, we're using `data/` folder for this.
After this PR, we pre-compile files from this folder and import it as JavaScript `Map`.
[Generated file example](https://gist.github.com/zharinov/d83a2c1379db066538c276216771a18d)

## Context:

Ref: #7157

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2020-12-07 09:28 UTC, viceice commented on tools/generate-imports.ts
> +    const prettyFileContent = `\n${rawFileContent.replace(/`/g, '\\`')}\n`;
I think `JSON.stringify` is a more secure solution

2020-12-07 13:40 UTC, viceice requested changes
Looks like it need coverage fixes now 🙃

2020-12-07 13:40 UTC, viceice commented on tools/generate-imports.ts
> +  const contentMapAssignments = [];
```suggestion
  const contentMapAssignments: string[] = [];
```

2020-12-07 13:51 UTC, zharinov commented
Ha, didn't expect it will help to get rid of dependency I found problematic some time ago

2020-12-07 13:54 UTC, viceice submitted a review, later dismissed

2020-12-07 13:54 UTC, viceice commented on yarn.lock
> -    lodash._getnative "*"
haha, renovate yarn patch strikes again 😛

2020-12-07 13:55 UTC, zharinov commented on yarn.lock
> -    lodash._getnative "*"
I was wrong about `find-up`

2020-12-07 13:56 UTC, viceice commented
🤦‍♂️  nuget needs find-up
![image](https://user-images.githubusercontent.com/1798109/101359276-552d0700-389c-11eb-8833-d373557727d3.png)

2020-12-07 15:37 UTC, viceice approved these changes

2020-12-08 13:07 UTC, merged

2020-12-08 13:20 UTC, renovate-release commented
:tada: This PR is included in version 23.97.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/23.97.0)
- `23.97.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: