feat(helm-values): Support for bumpVersion
renovatebot/renovate pull request #8240
Opened 2021-01-10 22:03 UTC by chgl

## Changes:

Implements the `bumpPackageVersion` interface for the `helm-values` manager. Because `helm-values`' packageFile is different from the file containing the version to be bumped (the `Chart.yaml`) this required adding support for decoupling the two. For now, only one additional `bumpVersionPackageFile` is supported, if the need arises it would probably be cleanest to provide a list of files that will need to be updated should the version be bumped.

I've tested it in the repo here: https://github.com/chgl/renovate-helm-values-bumpversion-test/pull/5/files and it *seems* to work.

## Context:

Closes #8231

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

2021-01-11 08:15 UTC, rarkins requested changes
Small types change

2021-01-11 08:24 UTC, rarkins commented on lib/manager/common.ts
> +  bumpedFile?: BumpedPackageFile;
I'm starting to think version bumping could/should be part of "artifacts updating" - but I don't object to continuing this PR as is. Agree with the idea to make it an array.

2021-01-11 08:25 UTC, rarkins commented
A potential problem in future (not affecting this functionality I think) is that the `Chart.yaml` could have *already* been updated by Renovate and if we read it from disk in this bumpPackageVersion function then we'll get the pre-updated version and not the updated one. But that's a bigger problem to solve.

2021-01-11 13:56 UTC, chgl commented on lib/manager/common.ts
> +  bumpedFile?: BumpedPackageFile;
should I create an issue for this? "Investigate using artifacts updating for version bumping" (better wording suggestions welcome ;)

2021-01-11 14:05 UTC, rarkins approved these changes, later dismissed

2021-02-27 20:24 UTC, chgl commented
is there

> A potential problem in future (not affecting this functionality I think) is that the `Chart.yaml` could have _already_ been updated by Renovate and if we read it from disk in this bumpPackageVersion function then we'll get the pre-updated version and not the updated one. But that's a bigger problem to solve.

Agreed! In this case, the helmv3 manager is able to bump the version of Chart.yaml as well, however since `bumpVersion` is a global setting, both this and the helmv3 manager would try to bump the version to the same value, overriding each other but still arriving at the same version.

Is there anything else I could improve or address for this PR?

2021-02-28 05:53 UTC, rarkins approved these changes

2021-02-28 05:53 UTC, merged

2021-02-28 06:28 UTC, renovate-release commented
:tada: This PR is included in version 24.67.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.67.0)
- `24.67.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: