fix: fetch changelog from self-hosted gitlab independent from url
renovatebot/renovate pull request #8336
Opened 2021-01-18 16:54 UTC by casdevs

## Changes:

fetches changelog from self-hosted Gitlab instance even if its url does not contain the word "gitlab"

## Context:

Closes #6704

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2021-01-18 16:56 UTC, casdevs commented
I'm not sure about 2-3 other source code locations where also only `.includes('gitlab')` is checked.

Are my code changes enough to close #6704?

2021-01-18 17:13 UTC, viceice requested changes
Needs tests

2021-01-18 17:13 UTC, viceice commented on lib/workers/pr/changelog/index.ts
> +
```suggestion
```
Use global url object. Module is deprecated.

https://nodejs.org/api/url.html#url_new_url_input_base

2021-01-18 17:13 UTC, viceice commented on lib/workers/pr/changelog/index.ts
> +          URL.parse(args.endpoint).hostname)
```suggestion
        new URL(args.sourceUrl).hostname ===
          new URL(args.endpoint).hostname)
```

2021-01-18 20:32 UTC, viceice approved these changes

2021-01-19 08:15 UTC, rarkins approved these changes

2021-01-19 08:36 UTC, merged

2021-01-19 08:51 UTC, renovate-release commented
:tada: This PR is included in version 24.24.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.24.0)
- `24.24.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: