feat: add preset to opt-out of rebase checkbox within PRs
renovatebot/renovate pull request #8390
Opened 2021-01-22 15:04 UTC by HonkingGoose

## Changes:

Adds a preset that removes the `{{{control}}}` template from the PR.
This in essence removes the checkbox to "rebase this pr".
This can help when a user has CI that checks if all checkboxes within a PR are ticked.

## Context:

Inspired by #8387.

I'd feel better if we had a unit test to check that this preset actually works, and keeps working in the future.
We are migrating away from the rebase term, so a unit test would alert us if we're breaking the new preset.

Also please check if this preset is added to the right document.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2021-01-22 15:08 UTC, viceice approved these changes, later dismissed

2021-01-22 15:10 UTC, rarkins requested changes

2021-01-22 15:10 UTC, rarkins commented on lib/config/presets/internal/default.ts
> +  disableRebaseCheckboxInPRs: {
```suggestion
  disableControls: {
```

2021-01-22 15:10 UTC, rarkins commented on lib/config/presets/internal/default.ts
> +      'Remove the checkbox to rebase the PR, this can help when your CI checks if all checkboxes are ticked.',
```suggestion
      'Remove the checkbox controls from PRs',
```

2021-01-24 21:08 UTC, HonkingGoose commented
Seems the auto-merge functionality got stuck somehow, I've merged the latest `master` branch.
Let's see what happens now.

2021-01-24 21:09 UTC, viceice approved these changes

2021-01-24 21:10 UTC, viceice commented
@HonkingGoose approval was missing. 🤗

2021-01-24 21:11 UTC, HonkingGoose commented
@viceice Ah okay. 😄 I thought it was because my fork branch was not up-to-date with `renovate/master`... 🙃

2021-01-24 21:15 UTC, viceice commented
This is another cause. All required checks need to be green. 🤗

2021-01-25 06:29 UTC, merged

2021-01-25 06:43 UTC, renovate-release commented
:tada: This PR is included in version 24.28.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.28.0)
- `24.28.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: