fix: add link to neo4j release notes
renovatebot/renovate pull request #8406
Opened 2021-01-25 01:44 UTC by jimmycrequer

2021-01-25 01:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=8406) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=8406) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=8406) it.</sub>

2021-01-25 05:01 UTC, viceice requested changes
Needs lint fix

2021-02-01 01:29 UTC, Mandymoore680 submitted a review, later dismissed
Ok

2021-02-01 05:40 UTC, viceice approved these changes
fixed lint issue 😈

2021-02-01 09:21 UTC, merged

2021-02-01 09:34 UTC, renovate-release commented
:tada: This PR is included in version 24.32.3 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.32.3)
- `24.32.3`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-02-01 23:20 UTC, jimmycrequer commented
@viceice Thank you for fixing the lint issue!