fix: remove unused binarySource=auto
renovatebot/renovate pull request #8461
Opened 2021-01-29 13:50 UTC by rarkins

## Changes:

Removes binarySource=auto

## Context:

It isn't used anymore

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2021-01-29 14:07 UTC, viceice submitted a review, later dismissed

2021-01-29 14:26 UTC, HonkingGoose requested changes

2021-01-29 14:26 UTC, HonkingGoose commented on lib/config/definitions.ts
> +      'Controls whether third party tools like npm or gradle are called directly, or via Docker sidecar containers',
```suggestion
      'Controls whether third party tools like npm or gradle are called directly, or via Docker sidecar containers.',
```

Add missing punctuation. 😄 🙃

2021-02-04 11:14 UTC, merged

2021-02-04 11:26 UTC, renovate-release commented
:tada: This PR is included in version 24.38.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.38.2)
- `24.38.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: