feat(datasource): perform filtering in datasource
renovatebot/renovate pull request #8475
Opened 2021-01-30 16:45 UTC by rarkins

## Changes:

Add generic `constraints` filtering to datasource index and removes from `pypi`.

## Context:

Closes #8365

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

2021-01-30 17:11 UTC, zharinov commented on lib/datasource/index.ts
> +  });
Maybe, use `forEach` instead?

2021-01-30 20:11 UTC, viceice requested changes
Needs new tests

2021-01-30 20:11 UTC, viceice commented on lib/datasource/index.ts
> +        }
i think this can be d
```suggestion
        if (!release.constraints?.[constraintName]) {
          return true;
        }
```

2021-01-30 20:11 UTC, viceice commented on lib/datasource/index.ts
> +  });
```suggestion
  res.releases.forEach((release) => delete release.constraints);
```

2021-01-30 20:31 UTC, rarkins commented
@viceice it's tested via the existing `pypi` tests

2021-01-30 20:46 UTC, viceice commented
> @viceice it's tested via the existing `pypi` tests

But currently it lacks coverage. 😉

2021-01-31 07:57 UTC, viceice approved these changes

2021-01-31 08:23 UTC, merged

2021-01-31 08:35 UTC, renovate-release commented
:tada: This PR is included in version 24.31.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.31.0)
- `24.31.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: