chore: migrate from master branch to main
renovatebot/renovate pull request #8663
Opened 2021-02-12 13:56 UTC by HonkingGoose

## Changes:

- `master` -> `main` for CI
- Replace links to `renovatebot/renovate master` to point to `renovatebot/renovate main` instead

Really rough draft to get an idea of the changes needed to migrate from `master` to `main` on this repo.

Maybe @rarkins can make a complete copy of this repo somewhere safe and try this out, and see where stuff breaks.
I have **not** tested this myself yet, as I would need to replicate the full setup that this repository has somehow (external bots, branch protection rules, semantic release bot, etc.)

I have also **not replaced** any mentions of `master` in the `docs/usage` section or in any fixtures or snapshots, as that pertains to the code of Renovate bot itself and what branches the bot supports on specific platforms.

## Context:

Explore what changes we would probably need to migrate from `master` to `main` as the default branch on the `renovatebot/renovate` repository.

Reference #8153.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-02-12 14:04 UTC, viceice commented
needs branch protection added for main, should be doable before exists

2021-02-12 14:05 UTC, HonkingGoose commented
Yeah the branch protection rules for `main` should be setup **before** merging.

2021-02-12 14:05 UTC, viceice approved these changes, later dismissed
Assuming you used search and replace ;)

2021-02-12 14:10 UTC, HonkingGoose commented
I used the search funtion in VSCode, with the following settings:

Search for string `master`.
Files to exclude: `__fixtures__, .spec.ts, __snapshots__`

2021-02-12 14:20 UTC, HonkingGoose commented
GitHub will migrate the branch protection rules automatically if you're doing the migration from `master` to `main` via the GitHub interface (see image): https://github.com/github/renaming/blob/main/README.md#renaming-existing-branches

2021-02-12 16:00 UTC, JamieMagee approved these changes, later dismissed

2021-02-18 14:54 UTC, HonkingGoose commented
Merged the latest `master` branch and resolved the merge conflict, that was caused by the newlines change in the label bot file: `label-actions.yml`. I've kept the newlines from `master` as having 2 newlines makes it so that the bot uses paragraphs.

2021-02-18 16:21 UTC, JamieMagee commented
@HonkingGoose This looks ready for merge, right? But it should be manually merged by @rarkins, as there are manual steps to follow.

2021-02-18 16:34 UTC, HonkingGoose commented
@JamieMagee Yeah I think this is ready for final review and merge.
Do you have any tips on the migration @JamieMagee?

The main idea, I think, would be to freeze everything, turn off all the bots, and migrate via GitHub interface, merge this PR, confirm tests work, and then enable bots one by one, with the Semantic Release bot as the last one to be re-enabled.

Proposed steps:

1. Stop manually merging things into `master`, (basically a full freeze).
1. Turn off all bots that do things on our `master` branch (Renovate bot, Semantic Release, other CI).
1. Use the GitHub interface to migrate from `master` to `main`.
1. Confirm branch protections are still good on `main`.
1. GitHub will re-target all open pull requests (including this one).
1. Merge this PR into `main` so that all the CI uses the new `main` branch.
1. Confirm branch status checks work properly again.
1. Turn on bots one by one (do Semantic Release bot last).

2021-02-20 05:38 UTC, JamieMagee commented
That sounds like a comprehensive migration plan. Could I suggest one more thing: can we try this on one of the other repos first as a test run for the main renovate repository?

2021-02-20 05:48 UTC, rarkins commented
Not sure semantic release needs to be turned off as long as we don't add any release-triggering commits to master/main?

And yes maybe let's do all the smaller repos first and finish with this one.

2021-02-20 09:04 UTC, HonkingGoose commented
> Could I suggest one more thing: can we try this on one of the other repos first as a test run for the main renovate repository?

Good idea! It's probably safer to try the smaller repos first, see if we've got all things covered, and as the last step migrate the main renovate repository.

> Not sure semantic release needs to be turned off as long as we don't add any release-triggering commits to master/main?

I'm trying to make sure that we don't create releases unnecessarily. But if we don't use any `fix:` or `feat:` or `refactor:` commits we should probably be safe?

2021-03-05 09:06 UTC, rarkins commented
I updated the renovatebot/pep440 repo to use `main` and it went smoothly. e.g. PRs in progress were retargeted, actions continued fine.

This guide for local development pops up:

![image](https://user-images.githubusercontent.com/6311784/110092941-75386d80-7d9a-11eb-9653-9dbc1c67da88.png)

2021-03-06 06:07 UTC, JamieMagee commented
Time to do the other repos, followed by this one?

2021-03-17 22:00 UTC, HonkingGoose commented
Merged in current `master` and checked if the new `stale-action` needs anything (it doesn't as it doesn't rely on the concept of a branch😄).

2021-03-20 23:01 UTC, rarkins commented
I think I've renamed all our repos except this one plus these:
- https://github.com/renovatebot/renovatebot.github.io
- https://github.com/renovatebot/docker-renovate-full
- https://github.com/renovatebot/docker-buildpack
- https://github.com/renovatebot/internal-tools
- https://github.com/renovatebot/.github

@viceice do you think they're all safe for a simple rename?

2021-03-21 07:40 UTC, viceice commented
> I think I've renamed all our repos except this one plus these:
> - https://github.com/renovatebot/renovatebot.github.io

Needs workflow update

> - https://github.com/renovatebot/docker-renovate-full

This too

> - https://github.com/renovatebot/docker-buildpack 

This too

> - https://github.com/renovatebot/internal-tools 

This too

> - https://github.com/renovatebot/.github

 Should be safe.

> 
> @viceice do you think they're all safe for a simple rename?

2021-03-21 07:41 UTC, rarkins commented
@viceice I've been checking them all out and updating workflows so no worries there. I was just concerned in case any of these are referred to by *other* repositories in workflows and could break if they somehow hardcode master

2021-03-21 07:45 UTC, viceice commented
I'm pretty sure they don't hardcode any master reference beside the workflow

2021-03-21 09:23 UTC, HonkingGoose commented
GitHub _should_ also redirect links pointing to old `master` to new `main` automatically.

Quote from https://github.com/github/renaming#whats-already-changed

> We've updated GitHub.com to redirect links that contain the deleted branch name such as master to the corresponding link in the repository's new default branch.

2021-03-21 09:44 UTC, HonkingGoose commented
We should probably put up a pinned issue on the repositories we've just changed/are about to change.

I'm thinking of something like this:

```markdown
## Help the branch was renamed how do I fix my fork?

It's easy to fix your fork, as you can do most of the work straight from the GitHub web interface.

1. Go to your forks "homepage" on GitHub.
2. GitHub will have a popup over your `master` branch name, to tell you that the upstream repository has changed its default branch name.
3. Rename your forks branch from `master` to `main` from within the GitHub interface (Settings -> Branches -> Default branch -> click on the pencil icon to rename.
4. Let GitHub automatically rename your fork's branch name.
5. Go back to your fork's homepage, and follow the instructions GitHub gives you to rename the branch name on your local clone of your fork.
```

2021-03-21 12:07 UTC, viceice commented
manual edit of `.\.git\refs\remotes\origin\HEAD` and change master to main. git won't do this automatically 😕

2021-03-21 12:13 UTC, rarkins commented
GitHub provides a nice 3-line command to run locally to switch an existing clone from master to main - I'll post it here

2021-03-21 12:15 UTC, viceice commented
> GitHub provides a nice 3-line command to run locally to switch an existing clone from master to main - I'll post it here

Yes, but it won't change the mentioned refs 😕

2021-03-21 14:55 UTC, rarkins commented
> > GitHub provides a nice 3-line command to run locally to switch an existing clone from master to main - I'll post it here
> 
> Yes, but it won't change the mentioned refs 😕

Here's what it is, in case it helps anyway:

```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
```

2021-03-21 14:59 UTC, viceice commented
Found a solution: `git remote set-head origin main` 🎉 

https://gist.github.com/libitte/cbde168d26bc5faf9bf9fef648091b42

2021-03-21 17:32 UTC, JamieMagee commented
👍 to @HonkingGoose's pinned issue idea. Also 👍 to including GitHub's information about switching your local clone, and @viceice's refs information.

Is 1 week's notice enough for the change in this repository?

2021-03-29 18:11 UTC, HonkingGoose commented
> Is 1 week's notice enough for the change in this repository?

@JamieMagee 1 week's notice in a pinned issue _before_ starting is fine.

I'd say keep the issue pinned and open for a month _afterwards_, so that the frequent contributors can find the help quickly.

After a month we unpin and close the issue and link to it when somebody asks for help on how to fix their fork.

2021-04-01 10:32 UTC, viceice commented
`.releaserc` needs `"branches": ["main"]`

2021-04-01 11:06 UTC, HonkingGoose commented
> `.releaserc` needs `"branches": ["main"]`

You're right, good catch! 😄 

@viceice Can you check if the current `.releaserc` config is correct?

2021-04-01 11:18 UTC, viceice commented on .releaserc
> +  ],
```suggestion
  "branches": ["main"],
```

This is enough

2021-04-08 10:02 UTC, viceice commented
i think the v25 release will be a good point to switch to `main`

2021-04-21 20:44 UTC, HonkingGoose commented
I've merged the latest changes from `master` into this branch as there were some changes related to making a build and release on the `v24` branch that I needed to pull in.

I've fixed the "bad merge" in the `.releaserc` file (it had two objects keys for the `branches` object...). We now have one `branches` object with configuration for the `v24` branch and the `main` branch.

This should be OK again, but please check my work.

2021-04-22 06:55 UTC, viceice requested changes
needs update, maybe deconflicting 😉

2021-04-22 07:50 UTC, viceice approved these changes, later dismissed

2021-04-22 08:22 UTC, viceice approved these changes

2021-04-22 14:17 UTC, viceice commented
new step popped up:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

2021-04-22 14:32 UTC, merged

2021-04-22 14:51 UTC, renovate-release commented
:tada: This PR is included in version 25.1.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/25.1.2)
- `25.1.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-04-22 20:58 UTC, HonkingGoose commented
Well that went smoothly! The build still works, the semantic release bot kept humming along, and things were fine. 😄 🎉 ✨ ✨ ✨ 

Thank you @viceice, @rarkins and @JamieMagee for the reviews, tips and suggestions to get this landed. ❤️