feat: static modules
renovatebot/renovate pull request #8679
Opened 2021-02-13 09:20 UTC by viceice

## Changes:

## Context:

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-02-13 15:07 UTC, JamieMagee commented
Is generate-imports required anymore?

2021-02-13 15:33 UTC, viceice commented
Yes, for node schedule and pip_setup extractor. Maybe it should be renamed. 😏

2021-02-13 16:49 UTC, rarkins requested changes
We should add a test for each of these modules to make sure that all (relevant) subdirectories are imported and match the import name.

2021-02-13 16:49 UTC, rarkins commented on tools/generate-imports.ts
> +    // });
Delete thesee

2021-02-13 16:51 UTC, viceice commented on tools/generate-imports.ts
> +    // });
sure

2021-02-13 17:51 UTC, viceice commented
Strange, not sure why it fails with oom. 🤔

2021-02-13 18:17 UTC, JamieMagee reviewed
Ugh, leaving a comment from the GitHub app starts a full review

2021-02-13 18:18 UTC, JamieMagee commented on tools/generate-imports.ts
> +    // await generate({ path: 'datasource', types: ['DatasourceApi'] });
```suggestion
```

2021-02-13 18:18 UTC, JamieMagee commented on tools/generate-imports.ts
> +    // });
```suggestion
```

2021-02-13 18:35 UTC, rarkins commented
Yes, happens to me often. It defaults to pending comments in a review, not sure if you can change that

2021-02-28 06:17 UTC, rarkins requested changes
Needs 2 missing managers added :)

2021-03-02 14:51 UTC, viceice commented
> We should add a test for each of these modules to make sure that all (relevant) subdirectories are imported and match the import name.

https://github.com/renovatebot/renovate/blob/21ebb743493ebb37b82749a282e70c573cc54502/lib/datasource/index.spec.ts#L49
https://github.com/renovatebot/renovate/blob/53ca91301f6a36c0c87e7d6b06b1bd8c9ec1b283/lib/manager/index.spec.ts#L35
https://github.com/renovatebot/renovate/blob/04d2cd1514d8f7e84844e2c5e6091478f59c21db/lib/platform/index.spec.ts#L29
https://github.com/renovatebot/renovate/blob/53ce3cf4d6bc2995aa2f95fdeb473873f09f5e69/lib/versioning/index.spec.ts#L38

Already tested 🙃

2021-03-02 15:53 UTC, rarkins approved these changes

2021-03-02 15:57 UTC, merged

2021-03-02 16:16 UTC, renovate-release commented
:tada: This PR is included in version 24.71.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.71.0)
- `24.71.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: