feat(github-actions): support jobs.<job_id>.container.image
renovatebot/renovate pull request #8829
Opened 2021-02-23 17:31 UTC by douglasduteil

## Changes:

Supported github actions syntax `jobs.<job_id>.container.image`

```
container:
  image: hadolint/hadolint:v1.19.0-alpine
```

see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainerimage

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-02-23 21:26 UTC, viceice reviewed
I don't see any new test for it?

2021-02-23 21:26 UTC, viceice commented on lib/manager/github-actions/extract.ts
> +      dep.versioning = dockerVersioning.id;
@rarkins I think this is obsolete?

2021-02-23 22:05 UTC, rarkins commented on lib/manager/github-actions/extract.ts
> +      dep.versioning = dockerVersioning.id;
Yes, it is not necessary

2021-02-24 12:04 UTC, douglasduteil commented
>  don't see any new test for it?

Test added @viceice :)

2021-02-25 07:49 UTC, rarkins commented on lib/manager/github-actions/extract.ts
> +      dep.versioning = dockerVersioning.id;
Please remove this line

2021-02-25 07:49 UTC, rarkins requested changes
Remove versioning.

2021-02-25 10:56 UTC, douglasduteil commented
> Remove versioning.

Done @rarkins 👍

2021-02-26 15:44 UTC, rarkins approved these changes

2021-02-26 15:44 UTC, merged

2021-02-26 16:15 UTC, renovate-release commented
:tada: This PR is included in version 24.66.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.66.0)
- `24.66.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-03-01 09:07 UTC, viceice commented
@douglasduteil We had to revert this pr, see #8897