feat(helmfile): Parse multidoc yaml
renovatebot/renovate pull request #8832
Opened 2021-02-23 22:32 UTC by kuzaxak

We should skip empty docs to be able to parse last one with contains
releases map.

## Changes:

* Skip empty docs in multidoc yaml
* Return `null` in case of empty release map

## Context:

Closes #8682

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [X] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-02-23 22:36 UTC, rarkins commented on lib/manager/helmfile/extract.ts
> +      continue;
```suggestion
      continue; // eslint-disable-line no-continue
```

2021-02-23 22:36 UTC, rarkins commented on lib/manager/helmfile/extract.ts
> +  if (deps.length == 0) {
```suggestion
  if (!deps.length) {
```

2021-02-26 06:46 UTC, rarkins requested changes
Let's make sure we have a test

2021-02-26 16:50 UTC, kuzaxak commented
> Let's make sure we have a test

What do you mean by that? 
Unit tests?

Could you add a link to example, I can help you with that. We really need this functionality :)

2021-02-26 17:16 UTC, rarkins commented
There are already unit tests for this manager in the same directory - just none with multi doc. Check out the corresponding spec.js file

2021-04-16 11:20 UTC, closed without merging