feat(go): support self hosted go modules in gitlab
renovatebot/renovate pull request #8876
Opened 2021-02-25 19:40 UTC by davidgwcurve

## Changes:

Fixes issue #8859, https://github.com/renovatebot/renovate/issues/8859. 

```
- Query hostRules for hostType=gitlab, url=https://[go module]
- If the answer back from hostRules contains a token field, then we know it's a GitLab host and can redirect the lookup to a gitlab tags one
```

Also fixes the same logic in the changelog functionality, as after this issue was resolved I got 404's. 

TODO: Tests

## Context:

Closes #8859

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or **(TODO)**
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-02-25 21:40 UTC, HonkingGoose commented
@davidgwcurve Your latest commit includes changes to `package.json` and `yarn.lock` files, was that intended?

2021-02-26 06:22 UTC, rarkins requested changes
Revert package json changes

2021-03-01 16:02 UTC, davidgwcurve commented on lib/datasource/go/index.spec.ts
> +        .reply(200);
there is a test that checks for a 404 returned from the specified URL already, this test should actually be checking that the call was successful but the code doesn't know how to handle the dependency (i.e. not github/gitlab.com/not a gitlab hostRules)

2021-03-01 16:28 UTC, davidgwcurve commented
@rarkins I've added unit tests now and ran on our own repository, it works as expected.

2021-03-01 17:34 UTC, rarkins approved these changes

2021-03-01 17:35 UTC, merged

2021-03-01 18:19 UTC, renovate-release commented
:tada: This PR is included in version 24.70.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.70.0)
- `24.70.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: