feat(util): Add lightweight parseUrl function
renovatebot/renovate pull request #9019
Opened 2021-03-07 16:45 UTC by zharinov

## Changes:

Simplest wrapper for new WHATWG URL parsing API.
Separate PRs which use it in `datasource/`, `manager/` and `workers/` directories are coming.
More complicated cases (mostly, `auth` field in `platform/` directory) will be handled separatedly.

## Context:

Ref: #7797

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-03-07 18:46 UTC, viceice commented
I've a branch for refactoring url usage too. Maybe i forgot to push it. Will do it tomorrow morning, maybe it helps to speed up this. 🤗

2021-03-07 18:47 UTC, viceice commented
This also only works with absolute urls.

2021-03-08 13:32 UTC, viceice requested changes
needs deconflicting

pushed my branch: https://github.com/renovatebot/renovate/tree/refactor/url-module

2021-03-08 13:51 UTC, rarkins commented
@viceice shall we use yours instead?

2021-03-08 13:56 UTC, viceice commented
> @viceice shall we use yours instead?

Sure, but it's not fully done. some tests are failing because of relative urls and i'm not sure hos to solve that properly.
Maybe add a `parseUrlLegacy` function for that case?

2021-03-13 08:05 UTC, viceice reviewed
We should use this pr and i'll rebase my branch onto this

2021-03-13 08:05 UTC, viceice commented on lib/util/url.ts
> +  } catch (err) /* istanbul ignore next */ {
```suggestion
  } catch (err) {
```

This is already tested 🙃

2021-03-13 08:05 UTC, viceice submitted a review, later dismissed

2021-03-13 08:41 UTC, viceice approved these changes

2021-03-13 08:41 UTC, merged

2021-03-13 08:57 UTC, renovate-release commented
:tada: This PR is included in version 24.80.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.80.0)
- `24.80.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: