feat: adapt for using jenkins as build system and integration for gitlab pipeline
renovatebot/renovate pull request #9192
Opened 2021-03-18 08:39 UTC by Tristar666

Check if MR cannot be merged for gitlab automerge
Fix bug with cache while getting information about MR for gitlab automerge.

## Changes:
Increase number of attempts to 100 for gitlab automerge
Check if MR cannot be merged for gitlab automerge
Fix bug with cache while getting information about MR for gitlab automerge.

## Context:

We use jenkins as build system with gitlab plugin for integration with gitlab pipelines. To start jenkins job we use web hooks and for a while build start and create pipeline in gitlab using jenkins plugin. In that case I increased initial delay for gitlab automerge. 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-03-18 08:53 UTC, HonkingGoose commented
Hi @Tristar666, thanks for making this PR to help us out! 😄 🎉 

Can you please tick the appropriate checkboxes in your original post?
That helps us to see at a glance what's going on.

To do this, you can either:

- Click on the wanted checkbox with your mouse
- Or you can fill in the checkbox with your keyboard while in the online text editor, so that it looks like this: `- [X]`

Greetings,

HonkingGoose

2021-03-20 21:17 UTC, rarkins commented
Is the comment of "Increase number of attempts to 100" outdated?

The new initDelay of 15s is double the previously attempts combined (0.5s, 1s, 1.5s, 2s, 2.5s = 7.5s). Now it will be 15s, 30s, 45s, 60s, 65s = ~3.5 minutes.

This seems very high and I don't see any justification for it yet, although the `useCache` fix seems valid.

2021-03-20 21:17 UTC, rarkins requested changes
Requires more info on justification

2021-03-21 06:35 UTC, Tristar666 commented
Hello!
>> Is the comment of "Increase number of attempts to 100" outdated?
Yes, it is outdated.
>> Now it will be 15s, 30s, 45s, 60s, 65s = ~3.5 minutes
We faced with problem due to high load on server, pipeline can be in Pending state for a long time.

2021-03-21 06:45 UTC, rarkins commented
Are you trying to adjust this feature so that it waits for the pipeline to *finish*?

2021-03-21 07:33 UTC, Tristar666 commented
Not to finish, only to start (status running). When it starts (status running), renovate sends PUT with merge_when_pipeline_succeeds and we need to wait for pipeline to finish.

2021-03-21 07:43 UTC, rarkins commented
@viceice what are your thoughts on this? If this affected the hosted gitlab.com app still there's no way I'd want to block a worker for 3.5 minutes because someone's got slow Jenkins..

2021-03-21 07:43 UTC, viceice commented
The problem is, that on jenkins the sourcode plugins are responsible for sending the build state, but they are first called when the pipeline starts.

So when all / required worker are busy, the jobs are queued and no state is send.

2021-03-21 07:48 UTC, viceice commented
Maybe this timeout should be an admin config option. Or at least a experimental env.

2021-03-21 07:51 UTC, rarkins commented
OK so:
- Apply the cache fix in this PR
- Allow the retry interval to be configurable via experimental variable?

2021-03-21 07:52 UTC, viceice commented
@Tristar666 another solution is to use a dummy jenkins pipelin step without an agent, that should trigger the gitlab state a lot earlier.

2021-07-30 11:25 UTC, closed without merging