feat(config): empty manager additionalBranchPrefix
renovatebot/renovate pull request #9373
Opened 2021-04-03 07:34 UTC by rarkins

## Changes:

Resets any language or manager additionalBranchPrefix values to empty string. Add the `compatibility:additionalBranchPrefix` prefix to restore previous behavior.

## Context:

BREAKING CHANGE: Removal of default additionalBranchPrefix values will cause branch names to change for docker/helm/buildkite/cargo/homebrew.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

2021-04-03 11:24 UTC, HonkingGoose requested changes

2021-04-03 11:24 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +Some managers previously populate this field, but they no longer do it by default.
```suggestion
Some managers previously populated this field, but they no longer do so by default.
```

- The sentence is in the past tense, so `populate` should be `populated`.
- `do it` -> `do so` looks better to me.

2021-04-04 07:47 UTC, viceice approved these changes
Is this enabled by default? Should we mention it on docs?

2021-04-04 08:58 UTC, rarkins commented
> Is this enabled by default? Should we mention it on docs?

We're removing defaults now, so it will cause some autoclosing/reopening due to branch name changes. Not sure if any further documentation will really help.

2021-04-04 09:00 UTC, viceice approved these changes

2021-04-04 09:02 UTC, merged