refactor(platform): getRawFile and getJsonFile throw instead of null
renovatebot/renovate pull request #9413
Opened 2021-04-06 12:22 UTC by zharinov

## Changes:

In order to show good error messages, it would be better to throw + handle, instead of return `null` + logging

## Context:

Ref: #9171

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-04-06 12:24 UTC, zharinov commented on lib/platform/gitlab/__snapshots__/index.spec.ts.snap
> +    "url": "https://gitlab.com/api/v4/projects/some%2Frepo/repository/files/dir%2Ffile.json?ref=HEAD",
To make `getJsonFile` tests look more uniform, I've intentionally added `dir/` prefix here

2021-04-06 12:25 UTC, zharinov commented on lib/platform/gitlab/index.spec.ts
> +      await expect(gitlab.getJsonFile('dir/file.json')).rejects.toThrow();
Note: `dir/` prefix was added

2021-04-06 12:59 UTC, viceice requested changes

2021-04-06 12:59 UTC, viceice commented on lib/workers/repository/init/apis.ts
> +async function getJsonFile(file: string): Promise<any | null> {
```suggestion
async function getJsonFile(file: string): Promise<RenovateConfig | null> {
```
should be typed

2021-04-07 03:58 UTC, JamieMagee approved these changes
LGTM

2021-04-07 04:04 UTC, viceice approved these changes

2021-04-07 04:23 UTC, merged

2021-04-07 09:30 UTC, renovate-release commented
:tada: This PR is included in version 24.104.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.104.0)
- `24.104.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: