docs: improve section on prCreation
renovatebot/renovate pull request #9571
Opened 2021-04-15 15:35 UTC by HonkingGoose

## Changes:

- Improve section on `prCreation`

## Context:

The current text contains some bad grammar and spelling, and was a bit hard to understand.
So I'm trying my hand at rewriting it. 😄 

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-04-15 15:40 UTC, HonkingGoose reviewed
Fixing up some typos

2021-04-15 15:40 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +With prCreation set to `immediate`, you'll get a GitHub notification right away when a new Renovate bot PR is avaiable.
```suggestion
With prCreation set to `immediate`, you'll get a GitHub notification right away when a new Renovate bot PR is available.
```

2021-04-15 15:40 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +With prCreation set to `not-pending`, Renovate waits untill all test have finished running, and only then creates the PR.
```suggestion
With prCreation set to `not-pending`, Renovate waits until all test have finished running, and only then creates the PR.
```

2021-04-15 16:10 UTC, rarkins requested changes

2021-04-15 16:10 UTC, rarkins commented on docs/usage/configuration-options.md
> +With prCreation set to `immediate`, you'll get a GitHub notification right away when a new Renovate bot PR is available.
```suggestion
With prCreation set to `immediate`, you'll get a Pull Request and possible associated notification right away when a new update is available.
```

2021-04-15 16:10 UTC, rarkins approved these changes, later dismissed

2021-04-15 16:17 UTC, HonkingGoose commented on docs/usage/configuration-options.md
> +With prCreation set to `not-pending`, Renovate waits until all test have finished running, and only then creates the PR.
```suggestion
With prCreation set to `not-pending`, Renovate waits until all tests have finished running, and only then creates the PR.
```

Add missing `s`.

2021-04-15 16:17 UTC, HonkingGoose commented
Sorry, I noticed a spelling error. 🙈

2021-04-15 16:30 UTC, rarkins approved these changes

2021-04-15 16:32 UTC, merged

2021-04-16 14:46 UTC, renovate-release commented
:tada: This PR is included in version 24.116.2 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/24.116.2)
- `24.116.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: