feat(config): convert datasource env to hostRules
renovatebot/renovate pull request #9698
Opened 2021-04-23 08:31 UTC by rarkins

## Changes:

Adds datasource env parsing into hostRules.

## Context:

Allows hostRules to be configured more conveniently using env.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-04-23 08:31 UTC, rarkins commented
This will need documenting, but I'll do so only once confirming that everyone likes this approach.

2021-04-23 08:36 UTC, viceice reviewed
like this, some performance suggestion 🙃

2021-04-23 08:36 UTC, viceice commented on lib/config/env.ts
> +  const datasources = getDatasourceList();
```suggestion
  const datasources = new Set(getDatasourceList());
```

perf

2021-04-23 08:36 UTC, viceice commented on lib/config/env.ts
> +    if (datasources.includes(prefix)) {
```suggestion
    if (datasources.has(prefix)) {
```

perf

2021-04-23 11:50 UTC, rarkins commented on lib/config/env.ts
> +    if (datasources.includes(hostType)) {
```suggestion
    if (datasources.has(hostType)) {
```

2021-04-23 11:55 UTC, rarkins commented
@Chumper do you think this "double underscore maps to hyphen" approach works well? I recall you found a similar problem in Bundler

2021-04-23 12:52 UTC, HonkingGoose requested changes
Needs documentation (once the code wizards have agreed on a approach).
I can't write the docs for this, but I'll be happy to review the docs that somebody else creates. 😉

2021-04-23 12:58 UTC, rarkins commented
Yes, switching back to Draft until I add docs

2021-04-23 18:08 UTC, Chumper commented
> @Chumper do you think this "double underscore maps to hyphen" approach works well? I recall you found a similar problem in Bundler

yeah, the problem that in bash the hyphen `-` is not a valid character in the name:
```
export TEST-123=abc
export: not valid in this context: TEST-123
```
It is the same with the period `.`, that's why bundler chose double underscore `__` as replacement for the period.
We would need a replacement for the hyphen `-` as well as that is not uncommon in a URL.

If you decide to use double underscore as a replacement for the hyphen that is fine by me.
I would recommend to stick to Bundler convention and add the hyphen as well.

So `MY__TEST` would be `MY.TEST`
and for hyphen we could do three underscores.
So MY___TEST` would be `MY-TEST`

In the end it depends on what characters from the URI definition are not valid in a bash env name and we need to support.
The period `.` and hyphen `-` are the basic ones we should support.

2021-04-23 19:12 UTC, rarkins commented
The underscore is not a valid character in host names so I thought it would work fine to have underscore replace dot and double underscore replace hyphen.  If we were to add an extra underscore to both scenarios like you suggest then what do we gain? I don't think the bundler approach is so widely used that we have to follow it.. just learn from it (eg hyphens)

2021-04-24 11:06 UTC, Chumper commented
Yeah, it was just an example. I am fine with single underscore for dot and double for hyphen.

2021-05-02 07:39 UTC, rarkins commented
Waiting on #9815

2021-05-06 12:24 UTC, HonkingGoose commented
Removing `status:blocked` as PR #9815 is now merged into `main`.

2021-05-06 20:06 UTC, HonkingGoose reviewed
@rarkins Don't we still need documentation for this? Or did you decide we don't need any documentation after all?

2021-05-06 20:13 UTC, rarkins commented
@HonkingGoose you're right! I forgot why I'd left it in Draft in the first place

2021-05-07 15:48 UTC, viceice reviewed
just a small issue

2021-05-07 15:48 UTC, viceice commented on lib/config/env.ts
> +import { HostRule } from '../types';
```suggestion
import type { HostRule } from '../types';
```

2021-05-08 04:05 UTC, JamieMagee commented on lib/config/env.ts
>    const unsupportedEnv = [
Everything that is old is new again 😂 

If you really wanted to, you could write a compatibility layer for these 😉

2021-05-08 04:06 UTC, JamieMagee approved these changes, later dismissed

2021-05-14 14:57 UTC, HonkingGoose requested changes
Some small changes. 😄

2021-05-14 14:57 UTC, HonkingGoose commented on docs/usage/private-modules.md
> +For self-hosted users, it is possible to use environment variables to configure the most common type of `hostRules` for authentication.
```suggestion
Self-hosted users can use environment variables to configure the most common types of `hostRules` for authentication.
```

2021-05-14 14:57 UTC, HonkingGoose commented on docs/usage/private-modules.md
> +The format of the environment variables should be all upper-case and follow:
```suggestion
The format of the environment variables must be all upper-case and follow:
```

2021-05-14 14:57 UTC, HonkingGoose commented on docs/usage/private-modules.md
> +Hyphens (`-`) in datasource or host name should be replaced with double underscores (`__`) and periods (`.`) in host names replaced with single underscore (`_`).
```suggestion
Hyphens (`-`) in datasource or host name must be replaced with double underscores (`__`).
Periods (`.`) in host names must be replaced with a single underscore (`_`).
```

Might make more sense to split this over two sentences?

2021-05-14 14:57 UTC, HonkingGoose commented on docs/usage/private-modules.md
> +- Underscore
```suggestion
- Underscore (`_`)
```

2021-05-14 14:57 UTC, HonkingGoose commented on docs/usage/private-modules.md
> +### hostRules Configuration using Environment Variables
```suggestion
### hostRules configuration using environment variables
```

2021-05-16 09:25 UTC, HonkingGoose requested changes

2021-05-16 09:25 UTC, HonkingGoose commented on docs/usage/private-modules.md
> +`NPM_REGISTRY_NPJS_ORG_TOKEN=abc123`:
```suggestion
`NPM_REGISTRY_NPMJS_ORG_TOKEN=abc123`:
```

I think we're missing a letter `M` in the `matchHost` part here?

2021-05-16 09:33 UTC, HonkingGoose approved these changes, later dismissed

2021-05-20 07:37 UTC, rarkins commented on docs/usage/private-modules.md
> +- `matchHost`
Yes, optional. But right now NPM_TOKEN won't be added to any `.npmrc` (I think we should add that independently)

2021-05-20 07:52 UTC, viceice approved these changes

2021-05-20 08:12 UTC, HonkingGoose requested changes
I feel we're missing some `h4` headings to separate out the different examples.

How about something like this?

```markdown
#### GitHub example

Renovate config JSON

#### GitLab example

Renovate config JSON

#### Docker example

Renovate config JSON
```

2021-05-20 08:16 UTC, rarkins commented
> I feel we're missing some `h4` headings to separate out the different examples.
> 
> How about something like this?

Would be great if you can improve it in a separate PR, as I really want to get this one merged finally.

2021-05-20 08:34 UTC, merged

2021-05-20 08:55 UTC, renovate-release commented
:tada: This PR is included in version 25.26.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/25.26.0)
- `25.26.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: