Trim whitespace around private key data
renovatebot/renovate pull request #9856
Opened 2021-05-04 19:42 UTC by DCKcode

## Changes:

When parsing a Git private key, remove any leading and trailing whitespace that may be present.

## Context:

Fixes #9855 .

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-05-04 19:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/renovatebot/renovate?pullRequest=9856) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/renovatebot/renovate?pullRequest=9856) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/renovatebot/renovate?pullRequest=9856) it.</sub>

2021-05-04 19:47 UTC, DCKcode commented
If you need test cases for this, I'd be happy to looking into providing those. Before I do, let me know if this solution would be acceptable.

2021-05-04 19:49 UTC, rarkins approved these changes, later dismissed

2021-05-05 06:42 UTC, viceice requested changes

2021-05-05 06:42 UTC, viceice commented on lib/util/git/private-key.ts
> +  gitPrivateKey = key.trim();
```suggestion
  gitPrivateKey = key?.trim();
```

2021-05-05 08:52 UTC, viceice approved these changes

2021-05-05 09:07 UTC, merged

2021-05-05 09:43 UTC, renovate-release commented
:tada: This PR is included in version 25.12.7 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/25.12.7)
- `25.12.7`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-05-05 14:46 UTC, DCKcode commented
Thanks all for fixing my crappy code 😄