Feat/quay registry v1 refactor
renovatebot/renovate pull request #9891
Opened 2021-05-06 13:01 UTC by giokara-oqton

## Changes:

Small refactor as requested in https://github.com/renovatebot/renovate/pull/9813.

## Context:

Refactor as requested in https://github.com/renovatebot/renovate/pull/9813.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

Live test in https://github.com/renovatebot/renovate/pull/9813

2021-05-06 15:19 UTC, viceice reviewed
Can you remove the quay.io relates changes from this pr, so it is only a refactor pr. after this you can update the original pr to only include the quay.io related changes.

2021-05-06 15:20 UTC, viceice commented
Sorry if i wasn't clear enough, but we like to have the required docker datasource refactoring in one pr and then the quay.io additions in an additional pr.

2021-05-06 16:09 UTC, giokara-oqton commented
Sorry - I misunderstood. Removed all quay related changes.

2021-05-06 16:13 UTC, viceice reviewed
- Move `id` and `http` to `./common.ts` too.
- Move all interfaces / types to `./types.ts`.

2021-05-07 12:05 UTC, viceice commented on lib/datasource/docker/index.ts
>  export function getRegistryRepository(
move this and all unecported function to `./common.ts`

2021-05-11 08:51 UTC, giokara-oqton commented
Anything else that I can do to help finish this?

2021-05-11 08:55 UTC, viceice commented
> Anything else that I can do to help finish this?

Next time use the (re)request review function to catch our attention
![image](https://user-images.githubusercontent.com/1798109/117788046-509fbc80-b247-11eb-84ac-51888c71209a.png)

Otherwise we don't know that you've fixed the requested issues.

2021-05-14 09:16 UTC, viceice commented on lib/datasource/docker/common.ts
> +export async function getECRAuthToken(
```suggestion
async function getECRAuthToken(
```

2021-05-14 09:16 UTC, viceice approved these changes

2021-05-14 09:18 UTC, viceice requested changes
Please rename the `index.spec.ts` to `common.spec.ts` and add a new `index.spec.ts to test the remaining functions in `index.ts`

2021-05-14 16:34 UTC, giokara-oqton commented
Not really sure why the codecov tests for https://github.com/renovatebot/renovate/pull/9891/commits/691f4e34b33e6286779e596775965ebb0b7ad0da failed above. I can't seem to access the codecov page either, any pointers on what is missing a test?

2021-05-14 18:32 UTC, viceice approved these changes

2021-05-19 16:14 UTC, merged

2021-05-19 16:34 UTC, renovate-release commented
:tada: This PR is included in version 25.25.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/25.25.0)
- `25.25.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: