feat(pep440): Implement isLessThanRange function
renovatebot/renovate pull request #9915
Opened 2021-05-08 12:43 UTC by zharinov

## Changes:

## Context:

Ref #9914

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

2021-05-08 19:32 UTC, rarkins requested changes
Please wrap in a try/catch just in case

2021-07-14 05:03 UTC, viceice approved these changes

2021-07-14 05:23 UTC, rarkins approved these changes

2021-07-14 07:48 UTC, merged

2021-07-14 08:44 UTC, renovate-release commented
:tada: This PR is included in version 25.55.0 :tada:

The release is available on:
- [GitHub release](https://github.com/renovatebot/renovate/releases/tag/25.55.0)
- `25.55.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: